### ISSUE TITLE
All btns showing up

### ISSUE THREAD

**Issue by chevvycc** [Alex-D/Trumbowyg#100]
The 'btns' property seems to add the correct buttons, but it looks like the default ones are always included after.

$('#editor').trumbowyg({
                        lang: 'fr',
                        removeformatPasted: true,
                        autogrow:true,
                        resetCss: true,
                        fullscreenable: false,
                        closable: false,
                        btns: ['bold', 'italic', '|', 'unorderedList', 'orderedList', '|', 'link', 'insertImage']
                    });

![trumboissue](https://cloud.githubusercontent.com/assets/10167837/6719651/76a43780-cd92-11e4-9cc7-7bbb28922e5a.JPG)

It shouldn't add any other after the first 'insertImage'.

**Comment by viion** [comment]
I'm also having this, for now I removed the default ones out of ``` t.o.btns[] ``` and then it just loads the ones I want.

**Comment by Alex-D** [comment]
Fix'd on master. Thanks for report ! :)

**Comment by Alex-D** [comment]
New tag : [v2.0.0-beta.1](https://github.com/Alex-D/Trumbowyg/tree/2.0.0-beta.1)
