### ISSUE TITLE
Plugin Dev : How to move caret after added content ?

### ISSUE THREAD

**Issue by NothingFaceX** [Alex-D/Trumbowyg#1000]
Hello dear Alex
I developed my plugin to add a custom content to html
but after adding text caret stays at same place it was ...
I used saveRange and restoreRange but same.

A little help ?

I open a modal dialog and get user input using :
`var input_text = document.getElementById('textinput').value;`

Then I call `trumbowyg.saveRange();` 

And after all I use `trumbowyg.execCmd('insertHTML', added_content);` to add new data to html.

**Comment by Alex-D** [comment]
Hey!

You can't move caret via Trumbowyg API/internal call, you need to call browser APIs on your side on the contenteditable.

This will be possible in v3 in few months (see #875)

Sorry :/

**Comment by NothingFaceX** [comment]
no problem Alex I fixed it by using added_content + '<p></p><br>'
it works perfect now ^^
