### ISSUE TITLE
href values are pre-pended with relative url from page (not desired behavior)

### ISSUE THREAD

**Issue by arievanden** [Alex-D/Trumbowyg#1004]
Hello.

Thank you for your great work!

I have an app that uses variables in href values such as 
`<a href='{merge_val_1}'>`. 

I found that if you cut and paste the content from the composer view into another composer view, the href value is prepended with the absolute url of current page.

So if you create `<a href='{merge_val_1}'>` in your simple demo,
Cut and paste it into the editor and it becomes this:
`<a href='https://alex-d.github.io/Trumbowyg/demos/core/{merge_val_1}'>`

While this might be handy in some cases, if you're using dynamic values it's definitely not desired. I can remove the inserted URL when saved, but it would be nice to see if there was a fix or setting to disable this.

Using Trumbowyg v2.18.0
I tested this in FF and Chrome on Win7.

I was reading this entry and was not sure if this was the cause of this behavior.
https://github.com/Alex-D/Trumbowyg/issues/256

**Comment by Alex-D** [comment]
That's a browser-level issue :/

Trumbowyg does not manage the clipboard, but you can add a `pasteHandler` if you want to clean that on paste front-side.

**Comment by arievanden** [comment]
Ok then. Just checking. I'll filter out the URL on my end. Thanks for your quick response!
