### ISSUE TITLE
Start trumbowyg in dynamic inserted textarea

### ISSUE THREAD

**Issue by joextra** [Alex-D/Trumbowyg#1006]
Hello,

I am writing a page, where you can insert dynamic (via js) blocks witch contains a textarea. I want that every textarea have trumbowyg. But when I start trumbowyg with the ID of the new inserted textarea, nothing happen. Can it be, that trumbowyg has a problem with dynamic content?

Thanks

**Comment by Alex-D** [comment]
It must be OK to init Trumbowyg on a new inserted textarea. Maybe your code does not run at the right time.

Feel free to add more infos in reply, maybe I could help :)

**Comment by joextra** [comment]
Thanks, that was the problem.
