### ISSUE TITLE
Can not type Vietnamese in MacOS

### ISSUE THREAD

**Issue by hieppham** [Alex-D/Trumbowyg#101]
Hi, thanks for creating fast and lightweight editor. However, it does not seem to work with my Vietnamese Input Method on MacOS. Would you mind taking a look at this?
![trumbowyg](https://cloud.githubusercontent.com/assets/1185186/6819981/bc3bf4da-d2fc-11e4-821b-f461b5e23e4c.gif)

**Comment by Alex-D** [comment]
I think it's due to the font-face used on my website. Download it and try it in local :)

**Comment by hieppham** [comment]
Hi Alex, thanks for your comment.
I've downloaded and tried with various common fonts but nothing changes. The editor works perfectly on Windows, so I think the font-face doesn't cause this problem.

**Comment by Alex-D** [comment]
Please, can you download the master version and retry ? I think the was fix'd by @foo9 with PR #105 

Thanks!

**Comment by hieppham** [comment]
Yeah, it works perfectly now, thank you very much :)

**Comment by Alex-D** [comment]
You can now get this fix with new version : v[2.0.0-beta.2](https://github.com/Alex-D/Trumbowyg/tree/2.0.0-beta.2)
