### ISSUE TITLE
Where is my <head> <body> tags?

### ISSUE THREAD

**Issue by mansres** [Alex-D/Trumbowyg#1012]
May be something I missing but just confirming with you, whether it is wrong or missed one.
I have pasted in html code, a page of html code start from 
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
.
.
.
</head>
<body class="">
...
</body>
</html>  
```
 
But after I switched to viewer and again switched to code behind then I can see above mentioned codes are being removed.
Please check my screenshots. 

Please help me that, How can I make it not removable in this editor.

![1](https://user-images.githubusercontent.com/12108539/63648897-c1d3cf00-c747-11e9-941b-edd52357ca29.png)
![2](https://user-images.githubusercontent.com/12108539/63648898-c304fc00-c747-11e9-87e7-9608f26843bc.png)
![3](https://user-images.githubusercontent.com/12108539/63648899-c39d9280-c747-11e9-826b-601076e40c5b.png)

**Comment by Alex-D** [comment]
Trumbowyg is not a full HTML page editor. It's a WYSIWYG editor for content like article, comments, etc.

So I did not support things like head, body, etc. in v2. Should be supported in v3 (see #875)
