### ISSUE TITLE
How to show custom message on error?

### ISSUE THREAD

**Issue by ipokane** [Alex-D/Trumbowyg#1015]
Hello,

How to set custom error message if upload error?

For example, I want to show a notification: "Image size is too large. Maximum is 500kB".

Which parameter should I use? How to do that?

Thank you in advance!

**Comment by Alex-D** [comment]
Hey!

You must override the `trumbowyg.o.plugins.upload.error` with your custom function. Check the original here: 

https://github.com/Alex-D/Trumbowyg/blob/9deda0c963dac1235812b5a1f2f75ad9a582f32d/plugins/upload/trumbowyg.upload.js#L228-L234

And documentation here: https://alex-d.github.io/Trumbowyg/documentation/plugins/#plugin-upload

**Comment by ipokane** [comment]
Thank you Alex, I'll try it.
