### ISSUE TITLE
New images showing as 0px width/height with resizeimg plugin

### ISSUE THREAD

**Issue by Yokomoko** [Alex-D/Trumbowyg#1018]
Possibly related to this: https://github.com/Alex-D/Trumbowyg/issues/786

I'm adding an image in as base64 with the resizeimg plugin enabled.  I have this:

```js
resizeimg: {
  minSize: 64,
  step: 16,
}
```

Within the plugins section of the trumbowyg initialisation, however it is showing as 0 width and 0 height so you're unable to view it. Any ideas how to resolve?

Edit - Also tried resizimg as per the documentation, same problem.

**Comment by Alex-D** [comment]
Can't reproduce here: https://alex-d.github.io/Trumbowyg/demos/#plugins-resizimg

Which browser and OS?

**Comment by Alex-D** [comment]
I close it for now, but fell free to reopen when you will add more context :)
