### ISSUE TITLE
Duplicate line when you use text to speech on iOS

### ISSUE THREAD

**Issue by SquirrelMobile** [Alex-D/Trumbowyg#1019]
### Description
Provide relevant details according to the context:
  - iOS 12.4
  - Safari

### How to reproduce?
if you use text to speech of the iOS keyboard and add a new line with speech, when you dismiss the keyboard, the last line a duplicate into the editor.

**Comment by Alex-D** [comment]
Hum. I can't reproduce. On simulator on macOS, I can't write anything after adding a new line... 

That's really strange, needs more investigations. Maybe it's related to `semantic` option.

It's not a priority for me, as I'm working on v3 and it's a specific usecase that I can't test with a real iOS device :/
