### ISSUE TITLE
Unable to insert a non-breaking space

### ISSUE THREAD

**Issue by xgretsch** [Alex-D/Trumbowyg#1020]
I'm trying to use "Alt-Space" to add an HTML `&nbsp;` code, which is standard usage for people who write in French (where they put non-breaking spaces in front of punctuation marks like "?", ":", "!" and others. But I'm unable to do this

If I take a normal Trumbowyg box and type "F r e d Alt-Space ?", this results in a normal space for the html:
`<p>Fred ?</p>`
If I change this to "F r e d Alt-Space Space ?", the result changes:
`<p>Fred&nbsp; ?</p>`
But I cannot see any way of getting the desired result:
`<p>Fred&nbsp;?</p>`

I've succeeded in writing some custom code to trap character code 160, but I then can't see how to insert an `&nbsp;` into the text and set the caret to immediately after it: there isn't enough documentation on the Range API to make it obvious how I do this.

**Comment by Alex-D** [comment]
I'm French and I can't insert any non-breaking space in any `contenteditable` anywhere on the Web.

Where does the "alt+space" shortcut come from?

Does it work anywhere else?

**Comment by xgretsch** [comment]
I'm told that it's a standard convention on French word processing software (i.e. Word, Google Docs, etc). My guess is that it kicks in if you have a French keyboard layout, but I haven't checked that out yet - I can do some more work if you like to narrow that down. Alt-space generates a separate key code (160) and I'm happy to trap the keypress event - I just need to know how to then add the "&nbsp;" into the html and move the caret after it...

**Comment by Alex-D** [comment]
Yep, I just want to understand how to fix the bug globally and include this in core if it works.

When I press alt + space, on Windows 10 / Chrome, it opens the window options (restore, resize, move, reduce, etc.) soooo idk how to trigger the 160 keycode.

But, if you want to insert anything, you need to run this:

```js
$editor.trumbowyg('execCmd', {cmd: 'insertHTML', param: '&nbsp;'})
```

See the source:

https://github.com/Alex-D/Trumbowyg/blob/8b64a97d7a83cf421d572f6996ec6eda3de33088/src/trumbowyg.js#L141-L143

**Comment by xgretsch** [comment]
I've done a bit more digging: as ever, the [article on French Wikipedia](https://fr.wikipedia.org/wiki/Espace_ins%C3%A9cable)  is fairly comprehensive. As far as I can see, the Unicode value of 160 is pretty much universal, the keyboard shortcuts vary wildly from one system to another (it's Alt-0160 on Windows). The [English Wikipedia article](https://en.wikipedia.org/wiki/Non-breaking_space) gives similar information.

The following code works fine, with one whoopsie (`trumbo` is my editor class).
```
$('.trumbo').on('keypress', function(e){
  if (e.charCode === 160) {
    $(this).trumbowyg('execCmd', {cmd: 'insertHTML', param: '&nbsp;'});
      e.preventDefault();
      e.stopPropagation();
    }
});
```
The whoopsie is that if the &amp;nbsp; added is the last thing in the paragraph, when you type the next character (for example, an exclamation mark), the &amp;nbsp; is changed to a space. If you then go back, delete the space and type "ALT-Space" again, everything is now fine.

The workaround is enough to get me out of jail for now, but it would be nice if you can find a better solution.

**Comment by Alex-D** [comment]
Maybe try with `skipTrumbowyg` set to `true`?

**Comment by xgretsch** [comment]
Hi Alex, I know it's been a long time, but I've got round to looking at this again. If you start with an editor containing the following html
`<p>a&nbsp;</p>`
...and then move your cursor to the end after the non-breaking space and type the letter 'b', what you get is
`<p>a b</p>`
The place where this happens is in the following routine:
```
syncTextarea: function () {
     var t = this;
     t.$ta.val(t.$ed.text().trim().length > 0 || t.$ed.find(t.o.tagsToKeep.join(',')).length > 0 ? t.$ed.html() : '');
 },
```
The function `t.$ed.html()` appears to convert the non-breaking space into a standard space.

If I'm not mistaken, the html() function is the one in jQuery, so it may be relevant to know that my jQuery version is 3.6.0.

Do you have any ideas on why the html() function is behaving like this, and what I might be able to do about it?

Thanks
