### ISSUE TITLE
Close viewHTML mode

### ISSUE THREAD

**Issue by beyondtheobservableuniverse** [Alex-D/Trumbowyg#1022]
Hi

How can i close editor viewHTML mode when blur on editor?

**Comment by Alex-D** [comment]
Hey!

Try something like:

```js
$editor.on('tbwblur', function () {
	if ($(this).parent().hasClass('trumbowyg-editor-hidden')) {
		$(this).trumbowyg('toggle');
	}
})
```

Hope it helps :)

**Comment by beyondtheobservableuniverse** [comment]
Thank you! But this is not working for me, maybe because i use editor in the iframe.

**Comment by Alex-D** [comment]
Did you put this code in the iframe?
