### ISSUE TITLE
XSS with escaped characters

### ISSUE THREAD

**Issue by martijnbolhuis** [Alex-D/Trumbowyg#1023]
Hi,

In addition to another XSS issues reported (#160), I found that
inserting a script tag in the text (not in the raw html input but in the
formatted text) also gets executed.

It seems that trumbowyg escapes special characters to html entities. So

```html
<script>alert('Hacked!')</script>
```

Becomes

```html
&lt;script&gt;alert('Hacked!')&lt;/script&gt;
```
Which gets executed. See the example below.

I am using server side sanitation (Ruby on Rails) as suggested in #160. However,
this does not sanitize escaped script tags.

To me,  this makes sense since HTML entities are meant to escape HTML special
characters. As far as I know, when including the escaped text into a web page it
will not get executed. Therefore, it is trumbowyg which somehow unescapes these
characters and executes it. Can and shouldn't this be avoided by trumbowyg?

Example

```html
<html>
  <head>
    <link rel="stylesheet" href="trumbowyg/dist/ui/trumbowyg.css">
  </head>
  <body>
    <textarea id="editor">
      &lt;script&gt;alert('Hacked!')&lt;/script&gt;
    </textarea>

    <!-- Import jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/vendor/jquery-3.3.1.min.js"><\/script>')</script>

    <!-- Import Trumbowyg -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.19.1/trumbowyg.min.js"></script>
    <script>
      jQuery(function(){
        $('#editor').trumbowyg();
      });
    </script>
  </body>
</html>
```

**Comment by Alex-D** [comment]
> Can and shouldn't this be avoided by trumbowyg?
Nope.

XSS cannot be solved client-side. It must be done server-side.

If user write `&lt;script&gt;alert('Hacked!')&lt;/script&gt;`, you must display &lt;script&gt;alert('Hacked!')&lt;/script&gt; and not a script tag for real.

So, same as #160: server issue, cannot be solved by Trumbowyg.

Why? Because if you want, you can use devtools or other things to cut the Trumbowyg security making it useless.

**Comment by martijnbolhuis** [comment]
Thanks for your response.
