### ISSUE TITLE
Formulas not editable after ViewHTML

### ISSUE THREAD

**Issue by step4** [Alex-D/Trumbowyg#1024]
I have created a Stackblitz with the following problem:

After adding all necessary files for trumbowyg and the MathML plugin everything seems to work fine.
But if you create a formula like `\sum` and switch to ShowHTML mode and then switch back, you cannot edit the formula anymore.

Stackblitz Link: https://stackblitz.com/edit/js-gxp17p

**Comment by Alex-D** [comment]
Seems that event listeners are lost while we switch between views :/

**Comment by atiabjobayer** [comment]
Anyone found a solve yet?

**Comment by Alex-D** [comment]
Fixed in develop branch :)
