### ISSUE TITLE
Adding HTML comment tags around HTML hides content in HTML view.

### ISSUE THREAD

**Issue by briang123** [Alex-D/Trumbowyg#1026]
How can we see the commented out HTML within the code view? When I add an HTML comment block around some HTML and toggle to view the 'friendly' pane, then back again, it comes up missing? I want to uncomment the HTML and continue on with my work. Thanks!

### How to reproduce?
```js
$('textarea').trumbowyg()
$('textarea').trumbowyg('html', '<!--<span class="toto">Some HTML</span>-->')
$('textarea').trumbowyg('toggle');
```

### OR

```html
<textarea>
<!--
<div slideractive="true" id="atlAuctionText">
	<div style="margin-left:125px">1300+ Units Available</div>
	<div style="margin-left:125px">600+ Harley-Davidsons</div>
	<div style="margin-left:125px">125+ Honda Motorcycles</div>
</div>
-->
</textarea>
```

```js
$('textarea').trumbowyg().toggle()
```

**Comment by Alex-D** [comment]
Trumbowyg does a clean, and does not support comments in the process of clean.

If you want to keep only comments in your textarea, you need to add some non-empty/kept tag from this list that you can customize.

See the code which clean the textarea: https://github.com/Alex-D/Trumbowyg/blob/03fb78bc52973a70cb1dce927f06b9a502c84864/src/trumbowyg.js#L1110-L1113

Sorry for that but I can't fix that without adding lot of code for an isolated usecase.

**Comment by briang123** [comment]
In my case, I don’t want to keep only comments in a text area, but would expect to support comments.

**Comment by briang123** [comment]
I’ve resolved this issue by simply replacing html comment tags with a display:none on a div tag wrapping the commented content.
