### ISSUE TITLE
Fontsize plugin size list parameter won't work as it is supposed to

### ISSUE THREAD

**Issue by BarbiesGroup** [Alex-D/Trumbowyg#1027]
### Description

When following [the documentation](https://alex-d.github.io/Trumbowyg/demos/#plugins-fontsize) of the font size plugin, it looks like we can set custom values (in pixels). After providing an array of sizes, the drop-down list of the buttons pane display correctly. The problem is when a size in the drop-down list is selected, the style attribute change of the HTML element is not set as the size chosen. Indeed, I noticed that no matter what array of sizes is provided, the value affected by the HTML element is always going to be the same, which is one of the following: x-small, small, medium, etc. (in this order).

_v2.19.1_ 

### How to reproduce?

You can see the bug in the documentation. Try the demo under "Custom font sizes" and inspect the modified HTML element. You'll notice that the style attribute is not the value of the drop-down list option you select.

Or, try it with this list (for example) :

```js
    plugins: {
	    fontsize: {
		    sizeList: ['18px','6px','13px']
	    }
    }
```

**Comment by Alex-D** [comment]
Thank you for your issue!

I've fixed the bug and it will be ship in the next version soon :)

**Comment by BarbiesGroup** [comment]
Mais de rien! J'attends la prochaine version avec impatience dans ce cas ;) 

Merci Alex-D
