### ISSUE TITLE
Remove format not working with h-tags

### ISSUE THREAD

**Issue by Felix-Puetz** [Alex-D/Trumbowyg#1033]
### Details
  - OS: MacOS Mojave 10.14.6
  - Browser + version: Google Chrome 77.0.3865.90 (Official Build) (64-bit)
  - Screen resolution: (2880 x 1800)

### How to reproduce?

- Open the editor anywhere (for example on [the website](https://alex-d.github.io/Trumbowyg/))
- Mark the whole text (Ctrl + a)
- Set the style to h1/h2/h3..
- Press the "remove format" Button.
-> h-tags are not removed

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/50131232/66453264-0bf8e180-ea64-11e9-995f-81c39c36a4f9.gif)

**Comment by Alex-D** [comment]
That's the expected behavior since blocks are not considered as format by browser contenteditable API. So... I understand your request, but I don't think I will "fix" that.

Feel free to create a button which will call both format block P *and* remove format if you want that :)
