### ISSUE TITLE
Error while inserting new link

### ISSUE THREAD

**Issue by alenxmedia** [Alex-D/Trumbowyg#1034]
### Description
If you try to insert new link with no text selected the link will be inserted at the top of the text.

### How to reproduce?
Go to https://alex-d.github.io/Trumbowyg/demos/ go to end of the text. Press enter and try to add a link. I have recorded the screencast.
![20191014_144745](https://user-images.githubusercontent.com/22632395/66752764-85dd0080-ee92-11e9-901f-3f6ba750959e.gif)

**Comment by Alex-D** [comment]
Cannot reproduce. I think you click outside before click on the actual button causing the lost of the selection.
