### ISSUE TITLE
Image not showing up after upload

### ISSUE THREAD

**Issue by inifinity-webdesigns** [Alex-D/Trumbowyg#1040]
When i use the editor on a page where i have loaded jquery-ui the image is not showing up after the upload.

I need jquery-ui on a different part of the page where i use jquery sortable.

**Comment by Alex-D** [comment]
Cannot help you without demo page where I can reproduce the issue.

Please take some time to create an demo page from that: https://jsfiddle.net/AlexandreDemode/p7hb3x6u/

Feel free to reopen when it's done :)
