### ISSUE TITLE
Nested Velocity tags are moved outside table when inserting via source code and switching back to design view

### ISSUE THREAD

**Issue by pionic** [Alex-D/Trumbowyg#1044]
### Description

(Velocity) templates tags, nested inside a table will be parsed out when switching to design view.

### How to reproduce?
Paste the following HTML into the editor source code:
`<table><tr><td>x</td></tr> #foreach() <tr><td>x</td></tr> #end</table>`

Switch back to design view and the #foreach() will be moved into a new paragraph tag before the table tag.
Result:

`<p> #foreach() #end</p><table><tbody><tr><td>x</td></tr><tr><td>x</td></tr></tbody></table>
`

**Comment by Alex-D** [comment]
Your are hacking! :D

Trumbowyg is based on browser's contenteditable API which avoid invalid HTML, and your HTML is invalid since you are trying to add some text outside of tags, so the browser take this take out of here.

I cannot fix that since it's a browser-level behavior.

**Comment by pionic** [comment]
> Your are hacking! :D
> 
> Trumbowyg is based on browser's contenteditable API which avoid invalid HTML, and your HTML is invalid since you are trying to add some text outside of tags, so the browser take this take out of here.
> 
> I cannot fix that since it's a browser-level behavior.

Too bad! Thanks for your quick reply!

I'll try to look for a workaround (e.g. replacing #foreach() with <#foreach()>)

**Comment by pionic** [comment]
For future reference: Wrapping the velocity tags inside html comments works.

E.g.:

`<table><tr><td>x</td></tr> <!--#foreach()--> <tr><td>x</td></tr> <!--#end--></table>`

That code will retain the original positions, but requires additional pre and postparsing of the template.
