### ISSUE TITLE
Resizimg plugin: Bad formatting when jQueryUI is included

### ISSUE THREAD

**Issue by agriffard** [Alex-D/Trumbowyg#1045]
The resizimg plugin is autoformating the images weirdly when jQueryUI is included in the page.

### Description
The img used in your https://alex-d.github.io/Trumbowyg/demos/#plugins-resizimg sample: 
`<img src="https://rawcdn.githack.com/Alex-D/Trumbowyg/develop/banner.jpg" style="height: 200px;" class="">`

is formatted into this:
`<p class="ui-wrapper" style="overflow: hidden; position: static; width: 257.141px; height: 200px; top: auto; left: auto; margin: 0px;"><p class="ui-wrapper" style="overflow: hidden; position: static; width: 257.141px; height: 200px; top: auto; left: auto; margin: 0px;"><img src="//rawcdn.githack.com/Alex-D/Trumbowyg/develop/banner.jpg" style="height: 200px; margin: 0px; resize: none; position: static; zoom: 1; display: block; width: 257.141px;" class="ui-resizable"><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div></p></p><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div>`

### How to reproduce?
See an example here: https://codepen.io/agriffard/pen/WNNdWqO

**Comment by Alex-D** [comment]
First, this plugin is not based on the jQuery resizable, but on this one: https://github.com/RickStrahl/jquery-resizable

So, you need to include it on your page to make resizimg works.

But, I've seen this issue which says that load both resizable plugins fails: https://github.com/RickStrahl/jquery-resizable/issues/25

So, it's not really on my side and I cannot do much except adding support for jQuery UI resizable to resizimg plugin... but as you notice it, the result code is not as clean :/
