### ISSUE TITLE
tbwtoggle event

### ISSUE THREAD

**Issue by Yakoot** [Alex-D/Trumbowyg#1047]
Hi. Can you add a toggle event after clicking viewHTML button? With some payload to detect current state

**Comment by Alex-D** [comment]
`tbwchange` is fired since 2.20.0, is that enough?

https://github.com/Alex-D/Trumbowyg/commit/a856623700c8bfd4a2ae0d48965981c494a75e3d

**Comment by Yakoot** [comment]
no, it triggers on each change in textarea. I want a special event for switching source mode to initialize codemirror or another syntax highlighting. I think I can realize it using custom button for viewHtml which will toggle html mode and do my stuff

**Comment by Alex-D** [comment]
Ah OK, I see your use case. Yep you can make a custom button which is a decorator for the original viewHTML. But you need to create it as a plugin to get access to Trumbowyg core's `toggle` method.

**Comment by SaDaT895** [comment]
> no, it triggers on each change in textarea. I want a special event for switching source mode to initialize codemirror or another syntax highlighting. I think I can realize it using custom button for viewHtml which will toggle html mode and do my stuff

Hello,

Did you manage to realize the custom button? Kind of in a same situation
