### ISSUE TITLE
Editor removes the form element.

### ISSUE THREAD

**Issue by minimalheight** [Alex-D/Trumbowyg#1048]
Removes the element even when I set ...
`tagsToKeep: ['form']`
Latest Chrome/Firefox

**Comment by Alex-D** [comment]
Is the editor in a form itself? If yes, it's the browser which cleans the invalid HTML and remove your form in form.

**Comment by minimalheight** [comment]
Yup :(

**Comment by Alex-D** [comment]
Nice workarround :)

**Comment by aneculau** [comment]
Hello, i am struggling with this issue also, just try and paste yourself this basic html - it cuts all the html and body tags: 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>ABC
</body>
</html>
Can i override this behaviours somehow? I would like it to NOT TOUCH to any of the pasted text (or typed in text) in there - no semantics, no tags replaced or removed, just the original pasted stuff? I tried all i could find with no success.
thanks,

**Comment by Alex-D** [comment]
Since you are trying to add some invalid HTML to the page (Trumbowyg renders your HTML inside the page), that makes no sense to the browser to have a doctype and so, so the browser strip it, and Trumbowyg only keep the valid HTML.
