### ISSUE TITLE
Is it possible to add custom classes on the .trumbowg-box container?

### ISSUE THREAD

**Issue by samzabala** [Alex-D/Trumbowyg#1050]
I'm trying to add a class to the containing element. tried declaring the classes on the textarea to initiate trumbowyg to but the classes stay on that field. is this an available option?
<img width="718" alt="Screen Shot 2019-11-11 at 2 29 36 PM" src="https://user-images.githubusercontent.com/20095546/68626235-c2028180-048f-11ea-8c8a-06002501c4cb.png">

**Comment by Alex-D** [comment]
No :/

There is no option for that. Why did you need that?

What about:
`$('#editor-demo').parent().addClass('my-custom-class')`

**Comment by samzabala** [comment]
oof bummer. no worries. I'm working on a internal framework for work with the plugin integrated. Trying to make the build reliant on helper classes and minimizing dom elements needed.
