### ISSUE TITLE
Add custom HTML where the cursor is

### ISSUE THREAD

**Issue by vkiranananda** [Alex-D/Trumbowyg#1052]
Hello!

I want to add custom HTML where the cursor is. How to do it?

Thank you!

**Comment by Alex-D** [comment]
You will get some responses here: https://github.com/Alex-D/Trumbowyg/issues?q=is%3Aissue+sort%3Aupdated-desc+insertHtml+is%3Aclosed

:)

**Comment by vkiranananda** [comment]
:)
Thanks @Alex-D
