### ISSUE TITLE
Is it possible to modify the markup of modals opened by buttons?

### ISSUE THREAD

**Issue by samzabala** [Alex-D/Trumbowyg#1053]
I'm trying to modify the modal form elements to inherit styles a proprietary framework's styles with helper classes.

from this:
![image](https://user-images.githubusercontent.com/20095546/68883519-11ca8e00-06c6-11ea-9f0d-a022a7aa1304.png)

to this:
![image](https://user-images.githubusercontent.com/20095546/68883646-522a0c00-06c6-11ea-8568-0df34f28f00e.png)

I was looking in the source code and saw a method outputs the html. Is there a way to override the html string in the method `openModalInsert` in 1582 from an external script file? I didn't want to modify trumbowyg's script itself.

Thank you!

**Comment by Alex-D** [comment]
Nope, you cannot do that. But, you can create your plugin based on `openModal`, which allows you to add custom markup :)

See documentation here: https://alex-d.github.io/Trumbowyg/documentation/core/#modal-box
And here: https://alex-d.github.io/Trumbowyg/documentation/plugins/#create-your-own

I hope it helps!

**Comment by samzabala** [comment]
oooo this might actually be what i needed. thank you!
