### ISSUE TITLE
'Table' plugin does not show its menu

### ISSUE THREAD

**Issue by a-enchanter** [Alex-D/Trumbowyg#1054]
When I click on the plugin table menu, it shows this:
![image](https://user-images.githubusercontent.com/57860079/69006087-3e8fd700-094c-11ea-8ebc-64dd457e9924.png)
The menu does not work. I installed the plugin according to its instruction. What could it be?

**Comment by Alex-D** [comment]
There is a CSS import which is missing from the documentation:

```html
<link rel="stylesheet" href="trumbowyg/dist/plugins/table/ui/trumbowyg.table.min.css">
```

I will fix that soon :)
