### ISSUE TITLE
Shift+Enter and new line unexpected behaviour

### ISSUE THREAD

**Issue by Magenta94** [Alex-D/Trumbowyg#1055]
![esempio](https://user-images.githubusercontent.com/15924478/69048806-abfc4000-09fe-11ea-9926-de1daa1b582f.gif)

### Description
- Windows 10
- Chrome 78.0.3904.97
- Edge 44.18362.449.0

### How to reproduce?
See the Gif above. In bold I've written "After this line there's a SHIFT+ENTER" to let you notice where the soft space is placed.

1. Break a paragraph with a new line
2. The next paragraph is breaked with a shift+enter
3. Delete the previous line break, and you can see that the shift+enter space is converted in a line break.

**Comment by Alex-D** [comment]
As you can see, you are not the first one to report this bug: https://github.com/Alex-D/Trumbowyg/search?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+shift+enter&state=closed&type=Issues

But, I can't fix that. I hope I can do make it works properly in v3 (#875)
