### ISSUE TITLE
Got "Cannot read property 'match' of undefined"

### ISSUE THREAD

**Issue by EVDW** [Alex-D/Trumbowyg#1059]
Given I use the 2.18.0 version, and I have done:

```js
$('textarea').trumbowyg({btns: [], disabled: true});`
```

In order to just display an html template without edition mode.
But I got this error in console:

```js
Uncaught TypeError: Cannot read property 'match' of undefined
    at new r (trumbowyg.js:238)
```

To solve the problem, I added `svgPath: false` to trumbowyg options.
But, why I have to add this option, it should have a default value to avoid error like this one?

**Comment by Alex-D** [comment]
https://github.com/Alex-D/Trumbowyg/blob/bb5332f0c8ce6549ef8570e5bd45e53203886870/src/trumbowyg.js#L223-L234

As you can see, it's a hack to make Trumbowyg setup easier, see documentation: https://alex-d.github.io/Trumbowyg/documentation/#svg-icons

Your error is a bug that I need to fix ^^
