### ISSUE TITLE
Selection is not smooth when selecting backwards using shift+arrow

### ISSUE THREAD

**Issue by rohit-htc** [Alex-D/Trumbowyg#106]
When selecting backwards with arrow key pressed one at a time the selected element gets unselected.

**Comment by Alex-D** [comment]
Fix'd since : https://github.com/Alex-D/Trumbowyg/commit/ee9987474bbf0a4b481022dc1e86ea73bde3e73f

**Comment by varun-raj** [comment]
Even now, When I try selecting the entire line from the end, it automatically selecting the previous line as well.

![image](https://cloud.githubusercontent.com/assets/3992409/19068062/8cd94e2c-8a3e-11e6-80f5-c89b8cfffb0b.png)
