### ISSUE TITLE
[Feature Request] Define more than one CSS for style attribute

### ISSUE THREAD

**Issue by timint** [Alex-D/Trumbowyg#1061]
I'd like to propose support for multiple defined stylesheets.

E.g.
`style: ["/path/to/css/variables.css", "/path/to/css/framework.min.css"]`

Currently the following is only supported:
`style: "/path/to/css/framework.min.css"`

PS! The documentation seems to miss explaining the "style" attribute. I couldn't find it.

**Comment by Alex-D** [comment]
Hey,
I don't know which attribute are you talking about ^^'
Can you give me a link to affected lines?

**Comment by timint** [comment]
"style" is the attribute that defines the css to be used inside the iframe. I will see if I can find the lines in the code.

**Comment by timint** [comment]
Terribly sorry, this is an invalid feature request.
Trumbowyg does not use a stylesheet in an isolated iframe. So this is not an issue.
