### ISSUE TITLE
upload image with data option value return 'false'

### ISSUE THREAD

**Issue by hagiwara-lvgs** [Alex-D/Trumbowyg#1063]
```javascript
$("#trumbowyg").trumbowyg({
    svgPath: icons,
    btns: ['upload'],
    plugins: {
        upload: {
            serverPath: '/api//upload/',
            fileFieldName: 'image',
            data: [{name: 'content', value: $('#trumbowyg').trumbowyg('html')}],
            urlPropertyName: 'href',
        },
    },
})
```

### Description

i want to get request with trumbow html content for image upload number validation.
but, content value of request  is 'false'.

### How to reproduce?

why '$('#trumbowyg').trumbowyg('html')'  return 'false' ???
how reproduce this?

**Comment by Alex-D** [comment]
Because you run this before Trumbowyg is initialized ^^'

It's a JS issue, not a Trumbowyg issue... Sorry
