### ISSUE TITLE
Adding Table in an Empty Modal

### ISSUE THREAD

**Issue by Ayberkone** [Alex-D/Trumbowyg#1064]
Adding Table in an Empty Modal

When I try to add a table in an empty modal, it appends to the parent node not to itself as it shown at the image below.

![image](https://user-images.githubusercontent.com/45696854/71659936-68fdee00-2d5a-11ea-9af1-8b6619acf4f4.png)

**Comment by Alex-D** [comment]
Can you reproduce the bug here: https://alex-d.github.io/Trumbowyg/demos/#plugins-table ?

**Comment by Ayberkone** [comment]
I couldn't reproduce it because the table is not empty when mounted.

**Comment by Alex-D** [comment]
Can you detail steps to reproduce your issue please?

**Comment by Ayberkone** [comment]
When I try to add a table,
If the editor div is empty (if the first input will be a table), the table is being appended to the parent node, not inside to the editor div as it shown in the image.
But if any other input inserted already in the editor div ( as there is already a text inserted [https://alex-d.github.io/Trumbowyg/demos/#plugins-table](url) ) everything works fine and the table is being appended to the editor div.

**Comment by Alex-D** [comment]
If I clean the editor, it does works too, so it's really strange :/

**Comment by Ayberkone** [comment]
It is for real, I couldn't even come up with an idea of what can cause that.

**Comment by Alex-D** [comment]
Can you make an isolated reproduction from here: https://jsfiddle.net/AlexandreDemode/p7hb3x6u/

**Comment by Ayberkone** [comment]
I can't, that's a huge project written in Ember and it's gonna take a huge time to adapt the code in jsfiddle which I don't have.

**Comment by Alex-D** [comment]
OK, So I can't help you :/

Good luck!
