### ISSUE TITLE
Can I disable enter?

### ISSUE THREAD

**Issue by MaestroMagnifico** [Alex-D/Trumbowyg#1065]
Hey. I need this plugin only for "input" tags, not for "textarea". So I need to disable enter button. Is there a way to do that?

Also I don't need paragraphs and br tags. This is not necessary, I can delete them later in back-end, but this would be nice anyway.
I tried to add "p" to tagsToRemove. But this breaks everything. Evey line in editor is wrapped with paragraph. So when I type some content, then switch to viewHTML and back, it deletes everything. So I don't think this is the way to do it.

**Comment by Alex-D** [comment]
Arf, nope, there is no solution nor hack to achieve something like that :/
