### ISSUE TITLE
Using Trumbowyg with Tailwind CSS doesn't work

### ISSUE THREAD

**Issue by edsuna** [Alex-D/Trumbowyg#1068]
### Description
We are trying to use Trumbowyg in a project that is built using Tailwind CSS. However, once the tailwind CSS file is included the editor stops working properly.

### How to reproduce?

```html
<!DOCTYPE html>
<html>
<head>
	<link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet" type="text/css" />
	<link href="https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.20.0/ui/trumbowyg.min.css" rel="stylesheet" type="text/css" />
</head>
<body class="">
	<textarea id="description"></textarea>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> </script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.20.0/trumbowyg.min.js"> </script>
	<script>
		$('#description').trumbowyg();
	</script>
</body>
</html>
```

If the tailwind css is included then the editor stops working properly. Trying to add bullet points or use the Formatting dropdown the HTML is updated but it doesn't display properly.

**Comment by Alex-D** [comment]
All is working well, just... Tailwind set a reset CSS so h1, h2, etc. have no style by default anymore. So...  you need to add them back maybe? Check the generated HTML, it is like we want it to be :)

Not a Trumbowyg issue.

**Comment by pildit** [comment]
Thank you for your answer. How can i add them back ?
