### ISSUE TITLE
TypeError: string is undefined 

### ISSUE THREAD

**Issue by Marcin1sto** [Alex-D/Trumbowyg#1069]
### TypeError: string is undefined
I get this message after clicking next to the editor, or when clicking the viewHTML button.
I'm using the js validator

Provide relevant details according to the context:
  - Windows
  - Mozilla latest
  - 1920x1080

### js
```js
let trumbowyg_default_options = {
    lang: 'pl',
    btns: [
        ['viewHTML','undo', 'redo', 'strong', 'underline', 'em', 'del', 'link', 'strikethrough', 'justifyLeft',
            'justifyCenter', 'justifyRight', 'justifyFull', 'horizontalRule', 'foreColor', 'backColor', 'upload', 'unorderedList', 'orderedList'],
        ['fullscreen']
    ],
    plugins: {
        /* TODO */
        upload: {
            serverPath: '/upload',
            fileFieldName: 'image',
            headers: {
                'Authorization': 'Client-ID xxxxxxxxxxxx'
            },
            urlPropertyName: 'data.link'
        },
        allowTagsFromPaste: {
            allowedTags: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'b', 'u']
        }
    },
    removeformatPasted: true,
}
```

```js
let trumbowyg = $('.trumbowyg').trumbowyg(trumbowyg_default_options);
```

### html
`<textarea name="content" id="module_event_add_category_content_field" class="trumbowyg" rows="1"></textarea>`

**Comment by gbjbaanb** [comment]
probably a problem with jquery-validation (a default with asp.net mvc forms)
when trumbo loses focus, the validation routine is run for all contenteditable elements, but as the div created by trumbowyg doesn't have a name (or ID but I think name is required) jquery-validation 
tries to check the name and fails - its this that is throwing the exception.

referenced here https://github.com/jquery-validation/jquery-validation/pull/2289

**Comment by Alex-D** [comment]
Oh! Okay :)

Trumbowyg does not set a name to the textarea if you come from div, but it's preferred to init from a textarea with all attributes you want :)

**Comment by gbjbaanb** [comment]
I don't think it does. Well, it might copy attributes, but the name property is not (maybe because its a property and not an attribute!)

**Comment by Alex-D** [comment]
I just recheck this issue, and I did not know how to tell to jquery-validation to ignore the div since there is already the textarea to check... so if it checks both, it will check 2 times for the same name, and it will cause bugs in payload on server side I think.

Can't do anything more on my side :/
