### ISSUE TITLE
Problem with auto replacement

### ISSUE THREAD

**Issue by Zud71** [Alex-D/Trumbowyg#1071]
Trumbowyg v2.21.0
When you insert an HTML-tag `<hr> `, it replaces with `<p><hr></p>`
The HTML markup validator considers this a bug. How to prevent AutoCorrect?

**Comment by Alex-D** [comment]
It's not possible in v2.

I hope it will be possible in v3.

**Comment by Zud71** [comment]
My way out of the situation.
Making a change to the code: `if ($from[0].tagName !== "HR")`

`           var wrapInlinesInParagraphsFrom = function ($from) { 
                      
                        if ($from.length !== 0)
                            if ($from[0].tagName !== "HR"){
                            var $finalParagraph = $from.nextUntil(blockElementsSelector).addBack().wrapAll('<p/>').parent(),
                                $nextElement = $finalParagraph.nextAll(inlineElementsSelector).first();
                            $finalParagraph.next('br').remove();
                            wrapInlinesInParagraphsFrom($nextElement);
                        }
`
