### ISSUE TITLE
Font size plugin removes any formatting in range

### ISSUE THREAD

**Issue by gabe565** [Alex-D/Trumbowyg#1072]
### Description

If a range contains any sort of text formatting (Nested html tags), then when the font size is changed, all of the formatting is lost. It can be reapplied, but it will be lost if the size is changed again.

### How to reproduce?

1. Type some text with any sort of formatting (Link, bold, italic, strikethrough, changed font, etc)
![Screen Shot 2020-01-28 at 5 24 41 PM](https://user-images.githubusercontent.com/7717888/73314286-18f83700-41f3-11ea-9bac-714b0a7d5782.png)
```html
<p>Text with a <a href="https://example.com" target="_blank">link</a> <strong>and</strong> <em>some</em> <span style="font-family: &quot;Courier New&quot;, Courier, monospace;">formatting</span> inside the highlight</p>
```

2. Highlight the text and change the font size. All formatting will be lost and the html structure will be replaced with a single `span`.
![Screen Shot 2020-01-28 at 5 20 24 PM](https://user-images.githubusercontent.com/7717888/73314102-90799680-41f2-11ea-9d85-4978f80d4e3d.png)
```html
<p><span style="font-size: x-large;">Text with a link and some formatting inside the highlight</span></p>
```

**Comment by Alex-D** [comment]
This code is buggy: https://github.com/Alex-D/Trumbowyg/blob/develop/plugins/fontsize/trumbowyg.fontsize.js#L201-L215

**Comment by gabe565** [comment]
I almost have a solution which creates a temporary `div` so that I can pull the HTML out of the range.

Only problem I'm working around now is if a user changes the font size on something, then changes the font size around it, there are multiple `span`s which set each font size. Working on cleaning up those children before I create a PR!
