### ISSUE TITLE
Add support for 'required' attribute

### ISSUE THREAD

**Issue by I-Valchev** [Alex-D/Trumbowyg#1074]
I'd like to be able to make this field required, so that it can act as if I added required to any HTML5 input element.

**Comment by Alex-D** [comment]
Which field are you talking about?

**Comment by I-Valchev** [comment]
Sorry @Alex-D , didn't really describe this well.

I am using Trumbowyg on a "form". I'd like to be able to add a required attribute, so that it will fail on validation if left empty.

**Comment by Alex-D** [comment]
Add the attribute on the textarea, it should work

**Comment by I-Valchev** [comment]
The textarea is hidden, so if I do that, on validation it pops it out which is very unpleasant.
Also to give you a little more background, I'm using [VueTrumbowyg](https://github.com/ankurk91/vue-trumbowyg) on top.

**Comment by Alex-D** [comment]
The `textarea` should be visible, as a 1px height block. So you should see the browser "Required" label. Can you send me a screen? Or a link to a demo page? I did not understand why it did not work.
