### ISSUE TITLE
npm WARN trumbowyg@2.19.1 requires a peer of jQuery@>=1.8 but none is installed.

### ISSUE THREAD

**Issue by seyfer** [Alex-D/Trumbowyg#1078]
When I install my dependencies or build with webpack I see this message

```
npm WARN trumbowyg@2.19.1 requires a peer of jQuery@>=1.8 but none is installed. You must install peer dependencies yourself.
```

### Description
Provide relevant details according to the context:
  - Linux
  - Latest npm and node

### How to reproduce?
Just run the install of any package with webpack, when trumbowyg@2.19.1 is installed

It is really easy to fix maybe? there is no package named `jQuery`. We have `jquery` installed
`"jquery": "^3.4.1",`
means `package.json` in trumbowyg is wrong. should be
```
  "peerDependencies": {
    "jquery": ">=1.8"
  },
```

**Comment by Alex-D** [comment]
Thank you for the fix :)

**Comment by andreiradoi** [comment]
Could we have this pushed to npm as well? Thanks :)

**Comment by xdmda** [comment]
I have same problem with jQuery@1.8. can anyone help me?

**Comment by Alex-D** [comment]
You just need to install jQuery on the version you want.

```zsh
npm install --save trumbowyg jquery
```
