### ISSUE TITLE
Custom Button Issue on Font Family

### ISSUE THREAD

**Issue by macsavers** [Alex-D/Trumbowyg#1083]
I was following your example on issue #114, but it doesn't seem to work on font family.

I tried using the foreColor icon, but it's not showing up. I've confirmed that the icon is in place, I did that by adding the button to the list, so I'm unsure as to why it won't work.

```js
$('#editor').trumbowyg({
    btnsDef: {
        fontfamily: {
            ico: 'foreColor'
        }
    },
    btns: [
         ['fontfamily']
    ],
    plugins: {
        fontfamily: {
            fontList: [
                {name: 'Montserrat', family: '\'Montserrat\', sans-serif'},
                {name: 'Merriweather', family: '\'Merriweather\', sans-serif'}
            ]
        }
    }
```

**Comment by Alex-D** [comment]
Hi!

I think you missed something. You cannot overwrite the existing `fontfamily` button via `btnsDef`.

You need to create a custom button that will call the `fontfamily`'s one. The important part is:

```js
$('#editor').trumbowyg({
    btnsDef: {
        customizedFontfamily: {
            fn: 'fontfamily',
            ico: 'foreColor'
        }
    },
    btns: [
         ['customizedFontfamily']
    ]
})
```

See documentation for more details: https://alex-d.github.io/Trumbowyg/documentation/#custom-buttons

**Comment by macsavers** [comment]
I tried this, but it did not work. The icon showed up, but the font family did not show below. Unless I need to change the plugin name in plugins: {}
