### ISSUE TITLE
Enter key dosen't work 

### ISSUE THREAD

**Issue by ismaelirc** [Alex-D/Trumbowyg#1084]
### How to reproduce?
Hi, I'm start using this editor, the system is develop using bootstrap 3.3.7 and jquery 2.2.4.
The editor is loaded normally and I can use all the features but the enter Key is not working.

I loaded the editor witch CDN

**Comment by Alex-D** [comment]
Can you please provide me a demo page, where I can 100% reproduce the bug?

**Comment by ismaelirc** [comment]
Hi, Alex. I just found the problem. There is an script that is included in this page that prevent the function of Enter key. Problem solved!

Thanks
