### ISSUE TITLE
How to paste without moving the caret back to the start?

### ISSUE THREAD

**Issue by xgretsch** [Alex-D/Trumbowyg#1085]
### Description
If I enable the 'cleanpaste' plug-in, when I paste text into the editor, the caret resets to the beginning of the text. That's because cleanpaste works by reading the text from the editor, manipulating it, and writing it back (see this line of code, line 102):
`trumbowyg.$ed.html(cleanIt(trumbowyg.$ed.html()));`

This is very much undesirable - we really want to leave the caret just after the newly pasted text.

I've tried various hacks like using saveRange and restoreRange, without success.

Could cleanpaste be modified to safely put the caret back where it should be? Or can you give me any tips - I'm happy to do the work!

**Comment by Alex-D** [comment]
Right now IDK how to do that.

There is a pending PR which seems to fix that: #977

**Comment by Alex-D** [comment]
I've just merged it. Please try from develop branch ^^

**Comment by xgretsch** [comment]
Works like a charm!

I shall have to try to analyse what you did. And then buy you a beer!!!

Many thanks
_______________________________________________
David Karlin
Director

Tel: +44 (0) 20 8004 6673
bachtrack.com <https://bachtrack.com/>
Bachtrack Ltd, 30B Lynton Road,
London N8 8SL, Registered in England, no. 06443197

**Comment by Alex-D** [comment]
Thank you for the beers :)
