### ISSUE TITLE
PayPal address for donation?

### ISSUE THREAD

**Issue by nCubed** [Alex-D/Trumbowyg#1088]
Do you have a PayPal email address we could send a small donation your way? The One-time donation that sends you to PayPal incurs a $0.99 fee to send your way. We could save a bit by sending something via friends and family which does not charge a fee on PayPal. Or maybe a Venmo address?

Great editor! Just found it and compared it against several others. Between the documentation, CDN's, and lightweight filesizes, Trumbowg leads the pack. Well done!

**Comment by Alex-D** [comment]
I did not have fees on the PayPal.me link.

https://www.paypal.me/demodealexandre/20eur

**Comment by nCubed** [comment]
Hard to find any actual articles from PayPal, but I suspect the fee is because I am sending from the U.S. to France. The fee is anywhere from 5% to 10% based on the amount. I wonder if there would be any difference if I were to send it directly using your PayPal email address using Friends and Family?

**Comment by Alex-D** [comment]
I did not get fees from US donation, don't worry :)
