### ISSUE TITLE
Change of fontsize doesn't change output of .trumbowyg('html');

### ISSUE THREAD

**Issue by Rasmusbdk** [Alex-D/Trumbowyg#1089]
If only changing fontsize - no changes of text etc. - the result of .trumbowyg('html') is the same as prior to the change of fontsize.

Demo: https://jsfiddle.net/v7ekxcqp/7/

Steps to reproduce
- In the above demo, the red box updates with result of .trumbowyg('html') every 10 seconds. 
- Access demo
- Edit only font size
- Notice that nothing changes in the output of .trumbowyg('html')
- Then changes text content.
- Notice how the result is now affected

**Comment by Rasmusbdk** [comment]
Is there any method I can call to force the field to register as updated, hence cause .trumbowy('html') to return real value?

**Comment by Alex-D** [comment]
Seems that `syncCode` is not called :(
