### ISSUE TITLE
Format buttons (e.g. bold/italic) don’t respond.

### ISSUE THREAD

**Issue by jenstroeger** [Alex-D/Trumbowyg#1092]
I’m on Mac using Chrome 80 on a Retina display, but reproducible for FF 74.0 and Safari 13.0.5.

To reproduce, hop onto the [Trumbowyg Demo](https://alex-d.github.io/Trumbowyg/demos/) page and start typing text in the default editor. Then click [**B**] or [_I_] to _continue_ typing in bold or italic—nothing happens. The buttons don’t toggle, and typing remains normal.

However, select the last few letters and then click [**B**] and the selection turns bold and I can continue typing in bold. But when I try to switch from bold to normal again, the [**B**] button stays selected. Same behavior with other format buttons. If this is intended behavior then it’s really confusing and a deviation to other editors…

There are no errors in the console.

**Comment by Alex-D** [comment]
Already reported multiple times. I can't fix that fin v2. I hope to fix that with v3, see #875.

**Comment by StrathCole** [comment]
I have created a (really) dirty workaround to allow toggling bold and italic with help of a temporary element:

https://github.com/StrathCole/Trumbowyg/commit/98aa16a4963b5a136f51bb94afcbf4d80c8cbeea
