### ISSUE TITLE
Bootstrap modal Close when exiting Fullscreen mode

### ISSUE THREAD

**Issue by Cholo981** [Alex-D/Trumbowyg#1093]
Hello, 
I need to open the editor inside a modal, it works pretty well, the only problem is with the fullscreen mode. Because when I close it, it close the Modal too.
Fun fact, if you click on the fullscreen closure button with the right mouse button... it exit from the fullscreen without closing the Modal!

I tried using the event 'tbwclosefullscreen' to show again the modal, with no success.
I need to keep the modal open because I make an asyncronous call when I open it, so it load the db data and every changes by the editor get lost.
Any Idea about how to solve this issue (and why the right click have a different behaviuor!)?
Thanks

**Comment by Alex-D** [comment]
I think it comes from this line:

https://github.com/Alex-D/Trumbowyg/blob/19bd369ed516ad05b09b8261dca619b93999fc84/src/trumbowyg.js#L822

which is not really a good way to do ^^'

**Comment by muneshkumar578** [comment]
@Cholo981 I'm also facing same issue. Did you find any workaround/solution?

**Comment by Alex-D** [comment]
Could you, please, provide me an example based on : https://jsfiddle.net/AlexandreDemode/p7hb3x6u/

I think it's impossible to make the fullscreen option working in a modal without custom code. The most simple solution is to disable the fullscreen option, or to not use Trumbowyg inside a modal.

I will reopen if I can reproduce with a working example, and will try to fix it.
