### ISSUE TITLE
Can't Create Links in Editor in a Modal jQuery UI Dialog Box

### ISSUE THREAD

**Issue by Bitcosoftware** [Alex-D/Trumbowyg#1098]
When I imbed the editor inside a jQuery UI Modal Dialog Box, I can't add or modify a link.  The dialog for a new link will open, when I try to type it will edit the text of the control and not the dialog box for the link.

### Description
I am using Google Chrome.

### How to reproduce?
I have create a jsfiddle to reproduce the issue here:

https://jsfiddle.net/Bitcosoftware/k1d3g0f2/14/

Just click on the button to open the Dialog Box.  Select some text to create a Hyperlink and click on the Link button.  You can't edit the text box.

**Comment by Alex-D** [comment]
Can't find why the input can't take the focus, the issue does not seem to come from Trumbowyg, but from the combo. Maybe the issue comes from the fact that Trumbowyg open modals at the bottom at the body, so they are not in the jQuery UI Modal.

I will think about that for the v3 (see #875)

**Comment by mgarcia96** [comment]
How did you fix this? I'm using 3.6.0 and still have this error

**Comment by feeela** [comment]
@Bitcosoftware Why did you close this issue? It is still open in the current versions.

@magarrent [There is no 3.x Version.](https://github.com/Alex-D/Trumbowyg/tags) How could you use it?

@Alex-D Did you find any solution to this? Or at least a practical workaround?

**Comment by magarrent** [comment]
> @Alex-D Why did you close this issue? It is still open in the current versions. Did you find any solution to this? Or at least a practical workaround?
> 
> @magarrent [There is no 3.x Version.](https://github.com/Alex-D/Trumbowyg/tags) How could you use it?

Hey @feeela, honestly I don't remember, but maybe I changed the editor for another, ckeditor or something

**Comment by PatrickAtM4** [comment]
Two possible fixes for this (its jquery dialog preventing you from clicking into the inputs when the modal is outside of the dialog with jquery dialog in modal mode):
 
Don't run jquery dialog in modal, add this to .dialog(

`modal: false`

That can cause other issues depending on what you're doing (it did for me) so I used the more brute force solution,which is to move the trumbowyg modal into jquery dialog like so when trumbowyg-modal is opened. Not sure this is the best/prettiest solution but it works for me:

```
.on('tbwmodalopen', function(){
                $(".trumbowyg-modal").detach().appendTo(".ui-dialog");
            });
```
