### ISSUE TITLE
cannot edit table properties after create a table

### ISSUE THREAD

**Issue by ngcgolf11** [Alex-D/Trumbowyg#1099]
not able to change editor properties after created a table. not be able to add or delete rows or cells or rows into the table.

**Comment by Alex-D** [comment]
Does it work here?
https://alex-d.github.io/Trumbowyg/demos/#plugins-table

**Comment by ngcgolf11** [comment]
no its not working here also. we cannot change table properties add or delete columns and rows

**Comment by ngcgolf11** [comment]
in active table it is not showing options to add or delete rows or columns

**Comment by Alex-D** [comment]
Please give me some context : browser version and OS... As you did not fill the issue template...

**Comment by ngcgolf11** [comment]
It is not working on Google Chrome and Mozilla browser in windows 10 Pro system

**Comment by Alex-D** [comment]
It works for me, I did not know what's wrong.

Click to add a table, choose table size via squares, then, the table is added. From that, you can click in any cell of the table, then the table dropdown has changed and shows new options to add/remove row/columns.
