### ISSUE TITLE
Possibility of publishing on NPM?

### ISSUE THREAD

**Issue by cojomojo** [Alex-D/Trumbowyg#110]
I think it would be great to get this listed on NPM. A lot of dev's seem to be going to using NPM exclusively without bower when possible.

**Comment by Alex-D** [comment]
I will do that soon, for v2.0.0 stable I think :)

**Comment by ldong** [comment]
@Alex-D which node version are you using?

Node: v0.12.2
NPM: 2.7.5

Here's what I have, and I'm running into issues for `gulp build`.

**Comment by Alex-D** [comment]
node : v0.10.32
npm : 1.4.28

I need to update dependencies to match with v0.12 & npm v2

**Comment by Alex-D** [comment]
I've build the 2.0.0-beta.5 on node 0.12.x and npm 2.x and i've push this version on NPM :)
