### ISSUE TITLE
Problem with combination of list and header

### ISSUE THREAD

**Issue by Dani-Sto** [Alex-D/Trumbowyg#1100]
Hi Alex,

i have an issue with the combination of lists and headers.
When i mark a text as list and then mark it as header it becomes a list in a header. This seems to be fine. But when i change the header lets say from h1 to h2 the font becomes bigger. For every other change it gets bigger and bigger.

### Description
- OS: Mac High Sierra
- Browser: Brave Version 1.7.92 Chromium: 80.0.3987.163 (Official Build) (64-bit)
- Trumbowyg version: 2.21.0

### How to reproduce?

1. write text
2. mark it
3. format to list
4. formate to h1
5. format to h2
6. this is the html result:

> `<p></p><h1><h2><ul><li>Some text</li></ul></h2></h1><p></p>`

working example on the demo page: https://alex-d.github.io/Trumbowyg/

**Comment by Alex-D** [comment]
You should not put any formatting block in list ^^'

I will not put effort to fix that in v2. I keep that as a note for v3 (see #875)
