### ISSUE TITLE
[Highlight Plugin] Improve language detection

### ISSUE THREAD

**Issue by mpryvkin** [Alex-D/Trumbowyg#1103]
### Description
Plugin not very accurately detect languages available for highlighting Prism and some internal methods appear, such as "extend", "insertBefore", please see below:

![image](https://user-images.githubusercontent.com/7396482/80319502-8578d700-87de-11ea-855c-4c12ca678aea.png)

### How to reproduce?

See [official Highlight plugin demo](https://alex-d.github.io/Trumbowyg/demos/plugins/highlight.html).

I can submit PR to offer provide ability to customize language list.

**Comment by Alex-D** [comment]
Seems to be improved via 
https://cdnjs.cloudflare.com/ajax/libs/prism/1.20.0/plugins/show-language/prism-show-language.min.js

But we should be able to make this optional. I think we can write a blacklist to exclude those properties from language list :)

**Comment by mpryvkin** [comment]
I agree, this should be optional. I will submit PR soon.

**Comment by mpryvkin** [comment]
I just submitted a PR but realized that I haven't made it optional they way you've meant it.

**Comment by mpryvkin** [comment]
Updated the code making this feature entirely optional by adding plugin option `languageNames`, please see PR description for more details.
