### ISSUE TITLE
Isn't execCommand obsolete?

### ISSUE THREAD

**Issue by Abhi0725** [Alex-D/Trumbowyg#1106]
### Description

Are we using execCommnad? Isn't this obsolete? https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand

**Comment by Alex-D** [comment]
I'm already working on a v3 (see #875).

But it's new that execCommand is deprecated. I did not see any replacement for this API... So we are going to a world where each editor will need to implement that on that own.

That's what I'm trying to do with v3 ^^

**Comment by Abhi0725** [comment]
Cool thanks for the update.
