### ISSUE TITLE
during the last two weeks your demo (inside your website) does not let me resize images

### ISSUE THREAD

**Issue by inglesuniversal** [Alex-D/Trumbowyg#1109]
I can see the arrows but nothing happens if I drag it... The image gets highlighted

Using Chrome: Latest Version

MacBook Air 13in screen

Hope you can fix this soon!!!

Stay safe

**Comment by Alex-D** [comment]
I need to update demo, but the resizimg plugin should work :)

The demo is still in 2.19, we are in 2.21 and the 2.21 contains a fix on this :)

**Comment by inglesuniversal** [comment]
Thanks @Alex-D ... I'll take a look at it! I'm very excited about your project
