### ISSUE TITLE
Question: move texts or  images with mouse inside trumbowyg doesn't work

### ISSUE THREAD

**Issue by PiemP** [Alex-D/Trumbowyg#1118]
Hi guys, 

I working with a project that include trymbowyg. From a couple of month the move of text selected or image with mouse cursor doesn't work anymore.

**Is not a trubowyg issue**, but I would like to find some info to understand what is generate this strange behavior to fix it.

Thank you for any kind of information.

**Comment by Alex-D** [comment]
I can move text and image on the Trumbowyg demo: https://alex-d.github.io/Trumbowyg/

I'm on Chrome / Windows 10

**Comment by PiemP** [comment]
Excatly... it work ... but I don't know why inside this project doesn't work now ... I would like to understand what can condition this functionality and fix what is wrong in the application where I work now.

Over this project work a lot of people and I'm not a genius on front end debugging...browser console is clean and I don't know where point my eyes.

![no_move](https://user-images.githubusercontent.com/2736009/81943940-521ab280-95fc-11ea-9a3c-7a5cb263f26a.gif)

**Comment by PiemP** [comment]
Hi @Alex-D ,

I have solved...someone have decided to bind event on the document: 
```
$(document).bind('drop dragover', function (e) {
                e.preventDefault();
});
```
I'm sorry for my inappropriate question, but it's been a couple of days behind this problem.
