### ISSUE TITLE
Color plugin behaves weird

### ISSUE THREAD

**Issue by jappyjan** [Alex-D/Trumbowyg#1121]
Color plugin behaves different than known from other editors...

### Description
In other Editors it's "standard" to be able to select a color and then type.
In the Trumbowyg color plugin i have to select text first, and then change the color.

Also it's not possible to "exit" the colored area/text and get back to black text w. white bakground by pressing the right arrow like its possible in other editors.
it is neither possible to click on the color plugin and select white as the background color (without selecting text) to disable coloring...

### How to reproduce?
Case 1:
Open the official Demo https://alex-d.github.io/Trumbowyg/demos/#plugins-colors
and start to write text (clean editor first)
click on background color black
type again (nothing changes)

Case 2:
create text with background color
press arrow right
type again
-> color is still there...

Case 3:
create text with background color
change color to black and white (without selecting text)
type again
-> color is still there...

**Comment by Alex-D** [comment]
Known bug which is not only for color, but also on strong, em, etc.
I will not fix that in v2 :/
