### ISSUE TITLE
Remove Formatting does not remove strikethrough

### ISSUE THREAD

**Issue by beboobailey** [Alex-D/Trumbowyg#1124]
When using the Remove Formatting button on selected text, if any of the selected text has the strike formatting, the strike formatting is not removed.

### Description
OS and browser independent

### How to reproduce?
https://jsfiddle.net/1ugma6v7/

**Comment by Alex-D** [comment]
Please try #1107

**Comment by Alex-D** [comment]
This should be fixed as of 2.23 :)
