### ISSUE TITLE
Trigger plugin by custom button

### ISSUE THREAD

**Issue by jack85811** [Alex-D/Trumbowyg#1129]
Hello,
first of all thank you for this awesome editor! 
i have a question regarding the html insertion into the editor.
i have written a plugin which inserts data into the editor by clicking a button in the editor toolbar.
Unfortunately i couldn't find an option to move this button outside of the editor.
hence my question, is it possible to trigger the plugin by an outside button?

I hope you can help out since i already tried everything.

Kind regards
Jack

**Comment by Alex-D** [comment]
Hey! Thank you :)

Documentation is missing, but there is an `execCmd` API in Trumbowyg, allowing you to call any button action from outside:

```js
const editor = $('#editor').trumbowyg()
editor.trumbowyg('execCmd', {
  cmd: 'yourPlugin',
  param: {key: 'value'},
  forceCss: false,
  skipTrumbowyg: true
})
```

**Comment by jack85811** [comment]
Hero! i will try it :)

**Comment by jack85811** [comment]
Good morning!
Good news: the command was working i could insert yesterday a tag.
`          const editor = $('#editor')
            editor.trumbowyg('execCmd', {
                cmd: 'insertHTML',
                param: '<p>hi</p>',
                forceCss: false,
                skipTrumbowyg: true
            })`
triggering the plugin however did nothing for me:
```
            const editor = $('#editor').trumbowyg()
            editor.trumbowyg('execCmd', {
                cmd: 'mypluginname',
                param: '',
                forceCss: false,
                skipTrumbowyg: true
            })
        })
```
the editor will not fire my "trumbowyg.addBtnDef".
Do i have to use a different event handler?

**Comment by jack85811** [comment]
Hey @Alex-D 
 any update on that?

**Comment by Alex-D** [comment]
I've re-read the code and... you cannot call plugin button code like that :/

You need to expose your plugin function somehow.

Sorry for the bad code example ^^'
