### ISSUE TITLE
Edit link action/button

### ISSUE THREAD

**Issue by ra100** [Alex-D/Trumbowyg#113]
It would be nice to have a Link edit option, just click somewhere on text which is inside <a></a> and choose from menu Edit link. And also option option to delete link without need of selecting whole text.
Maybe it could be done with plugin?

**Comment by ra100** [comment]
One other think, how does "unlink" work? I'd like to add "autoextend" selection, so I can delete whole link, when I've got just cursor on link, withou need to selecting whole "linked" text.

**Comment by ra100** [comment]
One other think, how does "unlink" work? I'd like to add "autoextend" selection, so I can delete whole link, when I've got just cursor on link, withou need to selecting whole "linked" text.

**Comment by Alex-D** [comment]
This feature is merged now as plugin thanks to @ra100 

For auto-extend selection, It's not easy so I close this issue.
