### ISSUE TITLE
Passing html content to PHP via jquery $.post getting 403 error

### ISSUE THREAD

**Issue by Calcul8or** [Alex-D/Trumbowyg#1130]
I've got four textareas with class `$('.editor').trumbowyg()`, and really struggling to pass `$(#textarea).trumbowyg('html')` to PHP.

They all output fine to console log, but are nulls by the time they hit PHP. I've tried `JSON.stringify` and `encodeURIComponent` without any success.

I don't have much hair left. Please help.

**Comment by Alex-D** [comment]
Does your form work without Trumbowyg?

It should work with just textarea, the add Trumbowyg on each textarea and it should be fine.

**Comment by Calcul8or** [comment]
Hi Alex, 

Yes, they all work fine without Trumbowyg. But the minute I initialize it, I get the error. 

I might be making a mistake with the way I'm passing html tags and styling as a string from the editor to PHP, and also single and double quotes etc. Is there any sample code you could refer me to that shows the right way to do it?

Must the textareas be in a form, or should it still work by assigning the `$('#textarea').trumbowyg('html')` values to variables for posting to PHP?
