### ISSUE TITLE
My problem with inserting <br /> tag

### ISSUE THREAD

**Issue by Elisha-m** [Alex-D/Trumbowyg#1131]
I made plugin with button and simple code which should insert new line in current caret position.
`fn : function(){
         trumbowyg.execCmd('insertHtml', '<br />');
                        }`
It inserts `<br />` , but the problem is that it also closes this paragraph and starts another one like that:
`<p>my te</p><br /><p>xt</p>`
So, as I understand, such issue would happen if I try to insert any tag having selection empty. 
For example `execCmd('insertHtml', '<strong>GGG</strong>')` would make `<p>my te</p><strong>GGG</strong><p>xt</p>` 
If some text is selected (at least 1 pos), it does not break paragraph in halfs as shown, but replaces current selection with `<br />`, which is obvious.  All I need, is to make new line in current caret position keeping `<p>` and without selecting anything.
Thanks in advance.

**Comment by Alex-D** [comment]
Hey,
it's not possible to do that easily for now in v2 :/
I hope to do something better in v3 for that.
