### ISSUE TITLE
A Part of Data get deleted automaticly

### ISSUE THREAD

**Issue by Moonracer97** [Alex-D/Trumbowyg#1134]
Hello,

i using as Browser Firefox and use your Text Editor at Databaseinteraction. 
There i creating a new Post and save it in my Database. Then i can edit this Post. For it i read the Data of the Database and render this in the Form. 

Everytime i going to my Editform a Part of the Data got deleted.

You can test it here: [https://editor.luckyscripting.de/index.php](url)

Click there first the "Zum Thema"-Button and than the "Thema bearbeiten" Button.

![lookModus](https://user-images.githubusercontent.com/32671090/84566463-a0dd7880-ad71-11ea-940d-b8ea6e841875.PNG)

![editModus](https://user-images.githubusercontent.com/32671090/84566457-915e2f80-ad71-11ea-8945-55a6a7fc31ca.PNG)

**Comment by Alex-D** [comment]
Does it work without Trumbowyg enabled? aka with just textarea fields?

**Comment by Moonracer97** [comment]
Thanks for your Answer.

I have did a mistake. I have used for textarea the value-Attribut. 

Now i render the Data directly in the textarea ( <textarea><?= $data ?> </textarea> ) and it works.
