### ISSUE TITLE
Save Range doesn't work after ajax call

### ISSUE THREAD

**Issue by viniciusARTioli** [Alex-D/Trumbowyg#1136]
Hi! Thanks for your editor! It is amazing by the way!
I've been having issues to save and restore range if the editor is initiated after an ajax call. I set the variable (var range = editor.trumbowyg('saveRange);) on ajax complete, but console log returns that the variable is undefined when a click on my custom toolbar button.
First i thought the issue happened because I have multiple editors on the same page.. however, after some tests, I realised that the editors will save and restore range if editors starts on page ready. So the issue is the ajax call for sure.

Is there a way to save and restore range after an ajax call?

Thanks in advance.

**Comment by Alex-D** [comment]
Hi!

I did not understand why the saveRange/restoreRange does not work :/
Did you have a demo page?
