### ISSUE TITLE
Cannot remove strikethrough after it is added

### ISSUE THREAD

**Issue by crlzfaiz** [Alex-D/Trumbowyg#1138]
The issue is as stated in the title

### Description
Provide relevant details according to the context:
  - Win10
  - Chrome Version 83.0.4103.106
  - 1080p
  - using latest Trumbowyg version

### How to reproduce?
- please refer to basic usage demo (https://alex-d.github.io/Trumbowyg/demos/)
- the issue can be reproduced on the page

**Comment by Alex-D** [comment]
Duplicates a lot of issues already. I will not fix that in v2, sorry.
