### ISSUE TITLE
Custom button

### ISSUE THREAD

**Issue by stefan-t** [Alex-D/Trumbowyg#114]
Is there a way for us to add completely custom buttons?
To simplify, let's say I want to add a "lorem ipsum" button, so when you click on it, it will put "Lorem ipsum" text inside of the textarea.
How would I go about making this?

Thanks!

**Comment by CFDaddy** [comment]
I need to add a button that inserts BBCode into the textarea.  Putting the button into the toolbar is easy enough, but how can I call a custom function that inserts text at the current caret position?

**Comment by ra100** [comment]
@CFDaddy look at this plugin https://gist.github.com/ra100/55c8c1c1bd4d2b9fe387#file-trumbowyg-cro-js look at `crSource` (line 250), it inserts text entered in field into text between custom tags.

**Comment by lewishowles** [comment]
I don't like to jump on someone else's question but I'm having the same one - even including the cro plugin in its entirety from @ra100 does absolutely nothing - the toolbar is added, buttons are added, but clicking on them doesn't do anything.

I thought maybe I was missing some kind of CSS that makes a popup work but even doing console.log('whatever') inside the function does nothing. Clearly I'm missing something stupid! I'm trying the most basic button below:

```
(function ($) {
	'use strict';

	$.extend(true, $.trumbowyg, {
		langs: {
			en: {
				soPlaceholder : "Insert Placeholder"
			}
		},
		opts: {
			btnsDef: {
				soPlaceholder: {
					ico: 'viewHTML',
					fn: function() {
						console.log('yep!');
					}
				}
			}
		}
	});
})(jQuery);
```

And my call is of course:

```
$('#brochure-template').trumbowyg({
	btns: ['btnGrp-semantic', '|', 'btnGrp-justify', '|', 'btnGrp-lists', '|', 'soPlaceholder'],
	fullscreenable: false,
	removeformatPasted: true
});
```

I even tried:

```
$('#brochure-template').trumbowyg({
	btns: ['btnGrp-semantic', '|', 'btnGrp-justify', '|', 'btnGrp-lists', '|', 'soPlaceholder'],
	fullscreenable: false,
	removeformatPasted: true,
	btnsDef: {
		soPlaceholder: {
			ico: 'viewHTML',
			fn: function() {
				console.log('yep!');
			}
		}
	}
});
```

Any ideas would be great!

**Comment by Alex-D** [comment]
If you try this on v2, it's normal if it's does not works. It was OK on v1.

Now, take a look in the plugins folder to check how to create plugins on v2. More doc soon.

**Comment by minkwe** [comment]
I've added a custom plugin and button, everything seems to be working. How do I set a custom icon for my custom button.

**Comment by Alex-D** [comment]
You need to get your icon in SVG and add as a SVG sprite, like so: https://raw.githubusercontent.com/Alex-D/Trumbowyg/master/dist/ui/icons.svg

You just need to add a SVG in your page:

```html
<svg xmlns="http://www.w3.org/2000/svg">
    <symbol id="trumbowyg-blockquote" viewBox="0 0 72 72">
        <!-- Your SVG here, don't forget to change viewBox and id above -->
    </symbol>
</svg>
```
