### ISSUE TITLE
Insert link option is selectable even in read-only mode

### ISSUE THREAD

**Issue by beena-yatin-kanyal** [Alex-D/Trumbowyg#1140]
### Description
We have the rich text editor _opened in a disabled mode_ and it works fine but even if the RTE is disabled (i.e. in the read-only mode) the link icon is still clickable. Refer below image -

![Capture](https://user-images.githubusercontent.com/46935197/86350764-cb3f9900-bc80-11ea-8873-6e33c09f827d.JPG)

Please suggest as to how we can fix this.

**Comment by Alex-D** [comment]
Is this the only one? Or the paragraph dropdown has the same behavior?

**Comment by beena-yatin-kanyal** [comment]
Yes, the issue is for both.
