### ISSUE TITLE
URL given in content is not displayed as a hyperlink

### ISSUE THREAD

**Issue by beena-yatin-kanyal** [Alex-D/Trumbowyg#1141]
### Description
We have the RTE opened in the read-only mode and during this, some content is prefetched into it (like - `<p>login using <a href="someurl.com">URL</a></p>`) but this link is displayed as a regular text but no hyperlink.

![Capture](https://user-images.githubusercontent.com/46935197/86351165-751f2580-bc81-11ea-87d3-c41cd4307330.JPG)

Please confirm as to how we can fix this.

**Comment by Alex-D** [comment]
What did you mean by "read-only mode"?

**Comment by beena-yatin-kanyal** [comment]
When the RTE is opened in the view-only mode.

**Comment by Alex-D** [comment]
OK, so you are talking about the **disabled** state? Am I right?

**Comment by beena-yatin-kanyal** [comment]
Yes.

**Comment by Alex-D** [comment]
I do not know why this is now shown as a link. It seems to be a CSS issue. I did not see any style in Trumbowyg which can cause that.

I close this, feel free to reopen with a working example of your issue that I can test, based on: https://jsfiddle.net/AlexandreDemode/p7hb3x6u/
