### ISSUE TITLE
How can i extend lang file in Persian (fa) mode?

### ISSUE THREAD

**Issue by hbsoftco** [Alex-D/Trumbowyg#1142]
Hi
I use some plugins, some words are not in the translation file, how can I extend the language file?

**Comment by Alex-D** [comment]
In each plugin, you can add the `'fa'` support :)

Example: https://github.com/Alex-D/Trumbowyg/blob/98be1fb0a253eb912a05e2beffa9c52a8b19ed32/plugins/table/trumbowyg.table.js#L18-L39
