### ISSUE TITLE
Autosave persist via Sisyphus.js or Garlic.js

### ISSUE THREAD

**Issue by liuyigh** [Alex-D/Trumbowyg#1144]
Trumbowyg rendered textarea does not persist with either Garlic or Sisyphus

### Description

- macOS
- Firefox 78.0.1
- form generated with Web2py

### How to reproduce?

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.20.0/trumbowyg.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/sisyphus.js/1.1.3/sisyphus.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/garlic.js/1.4.2/garlic.min.js"></script>
<script>
  $( function() {
    $( '#formNew' ).sisyphus()
  } );
</script>
<script>
    $.trumbowyg.svgPath = '/static/images/icons.svg';
    $('#t_log_f_note').trumbowyg({removeformatPasted: true, semantic: false});
</script>
```
will not work either with
`data-persist="garlic"`

Thanks!

**Comment by Alex-D** [comment]
Can't help you since I did not know those libs. Sorry for the lag ^^'

Try with a simple textarea and check if it works :)

I hope you fixed your issue since you've posted it.

**Comment by liuyigh** [comment]
Thanks for you reply. Both of those libraries works with the other textareas in the same form, except the one populated by trumbowyg.

Thanks all the same.
