### ISSUE TITLE
Paste Image handled by Upload

### ISSUE THREAD

**Issue by GrumpyCrouton** [Alex-D/Trumbowyg#1145]
There is a plugin for [pasting images](https://alex-d.github.io/Trumbowyg/documentation/plugins/#plugin-pasteimage), and there is a separate plugin for [uploading images](https://alex-d.github.io/Trumbowyg/documentation/plugins/#plugin-upload).

My question is, is there any way to make pasted image follow the same routine as uploaded images instead of being pasted as base64?

**Comment by Alex-D** [comment]
For now, in v2, there is no way to do that. You can do it by creating your custom plugin to handle that. What you want is a merge between the base64 plugin and the AJAX call in the upload plugin.

I note that idea for v3, I think it's a great idea, in fact. Maybe via drag and drop too :)
