### ISSUE TITLE
User Experience Issue

### ISSUE THREAD

**Issue by ATOPBIO** [Alex-D/Trumbowyg#1146]
Hello,

The method of formatting text is not UX friendly.

In every instance the text must be 'highlighted' to change the format.
It would be optimal to "activate" the button upon click so that the next typing adopts the activated buttons.

In instance, clicking on bold once does now allow the user to type directly in bold but rather has to type, then highlight and click bold.

Is there an easy way of implementing a button activation method?

Many thanks in advance

**Comment by Alex-D** [comment]
Already reported multiple times. Unfortunately, I won't fix that in v2. I hope to fix that with v3, see #875.

If you're interested, you can try #1107 but I can't help you since I'm not the author of the fix.
