### ISSUE TITLE
Use Trumbowyg with jQuery.noConflict()

### ISSUE THREAD

**Issue by SamGoody** [Alex-D/Trumbowyg#1147]
Unable to use with JQuery in noConflict mode.

I rarely use jQuery. On new sites, I have my own $() method that replaces jQ, and on older sites I used Mootools. When I need jQuery for anything, it must be in noConflict() mode.

How can I do that with Trumbowyg?

Related:   
I have lately come to using imports whenever possible.
I exported jQuery as a module, [see here](https://stackoverflow.com/a/52825767/87520).
is there any way to do something like this:
```
<script type='module'>
    import { jQuery as $ } from "../modules/jq.module.js";
    import 'https://cdn.pika.dev/trumbowyg';
    $('.trumbo').trumbowyg();
</script>
```

Perhaps the method used to activate trumbowyg can be exported, and passed in the scope and the name of the variable?

Thanks!

**Comment by Alex-D** [comment]
You can do something like that:

```js
import jQuery from "../modules/jq.module.js";
import 'https://cdn.pika.dev/trumbowyg';

(function ($) {
  $('.trumbo').trumbowyg();
})(jQuery)
```

or use `jQuery` instead of the `$` alias:

```js
import jQuery from "../modules/jq.module.js";
import 'https://cdn.pika.dev/trumbowyg';

jQuery('.trumbo').trumbowyg();
```

**Comment by SamGoody** [comment]
Thank you very much!

Unfortunately, it does not work for me!

even just including trumbowyg without calling it, causes the error: `Uncaught TypeError: can't access property "trumbowyg", jQuery is undefined`
```
import jQuery from "../modules/jq.module.js";
import 'https://cdn.pika.dev/trumbowyg';
```

Again, I am using noConfilct(). Otherwise, $ would be global, and there would be no issue (except that the rest of my pages wont work)

**Comment by Alex-D** [comment]
Trumbowyg does not use `$` internally, it uses `jQuery`, so that's strange.

Seems like you need to declare jQuery on `window` manually to allow Trumbowyg to get access to it:

```js
import jQuery from "../modules/jq.module.js";
window.jQuery = jQuery;
import 'https://cdn.pika.dev/trumbowyg';

jQuery('.trumbo').trumbowyg();
```

I will keep that in mind for the v3 (see #875)
