### ISSUE TITLE
Feature: Support Alt+Key mappings on custom buttons

### ISSUE THREAD

**Issue by therealrobbo** [Alex-D/Trumbowyg#1148]
### Description
I have developed several custom buttons for my application. This week I decided I would like to map keyboard shortcuts to them, and Tumbowyg very nicely provides the 'key' property on a button definition to create a CTRL+Key combo.

However, most CTRL+Key combinations are already mapped to browser functions, or other common Trumbowyg buttons. In fact, after chrome mappings and Bold / Italic (Ctrl+B and Ctrl+I) there are only four letters left unused (G, M, Q and Y).

 It would be nice if we could use Alt+Key as an additional mapping scheme.

**Comment by Alex-D** [comment]
I will add that idea to the v3 todo, since its a great idea, but I do not want to make changes like that in v2 anymore.

Feel free to subscribe to v3 issue to get notified #875
