### ISSUE TITLE
PasteEmbed Validation Error

### ISSUE THREAD

**Issue by teamayu** [Alex-D/Trumbowyg#1149]
When using the Pasteembed plugin, the html returned for iframes is invalid due to a space in the width attribute.

`<iframe width=" 480" height="270" src="https://www.youtube.com/embed/ofwFr8o8p0Y?feature=oembed" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p><iframe width=" 480" height="270" src="https://www.youtube.com/embed/ofwFr8o8p0Y?feature=oembed" frameborder="0" allowfullscreen="allowfullscreen"></iframe>`

The browser still renders it ok, but the space causes validation errors. Is this due to the api? Can be it fixed at all?

Thanks.

**Comment by teamayu** [comment]
OK, for now I adjusted the code to use:

t.html = t.html.replace('width=" ','width="');

Seems to work.

**Comment by Alex-D** [comment]
Yeah, the inserted HTML comes from [noembed](https://www.noembed.com/).

You can submit your fix on the server-side here: https://github.com/leedo/noembed

But it seems that the project is discontinued :/

I will not base the v3 paste embed feature on it, and write it full client-side I think.

**Comment by teamayu** [comment]
No problem Alex, thank you.
