### ISSUE TITLE
Syntax Changes With Twig

### ISSUE THREAD

**Issue by jamessampford** [Alex-D/Trumbowyg#1151]
I thought I'd use Trumbowyg for editing twig-based templates, however, I'm finding that the syntax is being changed when Trumbowyg loads or if I were to toggle from HTML editor to the WYSIWYG editor. ~~Is this is a feature?~~ I'm guessing this may be due to using contenteditable, so there's possibly no way of disabling this? Or possibly leaving everything between a set of tags alone?

For example, say I have the below:
```
<table>
<tbody>
<tr>
<th>Name</th>
</tr>
{% for item in items %}
<tr>
<td>{{ item.name }}</td>
</tr>
{% endfor %}
</tbody>
</table>
```

This would change on load and on toggle to the following:
```
{% for item in items %}

{% endfor %}
<table>
<tbody>
<tr>
<th>Name</th>
</tr><tr>
<td>{{ item.name }}</td>
</tr></tbody>
</table>
```

I like the idea of being able to use WYSIWYG with inserting snippets of code using a button, but if the twig logic moves around, it seems I may not be able to use Trumbowyg for this use case

**Comment by Alex-D** [comment]
Trumbowyg is meant to read and write HTML. Since your HTML is not valid, that can't work :/

**Comment by nakashu** [comment]
@jamessampford in a way it can be done by setting editor option.

```js
semantic` : false
```
Testr also on some very complex Semi broken HTML - this will disable to code cleanup.

@Alex-D /cc fiy - you already got support for it : ) -- keep up the good work
