### ISSUE TITLE
Is it possible to stop using P mark for FONT mark ?

### ISSUE THREAD

**Issue by flesage-000** [Alex-D/Trumbowyg#1153]
Hello,

I'm trying to use this wysiwyg to create script for a game.

The problem is that the game is a bit old and use old (own) html engine. I studied a bit this engine and assume that engine accept only some marks like“A”, “BR“, “DIV“, “FONT”, “IMG” and “U”. As we can, there is no "P" mark that is removed to "FONT" mark. (you can find a tutorial about HTML mark in game [here](https://alliancefrancophone.frenchparadise.net/viewtopic.php?f=84&t=262))

In addition, I have to use specific attributes like color and face (for font-family).

So my question is, is there a way t change default P mark for FONT mark.

Best regards.

**Comment by Alex-D** [comment]
Trumbowyg is not capable of that, sorry :/

**Comment by flesage-000** [comment]
ok :(
