### ISSUE TITLE
removeFormat button not removing paragraph, blockquote, or h1-h4

### ISSUE THREAD

**Issue by sml1990** [Alex-D/Trumbowyg#1154]
### Description
It seems that the removeformat button doesn't actually remove formatting such as `<p>`, `<blockquote>`, and `<h1-4>`, however It seems to remove all other formatting such as color formatting, `<b>`,` <i>`,` <u>`, etc just fine. Is anyone else having this problem?

System:
- Windows 10 64 bit

Browsers:
- Edge (Chromium) 84.0.522.58
- Chrome 84.0.4147.125 
- Firefox 77.0.1

Trumbowyg Version:
 2.20.0

### How to reproduce?
By calling trumbowyg() with the `btns` object containing `['removeformat']`

```
trumbowyg({
     btns: [
                ['viewHTML'],
                ['formatting'],
                ['strong', 'em', 'underline'],
                ['justifyLeft', 'justifyCenter', 'justifyRight'],
                ['unorderedList', 'orderedList'],
                ['foreColor', 'backColor'],
                ['removeformat'],
                ['link'],
                ['insertImage']
            ]
})
```

**Comment by Alex-D** [comment]
It is a browser-level issue I think.

The removeformat is a browser execCommand command. So I will not fix that in v2. I keep that for v3.

Sorry for that :/
