### ISSUE TITLE
Upload returns at the console "Cannot read property 'link' of undefined"  

### ISSUE THREAD

**Issue by 9Dann7** [Alex-D/Trumbowyg#1157]
Hello! I'm using the Upload plugin. I can send the image to the server side and I return a Json file with this content: 

```
{
    success: true,
    file: "http://localhost:60972/assets/BlogContent/Chrysanthemum204000218.jpg"
}
```

But the file called "**trumbowyg.upload.js**" at the line **49** throws the next error: _Uncaught TypeError: Cannot read property 'link' of undefined

This is my code at the front: 

```
<script>
    $('#editor').trumbowyg({
        btnsDef: {
            // Create a new dropdown
            image: {
                dropdown: ['upload'],
                ico: 'insertImage'
            }
        },
        btns: [
            ['undo', 'redo'], // Only supported in Blink browsers
            ['formatting'],
            ['strong', 'em', 'del'],
            ['superscript', 'subscript'],
            ['image'],
            ['link'],
            ['fontsize'],
            ['justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
            ['unorderedList', 'orderedList'],
            ['upload']
        ],
        plugins: {
            resizimg: {
                minSize: 64,
                step: 16,
            },
            upload: {
                serverPath: '@Url.Action("uploadImage","BlogPosts")', // I'm using ASP.NET MVC it returns "/BlogPosts/uploadImage", it works.
                fileFieldName: 'image',
                urlPropertyName: 'data.link'
            }
        }
    });
</script>
```

Hope you can help me! 

Best Regards :)

**Comment by Alex-D** [comment]
Hey

Change

    urlPropertyName: 'data.link'

For

    urlPropertyName: 'data.file'

Or change the `file` property in the response for `link`.

**Comment by 9Dann7** [comment]
Hello! @Alex-D, 

I have changed the urlPropertyName to`urlPropertyName: 'data.file'` and I get the same error: 

`Uncaught TypeError: Cannot read property 'file' of undefined`

Do you think that it happens because I'm using it at my localhost?

**Comment by Alex-D** [comment]
Oh I see, you copy/pasted the demo code, so just completely remove the `urlPropertyName` property, keep the the default which is `file`.
