### ISSUE TITLE
SaveRange and RestoreRange not working in FireFox/Safari

### ISSUE THREAD

**Issue by ruben-murcia** [Alex-D/Trumbowyg#1159]
In [another issue](https://github.com/Alex-D/Trumbowyg/issues/1155), I found the way to insert text at the caret.
The problem here is when we use an element outside the Editor to insert text into the editor, like the following code:

**HTML**
```html
<div id="insert-text">Insert text</div>
<textarea></textarea>
```

**Javascript**
```js
$('textarea').trumbowyg({
  btns: [['strong', 'em',]],
}).on('tbwblur', function(){
  $("textarea").trumbowyg('saveRange');
}).on('tbwfocus', function(){
  $("textarea").trumbowyg('saveRange');
});

$('#insert-text').on('click', function() {
  $("textarea").trumbowyg('restoreRange');
  $("textarea").trumbowyg('execCmd',
  {
    cmd: 'insertText',
    param: $(this).html(),
    forceCss: false
  });
});
```

It wors fine in Chrome and Edge, inserting the text where the caret was before losing focus, but in FireFox and Safari it always inserts at the beginning of the text.

### Description
  - Firefox (latest version) / Safari (latest vesion) 
  - Trumbowyg v2.21.0

### How to reproduce?
Live example: https://jsfiddle.net/hrzgk0q4/5/
- Write some text
- Click on the text to set the caret
- Click on the Div to insert a text
- In Chrome/Edge the text is inserted where the caret was, but in FireFox/Safari it always inserts the text at the beginning.

Does saveRange and restoreRange work on FireFox/Safari?
Any idea on how it can be fixed?

Thanks!

**Comment by ruben-murcia** [comment]
I investigated the source code a little bit, and in saveRange() we have

```
 documentSelection = t.doc.getSelection();
```

Here in Chrome and Edge, it gets the proper values but in FireFox the values of ranges are 0.
Maybe it does not work in Firefox?

After that, in restoreRange, the `t.metaRange` should have the correct values, and while in Chrome/Edge we have something like

```
Object { start: 3, end: 7 }
```

In FireFox it always have

```
Object { start: 0, end: 0 }
```

@Alex-D Any idea of how to make it work?

**Comment by ruben-murcia** [comment]
It seems the problem is that in Firefox/Safari, when losing the focus on clicking a div, you lose the range.
To save the range before losing the range, I saw that we can use the event `tbwchange`, that triggers every time we click on the Editor. Using it, it works in Chrome, Edge , Firefox and Safari.

The problem is that in IE11, `insertText` command does not seems to work. Nothing is inserted in the Editor. 
@Alex-D Are you aware of that?

Here is the code to fix the mentioned problem in Firefox/Safari:

```javascript
$('textarea').trumbowyg({
  btns: [['strong', 'em',]],
}).on('tbwchange', function(){
  // Save the selection range every time we click on the editor
  $("textarea").trumbowyg('saveRange');
});

$('#insert-text').on('click', function() {
  $("textarea").trumbowyg('restoreRange');
  $("textarea").trumbowyg('execCmd',
  {
    cmd: 'insertText',
    param: $(this).html(),
    forceCss: false
  });
});
```

**Comment by Alex-D** [comment]
Hey @ruben-murcia thank you for your investigation! :)

Yes, I'm aware of the fact that IE11 does not support `insertText` nor `insertHTML`, I think we can make a polyfill, but as IE11 will be deprecated soon, should we continue to put efforts in it?

I know that the save/restore range is not ideal :/ I've worked on a better approch for Trumbowyg 3, but still paused right now, as it's a big project, and I have some other things to work on before.
