### ISSUE TITLE
Software keyboard closes after space key is pressed on Android devices

### ISSUE THREAD

**Issue by tbrzek** [Alex-D/Trumbowyg#1161]
Every time the space key is pressed (sometimes if any key) the software keyboard of Android closes.

Tried with default keyboard and Google's gBoard and both in Chrome and Android Browser on several devices throughout Android versions from 5 to 10.

You can try it here: https://alex-d.github.io/Trumbowyg/

**Comment by jdussouillez** [comment]
I have the same issue with Chrome 85.0.4183

- 1st case: with this device the keyboard collapses when a space (or newline) character is typed

![chrome_version_1](https://user-images.githubusercontent.com/5428355/92479736-3c9d4a00-f1e4-11ea-83ce-2f478873e25d.png)

- 2nd case: with this device the keyboard collapses when any character is typed

![chrome_version_2](https://user-images.githubusercontent.com/5428355/92479783-47f07580-f1e4-11ea-8ea0-c77fb9046fb1.png)

**Comment by jdussouillez** [comment]
When you switch to the "view HTML" mode the bug is gone and the keyboard is not hidden.

**Comment by Kyle-Oliveira** [comment]
Bizarrely, this seems to have returned on the most recent version of Chrome on Android. However, rather than simply disappearing when pressing the "enter" key, the keyboard flashes, the "enter" is inserted, but the cursor is not brought down with it.

Chrome v. 88.0.4324.141
Android v 8.1.0
