### ISSUE TITLE
External libraries (e.g. Bootstrap) are accessible inside Trumbowyg editor 

### ISSUE THREAD

**Issue by muneshkumar578** [Alex-D/Trumbowyg#1164]
I have used bootstrap 4 library inside my application. But I don't want Trumbowyg editor to use its classes. Can I restrict Trumbowyg editor to not use Bootstrap or any other external library that is being used inside application?

**Comment by Alex-D** [comment]
Nope :/
It's not possible since you are editing HTML inside a web page. So everything in the page is accessible. If you want to clean up the HTML, you must do it server side.
