### ISSUE TITLE
Facing issue in uploading the file

### ISSUE THREAD

**Issue by naveenkn456** [Alex-D/Trumbowyg#1165]
Apologies if I am creating this item in the wrong place. I am trying with the upload option in the Trumbowyg editor, I see we have a feature when the user upload the file it will store in the server and insert the file on the UI. In my case, I don't want to store the file/image in a separate folder, as soon as the user selects the file it should insert into the editor. Is this option available in this editor. 

Please guide me if I need to ask this in any other forum. Thanks.

**Comment by Alex-D** [comment]
Maybe you need the base64 plugin? Or I did not understand the issue ^^'

**Comment by naveenkn456** [comment]
when we upload the image in the editor > it will be uploaded to the server mentioned and it returns the URL > again the image will be added to the editor

In my case, I don't want to upload the image to the server. when the user selects the file from the local folder it should directly insert into the editor window. is this option is available. Thanks for your time Alex.

**Comment by Alex-D** [comment]
Please read the base64 plugin doc: https://alex-d.github.io/Trumbowyg/demos/#plugins-base64
