### ISSUE TITLE
Is there any way to apply inline css to image tag ?

### ISSUE THREAD

**Issue by shalin007** [Alex-D/Trumbowyg#1166]
Hi, I would like to apply inline CSS to the image tag on image insertion, I did not find any event for image insertion in docs, and is there any way to wrap my image tag into anchor?
Any help would be appreciated.

**Comment by Alex-D** [comment]
You can't wrap images unless you create your own plugin to do that.

To add inline style, you can use the tbwchange and search for img tag without style attribute maybe.

**Comment by Alex-D** [comment]
You can now add classes to any element with [`tagClasses`](https://alex-d.github.io/Trumbowyg/documentation/#tag-classes) option.

Hope it helps :)
