### ISSUE TITLE
Set HTML content without trigger the 'tbwchange' event

### ISSUE THREAD

**Issue by ravid007** [Alex-D/Trumbowyg#1167]
Hi,
I'm trying to implement a textarea with Trumbowyg with the following behavior:
1. The content is saved automatically on each change of the textarea (I'm using the `tbwchange` event)
2. The content is associated with a datepicker control, and every change of date will load a new content to the textarea (using `$('#editor').trumbowyg('html', daily content")`).

Each time when I set the html content to the text area, the `tbwchange` event is triggered.
Is is possible to load content to the textarea with Trumbowyg without trigger the `tbwchange` event?

Thanks,
Ravid

**Comment by Alex-D** [comment]
Hey!

There is no option for this. But you can find a workaround, for sure. With a boolean that will allow you to ignore the next event or something like that.

Good luck
