### ISSUE TITLE
Resizimg plugin bug. After page refreshes, the resizing image doesn't show

### ISSUE THREAD

**Issue by riskadewi** [Alex-D/Trumbowyg#1168]
Image resizing works perfectly before. I find the img tag in it. After I save html code generated from the image resizing & refresh the page to show the resize image. The resizing image doesn't show. I can't find the img tag, instead I find a blank canvas tag.

OS: Mac
Browser: Chrome
Link: http://rmgvirgo.sangnilaindonesia.com/Faq/edit/1
I'm using Bootstrap & Jquey UI

**Comment by lazybird** [comment]
Hi @riskadewi,
I think this issue is described as well here : Issue #1158 
May be this issue can be marked as duplicated.

**Comment by riskadewi** [comment]
ok. will check it later. thank you

**Comment by Alex-D** [comment]
Should be fix in v2.22 (will be released soon)
