### ISSUE TITLE
issue in iOS app with wkwebview

### ISSUE THREAD

**Issue by khatridev** [Alex-D/Trumbowyg#1171]
### Description

Editor does not respond when built for ios using cordova.
iOS version -13.5

### How to reproduce?
Create the editor as usual. Build for the ios version using cordova-ios@6.x. 
Textarea, toolbar touch does not work, user has to double tap for any action.

**Comment by Alex-D** [comment]
I will not fix that in v2 so if you need that, you should try another WYSIWYG.

I keep this issue in mind for v3.
