### ISSUE TITLE
windows app font family and strikethrough does not work

### ISSUE THREAD

**Issue by khatridev** [Alex-D/Trumbowyg#1172]
### Description

Editor on Windows 10 built using Cordova

### How to reproduce?

Build the editor as usual. Font Family tool does not work as expected, also cannot do un-strikethrough any text
On selecting any font family the text remains in the same format.

**Comment by Alex-D** [comment]
Since I cannot reproduce, I will not fix that, sorry :/

For the un-strikethrough, its a known issue, that I will not fix in v2.
