### ISSUE TITLE
"Clean paste" plugin destroys previous formatting which is already in the text box

### ISSUE THREAD

**Issue by King555** [Alex-D/Trumbowyg#1173]
### Description

When I paste any plain-text content to the editor and have the "Clean paste" plugin enabled, the already formatted text loses most of the formatting.

Tested with latest release of Trumbowyg, Firefox 82.0.2 x64, Windows 10 2004 x64.

### How to reproduce?

- Paste this HTML code into the code view of the editor (this has been generated with the WYSIWYG view):
`<p><u><span style="font-size: x-large;">Headline</span></u></p><p><u><span style="font-size: x-large;"><br></span></u></p><p style="text-align: right;"><span style="font-size: medium;">Content!</span></p><p><span style="font-size: x-large;"></span><br></p>`

- Switch to WYSIWYG view and paste any text (can be a single letter) from a text editor

**Comment by rigardbester** [comment]
The same behaviour is seen when you add classes to elements.

<div class="btn btn-primary">Click me!</div>

When I paste some text from notepad on the WYSIWYG this class is removed.

Would this be related or should I create a new ticket for this?

**Comment by Alex-D** [comment]
Should be fixed in 2.22
