### ISSUE TITLE
placeholder attribute value with line breaks renders in a single line

### ISSUE THREAD

**Issue by jroy-dialpad** [Alex-D/Trumbowyg#1174]
PS thank you for a great library.

### Description
I'd like to show a placeholder with multiline content, but trumbowyg seems to lose the linebreaks.

### How to reproduce?
* Render a textarea with a placeholder attribute, where the attribute value has line breaks
* Trumbowygize it. The placeholder is all on a single line.

https://jsfiddle.net/ojf0pmyw/30/

**Comment by jroy-dialpad** [comment]
This style hack seems to fix it, but not sure what else it may break: https://jsfiddle.net/25earns8/1/

**Comment by Alex-D** [comment]
Thanks you for the fix :)
