### ISSUE TITLE
Resize with canvas script missing in the plugins/resizimg directory

### ISSUE THREAD

**Issue by moseleyi** [Alex-D/Trumbowyg#1177]
I've just downloaded Trumbowyg and set up a simple demo but I realised that `resizimg` doesn't work because this file

```<script src="trumbowyg/dist/plugins/resizimg/resize.with.canvas.min.js"></script>```

doesn't exist in this directory.

Do we need to add it separately?

**Comment by Alex-D** [comment]
This file is not needed anymore, I did not have updated the doc as 2.22, that's why

**Comment by moseleyi** [comment]
I'm going to double check because I think the error was in the console and the resize with canvas didn't work without that file, but I'll do some tests and come back with more details.

**Comment by Alex-D** [comment]
Working & up to date demo here: https://alex-d.github.io/Trumbowyg/demos/#plugins-resizimg
