### ISSUE TITLE
Ability to merge cells in table plugin

### ISSUE THREAD

**Issue by moseleyi** [Alex-D/Trumbowyg#1178]
When cursor is active within a table, it would be great to get options to merge with cell above/below/to the left/to the right.

**Comment by Alex-D** [comment]
I will not dev that in v2, maybe in v3, but for now I will close this and keep it in mind for v3.

**Comment by Alex-D** [comment]
Finally, a sponsor makes this possible, so it is available in v2.27.2 :)
See release note: https://github.com/Alex-D/Trumbowyg/releases/tag/v2.27.2
