### ISSUE TITLE
LineHeight plugin not working when resetCss is enabled

### ISSUE THREAD

**Issue by stevenLT** [Alex-D/Trumbowyg#1180]
### Description

When resetCss is 'true' the [LineHeight](https://alex-d.github.io/Trumbowyg/documentation/plugins/#plugin-lineheight) plugin do nothing. 

- Using Mac OS 10.15.7
- Chrome 86.0.4240.198

### How to reproduce?

You can try it here: [JsFiddle](https://jsfiddle.net/stevenAcseo/x2fqr7w0/4/)

- Add some generated text like: [Lorem Ipsum](https://www.lipsum.com/feed/html)
- Select some paragraphe and try to use the plugin

```
$('#trumbowyg-test').trumbowyg({
    lang: 'fr',
    resetCss: true,
    btns: [
        ['viewHTML'],
        ['lineheight'],
    ]
});
```

**Comment by Alex-D** [comment]
Due to this: https://github.com/Alex-D/Trumbowyg/blob/1a3c888d240d84854774f31aa6dedf57ecf4dbff/src/ui/sass/trumbowyg.scss#L551

I don't know how to avoid this issue, sorry :/
