### ISSUE TITLE
Indent plugin demo page doesn't work

### ISSUE THREAD

**Issue by dmorrison-olive** [Alex-D/Trumbowyg#1182]
I see the following when I go to the [demo page for the indent plugin](https://alex-d.github.io/Trumbowyg/demos/#plugins-indent):

![image](https://user-images.githubusercontent.com/73316418/101418720-15721980-38b4-11eb-8f8f-f6c688ebfd83.png)

Love the project - thanks for the work!

**Comment by Alex-D** [comment]
AH. I tested it in local in HTTP... did not see that.
Will be fixed on next doc push, maybe soon ^^'

**Comment by Alex-D** [comment]
Fixed!

**Comment by dmorrison-olive** [comment]
That was fast - thanks!
