### ISSUE TITLE
UC mobile Browser upload image success, but not return img-url insert to content

### ISSUE THREAD

**Issue by ssqlove10** [Alex-D/Trumbowyg#1183]
### Description
OS: IOS
uc last version

UC mobile Browser upload image success, not return img-url insert content

![image](https://user-images.githubusercontent.com/1673073/101566905-ce4a6c80-3a0a-11eb-91e3-bb0898837d28.png)

**Comment by Alex-D** [comment]
Not enough details, sorry.
Feel free to reopen with more details :)
