### ISSUE TITLE
Paste plain text creates extra line spacing / paragraphs.

### ISSUE THREAD

**Issue by smalos** [Alex-D/Trumbowyg#1184]
When I copy text from e.g. Notepad and paste it into Trumbowyg, line breaks  (or Paragraphs)  `<p>`  are added.

- Cleanpaste doesn't fix it.
- semantic: false doesn't change anything
-  `document.execCommand('defaultParagraphSeparator', false, 'p');` doesn't change anything either

The expected behaviour is that `<br>` instead of  `<p>` are inserted to prevent the extra line spacing.

How to solve this? I searched through all issues and googled but I wasn't able a solution for it.

![paste_line_spacing](https://user-images.githubusercontent.com/45562597/102006227-b717c180-3d1f-11eb-979f-ec9305a76b9b.png)

**Comment by Alex-D** [comment]
Hey!

Create your own pasteHandler and do what you want with the pasted content :)

This is not in the documentation, I admit.

This is the option:
https://github.com/Alex-D/Trumbowyg/blob/74815e6bbee93d0b570cf033939dd16acaf673e5/src/trumbowyg.js#L110

This is the usage done in Clean paste plugin, for inspiration:
https://github.com/Alex-D/Trumbowyg/blob/74815e6bbee93d0b570cf033939dd16acaf673e5/plugins/cleanpaste/trumbowyg.cleanpaste.js#L99
