### ISSUE TITLE
Custom Plugin To Revise B and I Buttons

### ISSUE THREAD

**Issue by volomike** [Alex-D/Trumbowyg#1185]
I'm a really strong Javascript coder, but still scratching my head on trying to figure out how to take this documentation:

https://alex-d.github.io/Trumbowyg/documentation/plugins/#create-your-own

...and then make a plugin that intercepts the B and I buttons so that instead of them doing STRONG and EM tags, they do B and I tags in the HTML.

Can you help guide me in the right direction?

**Comment by Alex-D** [comment]
You just need to switch `semantic: false` or customize the object :
https://alex-d.github.io/Trumbowyg/documentation/#semantic

**Comment by volomike** [comment]
Very good. Thank you.
