### ISSUE TITLE
Remove format button is not removing deleted/line through state

### ISSUE THREAD

**Issue by dngadelha** [Alex-D/Trumbowyg#1189]
Clicking the **Remove format** button is not removing deleted/line through state.

### Description
Windows 10
Chrome 87.0.4280.141 (Official Build) (64-bit)

### How to reproduce?
https://alex-d.github.io/Trumbowyg/

1. Type anything in the editor.
2. Select a text excerpt.
3. Click the **Deleted** state button.
4. Select the entire text.
5. Click the **Remove format** button.

**Comment by Alex-D** [comment]
Duplicates #1124 
Are you on the latest version of Trumbowyg?

**Comment by dngadelha** [comment]
@Alex-D It still occurs in the latest version.
