### ISSUE TITLE
Formatting of Insert Link pop up

### ISSUE THREAD

**Issue by Mugwomp** [Alex-D/Trumbowyg#119]
I have just implemented your code and think it is excellent but when I highlight text and click Insert Link the pop up that is revealed is formatted so that it is hard to read. I have checked this on several browsers all with the same result. 

The code is not password protected at present and can be seen at www.hdprint.co.uk/hdadmin/index.php if you would like to try it yourself.

I am sending a screenshot for your information.
![hdprint](https://cloud.githubusercontent.com/assets/12432139/7615131/5f7a7e8e-f993-11e4-9b24-1048ee8c0fb2.png)

Any ideas?

**Comment by Alex-D** [comment]
It's due to your code : you apply styles on `<input>` globaly insteed of scope it in a class on a form or something like this. I can't do anythink for that.
