### ISSUE TITLE
Upload after success function

### ISSUE THREAD

**Issue by Evrim267** [Alex-D/Trumbowyg#1198]
Hi,

```js
success : function(data){
  if (data.success == false) {
    Swal.fire({
      icon: 'error',
      text: data.message,
    });
  }
}
```

i have a code like this. If value is false it gives a swal error this is okay but if not plugin doesn't print image to editor even is image upload. If i remove the all success function it prints the image to editor. 

What i have to if data.success == true, print image to editor?

**Comment by Alex-D** [comment]
This not an event, it's a callback: that means that you can create your own custom success callback. If you just want to add a behavior, you need to copy/paste the original function and add your custom code to it.

See #1210
