### ISSUE TITLE
Button panel doesn't show the current status

### ISSUE THREAD

**Issue by ldani86** [Alex-D/Trumbowyg#12]
I am not sure it is a bug report or a feature request, but it would be nice if I could see the selected text's current status on the button panel (e.g.: if I bold the selected text and then I select it again the bold button is still off)

**Comment by ra100** [comment]
I have an idea how to make it work, but I don't know how to make it as plugin. I'd need to add listener on mousedown or keydown. 
Or would something like this work?
```
(function ($) {
    'use strict';

    $.extend(true, $.trumbowyg, {
          t.$ed.on('mousedown', function() {...})
    });
})(jQuery);
````

When I solve this, I can make module that will add .active class to buttons in trumbowyg panel. And also add some small css.

**Comment by Alex-D** [comment]
A contributor has send me a lot of code to resolve this problem. I just need to take the time to do this.

**Comment by hammat** [comment]
I'd be glad if I can be of any help !

**Comment by ra100** [comment]
I've done it with plugin https://github.com/ra100/Trumbowyg/commit/3b09bdf6d2a92b09a2bc72d992bd817ebbe56c83 but I also needed to add few lines of code to trumbowyg.js https://github.com/ra100/Trumbowyg/commit/8b2b04624c45991d27e41a26bcbadcf98f5a3c45 maybe there is better solution.

**Comment by Alex-D** [comment]
Note: a behavior of this issue is this sort of bug #226

**Comment by ra100** [comment]
I believe 0efbbcfe184d1adc78227cec138aebf0e67f717e adds this feature to core.

**Comment by Alex-D** [comment]
Yep, I've added and adapted your code to the core and make it extensible for plugins :)
