### ISSUE TITLE
Arrow of the Upload plugin's icon

### ISSUE THREAD

**Issue by ozgurg** [Alex-D/Trumbowyg#1200]
Hi.
I think the arrow of the [Upload](https://alex-d.github.io/Trumbowyg/demos/#plugins-upload) plugin's icon is upside down. What do you think?

![upload](https://user-images.githubusercontent.com/6717356/110806045-bb0d9e00-8292-11eb-9b64-8611ed37c6ed.jpg)

**Comment by Alex-D** [comment]
Why not ^^ you can make a pull request with the updated SVG if you want :)

**Comment by ozgurg** [comment]
I will then. 😃

**Comment by Alex-D** [comment]
Thank you, merged! :)
