### ISSUE TITLE
Is it possible to use MDI replace svg?

### ISSUE THREAD

**Issue by JackyRoss** [Alex-D/Trumbowyg#1202]
Awesome editor, I'm trying to use it in my application.
Just one question, is it possible to use MDI replace the svg icon? And really wanna know how to implement it. Thanks in advance.

**Comment by Alex-D** [comment]
Idk if you can, you can disable default icons and use your own, but Idk how Material Icons works so I can't help you more :/

**Comment by JackyRoss** [comment]
Thanks for response me. Anyway, I solved this problem.
