### ISSUE TITLE
The editor crashed after copying and pasting large text

### ISSUE THREAD

**Issue by Dyoniso** [Alex-D/Trumbowyg#1206]
### Description
After copying a large text, the editor crashes the page.
Is there any way to limit the text in the editor?

### How to reproduce?
1 - Copy text with more than 80000 characters
2 - Paste in the editor
3 - after that the page will crash

**Comment by ozgurg** [comment]
This is is about the browser. If you render very large content, many browsers are crashed.

**Comment by Dyoniso** [comment]
is there any way to limit the copied characters or to block the html when it is pasted into the editor?

**Comment by ozgurg** [comment]
> is there any way to limit the copied characters or to block the html when it is pasted into the editor?

Sorry, I don't know.

**Comment by Alex-D** [comment]
You can add a custom `pasteHandler`:

https://github.com/Alex-D/Trumbowyg/blob/80c1980c0a965c0684b9be1331b5b90a7211d8d1/plugins/allowtagsfrompaste/trumbowyg.allowtagsfrompaste.js#L149-L157

Sorry for the lack of documentation

**Comment by Dyoniso** [comment]
Thanks man, it worked perfectly :D
