### ISSUE TITLE
Upload module with PHP

### ISSUE THREAD

**Issue by lvalero** [Alex-D/Trumbowyg#1209]
Hello,

Problem : after successful uploading (the image is on the filesystem of the webserver), the upload dialog stays on the screen with a red border surrounding the file field and the image is not displayed.

I am using the upload php version here :

https://github.com/teppokoivula/InputfieldTrumbowyg/blob/master/trumbowyg/plugins/upload/trumbowyg.upload.php

The image is uploaded, the json output of the php script is \:

        $data = array(
            'message' => 'uploadSuccess',
            'file'    => $file,
        );

the developer tools on the browser shows it correctly.

I do not know if it can be an issue but i notice that the documentation states \:

It must save this image, then return a JSON response like that:
{
    success: true,
    file: 'https://example.com/myimage.jpg'
}

which differs from the output that produces the PHP file, so i changed for \:

        $data = array(
            //'message' => 'uploadSuccess',
            'success' => true,
            'file'    => $file
        );

And when i do that i have no more red border surrounding the file field (the image is still correctly uploaded) but on the console shows \:

Uncaught TypeError: r is undefined
    a https://***/Trumbowyg-master/dist/plugins/upload/trumbowyg.upload.min.js:1
    a https://***/Trumbowyg-master/dist/plugins/upload/trumbowyg.upload.min.js:1
    success https://***/Trumbowyg-master/dist/plugins/upload/trumbowyg.upload.min.js:1

Regards

**Comment by Alex-D** [comment]
Try to use the non-minified version of the plugin to get a more clear error. Check your network tab and be sure that everything is fine too.

Ensure that the URL that you send is a valid URL that can work and show the wanted image.
