### ISSUE TITLE
v1.1.7 tar contains v1.1.6 in files

### ISSUE THREAD

**Issue by jorrit** [Alex-D/Trumbowyg#121]
bower downloads https://github.com/Alex-D/Trumbowyg/archive/1.1.7.tar.gz, but the files contain version number 1.1.6. Is just the version number wrong?

**Comment by Alex-D** [comment]
Tar files are generated by Github base on tags.

When I check https://github.com/Alex-D/Trumbowyg/tree/1.1.7 both in bower.json and package.json I've 1.1.7 so I don't understand your point :/

**Comment by jorrit** [comment]
I was not specific, sorry. The .js files themselves contain '1.1.6'.

See:
 * https://github.com/Alex-D/Trumbowyg/blob/1.1.7/dist/trumbowyg.js
 * https://github.com/Alex-D/Trumbowyg/blob/1.1.7/dist/trumbowyg.min.js

**Comment by Alex-D** [comment]
It's OK. Juste I've build dist folder before upgrade version number in package.json :/

Sorry for that ^^"
