### ISSUE TITLE
Unable to use inputs in "insert link" modal

### ISSUE THREAD

**Issue by MelonSmasher** [Alex-D/Trumbowyg#1218]
### Description
When the insert link modal is presented I am unable to enter text into the inputs in the insert link modal. When I click on them the cursor does not select them and does not blink like I'm able to type. When I type after clicking nothing happens.
  - Windows, macOS
  - Firefox, Chrome

### How to reproduce?
  - click insert link
  - click on any text input in the modal
  - try to use the inputs

![Screen Shot 2021-05-06 at 10 21 09 AM](https://user-images.githubusercontent.com/1491053/117314472-cd502680-ae54-11eb-886e-9215017197a7.png)

**Comment by Alex-D** [comment]
Can you provide me a demo page with the bug?
I can't reproduce :/
Feel free to reopen if you have a working (I mean... a buggy :D) demo :)
