### ISSUE TITLE
Font size label and value

### ISSUE THREAD

**Issue by spacedog4** [Alex-D/Trumbowyg#1219]
Would be great if you could provide a list of labels and values on fontsize plugin, so I can do values as "2rem" but the user see "32px" or "32pt" I have to do accessibility on this website, so the paragraphs need to be in em or rem

**Comment by Alex-D** [comment]
You can already do this by using translations :)
I admit, its a little bit hacky, but you can put some labels like this:

```js
// 				   v--- 'en' or any language you are using
$.trumbowyg.langs.en.fontsizes = [
	'1rem': '14px',
	'1.2rem': '17px',
	'1.5rem': '21px'
};

$('#editor-custom-font-sizes')
.trumbowyg({
    btns: [
        ['fontsize']
    ],
    plugins: {
        fontsize: {
            sizeList: [
                '1rem',
                '1.2rem',
                '1.5rem'
            ],
            allowCustomSize: false
        }
    }
});
```
