### ISSUE TITLE
Problem on quote formating

### ISSUE THREAD

**Issue by gbiobob** [Alex-D/Trumbowyg#122]
Hi!
when a quote formatting is applied,
there is no way to remove the quote formatting or change it back to a paragraph
(the only way is to go back in source view, not friendly for most of users).

NB: great job on this tool, love it :)

**Comment by Alex-D** [comment]
Hi!
Thanks :)
Witch browser do you use? On Chrome 42 I can back to paragraph.

**Comment by gbiobob** [comment]
I use Firefox last beta release (38.0.5) and to be sure I also make my tests on http://alex-d.github.io/Trumbowyg/

On Opera & Safari it's working,
On IE11 the button for quote formatting do nothing (others format work)

**Comment by Alex-D** [comment]
It's a Firefox bug and an IE bug :( I can just develop polyfill but I prefer don't make my code heavier.
