### ISSUE TITLE
Hyperlinks don't respond to clicks

### ISSUE THREAD

**Issue by paparush** [Alex-D/Trumbowyg#1220]
### Description
I create a hyperlink to a website (https://www.google.com).  It looks like a hyperlink, but when I click it nothing happens. I can right click and select "Open link in new tab", and that works

### How to reproduce?
Highlight some text and click the hyperlink item on the toolbar and choose Insert Link.  
Supply the url.  Example: https://www.google.com.  
Click Confirm
The result LOOKS like a hyperlink but does not behave like one. My users are not going to want to right click and select "Open link in new tab" to navigate. This is happening in Chrome Version 90.0.4430.212 (Official Build) (64-bit), and MS Edge Version 90.0.818.66 (Official build) (64-bit)

**Comment by Alex-D** [comment]
That's the default browser behavior with links in _content editable_ divs
So, yeah, that's not a bug, it's a feature :)
