### ISSUE TITLE
Trumbowyg editor Inline Styling Causing CSP issues

### ISSUE THREAD

**Issue by akhil4454** [Alex-D/Trumbowyg#1222]
### Description
When I try to format the content using alignment button. It adds inline styling on the selection. While in our project we are having restriction that doesn't permit inline style to be executed. 
Is there any way we can define classes based on command, and instead of adding the inline style it add the defined class. Or I can provide a nonce value while configuring trumbowyg and same nonce gets apply to all inline style that gets apply.

### How to reproduce?
Restrict the Project CSP rule not to allow inline style.(Remove Unsafe-inline)
Add some content in the editor.
try to align the content.

**Comment by Alex-D** [comment]
Feel free to create your very own plugins that add classes instead of inline style :)
