### ISSUE TITLE
Escape all HTML Entities

### ISSUE THREAD

**Issue by CalvT** [Alex-D/Trumbowyg#1224]
Right now Trumbowyg escapes characters such as `<` and `>` into `&lt;` and `&gt;` which is great.

However it doesn't escape apostrophes and quotes into `&apos;` and `&quot;` (I'm guessing there could be a few others, but these are the ones that are important to me). 

Could this be changed? Or could you point me to the area Tumbowyg does the current escaping so I can look at fixing this?

Thanks

**Comment by Alex-D** [comment]
Trumbowyg does not do this, it's the browser since Trumbowyg is based on a content editable div.

Sooo, there is no code to point you to :/

Why do you not manage that on form submit, or on the server-side?
