### ISSUE TITLE
JavaScript error when invoking editor

### ISSUE THREAD

**Issue by Bikermart** [Alex-D/Trumbowyg#1229]
The problem occurs in both IE and Chrome.
The editor is invoked on a <textarea> which has been pre-populated with text.

When the amount of text is just a few lines, the icons show.
When the amount of text is large, with a number of html tags, the icons do not show and a JavaScript error occurs:
trumbowyg.min.js:12 Uncaught TypeError: Cannot read property 'startContainer' of null
    at HTMLElement.<anonymous> (trumbowyg.min.js:12)
    at Function.each (jquery.min.js:2)
    at S.fn.init.each (jquery.min.js:2)
    at i.semanticTag (trumbowyg.min.js:12)
    at i.semanticCode (trumbowyg.min.js:12)
    at i.buildEditor (trumbowyg.min.js:12)
    at init (trumbowyg.min.js:12)
    at new i (trumbowyg.min.js:12)
    at HTMLTextAreaElement.<anonymous> (trumbowyg.min.js:12)
    at Function.each (jquery.min.js:2)

Is it possible that something within the text is causing this? Maybe a character such as an apostrophe, or an HTML tag?

**Comment by Alex-D** [comment]
If you can make a demo of this bug, I can check :)

**Comment by Bikermart** [comment]
Alex,

Can you try this URL:
https://abilitylms_nextgen.learnerhall.com/AbilityLMS_NextGen/Programs/Standard/Control/mb.php

You will see two textarea elements.
One displays the icons and the other does not.

Merci bien!
Martin

**Comment by Bikermart** [comment]
Alex,

Were you able to look at this issue?

Thanks,
Martin

**Comment by Alex-D** [comment]
Oh sorry, I did not ping you ^^'

I think I've fixed this in last version, see https://github.com/Alex-D/Trumbowyg/commit/5ad49f30e31cc9a543f9dfc7c1d9a33bd6c3bae5

If not, tell me :)
