### ISSUE TITLE
Line wrapping issue on Edge and Chrome,but on Firefox is fine 

### ISSUE THREAD

**Issue by Shayimerdan** [Alex-D/Trumbowyg#1236]
When I am pressing Enter to wrap lines,I am getting unknown spaces between each lines on Edge and Chrome,but on Firefox is fine.I have also set the semantic as false.

The issue:
![edge trum](https://user-images.githubusercontent.com/64922285/126966936-75048182-5263-44a2-bf73-743771fedd65.jpg)

But on Firefox is fine:
![ff trum](https://user-images.githubusercontent.com/64922285/126966977-386afe5c-7675-4378-9e48-cd0eb6818ba0.jpg)

  - OS: Ubuntu
  - Browser: Edge and Chrome

**Comment by Alex-D** [comment]
Probably because Firefox has a bug and does not create paragraphs when you hit enter, or the p tag does not have the same style in both browsers?

**Comment by Shayimerdan** [comment]
> Probably because Firefox has a bug and does not create paragraphs when you hit enter, or the p tag does not have the same style in both browsers?

No it works perfectly on Firefox,but as you see in first pic,on Edge there are unknown spaces between each two lines up and down.

**Comment by Alex-D** [comment]
Is the HTML the same in all browsers?

**Comment by Shayimerdan** [comment]
> Is the HTML the same in all browsers?

yes,same HTML

**Comment by Alex-D** [comment]
So, the issue is in your CSS, check the margins on `<p>` tags or something like that

**Comment by Shayimerdan** [comment]
> So, the issue is in your CSS, check the margins on `<p>` tags or something like that

trumbowyg.css you mean?

**Comment by Alex-D** [comment]
No, *your* CSS.

I can't reproduce the issue on my side here: https://alex-d.github.io/Trumbowyg/
So you need to define the `<p>` margin/padding

One of the goals of Trumbowyg is to show you exactly how your content will be shown. So if there is a style issue here, you will get a style issue on your final page. If you don't care about getting the same style in the WYSIWYG and on your page, [you can use the `resetCss` option](https://alex-d.github.io/Trumbowyg/documentation/#reset-css)

**Comment by Shayimerdan** [comment]
> No, _your_ CSS.
> 
> I can't reproduce the issue on my side here: https://alex-d.github.io/Trumbowyg/
> So you need to define the `<p>` margin/padding
> 
> One of the goals of Trumbowyg is to show you exactly how your content will be shown. So if there is a style issue here, you will get a style issue on your final page. If you don't care about getting the same style in the WYSIWYG and on your page, [you can use the `resetCss` option](https://alex-d.github.io/Trumbowyg/documentation/#reset-css)

This is exactly what I mean.That paragraph that you wrote,between two lines up and down there is no space,it is perfect.
But when I write something,there are so huge spaces between two lines.
![te](https://user-images.githubusercontent.com/64922285/126983750-148a813a-c8aa-4b04-976e-e9675a1a458c.jpg)

**Comment by Alex-D** [comment]
Check the CSS, really, please.

**Comment by Shayimerdan** [comment]
> Check the CSS, really, please.

ok i will check,thanks

**Comment by Shayimerdan** [comment]
> Check the CSS, really, please.

It was really a CSS problem,sorry for taking your time and thank you for the reply.
