### ISSUE TITLE
[Feature Request] Separate minified files from uncompressed

### ISSUE THREAD

**Issue by timint** [Alex-D/Trumbowyg#1239]
Hi, Tim here from LiteCart. Love the work! Been supporting Trumbowyg since the very beginning.

I'd like to propose that the minified/uglified files are separated from the uncompressed files in the dist/ folder. There is not much purpose in uploading both to a website.

I am obsessed with leghtweight. So I am only redistributing the minifed files with LiteCart. And it's a lengthy process to browse around removing the uncompressed files upon every new update of Trumbowyg. Yes, I could automize this. But I wanted to share my thoughts for improvements.

**Comment by timint** [comment]
A commit can be cherry picked here if you like
https://github.com/timint/Trumbowyg/commit/036c35eac48d861fd35817327dd1c4a045bda556

**Comment by timint** [comment]
@Alex-D Any comments?

**Comment by Alex-D** [comment]
It will be a major release if I do that since there are people using the non-minified files and making their own build. I do not want to release a major just for that.
Also, today, people use bundlers like esbuild, webpack, parcel, etc. to only bundle used files.
So, I do not think to do that today nor later.

**Comment by timint** [comment]
Oh well, I had the job made for you already. Do what you like with it.
https://github.com/Alex-D/Trumbowyg/pull/1267/commits/a50dbe4c6ae06e5388d2969cb17e831ae679adb6

**Comment by timint** [comment]
Wouldn't it be convenient if you had 3 branches?
- minor-dev
- major-dev
- master/release
