### ISSUE TITLE
Button Pane on Safari

### ISSUE THREAD

**Issue by bonster21** [Alex-D/Trumbowyg#124]
First let me thank you for the excellent Trumbowyf editor - I love it! 
I've come to a small problem with the rendering of the button pane in Safari on Mac and iPad. The buttons (excluding the fullscreen toggle button which is a float: right) seem like they have a padding-top. The separators between the buttons are displayd correctly, but the buttons themselves are too far down. I've attached a screenshot to make it more clear what I'm saying.
![screenshot](https://cloud.githubusercontent.com/assets/12571155/7783256/e692cd0e-013b-11e5-821c-406541998bf4.jpg)
I've tried all things I could think of in CSS but didn't manage to get it to display correctly. Any ideas? Is this a known problem?
Thank you so much for taking the time to answering it. Have a nice weekend!

**Comment by vitosamson** [comment]
I was able to work around this issue by applying `margin-bottom: -13px` to the divider elements. I'm doing this conditionally in my script:
```js
var appVersion = navigator.appVersion;
if (appVersion && appVersion.indexOf('Safari') > -1 && appVersion.indexOf('Chrome') === -1) {
  $('li.trumbowyg-separator').css('margin-bottom', '-13px');
}
```

**Comment by Alex-D** [comment]
I've fix it on master.
