### ISSUE TITLE
How do I change the behavior of a align button ?

### ISSUE THREAD

**Issue by edreamwork** [Alex-D/Trumbowyg#1249]
The Align Left button adds style = "text-align: left" to the wrapper. I dont want to have any inline style in my code. So I have the below css
```
align-left {
 text-align:left;
}

```
How do I modify that button so that it would **add** align-left class to the wrapper instead of adding the inline style ?

**Comment by Alex-D** [comment]
You cannot do that with version 2.

I keep that in mind for Trumbowyg 3 :)
