### ISSUE TITLE
New plugin icon not showing

### ISSUE THREAD

**Issue by antoniofalcone89** [Alex-D/Trumbowyg#1250]
Hi, i'm developing a new plugin, this is the folder structure (taken from docs):

plugins
 └── internalLink
     ├── ui
     │   ├── icons
     │   │   └── internalLink.svg
     └── trumbowyg.internalLink.js

There's no sass folder because i don't need any style customization. 
Icon is not showing in the editor: 

![image](https://user-images.githubusercontent.com/22471336/132184536-29c1ad5f-1c58-4bbc-b873-6148a30cd815.png)

Can you give me support? 
Thank you

**Comment by Alex-D** [comment]
If you are building a custom version of Trumbowyg with this plugin, you can follow instructions from README to rebuild the projet.
Check the gulp task code here: https://github.com/Alex-D/Trumbowyg/blob/fd304a39433b5918291824bfe961bb54d60bfc29/gulpfile.js#L100-L106

If you just want to add this icon, you can inject your icon as a SVG sprite into your HTML.

**Comment by antoniofalcone89** [comment]
Solved by adding <symbol> with my custom plugin id in icons.svg. 
Thank you for your quick reply!
