### ISSUE TITLE
Font-size is only updated once, then is no more updated

### ISSUE THREAD

**Issue by BenMonteiro** [Alex-D/Trumbowyg#1252]
It seemed that the span tag is not removed when the font size of an element is updated more than one time

![font-size issue](https://user-images.githubusercontent.com/50099945/133401525-7ac9bdd2-c29b-40e8-afda-133241881c56.png)

**Comment by Alex-D** [comment]
Hey!

As you did not follow the issue template, please, can you give me more details? I can't reproduce here: https://alex-d.github.io/Trumbowyg/demos/#plugins-fontsize

Issue template: https://github.com/Alex-D/Trumbowyg/blob/develop/.github/ISSUE_TEMPLATE.md?plain=1

**Comment by kevinlem14** [comment]
Hi,

I can reproduce this problem too here : https://alex-d.github.io/Trumbowyg/demos/#plugins-fontsize
Browser : Firefox 92
OS : Ubuntu

Just select all the line (with triple clicks for example) and change the size.

**Comment by aeyoll** [comment]
Hello @Alex-D,
Did you had the chance to take a look at this issue please? Thanks a lot!

**Comment by Alex-D** [comment]
Will be deployed in the next release
