### ISSUE TITLE
 Hire Freelance to implement a role in the print component

### ISSUE THREAD

**Issue by PauloLaurino** [Alex-D/Trumbowyg#1255]
We implemented this fantastic Editor in our project, we are using it not as a web page editor, but as a document EDITOR, when printing the document we define that the text is justified with left and right margins in the A4 sheet pattern, the What we can't do is define a header with an image (jpg) and a page numerator starting at an informed counter, for example it should start at number 13 on the next page the header must have page 14 etc., we intend to invest in this implementation so we are looking for a freelancer who can make us a commercial proposal.

If you are interested, contact: paulo@seprocom.com.br

**Comment by Alex-D** [comment]
Duplicates #1254
