### ISSUE TITLE
how to modify config after init?

### ISSUE THREAD

**Issue by webasoo** [Alex-D/Trumbowyg#1256]
### Description
how to modify config after init?
ex: modify items of dropdowns .

**Comment by Alex-D** [comment]
Hey!

You can't, but you can destroy + init with a new config.

**Comment by webasoo** [comment]
Hey! thanks, but
Unfortunately I use the  [vue-trumbowyg](https://www.npmjs.com/package/vue-trumbowyg) package. And it does not have this feature ! :(

**Comment by KR34T1V** [comment]
@webasoo Were you able to solve your issue somehow?

**Comment by webasoo** [comment]
@KR34T1V 
I add key-prop to  vue-trumbowyg component.
ex: <my-editor :key="index" />
In every update, I change "index" data, therefore the component is updated!
(vue-trumbowyg is in my-editor)
