### ISSUE TITLE
Remove format button is not removing deleted/line through state

### ISSUE THREAD

**Issue by dngadelha** [Alex-D/Trumbowyg#1260]
Clicking the **Remove Format Button** is not removing **deleted/line through state**.

Description
Windows 10
Chrome 95.0.1020.30 (Official Build) (64-bit)

How to reproduce?
https://alex-d.github.io/Trumbowyg/

1. Type anything in the editor.
2. Select a text part.
3. Click the Deleted state button.
4. Select the entire text (CTRL + A).
5. Click the Remove format button.

**Comment by brvoisin** [comment]
I have the same issue.
When I select a text "deleted" and I click on the Delete button or the Remove format button, nothing changes.

1. Go to https://alex-d.github.io/Trumbowyg/
2. Replace all the text by a random word
3. Select the word
4. Click the Deleted button
5. Select the word again
6. Click the Deleted button (no effect)
7. Select the word again
8. Click the Remove format button (no effect)

**Comment by Alex-D** [comment]
It's a known issue, a browser-level bug, and cannot be fixed easily.

Wait for Trumbowyg 3 :)
