### ISSUE TITLE
Bug with formatting text on Chrome

### ISSUE THREAD

**Issue by Fayrefiive** [Alex-D/Trumbowyg#1263]
Hi, i'm french and i'm sorry if my english isn't the best
I've a problem issue when i use trumbowyg editor on Chrome

When i write text and i click on "Formatting", the page freeze and i cant't do anything anymore.
I don't have the problem on Firefox and Chromium.
I'm in version 2.25.1, i've test with CDN, i've test in version 2.24, and i've the same issue

It's little weird because i've use it many time to make article for blog, and now it crash

This is my code for test :

    <head>
        <link rel="stylesheet" href="admin/trumbowyg/dist/ui/trumbowyg.min.css">
        <link rel="stylesheet" href="admin/trumbowyg/dist/plugins/colors/ui/trumbowyg.colors.min.css">
    </head>
    <body>
        <div id="trumbowyg"></div>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="admin/trumbowyg/dist/trumbowyg.min.js"></script>
        <script src="admin/trumbowyg/dist/plugins/colors/trumbowyg.colors.min.js"></script>
        <script src="admin/trumbowyg/dist/plugins/upload/trumbowyg.upload.min.js"></script>
        <script src="admin/trumbowyg/dist/plugins/base64/trumbowyg.base64.min.js"></script>
        <script src="admin/trumbowyg/dist/plugins/pasteimage/trumbowyg.pasteimage.min.js"></script>
        <script src="admin/trumbowyg/dist/plugins/fontsize/trumbowyg.fontsize.min.js"></script>
        <script>
            $('#trumbowyg').trumbowyg({
                btns: [
                    ['viewHTML'],
                    ['formatting'],
                    ['strong', 'em', 'underline', 'del'],
                    ['fontsize', 'foreColor', 'backColor'],
                    ['superscript', 'subscript'],
                    ['link', 'base64'],
                    ['justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
                    ['unorderedList', 'orderedList'],
                    ['horizontalRule'],
                    ['removeformat'],
                    ['undo', 'redo'],
                    ['fullscreen']
                ],
                autogrow: true,
                defaultLinkTarget: '_blank',
                plugins: {
                    colors: {
                        colorList: [
                            'ffffff', 'cccccc', '999999', '777777', '555555', '333333', '000000', 'cabc80', 'baac70', 'e9c9b1', '582900',
                            'ff0000', 'ffa500', 'ffff00', '90ee90', '00ff00', '008000', '006400', 'add8e6', '00bfff', '0000ff', '00008b',
                            '4b0082', '800080', 'ff1493', 'ffc0cb'
                        ]
                    }
                }
            });
        </script>
    </body>

**Comment by Alex-D** [comment]
Duplicates #1259
