### ISSUE TITLE
Corrupt styling when editing text

### ISSUE THREAD

**Issue by CarlAtIssl** [Alex-D/Trumbowyg#1265]
### Description

If you create some text 👎 
Outside there is a block paved garden to the front and to the rear is the yard.

Entrance Hall

Then, highlight "Entrance Hall", make it bold
Place your cursor before the E and press delete until your cursor is at the "yard."
Press the </> button, there is a spurious:
```<b style="font-size: 1.6rem;">Entrance Hall</b>```

This has got to be a bug????

**Comment by Alex-D** [comment]
Cannot reproduce anymore :)
