### ISSUE TITLE
Image Description label exceeds button

### ISSUE THREAD

**Issue by dandv** [Alex-D/Trumbowyg#127]
![image](https://cloud.githubusercontent.com/assets/33569/7907136/66b890ea-07ea-11e5-9245-dee91ab64fbc.png)

**Comment by Alex-D** [comment]
Navigator ? Version ? Screen size ?

Thanks :)

**Comment by Alex-D** [comment]
Fix pushed to demo page :)

**Comment by dandv** [comment]
Awesome, thanks! I've added it to [AlternativeTo](http://alternativeto.net/software/trumbowyg/) because everyone knows about bloated libraries like TinyMCE and CKEditor, but not about Trumbowyg. Can't wait for #135  :)
