### ISSUE TITLE
Critical: Applying formatting e.g. h1 hangs the web browser and cooks cpu

### ISSUE THREAD

**Issue by timint** [Alex-D/Trumbowyg#1271]
As reported by a user in the LiteCart Forums I can confirm an issue where applying formatting hangs the web browser with cpu going wild. (Reference: https://www.litecart.net/en/forums/15/errors-and-troubleshooting/15666/how-to-solve-trumbowyg-bug)

It is reproduced here with cdnjs sources.
https://jsfiddle.net/timint/97fgj5w6/

Simply select text and apply a formatting e.g. h1.

  - Windows 11
  - Chrome + 95.0.4638.54 (Official)
  - 1920x1200

**Comment by Alex-D** [comment]
Duplicates #1259
