### ISSUE TITLE
Problem to center text after delete chip

### ISSUE THREAD

**Issue by Fayrefiive** [Alex-D/Trumbowyg#1273]
Hello,

I've a problem when i want to center text after deleting the list of chip.
In the code i see the "text-align: center", but in visual the text stay left-align. 
The left and right align works, but center and justify doesn't work after deleting chip.

### Description
OS: Windows 7, WIndows 10
Browser : Chrome, Firefox and Safari

### How to reproduce?
-> Have a text center with a chip
-> delete chip
-> center text or justify
-> Doesn't work in the rendering, but in the code I see the attributes

Best Regards for your job,

LAULY Téo

**Comment by Alex-D** [comment]
Cannot reproduce :/
