### ISSUE TITLE
Position: sticky - editor panel

### ISSUE THREAD

**Issue by anielka41** [Alex-D/Trumbowyg#1277]
Hi,
as I have a lot of content, you have to go back to the top to use the options in the edit panel. Can you add Position: sticky?

**Comment by Alex-D** [comment]
There is an undocumented option to do that, named `fixedBtnPane`, you can pass it to `true` to get a fixed button pane :)

If you want the button pane to go full width, you have `fixedFullWidth: true` for that.

I should add this to the doc ^^'
