### ISSUE TITLE
Z-index of popups needs to be higher

### ISSUE THREAD

**Issue by dandv** [Alex-D/Trumbowyg#128]
Paste some code block from [Addy Osmani's book](http://addyosmani.com/resources/essentialjsdesignpatterns/book/) and notice how the `?` in the upper right corner of the box shows up on top of the Add image pop-up/

![image](https://cloud.githubusercontent.com/assets/33569/7907166/dc688228-07ea-11e5-908b-26e19ce6917d.png)

**Comment by Alex-D** [comment]
Fix'd on master
