### ISSUE TITLE
[Feature Request] No sloppy markup

### ISSUE THREAD

**Issue by timint** [Alex-D/Trumbowyg#1283]
Hi I would like to propose a change to proper HTML markup.

To turn this:
`<h1></h1><p>...</p><p><img src="..."></p><p><br></p>`

Into:
```
<h1>...</h1>

<p>...</p>

<p><img src="..." /></p>

<p><br />
</p>
```

No sloppy coding like `<img>` and `<br>`, but instead properly `<img />` and `<br />`.
Headers, and paragraphs nicely separated by double \r\n.
Line breaks `<br />` with \r\n after.

Toggling the source code mode would be much nicer and effective this way.

**Comment by Alex-D** [comment]
I will not add something like this since it is hard to get it right.
