### ISSUE TITLE
Need an Upload file plugin(Not images)

### ISSUE THREAD

**Issue by humamabd** [Alex-D/Trumbowyg#1287]
I've came across a plugin built by @jakejohns in this issue #987 for uploading files like pdfs or docs. But it doesn't seem to be working in firefox browser(v 97.0.1). Can anybody help with this? It seems like `createLink` command is not working or `a` tag is not getting added to `trumbowyg.$box` in the uploadfile plugin [in this repo branch](https://github.com/jakejohns/Trumbowyg/tree/feature/uploadfile/plugins)

**Comment by humam-abd** [comment]
See this PR #1289
