### ISSUE TITLE
Tag classes dont set class to img

### ISSUE THREAD

**Issue by solich** [Alex-D/Trumbowyg#1291]
Hi. When configuring Tag classes, everything is ok (no error in the console), but it is not added class for the img tag in the editor. When can there be a problem?

Code configuration:
```js
tagClasses: {
		h2: 'highline2Editor',
		h3: 'highline3Editor',
		img: 'imageEditor',
		p: 'paragraphEditor',
	},
```

Trumbowyg v2.25.0

**Comment by wromthrax** [comment]
It also doesn't work for paragraph (p) elements unless you explicitly press the paragraph button in formatting menu.

**Comment by Alex-D** [comment]
Duplicates #1227
