### ISSUE TITLE
Enable the user to upload an image

### ISSUE THREAD

**Issue by dandv** [Alex-D/Trumbowyg#130]
Is this possible somehow not shown in the demo?

*UPDATE*: I see an [upload plugin](https://github.com/Alex-D/Trumbowyg/tree/2.0.0-beta.2/plugins/upload). Adding it to the demo would help show this feature to users. I almost marked it as "no" in this [comparison table](http://socialcompare.com/en/comparison/javascript-online-rich-text-editors).

**Comment by Alex-D** [comment]
I've added upload plugin to demo page but I don't have put any server-side script, so that's juste a visual demo.

**Comment by dandv** [comment]
Maybe [upload to an imgur account](https://hacks.mozilla.org/2011/03/the-shortest-image-uploader-ever/) for the demo, no server-side script necessary?

**Comment by comtronix** [comment]
When uploading an image the result after uploading is wrong.
The succes message is reporting a url back like this:

<img src="/js/trumbowyg/plugins/upload/sites/domain.com/subdomains/images/httpdocs/files/image.jpg">

**Comment by Alex-D** [comment]
Maybe you need to put the protocol before your link:

`https://domain.com/subdomains/images/httpdocs/files/image.jpg`

**Comment by Alex-D** [comment]
You can now upload images for demo page :)
