### ISSUE TITLE
Fullscreen mode, background color changed to white

### ISSUE THREAD

**Issue by hy-net** [Alex-D/Trumbowyg#1302]
When using with bootstrap dark mode (background black, foreground white), the background will switch to white and foreground remains white when enter .trumbowyg-fullscreen mode

I mitigate this issue by adding:

.trumbowyg-fullscreen	{
    background-color: var(--bs-body-bg) !important;
}

**Comment by Alex-D** [comment]
Please try using Trumbowyg dark theme:
https://alex-d.github.io/Trumbowyg/demos/#core-dark-theme
