### ISSUE TITLE
The full screen button is invisible if it is the only button in it's row

### ISSUE THREAD

**Issue by hy-net** [Alex-D/Trumbowyg#1303]
I need to add the follow CSS show that it will appears.

.trumbowyg-button-group.trumbowyg-right {
   background: #ecf0f1 !important;
}

Example:

![image](https://user-images.githubusercontent.com/55421612/168454144-b4ce1891-b09e-4ef6-9b9b-a5581cd7f775.png)

The button will be invisible without the CSS above

**Comment by Alex-D** [comment]
Edge case that I will not fix in version 2, sorry :/

Wait for Trumbowyg 3 :)
