### ISSUE TITLE
Trumbowyg don't die

### ISSUE THREAD

**Issue by ZeoNish** [Alex-D/Trumbowyg#1305]
Don't die, my beloved editor. I really hope that there will be life. This is the best editor that I have used in my projects. Thank you for it.

**Comment by Alex-D** [comment]
Hi!
I'm working on other projects. One of them is that [I'm creating a video game studio](https://spilium.com) ^^
I want to work on the v3, but I need tons of time to hope to get an initial version of it.

Thank you for your support and your kind words :)
