### ISSUE TITLE
Cannot press Enter to create new line

### ISSUE THREAD

**Issue by Miaozxje** [Alex-D/Trumbowyg#1306]
I just get started using Trumbowyg today and I find a problem with Trumbowyg when I tried to have a new line with "Enter" key

Provide relevant details according to the context:
  - OS: Windows 11 21H2
  - Browser + version: Chrome Version 102.0.5005.63
  - Screen resolution: 1920 x 1080

This is a video record of the issue I have
https://user-images.githubusercontent.com/72405743/171778802-51eef96e-65d2-4cd7-bd6c-2a2fd444dec7.mp4

This is the setting of Trumbowyg
![image](https://user-images.githubusercontent.com/72405743/171778873-e3722560-f115-4e6b-8992-3e11fe35b37d.png)

**Comment by Alex-D** [comment]
Cannot reproduce :/
