### ISSUE TITLE
Closing tags on <br> <img>

### ISSUE THREAD

**Issue by iwolfm** [Alex-D/Trumbowyg#1307]
The current implementation adds
`<br>` for line breaks
and 
`<img src="" alt="">` for images
as code.
It would be very appreciated if this can be changed to `<br />` and `<img src="" alt="" />` as it would ease some efforts on other projects when it comes to application security checks (OWASP). Some sanitizers fail if a tag is not closed.

**Comment by renoth** [comment]
This is indeed an issue when parsing the markup with other tools for example SAXParser in Java
