### ISSUE TITLE
Working on localhost not on live server

### ISSUE THREAD

**Issue by rashhworld** [Alex-D/Trumbowyg#1308]
The editor works fine with a local server, but when deployed on a live server, the editor input is not getting submitted.
And also it somehow causes issues with jquery validation.
![image](https://user-images.githubusercontent.com/54672825/175553007-34119e70-a653-4bf0-94db-39ef462297c3.png)

**Comment by Alex-D** [comment]
Which Trumbowyg version?
Which jQuery Validates version?
Can you send me a demo page that reproduces the error, based on: https://jsfiddle.net/AlexandreDemode/p7hb3x6u/

Feel free to reopen the issue if you have more details.

**Comment by rashhworld** [comment]
> Which Trumbowyg version? Which jQuery Validates version? Can you send me a demo page that reproduces the error, based on: https://jsfiddle.net/AlexandreDemode/p7hb3x6u/
> 
> Feel free to reopen the issue if you have more details.

I am using,
Trumbowyg v2.25.1
jQuery v3.6.0
jQuery Validation Plugin - v1.19.3

I have uploaded a video u can see

[https://vimeo.com/724113074](url)

**Comment by Alex-D** [comment]
Check this: 
https://github.com/Alex-D/Trumbowyg/issues/259#issuecomment-830746809

or this: 
https://github.com/Alex-D/Trumbowyg/issues/259#issuecomment-1078728435
