### ISSUE TITLE
Cycling code view destroys formatting

### ISSUE THREAD

**Issue by dandv** [Alex-D/Trumbowyg#131]
In the mode, paste the first code block from http://addyosmani.com/resources/essentialjsdesignpatterns/book/#mixinpatternjavascript. It looks good enough. Now go to the code view, and back to WYSIWYG view. The formatting will be lost. Related to #103?

[Summernote](http://summernote.org) handles this correctly.

**Comment by Alex-D** [comment]
I think this was fix'd yesterday on master. I need to make a new beta.

**Comment by Alex-D** [comment]
Fix'd on `2.0.0-beta.4` and visible on demo page.

**Comment by dandv** [comment]
Thanks for the quick fix. The formatting looks much better now.

Only the black background is lost:

![image](https://cloud.githubusercontent.com/assets/33569/7928131/d1576f42-089f-11e5-95aa-e0e4e7812b7b.png)

**Comment by Alex-D** [comment]
Strange, on my Chrome I've got the background :/
