### ISSUE TITLE
Error in rendering

### ISSUE THREAD

**Issue by r-a-s-h-h** [Alex-D/Trumbowyg#1313]
On the editor page, when i click to insert code, it render perfectly
![image](https://user-images.githubusercontent.com/54672825/184387447-2cb43044-79c5-47c0-8e67-d54ad0365bc6.png)

But when I see what get inserted, it render like this
![image](https://user-images.githubusercontent.com/54672825/184387649-ed4a633e-b87f-46cb-b641-663c1af1102d.png)

And when I click to edit the content, it render like this
![image](https://user-images.githubusercontent.com/54672825/184387765-f47ef1be-e720-42e5-b7c5-d5d091d55a22.png)

How to fix this?
Using latest JQuey and latest trumbowyg

**Comment by Alex-D** [comment]
I cannot reproduce :/

Feel free to reopen with an example page of this issue.
