### ISSUE TITLE
Where to get additional icons?

### ISSUE THREAD

**Issue by urosg80** [Alex-D/Trumbowyg#1320]
I am working on some additional functionality (column resizing, table borders, CSS class styling per cell, row, column, table) for Table plugin but would need some more icons for the toolbar.

Are the default icons from some icon pack or are all your artwork @Alex-D?

**Comment by Alex-D** [comment]
Amost all Icons were made by @adriengervaix for Trumbowyg. So there is no other icons available.
What is the need?

**Comment by urosg80** [comment]
At this moment I would like to include icons for setting table borders.

For now I have implemented functionality for these types - excerpt from MS Word:
![borders](https://user-images.githubusercontent.com/11760571/185416736-3b6af162-2c7f-44fe-b4c8-a919225d5293.PNG)

For CSS class styling I modified the icons that come with Trumbowyg like this:
![css](https://user-images.githubusercontent.com/11760571/185417170-45fe3d8a-bda1-4660-9670-da08d0a504ba.PNG)

Small demo of my changes so far:

https://user-images.githubusercontent.com/11760571/185419498-1844fb0f-3b91-4907-8afb-dbae47896ccf.mp4

**Comment by Alex-D** [comment]
Oh, nice! :)
If you can list all needed icons, I can check if I can create them or ask the original designer

**Comment by urosg80** [comment]
If the icons I made for CSS class settings (the yellow fill) are OK then these I can leave; but the icons I would like to use are the ones marked in the excerpt from MS Word - for:
- Table borders (as drop down menu)
- No border
- All borders
- Outside borders
- Inside borders
- Vertical borders
- Horizontal borders

Then I think it would be nice to give the user the option to select border type - so extra icons are needed:
- Single border (solid)
- Double border (double)
- Dotted border (dotted)
- Dashed border (dashed)

And with that also the border width - this would be a "spin edit".

**Comment by Alex-D** [comment]
Please submit a PR, this will be more simpler for me to follow :)

**Comment by urosg80** [comment]
Will do as soon as possible, unfortunately I am currently busy with other projects.

**Comment by Alex-D** [comment]
I made the last table icons, so I could create more.

Note that since then, the Table plugin has been completely rewritten.

I close this, feel free to post here or reopen if needed :)
