### ISSUE TITLE
"Strikethrough" button of text-editor is not working properly

### ISSUE THREAD

**Issue by farhank31** [Alex-D/Trumbowyg#1322]
When we select a particular word and add a strikethrough to that word it's get added and without removing the selection if we again click on the strikethrough button then its get removed but when the cursor is moved or the selection from the highlighted word is removed and if we again try to select the same word and click on the strikethrough button the word remains unchanged and the cursor is moved to the end of that word and the word remains deleted.

**Comment by Alex-D** [comment]
Known issue, its a browser-level bug :(
