### ISSUE TITLE
Auto-hyperlink

### ISSUE THREAD

**Issue by dandv** [Alex-D/Trumbowyg#133]
When tying an `http(s)://` link, it would be nice if Trumbowyg automatically hyperlinked it.

I've done the research on [auto-hyperlinking plugins on StackOverflow](http://stackoverflow.com/questions/37684/how-to-replace-plain-urls-with-links/21925491#21925491).

**Comment by comtronix** [comment]
..make it as an option to disablle/enable it.

**Comment by Alex-D** [comment]
Autolink plugins have the same size like Trumbowyg itself... It's not cool :/

Maybe I will see for an simplified version of that feature.

**Comment by dandv** [comment]
Plugin

**Comment by Alex-D** [comment]
Maybe but not for now.

**Comment by AdamHess** [comment]
how about just explicit links, like http(s)://  (or http(s):\\)

**Comment by Alex-D** [comment]
Too hard, I don't have the time :/
