### ISSUE TITLE
Node Sass no longer supported

### ISSUE THREAD

**Issue by timint** [Alex-D/Trumbowyg#1335]
The build tools needs a replacement for node-sass. Which only supports node v14.

> Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (108)
> For more information on which environments are supported please see:
> https://github.com/sass/node-sass/releases/tag/v4.14.1
>
> Node.js v18.2.0

**Comment by timint** [comment]
A fix can be cherry picked here
https://github.com/timint/Trumbowyg/commit/0b34918348f56ec9e70efa71377ffee0e4262e61

**Comment by Alex-D** [comment]
Done too, thank you :)
