### ISSUE TITLE
Update node dependencies

### ISSUE THREAD

**Issue by timint** [Alex-D/Trumbowyg#1337]
A commit can be cherry picked here taking the node dependencies up to date. Compatible with latest Node 18.
https://github.com/timint/Trumbowyg/commit/80a187bcd6609c73f3441c4f25b5a3a1f4689050

Note: the last versions of del and vinyl-paths do not support CommonJS and this commit holds the CommonJS versions.

**Comment by Alex-D** [comment]
I'm on it, thank you for the suggestion :)
