### ISSUE TITLE
Wrong locale for Norwegian patch

### ISSUE THREAD

**Issue by timint** [Alex-D/Trumbowyg#1338]
The norwegian language patch no_nb.js should be "nb.js".
"no" is not a language code, but nb is Norwegian (Bokmål).
System Locale nb-NO. NO is the only dialect for bokmål, so nb is good enough.

Commit for cherry pick is available here:
https://github.com/timint/Trumbowyg/commit/3cb7407b261c59c30aec0af3c456af780aab4b36

**Comment by Alex-D** [comment]
Thank you :)
