### ISSUE TITLE
[mention] After inserting '@' username to be autocompleted

### ISSUE THREAD

**Issue by messalas** [Alex-D/Trumbowyg#1343]
This is not a bug, but a question or suggestion.. Is it possible on mention plugin to autocomplete the user after inserting the '@' character, rather than selecting the user from the toolbar?

Great work btw!

**Comment by Alex-D** [comment]
I need to check that: 
Duplicates #926
But it's an issue, not a PR, so I've forgotten it -_-

**Comment by solsticesurfer** [comment]
Unfortunately, that plugin seems to have been abandoned, was not submitted as a PR, and doesn't actually work.
