### ISSUE TITLE
Problem on es6 import

### ISSUE THREAD

**Issue by WebCimes** [Alex-D/Trumbowyg#1348]
Hi,

I just need to include trumbowyg in a script.js (with type="module"), so I import simply like this : 
`import  "../node_modules/trumbowyg/dist/trumbowyg.min.js"`
But I have two problem, the first is that a function of jquery is deprecated `$.isArray` at line 804, so I reccomand you to change with this : `Array.isArray` and the second problem is about svg button who doesn't appear when I use "import" : 
![image](https://user-images.githubusercontent.com/43851969/208405342-26ec8461-f48f-40b9-82f0-2fe7bec3d58d.png)
![image](https://user-images.githubusercontent.com/43851969/208405470-66ddacc7-5625-4018-b4da-0ac1c1cf20ac.png)

If you have an idea of the problem ?

Edit : It's work when I precise the option "svgPath"

Thanks

**Comment by Alex-D** [comment]
I've created an issue for the isArray upgrade, Thanks :)
