### ISSUE TITLE
Paste image from clipboard

### ISSUE THREAD

**Issue by dandv** [Alex-D/Trumbowyg#135]
Trumbowyg can successfully paste rich text containing images accessible via URLs (e.g. the contents of [this Google Doc](https://docs.google.com/document/d/11HIrMPLWsxYjcBlMUIqrE4ELiQWpyYk-mj5nbhjOLrg/edit#)), but not standalone images from the system clipboard.

Pasting images directly from the clipboard is very widespread nowadays: Google Docs, GitHub, StackOverflow, Slack etc.

Having this feature would make this the most handy plightweight [WYSIWYG editor we have evaluated](https://github.com/iDoRecall/comparisons/blob/master/JavaScript-WYSIWYG-editors.md).

**Comment by dandv** [comment]
How about integrating the short [paste.js](https://github.com/layerssss/paste.js) plugin?

**Comment by Alex-D** [comment]
Done as a plugin, visible on `develop` branch only for the moment. I need to fix some bugs on other things before push this in a release.
