### ISSUE TITLE
Fire change event when spelling suggestions are applied

### ISSUE THREAD

**Issue by abrom** [Alex-D/Trumbowyg#1363]
### Description
This seems to be similar to #162 (if not the same issue) in that spelling changes (selected from the context menu) don't trigger any sort of event. However it does seem that the `input` event is fired on the editor element and when filtering this to events where the original event `data` is null it *seems* to provide a point where we can fire the `tbwchange` event, thus solving the problem. 

My first crack at this problem tried testing the `originalEvent.inputType` to check if it was `'insertReplacementText'` however Safari just uses the normal `'insertText'` value (Safari is the new IE, right?! 😆). However, the `data` property of the `originalEvent` does appear to consistently be `null` for the spelling change event.

ie
```js
.on('input', function (e) {
    // This worked fine on all browsers except Safari
    // if (e.originalEvent instanceof InputEvent && e.originalEvent.inputType === 'insertReplacementText') {

    // This worked on all tested browsers.
    // Although I couldn't say what other interactions with the input might trigger something similar??!
    if (e.originalEvent instanceof InputEvent && e.originalEvent.data === null) {
        t.$c.trigger('tbwchange');
    }
})
```

Tested against Chrome 108, Safari 16.2, Firefox nightly (v111), Edge 109, Opera 94

Happy to put together a pull request if the above sounds good 😄

**Comment by Alex-D** [comment]
If it works, I will be happy to merge a PR like that!
