### ISSUE TITLE
Translation bugs and missing entries in Catalan language

### ISSUE THREAD

**Issue by carmarri** [Alex-D/Trumbowyg#1370]
Hello,
I'm Catalan-native and I've found some bugs in file ca.min.js of words that look like "google-translated" or conceptually wrong from a programmer's or designer point of view in the following variables:
formatting: 'Formatar'
unorderedList: 'Lista desordenada'
orderedList: 'Lista ordenada'
italic: 'Itàlica'
strikethrough: 'Suprimir'
strong: 'Forta'
em: 'Èmfasi'
reset: 'Reiniciar'

they should be:
formatting: 'Format'
unorderedList: 'Llista desordenada'
orderedList: 'Llista ordenada'
italic: 'Cursiva'
strikethrough: 'Ratllat'
strong: 'Negreta'
em: 'Cursiva'
reset: 'Cancel·lar

There are also some missing translations for the following variables:
undo
redo
removeformat
superscript
subscript
target
width
_blank

I've attached the full file fixed ("ca.js" & "ca.min.js")

[lang-ca.zip](https://github.com/Alex-D/Trumbowyg/files/10673855/lang-ca.zip)

**Comment by Alex-D** [comment]
Translations are made by contributors, so I cannot really verify them. I just hope that some persons like you come to fix them if necessary :)

Thank you for all your contributions!
Those will be available in the release 2.27.1!
