### ISSUE TITLE
 Missing language entries in Plugin InsertAudio (ES, CA)

### ISSUE THREAD

**Issue by carmarri** [Alex-D/Trumbowyg#1375]
Here you have the missing translation into Spanish and Catalan for plugin InsertAudio:

```
es: {
    insertAudio: 'Insertar Audio'
}

ca: {
    insertAudio: 'Inserir Audio'
}
```

**Comment by Alex-D** [comment]
Thank you for your contribution :)
This will be available in the release **2.27.1**!
