### ISSUE TITLE
Missing language entries for Plugin Emoji (ES, CA)

### ISSUE THREAD

**Issue by carmarri** [Alex-D/Trumbowyg#1378]
Here you have the translations into Spanish and Catalan which are missing in Plugin Emoji:

```
es: {
    emoji: 'Añadir un emoticono'
}

ca: {
    emoji: 'Afegir una emoticona'
}
```

**Comment by Alex-D** [comment]
Thank you for your contribution :)
This will be available in the release **2.27.1**!
