### ISSUE TITLE
Create linebreaks in the code view

### ISSUE THREAD

**Issue by dandv** [Alex-D/Trumbowyg#138]
1. Select all and copy from [this Google Doc](https://docs.google.com/document/d/11HIrMPLWsxYjcBlMUIqrE4ELiQWpyYk-mj5nbhjOLrg/edit#)
2. Paste in the demo
3. Switch to code view
4. Notice how everything is one huge wrapped string

![image](https://cloud.githubusercontent.com/assets/33569/7926353/6065cc3e-0886-11e5-93a1-ff6a3bf8fa2e.png)

If you past the same text at http://sumernote.org and switch to code view, the code is split on 6 lines. 

![image](https://cloud.githubusercontent.com/assets/33569/7926365/79bcd8da-0886-11e5-8254-9ab5aee612ba.png)

(They also use CodeMirror to highlight it, but I'm not asking for that).

**Comment by Alex-D** [comment]
Sorry, but that's a WYSIWYG, not a code editor. Paste from any other editor/text-editor is not a good practice.

You can go to HTML to adjust somethings but the force of Trumbowyg is to be light and simple.

**Comment by phantasma2983** [comment]
Hey Alex,

I respect your decision to make this as light and simple as possible but unfortunately this also make your editor not very useful in real life situations. I want to integrate it with codemirror for the added advantage of proper source code hightlight and arrangement but I'm having trouble finding a proper event to trigger the code to update in preview mode after changes in the source code. Can you help me out with some advice?

Daniel

**Comment by Alex-D** [comment]
Hi!

You can use both [events](http://alex-d.github.io/Trumbowyg/documentation.html#events) and the [HTML setter](http://alex-d.github.io/Trumbowyg/documentation.html#manage-content).

I think you can have a great result with this combination :)
