### ISSUE TITLE
Bug on HTML mode

### ISSUE THREAD

**Issue by rainerborene** [Alex-D/Trumbowyg#1381]
![bug](https://user-images.githubusercontent.com/101501/220966778-ca993bd7-3c9c-4cc6-bceb-fc95232f341a.png)

**Comment by Alex-D** [comment]
Thank you, will be fixed soon :)

**Comment by rainerborene** [comment]
Bug still there. I also noticed that in normal mode the `editor-box` does not fit the entire container height. That means if you click on the bottom (which is an empty space) of the editor it does not focus the input field. Not sure if I was clear enough. Let me know. Thanks a lot.

![Screenshot 2023-02-28 at 11-22-58 Trumbowyg - A lightweight WYSIWYG editor by Alex-D _ Alexandre Demode](https://user-images.githubusercontent.com/101501/221881951-a25011e6-3638-453a-9e46-d3fa33ba5eba.png)

**Comment by Alex-D** [comment]
Oh :(
I have fixed it in 2.27.1 bug broke it in 2.27.2 -_-
A `flex: 1;` is missing on `.trumbowyg-box.trumbowyg-editor-hidden .trumbowyg-textarea`

**Comment by rainerborene** [comment]
Just one more thing left to fix it. The white box (div with class trumbowyg-editor trumbowyg-reset-css) should have height 100%.
![bug_tbw](https://user-images.githubusercontent.com/101501/226197010-68aeed5f-feb6-4bdf-afd4-b96d1fe1c41c.png)

**Comment by rainerborene** [comment]
@Alex-D First erase all the content inside the editor then try to click inside at the bottom position. It won't focus it.

**Comment by Alex-D** [comment]
Yes I see it, thank you :)

That's strange, I have that in CSS: 
```scss
.trumbowyg-box .trumbowyg-editor {
    min-height: 100%;
}
```
