### ISSUE TITLE
Content overflows in fullscreen becuase of button panel

### ISSUE THREAD

**Issue by VrbovskyM** [Alex-D/Trumbowyg#1383]
I have trumbowyg editor in modal window. When I open it in fullscreen, it overflows the modal div if the button panel goes into two lines.
This is the modal div. You can see in the bottom it overflows.
![image](https://user-images.githubusercontent.com/100531156/221582523-e3dcea4a-42e0-4a18-bb49-627cfc004533.png)
![image](https://user-images.githubusercontent.com/100531156/221583361-0f98241c-9045-4fb7-993f-72dee807113d.png)
![image](https://user-images.githubusercontent.com/100531156/221582803-c31b20ae-1706-4bc1-b3f8-20957f553a96.png)
Here is screenshot when button panel is in one line (doesnt overflow)
![image](https://user-images.githubusercontent.com/100531156/221583540-b9063a0b-8528-44fb-b132-71ee4136ca6e.png)
![image](https://user-images.githubusercontent.com/100531156/221583570-559564a3-5999-468f-893d-4cf26f88e1d1.png)

**Comment by Alex-D** [comment]
I think it's fixed in the lastest 2.27.2 release :)

**Comment by VrbovskyM** [comment]
I used the latest CDNJS for trumbowyg.min.js
And now it seems like its not scrollable. The more I type the more it grows vertically. is there something else I should download with the new version ?
Is  `<script src="https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.27.2/trumbowyg.min.js"></script>` not enough ?
![image](https://user-images.githubusercontent.com/100531156/221721032-d8d66399-ac1f-47c4-a899-017fb73b37b6.png)

**Comment by Alex-D** [comment]
It would be best if you had the last CSS too

**Comment by VrbovskyM** [comment]
Hmm. The overflow is fixed but the scroll behaves weirdly.
This is before 2.27.2. You can see theres scroll bar on right. (no height set for the div that holds trumbowyg textara)
![image](https://user-images.githubusercontent.com/100531156/221939477-dfa893fa-5927-446c-a060-6e85d879943c.png)

This is with 2.27.2 js and css. It just grows (no height set for the div that holds trumbowyg textara)
![image](https://user-images.githubusercontent.com/100531156/221939889-919e1b08-41d9-457d-b0b0-ec839d82d20b.png)

When I set height for the div that holds trumbowyg. It kinda works, but it also scrolls the button panel 
![image](https://user-images.githubusercontent.com/100531156/221940291-f7c64280-5dba-4491-88c8-6ded2068b49f.png)

Im sorry if Im missing something crucial. But I would like this library to work for me.

**Comment by Alex-D** [comment]
Did you try to set the height of your source element (textarea or div) instead?

**Comment by VrbovskyM** [comment]
I tried setting height to the div and textarea. When I set the height to the div. it is scrollable, but also button panel scrolls.
When I set it to textarea of trumbowyg, it gets ignored. Nothing happens
(Im using tailwind h-80 means height: **x**_rem_)
```
<div>
     <textarea name="content" id="trumbowyg-editor" class="h-80 overflow-y-scroll "></textarea>
</div>
```

**Comment by Alex-D** [comment]
Hum, I use a fixed size on the Trumbowyg landing page, so I'm pretty sure it can work.

I do not think you must set the overflow yourself, only the height.

**Comment by Alex-D** [comment]
Hey!

I've made some adjustments: 
https://jsfiddle.net/negqhs7u/1/

- Only one CSS trick to get the editor to take full height
- Use Flexbox in your modal to make the #trumbowyg-box take all height it can

I hope it helps :)

**Comment by VrbovskyM** [comment]
Hi. Thank you for looking at it!

Few issues still persists tho.
When you write bunch of long text, the editor is going to eventually overflow from to modalContent div. Both in fullscreen and not fullscreen.
Few interesting things I noticed
If you write long text in non-fullscreen, its going to overflow.
If you put it in fullscreen with already long text thats overflown, the text wont be overflown but white background is.
If you put empty editor to fullscreen and start typing long text, it behaves correctly. No overflown. However, if you put it out of fullscreen and back to fullscreen, its gonna have that weird white overflown.
