### ISSUE TITLE
Is There any way we can stop script initializing the Script Inside the Editor ?

### ISSUE THREAD

**Issue by simranjeetsingh** [Alex-D/Trumbowyg#1398]
Hi 

I am having an issue with script initializing within editor

Is there any way to stop that

Please help

**Comment by Alex-D** [comment]
Hi,

Please give an example.

If you are thinking about writing a `<script>alert('hi')</script>` in the _viewHTML_, then you can't do anything on the client side: the goal of the WYSIWYG is to render what you set in the HTML.

Feel free to reopen if needed
