### ISSUE TITLE
Plugin for wordpress?

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Alex-D/Trumbowyg#141]
Is there a plugin for wordpress with Trumbowyg? I absolutely love it and would like to have it embedded as plugin and replace the wordpress fugly editor.

**Comment by Alex-D** [comment]
That's an interesting idea. Maybe a day :)

**Comment by Alex-D** [comment]
I thought about that and I don't this do that because it's sooo complex to support all WordPress Core possibilities : gallery, media, plugins, ...

Sorry :/

**Comment by BAProductions** [comment]
IM working on one, but i can't get the media uploader to work with it
