### ISSUE TITLE
Icons #trumbowyg-table-border-color and #trumbowyg-table-cell-background-color don't appear

### ISSUE THREAD

**Issue by panorius** [Alex-D/Trumbowyg#1413]
Bonjour/Hello !

J'ai lu que vous étiez français, donc j'en profite pour faire mon issue en FR. ;)
J'ai un souci avec deux icons qui ne veulent pas apparaître alors que les autres si.
Je suis sur Google Chrome, projet localhost.
J'ai mis à jour, aujourd'hui, le plugin Table avec les deux nouveau bouton pour la couleur des cellules et bordures. J'ai bien évidemment mis à jour le css principal, le js principal ainsi que du fichier SVG icons.svg.

Voici l'architecture:

- stylesheet
  - rich-text
    - ui
      - icons.svg
      - trumbowyg.table.min.css
    - trumbowyg.min.css

Pareil pour le JS mais dans le fichier javascript
Les calls JS et CSS ont bien été fait vu que j'utilisais l'ancienne version du plugin Table ;)

Implémentation de la librairie:

```
$('#formRichText').trumbowyg({
        //svgPath:'/stylesheets/rich-text/ui/icons.svg',
        btns: [
            ['historyUndo','historyRedo','removeformat'],
            ['formatting'],
            ['fontfamily'],
            ['fontsize'],
            ['strong','em','underline','del','foreColor', 'backColor'],
            ['link','image'],
            ['align','lineheight','unorderedList','orderedList'],

            ['horizontalRule'],

            ['mention'],
            ['ruby'],
            ['emoji'],

            ['table','tableCellBackgroundColor','tableBorderColor'],
            ['fullscreen']
        ],
        btnsDef: {
            image: {
                dropdown: ['insertImage','base64','noembed'],
                ico: 'insertImage',
                hasIcon: true
            },
            align: {
                dropdown: ['justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
                ico: 'justifyLeft',
                hasIcon: true
            }
        },
        semantic: {
            'i': 'em'
        }
})
```
Voici un imprime écran.
![image](https://github.com/Alex-D/Trumbowyg/assets/4655291/90d478c5-616b-42d2-a121-13efae791f89)

En tout cas, un grand merci pour ton traitement de texte, il est vraiment bien fait et modulable. ;)
Bien à vous !

**Comment by panorius** [comment]
My bad, je me suis trompé de projet (dupliqué..) ;)
Bonne continuation !

**Comment by code-shiva-kumar** [comment]
make sure you inserted the <`script>` file correctly.
check the scripts inside the table script file or re-download it.
`<script src="trumbowyg/dist/plugins/table/trumbowyg.table.js"></script>`
