### ISSUE TITLE
Change language on file upload button

### ISSUE THREAD

**Issue by 0xLDev** [Alex-D/Trumbowyg#1428]
I have uploadImage, how do I change the text "Select File" and "File Not Selected" to my own?
![screen](https://github.com/Alex-D/Trumbowyg/assets/67437278/b952d8eb-ff28-43c6-86c0-b069fb79c3a2)

**Comment by 0xLDev** [comment]
I would not like to fork the library and somehow customize input with file type, whether it is possible to do this through config trumbowyg

**Comment by 0xLDev** [comment]
@Alex-D

**Comment by Alex-D** [comment]
In short: You can't.
Your Browser sets that text, not Trumbowyg.
