### ISSUE TITLE
Line Break in Firefox not working

### ISSUE THREAD

**Issue by bonster21** [Alex-D/Trumbowyg#143]
When using Firefox, a line break (Shift + Enter) moves the cursor to the far right edge of the screen. Repositioning it gets you a new paragraph... Is this a known behaviour?

**Comment by Alex-D** [comment]
> Is this a known behaviour?

Nope :/

**Comment by comtronix** [comment]
I don't have this problem in my Firefox browser. Maybey you have an issue with another js?

**Comment by bonster21** [comment]
Just updated from beta 2 to beta 4 - and the problem is gone. Instead there is a new behaviour: line breaks are always accompanied by a new paragraph which kinda defeats the purpose of line breaks... The problem exists in Firefox, Chrome, Opera. IE doesn't add a line break at all, only a paragraph.

Line Break works perfectly fine if executed inside text thats already there. Just not when entering new text (cursor at the end of content)

**Comment by Alex-D** [comment]
Seem works.
