### ISSUE TITLE
Font size usability issue

### ISSUE THREAD

**Issue by garygreen** [Alex-D/Trumbowyg#144]
At the moment it's not very clear how to increase the font size. There is a 'heading formatter' icon but that doesn't really allow incremental changes of font size. Also the word 'heading' makes it seem inappropriate to use for increasing the main text font size.

**Comment by Alex-D** [comment]
It's a WYSIWYG : font-size is set by your CSS, not by the editor.

> Also the word 'heading' makes it seem inappropriate to use for increasing the main text font size.

Heading create h1, h2, h3, h4 so it's appropriate :)

**Comment by garygreen** [comment]
This is an example of what I mean... https://www.froala.com/wysiwyg-editor

It has a 'T' icon where you can choose the size of the selected text. It would be cool to implement something like that. The current formatter is more for 'common styles' and not really for fine tuning font sizes, if you know what I mean?

**Comment by Alex-D** [comment]
Sure, that's not usefull. Why change font-size? Trumbowyg is semantic. If your allow user change size, he don't see the difference between font-size change and use a title. So I don't prefer permit font-size change by default.

Maybe I can take a look to add that as a non-default option.

**Comment by dandv** [comment]
How does Trumbowyg deal with rich text that is pasted from somewhere else, and contains font sizes specified inline?

For example, I created a few lines of different sizes in Froala, and pasted them in Trumbowyg. So far they *look* okay:

![image](https://cloud.githubusercontent.com/assets/33569/8243109/1cbe93da-15c9-11e5-9dae-a404b4666b00.png)

**Comment by Alex-D** [comment]
> How does Trumbowyg deal with rich text that is pasted from somewhere else, and contains font sizes specified inline?
