### ISSUE TITLE
Support for jQuery 4

### ISSUE THREAD

**Issue by marcellov7** [Alex-D/Trumbowyg#1442]
Hi,

I'm an enthusiastic user of Trumbowyg and greatly appreciate its features and effectiveness. However, with the recent announcement of the release of jQuery 4 and its promises to significantly improve library performance, I was wondering if there are plans to ensure Trumbowyg compatibility with this new version of jQuery.
https://blog.jquery.com/2024/02/06/jquery-4-0-0-beta/

I understand that Trumbowyg relies on jQuery and that the upgrade may take time and effort, but considering the potential benefits in terms of performance and future compatibility, it would be extremely helpful for the community to know if there is a commitment to making Trumbowyg compatible with jQuery 4.

Is there a roadmap or defined plan for this? Additionally, if there are opportunities to contribute or support this effort, I would be happy to provide my assistance.

In general it seems to me to be running, but from what I can see $.isArray has been deprecated and is present in a few places, but it seems easy to change.

Thank you

**Comment by Alex-D** [comment]
Hey!

It seems legit to want Trumbowyg working with jQuery 4. I will check that when I have time to work on it.

I appreciate your interest in this project :)

**Comment by Alex-D** [comment]
I've worked on that today. It was easy to make it work with jQuery since the code did not use deprecated APIs so much.

I'm trying to make Trumbowyg compatible with the slim version by removing `$.ajax` for `fetch`.

You can see that on the develop branch right now :)
