### ISSUE TITLE
Check if link is valid http:

### ISSUE THREAD

**Issue by comtronix** [Alex-D/Trumbowyg#145]
Add a check if the insert link is valid and starts with http:// if its entered without http://

if http:// ftp:// or https:// is used then its proper, 
if not; auto-format link to http://my.link

**Comment by Alex-D** [comment]
Too complex. That's a lightweight editor, so it's to the user to put the protocol in the address.

Why it's complex? How can I detect the difference between this text with a typo:

```
hello.can you check...
```

And this URL:

```
hello.can <- this site is wonderful
```

The anwser is: that's impossible.

Sorry :/

**Comment by Alex-D** [comment]
Hum. I've write this message too speedy...

The right problem is: it's too complex to support relative links, absolute, ... this need a lot of Kb of code for this check.

**Comment by comtronix** [comment]
just add something like this before the link is returned to the textarea:

                // add option to check if url is valid http://
                if (!v.url.indexOf("http://") == 0){
                    v.url = "http://" + v.url;
                }

**Comment by atk** [comment]
Truly a compilcated problem; have a look at the implications here: https://mathiasbynens.be/demo/url-regex

**Comment by Alex-D** [comment]
Too complex to be added to a 16kb library, sorry :/
