### ISSUE TITLE
Line height plugin displaying custom size 1.5 as large

### ISSUE THREAD

**Issue by amy-simmons-cloudm** [Alex-D/Trumbowyg#1458]
I am using the line height plugin and specifying a list of sizes as below

` lineheight: {
                            sizeList: [
                                '1',
                                '1.1',
                                '1.2',
                                '1.3',
                                '1.4',
                                '1.5',
                                '2'
                            ]
                        },`

However the size 1.5 is being displayed as 'large' in the dropdown. The other sizes display as expected. 

I am using https://alex-d.github.io/Trumbowyg/documentation/plugins/#plugin-lineheight as reference but the custom size list section here seems to be referencing fontsize and not lineheight.

Can you clarify how to resolve this?

**Comment by Alex-D** [comment]
Hey,
its due to translations: 
https://github.com/Alex-D/Trumbowyg/blob/develop/plugins/lineheight/trumbowyg.lineheight.js#L9-L13

**Comment by amy-simmons-cloudm** [comment]
Hi, thanks for getting back to me. I have been able to resolve this based on your information
