### ISSUE TITLE
Hard to click for focus on empty editor

### ISSUE THREAD

**Issue by themikegreider** [Alex-D/Trumbowyg#1470]
We upgraded from v2.23.0 to v2.27.3, and the behavior for entering into the editor is changed. Previously, you could click anywhere in the editor and the focus would start at the top left and you could begin typing. On v2.27.3, you have to click up in the top row now. Clicking elsewhere will not add focus into the edit.

In this screenshot, only in the upper corner would a mouse click add focus. Everywhere else with the red X would not.

![image](https://github.com/Alex-D/Trumbowyg/assets/119977770/f5feb181-8cc6-4e61-8464-0b0b53e061e2)

This appears cross browser, but definitely Chrome and Firefox.

You can reproduce by going to any of the public demos on the Trumbowyg homepage. Delete the text, remove focus, then try to click back into the editor. In this screenshot, one the text is removed and the focus is gone, you have to click in the green section. Clicking anywhere in the red won't work.

![image](https://github.com/Alex-D/Trumbowyg/assets/119977770/4b642b73-076f-4fcf-ad82-d311f4d82e4f)

Is there a way to revert that behavior or to add a custom listener that will put focus if anywhere is clicked?

**Comment by zymbth** [comment]
You could try one of these ways:

1. Fix the `height` of trumbowyg box, e.g., `.trumbowyg{height:300px}`
2. Set the `min-height` of trumbowyg editor, e.g, `.trumbowyg-box .trumbowyg-editor{min-height:260px}`

**Comment by themikegreider** [comment]
Thank you for the comment. #1 did the trick for me. #2 increased the editor size, but didn't fix my issue above. But by matching the box with the editor size, that fixed my issue.

**Comment by themikegreider** [comment]
Marking closed as fixed
