### ISSUE TITLE
Inserting link always gives me invalid url error

### ISSUE THREAD

**Issue by Jordan4jc** [Alex-D/Trumbowyg#148]
If I comment out the lines containing the URL pattern check I can paste in a url and submit just fine, but if the check is there no matter what url I copy from the address bar and attempt to paste in the url field it always tells me it's invalid.

Seems to be an issue with the pattern?

**Comment by comtronix** [comment]
do you have online version fo testing?

**Comment by Alex-D** [comment]
Browser? Version of browser? Version of Trumbowyg?

In v2 there is no check on URL: https://github.com/Alex-D/Trumbowyg/blob/master/src/trumbowyg.js#L371

The field is just required.

**Comment by Jordan4jc** [comment]
I switched to version 2.0.0 and all is good, wish that version was on bower though.
