### ISSUE TITLE
`semantic` option doesn't always result in semantic markup

### ISSUE THREAD

**Issue by green-arrow** [Alex-D/Trumbowyg#150]
When using the editor, if you click on the "bold" icon and start typing, the text is bold and surrounded by `<strong>` tags. However, if you highlight a piece of normal text and click on the "bold" icon, it is surrounded by `<b>` tags instead. This holds true for the example on http://alex-d.github.io/Trumbowyg/

**Comment by Alex-D** [comment]
Browser? Version? I can't test without that basic informations :/

On Chrome, it's working.

**Comment by green-arrow** [comment]
Whoops, sorry about that! 

Chrome 
2.0 beta 4
Mac OS

**Comment by green-arrow** [comment]
Also to clarify, on the documentation site when you click to view the HTML, it does say `<strong>` in the scenario I described. The issue is in the actual markup in the DOM. When inspecting via Chrome dev tools, you can see the switch between the two tags.

**Comment by Alex-D** [comment]
Trumbowyg use execCommand API.

`semantic` option is an overlay which clean the code to be semantic. So it transforms `<b>` into `<strong>`, `<i>` into `<em>`, ...

So, in fact, you can see the change. But if you submit the form which wrap Trumbowyg or if you switch to HTML view, you can see the right `<strong>` tag.

If you see that, it's OK and that's not a bug. Unless, I don't understand the bug ^^"

**Comment by green-arrow** [comment]
Ah I understand. I was just confused because the actual DOM switched between `<strong>` and `<b>`, which can cause styling issues in come applications. As long as the end output is ok, we should be good.

**Comment by Alex-D** [comment]
Yep I know but that's the cost to get semantic code with execCommand API :/
