### ISSUE TITLE
Adding custom insert embed code plugin

### ISSUE THREAD

**Issue by littlealien** [Alex-D/Trumbowyg#151]
I tried to replicate upload plugin and willing to insert embed code (just  code snippet).

When I try to use insertImage method in my own embed plugin, it will create an image and putting my data to image src. But can't find where this image is creating. If i find it, I will change it for embed plugin. 

I just want to put code snippet which is written on editorModal to editor, just like insertImage.

Where should I check in files?

My plugin snippet:

```js
embed: {
    func: function(params, tbw) {
        var embed, pfx = tbw.o.prefix;
        var $modal = tbw.openModalInsert(
            tbw.lang.embed,
            {
                embed: {
                    label: 'embed',
                    required: true
                }
            },
            function(){
                tbw.execCmd('insertEmbed', $('[name="embed"]').val());
                setTimeout(function(){
                    tbw.closeModal();
                }, 250);
            }
        );
    },
    ico: 'insertEmbed'
}
```

**Comment by hajrice** [comment]
hi!

did you managed to figure this out?

Trying to do the same :(

**Comment by Alex-D** [comment]
I need to improve the documentation.

Maybe this branch can help you: https://github.com/Alex-D/Trumbowyg/pull/189
