### ISSUE TITLE
image upload plugin issue

### ISSUE THREAD

**Issue by shaheer-javaid** [Alex-D/Trumbowyg#153]
there is two issues in image upload plugin first one is images is overlapping to the existing images in image upload folder (if the name is same) without any alert .
the second one issue is that in image upload image (alt) description does not work

**Comment by Alex-D** [comment]
> images is overlapping to the existing images in image upload folder (if the name is same) without any alert .

You need to manage that server-side by creating new name if filename already exists. Don't use the PHP file in this project, that's juste for example.

> the second one issue is that in image upload image (alt) description does not work

Maybe. I need to take a look at that.

**Comment by shaheer-javaid** [comment]
i am a web designer not to very much good in php kindly give some type of code which prevent overlapping the images

**Comment by kcijezie** [comment]
Any luck with the alt description not showing problem?

**Comment by Alex-D** [comment]
That's was fixed https://github.com/Alex-D/Trumbowyg/commit/460a642a197b834aaa11e1b03ff0912bb3cf32fe#diff-eee99506f2e170a6d93f6a7c5b5537d4R131
