### ISSUE TITLE
Image float

### ISSUE THREAD

**Issue by klocus** [Alex-D/Trumbowyg#159]
How to add image float in modal box with select options? I've done something like that:

```
            .on('dblclick', 'img', function(){
                var $img = $(this);
                t.openModalInsert(t.lang.insertImage, {
                    url: {
                        label: 'URL',
                        value: $img.attr('src'),
                        required: true
                    },
                    alt: {
                        label: t.lang.description,
                        value: $img.attr('alt')
                    },
                    float: {
                        label: t.lang.float,
                        value: $img.css('float')
                    }
                }, function(v){
                    return $img.attr({
                        src: v.url,
                        alt: v.alt
                    }).css('float', v.float);
                });
                return false;
            })
```

It works but user have to enter float value... Any ideas?

**Comment by Alex-D** [comment]
I don't manage select in Trumbowyg modals :/ You can use them, but you need to recode the modal builder.

**Comment by pyriel4you** [comment]
/* ===========================================================
 * trumbowyg.upload.js v1.0
 * Upload plugin for Trumbowyg
 * http://alex-d.github.com/Trumbowyg
 * ===========================================================
 * Author : Alexandre Demode (Alex-D)
 *          Twitter : @AlexandreDemode
 *          Website : alex-d.fr
 */

(function($){
    'use strict';

    addXhrProgressEvent();

    $.extend(true, $.trumbowyg, {
        langs: {
            en: {
                upload: "Upload",
                file:   "File",
                uploadError: "Error"
            },
            sk: {
                upload: "Nahrať",
                file:   "Súbor",
                uploadError: "Chyba"
            },
            fr: {
                upload: "Envoi",
                file:   "Fichier",
                uploadError: "Erreur"
            },
            cs: {
                upload: "Nahrát obrázek",
                file:   "Soubor",
                uploadError: "Chyba"
            }
        },

        upload: {
            serverPath: './src/plugins/upload/trumbowyg.upload.php'
        },

        opts: {
            btnsDef: {
                upload: {
                    func: function(params, tbw){
                        var file,
                            alt,
                            size,
                            pfx = tbw.o.prefix;

                        var $modal = tbw.openModalInsert(
                            // Title
                            tbw.lang.upload,

                            // Fields
                            {
                                file: {
                                    type: 'file',
                                    required: true
                                },
                                alt: {
                                    type: 'input',
                                    label: 'Description',
                                    name: 'alt'
                                },
                                size: {
                                    type: 'sel',
                                    label: 'Dimensions',
                                    name: 'size',
                                    value: {'ui left floated medium image': 'medie aliniata stanga', 'ui right floated medium image': 'medie aliniata dreapta'}
                                        
                                }
                            },

                            // Callback
                            function(){
                                var data = new FormData();
                                data.append('size', size);
                                data.append('alt', alt);
                                data.append('fileToUpload', file);

                                if($('.' + pfx +'progress', $modal).length === 0)
                                    $('.' + pfx + 'modal-title', $modal)
                                    .after(
                                        $('<div/>', {
                                            'class': pfx +'progress'
                                        })
                                        .append(
                                            $('<div/>', {
                                                'class': pfx +'progress-bar'
                                            })
                                        )
                                    );

                                $.ajax({
                                    url:            $.trumbowyg.upload.serverPath,
                                    type:           'POST',
                                    data:           data,
                                    cache:          false,
                                    dataType:       'json',
                                    processData:    false,
                                    contentType:    false,

                                    progressUpload: function(e){
                                        $('.' + pfx + 'progress-bar').stop().animate({
                                            width: Math.round(e.loaded * 100 / e.total) + '%'
                                        }, 200);
                                    },

                                    success: function(data){
                                        if(data.message == "uploadSuccess") {
                                            tbw.execCmd('insertImage', data.file);
                                            var img = $("img[src$='"+data.file+"']");
                                            if(data.alt != 'undefined'){
                                                img.attr('alt', data.alt);
                                            }
                                            if(data.size != 'undefined'){
                                                img.attr('class', data.size);
                                            }
                                            setTimeout(function(){
                                                tbw.closeModal();
                                            }, 250);
                                        } else {
                                            tbw.addErrorOnModalField(
                                                $('input[type=file]', $modal),
                                                tbw.lang[data.message]
                                            );
                                        }
                                    },
                                    error: function(){
                                        tbw.addErrorOnModalField(
                                            $('input[type=file]', $modal),
                                            tbw.lang.uploadError
                                        );
                                    }
                                });
                            }
                        );

                        $('input[type=file]').on('change', function(e){
                            try {
                                // If multiple files allowed, we just get the first.
                                file = e.target.files[0];
                            } catch (err) {
                                // In IE8, multiple files not allowed
                                file = e.target.value;
                            }
                        });
                        $('input[name=alt]').on('change', function(e){
                            try {
                                // If multiple files allowed, we just get the first.
                                alt = e.target.value;
                            } catch (err) {
                                // In IE8, multiple files not allowed
                                alt = e.target.value;
                            }
                        });
                        $('select[name=size]').on('change', function(e){
                            try {
                                // If multiple files allowed, we just get the first.
                                size = e.target.value;
                            } catch (err) {
                                // In IE8, multiple files not allowed
                                size = e.target.value;
                            }
                        });
                    },
                    ico: 'insertImage'
                }
            }
        }
    });


    function addXhrProgressEvent(){
        if (!$.trumbowyg && !$.trumbowyg.addedXhrProgressEvent) {   // Avoid adding progress event multiple times
            var originalXhr = $.ajaxSettings.xhr;
            $.ajaxSetup({
                xhr: function() {
                    var req  = originalXhr(),
                        that = this;
                    if(req && typeof req.upload == "object" && that.progressUpload !== undefined)
                        req.upload.addEventListener("progress", function(e){
                            that.progressUpload(e);
                        }, false);

                    return req;
                }
            });
            $.trumbowyg.addedXhrProgressEvent = true;
        }
    }
})(jQuery);


And change:

// Preformated build and management modal
        openModalInsert: function(title, fields, cmd){
            var t = this,
                prefix  = t.o.prefix,
                lg = t.lang,
                html = '';

            for(var f in fields){
                var fd = fields[f], // field definition
                    l = fd.label,
                    n = (fd.name) ? fd.name : f;
                if(fd.type == 'sel'){
                    html += '<label><select name="'+n+'" class="ui dropdown">';
                        $.each(fd.value, function(i, val) {
                            html += '<option value="'+i+'">'+val+'</option>';
                        });
                    html += '</select>';
                    html += '<span class="'+prefix+'input-infos"><span>'+
                            ((!l) ? (lg[f] ? lg[f] : f) : (lg[l] ? lg[l] : l))+
                            '</span></span></label>';
                } else { 
                    html += '<label><input type="'+(fd.type || 'text')+'" name="'+n+'" value="'+(fd.value || '')+'"><span class="'+prefix+'input-infos"><span>'+
                            ((!l) ? (lg[f] ? lg[f] : f) : (lg[l] ? lg[l] : l))+
                            '</span></span></label>';
                }
            }

in trumbowyg.js

**Comment by atk** [comment]
Small suggestion for improvement: instead of $.each to process the select's options, you can also use
```
+ fs.value.map(function(){ return '<option value="'+i+'">'+val+'</option>'; }).join('') + 
```

**Comment by Alex-D** [comment]
This feature is too strong for Trumbowyg, sorry :/
