### ISSUE TITLE
target support for links

### ISSUE THREAD

**Issue by bestxp** [Alex-D/Trumbowyg#16]
Need support target property support in insertion links

**Comment by mmoravcik** [comment]
+1

I guess free text "target" field would do for now?

**Comment by Alex-D** [comment]
I've do that on master. Need to build `/dist` folder to try this with good design improvements. You can just use `src/trumbowyg.js` to test the new field.

**Comment by kcijezie** [comment]
Hi Alex, nice job. Can you please add the target enhancement to the build? the one on source seem to display the editor twice. Thanks.

**Comment by Alex-D** [comment]
You already can add target to your link as you can see here : http://alex-d.github.io/Trumbowyg/

But you need to type "_blank" or whatever.

**Comment by kcijezie** [comment]
Thanks Alex but I did bower install trumbowyg and referenced the appropriate files. But the link modal only has URL, title and text. No target like your demo. Can you build so that the dist folder has the recent js updates?

**Comment by Alex-D** [comment]
As we still in beta for now, you need to install the last beta version like that : 

`bower install trumbowyg#2.0.0-beta.5`

I need to stabilize the 2.0 and publish it ASAP.

**Comment by kcijezie** [comment]
Hi Alex,

The upload image works fine but the alt (description) is display or
rendered. Can you fix it? And also the ability to add other attributes
(like id, class etc) to the img tag.

Thanks,
Kene

**Comment by Alex-D** [comment]
A free text field is availble, I don't think to add a select dropdown for that because it's too eavy for a 16kb library.
