### ISSUE TITLE
"XSS" by JavaScript inject in viewHTML pane

### ISSUE THREAD

**Issue by mightylal** [Alex-D/Trumbowyg#160]
When I go into the source code view I call an alert('test') and when I go back to the regular view the alert actually runs. Is this unexpected behavior?

**Comment by Alex-D** [comment]
Trumbowyg lightweight is an editor. You can do anything you want in it.

If you don't want users can add some JS, clean the HTML in your back-end :)

**Comment by mightylal** [comment]
Well obviously, but that was not the question nor the issue. The question was that when I switch from source view back to the regular view the alert that I wrote in the source view runs! I don't believe that should happen.

**Comment by Alex-D** [comment]
Why? You write an alert, you back to the regular view, Trumbowyg update the regular view from the source view content. How can I don't run JS? Why do not I should run JS? If I want wrote a little script in source view to manage popin or whatever?

If you have a solution, you can explain it or submit a pull request, but I don't understand your point.

**Comment by CanRau** [comment]
Just moved from CKE to Trumbowyg, thanks for this nice little editor :)

I don't think there is any security issue here, or is there any difference to a user running JS from the browsers console?
To be safe just disable viewHTML button..

**Comment by Alex-D** [comment]
Mmh OK, I work on it.

**Comment by alexkarpxb** [comment]
Hi Alex, I see that if I paste script tag into editor in viewHtml mode, tag's removed, but if I paste it without this mode, tag's saved and script is running.. I can't remove it from backend, cause form post it like &lt script &gt, but editor executes script anyway

Property  {tagsToRemove: ['script', 'style']} don't handle this case

Can you please tell how I can avoid script execution?

**Comment by Alex-D** [comment]
It's to your backend to clean that... Idk which language you are using, but you should apply something like: 
 http://php.net/manual/fr/function.htmlentities.php

`<strong>foo</strong>` becomes `&lt;strong&gt;foo&lt;/strong&gt;` which will be displayed as <strong>foo</strong>

`&lt;strong&gt;foo&lt;/strong&gt;` becomes `&amp;lt;strong&amp;gt;foo&amp;lt;/strong&amp;gt;` which will be displayed as &lt;strong&gt;foo&lt;/strong&gt;

So script tag from viewHTML will be executed (you should remove it from backend too). Script tag pasted from the WYSIWYG side will not be executed. I can't make you a full tutorial about XSS... but one thing: **never trust client**. As client I mean JavaScript too. If I send my script tag without using Trumbowyg, I can send you a script tag if you did not clean it in backend.

Also, if I cannot add a `<script>` tag, I could add an `onerror` attribute to some `<img>`.

`<img onerror="window.location='http://example.com'" src="http://example.com/some-non-existing-image.jpg"/>`

This will redirect any visitor to example.com.

Go read some docs about XSS ;)

**Comment by edwinveldhuizen** [comment]
https://github.com/voku/anti-xss
Is a pretty useful lib as well
