### ISSUE TITLE
Setting focus() on trumbowyg

### ISSUE THREAD

**Issue by CanRau** [Alex-D/Trumbowyg#161]
Hola, haven't tried Trumbowyg extensively, but so far I like it.

I wanna set back the focus() after jquery $.post()
Tried on the .trumbowyg-editor and .trumbowyg-textarea elements like this $(".trumbowyg-editor").focus() with no luck.

Ah, and the $(".trumbowyg").trumbowyg('empty'); isn't working, at least from within my $.post done() function

**Comment by CanRau** [comment]
Okay after changing .trumbowyg to #trumbowyg emptying the editor works now.

Aaaha, and after changing textarea from class to id I get the focus with

$('.trumbowyg-editor').focus();

Great :D

**Comment by CanRau** [comment]
Just for clarification. It's not about id or class! Just used the wrong class, because trumbowyg is used for other elements. So changing class="trumbowyg" to e.g. class="rte" and everything works now as expected :+1: :)

**Comment by santiago1230** [comment]
good
