### ISSUE TITLE
IE 10 Spell Check not posting

### ISSUE THREAD

**Issue by Dunleavy-Aaron** [Alex-D/Trumbowyg#162]
Hi,

Am having an issue with a textarea in IE 10. The if the users makes a spelling mistake and corrects it using the built in checker, the page gets updated with the correct word but the original text gets posted with the form. Any suggestions (other than not using IE).

Thanks,

**Comment by Alex-D** [comment]
The bug is the same in all browsers and I can't fix it because browser do not fire any event :(

**Comment by evolross** [comment]
Currently dealing with this in Chrome. Anyone found any work-arounds?

**Comment by evolross** [comment]
This seems to work. Using this, you can ignore listening for `tbwchange` and `tbwpaste` with this.
```
$(document).on("DOMSubtreeModified", ".text-editor", function () {
   console.log("trumbowyg paragraph changed. Do something now...");
});
```
