### ISSUE TITLE
Image size adjusting

### ISSUE THREAD

**Issue by gaaarfild** [Alex-D/Trumbowyg#168]
When uploaded new image and trying to adjust size, it sets correctly in CSS, but image render stays as it is.

**Comment by Alex-D** [comment]
I don't understand, can you post a screencast or a example?

**Comment by gaaarfild** [comment]
http://youtu.be/lLLh90zI6bI

**Comment by Alex-D** [comment]
I think your CSS has a think like `img { width: 100% }`

**Comment by gaaarfild** [comment]
I found a line in trumbowyg.min.css
`width: auto;`
```
.trumbowyg-editor embed, .trumbowyg-editor img, .trumbowyg-editor object, .trumbowyg-editor video
```
for this selector. If I remove it, everything become correct.

**Comment by llogiq** [comment]
Can confirm this happens on current firefox with the demonstration page.

**Comment by Ydalb** [comment]
Hm, sorry to re-open it, but how do you get the little square to resize the picture ? I don't have it :(
If I double click on the picture, it opens the modal to edit URL & description.
 
![capture d ecran 2017-04-05 a 16 20 26](https://cloud.githubusercontent.com/assets/1888805/24709934/d15968a8-1a1b-11e7-80ba-241144857ccd.png)
