### ISSUE TITLE
disable wrapping in<p>-Tags

### ISSUE THREAD

**Issue by dirko0816** [Alex-D/Trumbowyg#170]
I want to use your pretty tool to edit tooltipps for my webapp.
Unfortunately every entry ist wrapped in P-tags and at end of line an unnecessary line-break (BR). Is there a way to disable this?
(Firefox 39 / Win 7)

![2015-08-18 12_49-dev hs-fresenius __ hochschulverwaltung __ sprachen](https://cloud.githubusercontent.com/assets/11752344/9328276/b8263d1a-45a7-11e5-9892-66b37c00948f.jpg)
![2015-08-18 12_50-dev hs-fresenius __ hochschulverwaltung __ sprachen](https://cloud.githubusercontent.com/assets/11752344/9328281/bd96f226-45a7-11e5-8e57-729a209ed12b.jpg)

**Comment by dirko0816** [comment]
I Think I found it. ;-)
setting semantic: false disabled this behaviour.

**Comment by Alex-D** [comment]
I don't know why Firefox add a `<br>` but if you don't want `<p>` tags, you need to disable semantic option.

**Comment by AdamHess** [comment]
What if we want semantic, but don't want it to wrap everything in a p tag? 

some of us need to prevent our users from inserting a P or line break at start so other formatting works correctly.
