### ISSUE TITLE
XSS attack  - escape script tags in editor

### ISSUE THREAD

**Issue by rstormsf** [Alex-D/Trumbowyg#175]
if I click on html mode I'm able to inject script tag
```html
<script>alert('1');</script>
```
which means, I can inject malicious javascript 

https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)

**Comment by rstormsf** [comment]
looks like it's duplication of #160

**Comment by Alex-D** [comment]
Yep that's the same point in #160.
