### ISSUE TITLE
No paragraphs?

### ISSUE THREAD

**Issue by odraencoded** [Alex-D/Trumbowyg#176]
Hey, I'm having a problem with Trumbowyg. When I start it with an empty textarea I don't get any paragraphs?

On chrome if I press enter I get a new DIV. On firefox I get a BR. Actually Firefox won't even let me type anything if the textarea is empty. I always need to switch to HTML and create a P tag before I can write. If I start typing inside a P tag then when I press enter I get new P tags.

**Comment by Alex-D** [comment]
That's strange :/ I need to take a look at that.

**Comment by Alex-D** [comment]
I've made a test on the master `index.html` with the default configuration and I get `<p>` tags in both Chrome 45 and Firefox 41. And I can type in empty textarea on Firefox.
