### ISSUE TITLE
No option to change the width of image

### ISSUE THREAD

**Issue by kisna72** [Alex-D/Trumbowyg#177]
When uploading image, I didn't see any options to edit its width or height, so when I upload a really big image, to show it elsewhere, it expands outside of the scree. Is there a 'graphical' way to edit this? Or make the image always be 100% width by adding an extra attribute of width in the <img> tag?

**Comment by Alex-D** [comment]
Trumbowyg is a WYSIWYG, so it use your website CSS. If you want a specific style, create a CSS class and go to HTML panel, then add the class: well done :)
