### ISSUE TITLE
SVG icons

### ISSUE THREAD

**Issue by atk** [Alex-D/Trumbowyg#178]
Instead of 2 PNG icon sprites that don't scale well, why not use 1 SVG icon sprite - if neccessary, with an PNG fallback?

To detect SVG support, you can simply use:
```
document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#Image", "1.1")
```

**Comment by Alex-D** [comment]
I think switch fully to SVG with a drop of the IE8 support in v2.0 :)

**Comment by atk** [comment]
You could provide a legacy css/js that would be included in conditional comments for IE8 support if is still required.

**Comment by Alex-D** [comment]
Nope. JS support will be drop too. IE8 is dead \o/

**Comment by atk** [comment]
I see dead browsers... ;-)

**Comment by Alex-D** [comment]
Almost done.
