### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by ra100** [Alex-D/Trumbowyg#190]
Which editor do you, Alex-D, use, and how do you have code formatter options set? I'd like to sync jsbeautify settings with you, for better pull requests, so there are no unnecessary changes.
I see you use 4 spaces indent, but I'm not sure how to set spaces in functions and conditionals
```function()``` vs ```function ()``` and ```if(true)``` vs ```if (true)```.
Thanks.

**Comment by Alex-D** [comment]
Yop!

I use Sublime Text 3.

I prefer `if (true)` with spaces.

**Comment by ra100** [comment]
OK, I'll try to search sublime-styled config for Atom.

**Comment by Alex-D** [comment]
I just fix all style in `src` and `plugins` folders. Thanks!
