### ISSUE TITLE
Fullscreen editor outside div

### ISSUE THREAD

**Issue by Muphet** [Alex-D/Trumbowyg#194]
Hi. I'm kinda new to github (well, as contributor) so if this question landed in wrong place - that's probably my bad.

Anyway, heres what I need help for. By default, editor that goes fullscreen maximizes only in current DIV. Is there a way to append it to browser window instead? I am oppening editor in a modal box and when applying full screen effect, it opens inside that modal making it almost unusable.

**Comment by ra100** [comment]
Can you share link or post code, so we can see how you used editor?

**Comment by Muphet** [comment]
it's just a custom div that slides from side of the screen:
	<div class="cd-panel-content">
		<div id="editor">
			...
                </div>
        </div>
![editorn1](https://cloud.githubusercontent.com/assets/11758669/10637677/34778b80-7807-11e5-98c0-05e431bb3262.jpg)
![editorn2](https://cloud.githubusercontent.com/assets/11758669/10637678/349620ae-7807-11e5-907e-57bffeec91c9.jpg)
on first picture editor normal view and second is fullscreen (i already fixed margin top since navbar was overlapping it). at same time i noticed buttons have this white square hover effect, thats probably me failing with css tho

**Comment by ra100** [comment]
I created new branch for testing of modal https://github.com/ra100/Trumbowyg/tree/modal and it seems working fine. But I'll try to look into that tomorrow.
If you could tell me what you use for modal/how you open it, it would help. So I can simulate that bug. Thanks.

**Comment by Muphet** [comment]
i am using jquery to add class on click and i am opening div using css transition
<code>.cd-panel-container {
  position: fixed;
  width: 90%;
  height: 100%;
  top: 0;
  background: #dbe2e9;
  z-index: 1;
  -webkit-transition-property: -webkit-transform;
  -moz-transition-property: -moz-transform;
  transition-property: transform;
  -webkit-transition-duration: 0.3s;
  -moz-transition-duration: 0.3s;
  transition-duration: 0.3s;
  -webkit-transition-delay: 0.3s;
  -moz-transition-delay: 0.3s;
  transition-delay: 0.3s;
  box-shadow: -2px 0 3px -3px #424242;
}
.from-right .cd-panel-container {
  right: 0;
  -webkit-transform: translate3d(100%, 0, 0);
  -moz-transform: translate3d(100%, 0, 0);
  -ms-transform: translate3d(100%, 0, 0);
  -o-transform: translate3d(100%, 0, 0);
  transform: translate3d(100%, 0, 0);
}
.from-left .cd-panel-container {
  left: 0;
  -webkit-transform: translate3d(-100%, 0, 0);
  -moz-transform: translate3d(-100%, 0, 0);
  -ms-transform: translate3d(-100%, 0, 0);
  -o-transform: translate3d(-100%, 0, 0);
  transform: translate3d(-100%, 0, 0);
}
.is-visible .cd-panel-container {
  -webkit-transform: translate3d(0, 0, 0);
  -moz-transform: translate3d(0, 0, 0);
  -ms-transform: translate3d(0, 0, 0);
  -o-transform: translate3d(0, 0, 0);
  transform: translate3d(0, 0, 0);
  -webkit-transition-delay: 0s;
  -moz-transition-delay: 0s;
  transition-delay: 0s;
}</code>

**Comment by ra100** [comment]
Which browser and OS do you use? I can't find anything wrong in Opera, Chrome, Firefox (on Linux).

**Comment by dawidxt** [comment]
I have the same issue. When my textarea is inside a div, it's just maximizing to it's parent div, not the browser's window, like it has place when the text area is not overriden by any div.

**Comment by Alex-D** [comment]
It's because your div has `position: relative` or something like that.

**Comment by dawidxt** [comment]
yep, indeed, but almost every complex layout which contain elements positioned: absolute must have it. Is there any trick to override it ?

**Comment by Alex-D** [comment]
Nope :(
