### ISSUE TITLE
Words with accents can't be written.

### ISSUE THREAD

**Issue by isalcedo** [Alex-D/Trumbowyg#195]
Actually you can only write words with accentuation if semantic is turned off (that's a pity), i love the code when the editor is using semantic, how can i solve this?

**Comment by Alex-D** [comment]
Same as #158 and #89

Semantic mode rewrite code between each keypress so if your character is composed (` then a for example to get à) Trumbowyg rewrite the code and clean force browser to clean his buffer :/

**Comment by isalcedo** [comment]
Sorry for the repost. I'll look for this and the way that I can help.
