### ISSUE TITLE
IE error - Could not complete the operation due to error 800a025e 

### ISSUE THREAD

**Issue by rvwoens** [Alex-D/Trumbowyg#196]
I got this error in IE when loading a trumbowyg element using ajax. 

It turned out it was due to a removeAllRanges without checking. This fixed it:

```javascript
if (s.rangeCount > 0 && s.getRangeAt(0).getClientRects().length > 0) {
    s.removeAllRanges();
}
```

**Comment by Alex-D** [comment]
Hi!

Which version of IE?

**Comment by mrtom808** [comment]
Hi, this problem is present in the latest version. Can you re-apply the fix? (IE11)

https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L1513
