### ISSUE TITLE
image upload plugin

### ISSUE THREAD

**Issue by gmaniac** [Alex-D/Trumbowyg#202]
I am trying to create a custom plugin for image uploading so it will send to a server side script I wrote. What should the object look like for the upload plugin you provide? On line 89 in `trumbowyg.upload.js` I am seeing that you use `data.message` and `data.file`, I have tried passing the response I am sending back which contains the following

    {
        'is_error': false,
        'message': 'uploadSuccess',
        'file': {
            'url': //the.com/url/of/the/image.jpg',
            'alt': 'something anything',
        },
    }

should there be more or am I doing it wrong? When I wen through `dist/trumbowyg.js` from lines 863-867 it doesn't look like anything other than `url` and `alt` are being used.

But when I try to upload an image it always is inserts like this `<img src="[object Object]">`

**Comment by madebycambiamentico** [comment]
the standard plugin "upload" expect "file" to be the url of the image, "message" is encoded in section lang of the same plugin (you need to add other ones if you want custom messages to show up, eg. "uploadNotAjax" from the examples).

so the standard object from your server - if the file is succesfully uploaded - should be:

```javascript
{
    'message': 'uploadSuccess',
    'file': 'url/path/to/image.jpg'
}
```

**Comment by madebycambiamentico** [comment]
i came up with se same problem...
seems that "file" have to be the plain text url to show up... is it a bug in plugin or in master js?

```javascript
{
    'message': 'uploadSuccess',
    'file': '//the.com/url/of/the/image.jpg', //bug bug bug?
}
```

**Comment by madebycambiamentico** [comment]
Since i really like the style of this plugin, I made some debug. the bug is in the plugin.

calling `tbw.execCmd('insertImage', data.file)` doesn't do what it's mean to be. So istead I use this code:
```javascript
	tbw.execCmd('insertImage', data.file.url);
	$('img[src="'+data.file.url+'"]:not([alt])', tbw.$box)
		.attr('alt', data.file.alt)
		//section below is an enhancement - not pertinent with the question. you can skip it
		.css( typeof data.file.sizes === 'undefined' ? {} : {
			maxWidth : data.file.sizes.w+'px',
			maxHeight : data.file.sizes.h+'px'
		});
```

**Comment by Alex-D** [comment]
There is no `alt` support on upload plugin actually.
If you want to add it, you can submit a pull request :)

**Comment by Alex-D** [comment]
I've worked on upload plugin as you can see here : https://github.com/Alex-D/Trumbowyg/blob/master/plugins/upload/trumbowyg.upload.js

This version is avaible under 2.0.0-beta.6 version.

I've added a lot of options, see example of use here : https://github.com/Alex-D/Trumbowyg/blob/master/index.html#L173

I need to write documentation ASAP.

**Comment by SeunMatt** [comment]
I struggled with implementing the upload stuff for some time so I wanna drop my insights here incase it may help someone else using nodejs

STEPS:
- include the js file <script type="text/javascript" src="js/trumbowyg.upload.min.js"></script>
- then initialise trumbowyg like this
 $("#test").trumbowyg({

  btnsDef: {
        // Customizables dropdowns
        image: {
            dropdown: ['insertImage', 'upload', 'base64', 'noEmbed'],
            ico: 'insertImage'
        }
    },
    btns: [
        ['viewHTML'],
        ['undo', 'redo'],
        ['formatting'],
        'btnGrp-design',
        ['link'],
        ['image'],
        'btnGrp-justify',
        'btnGrp-lists',
        ['foreColor', 'backColor'],
        ['preformatted'],
        ['horizontalRule'],
        ['fullscreen']
    ],
    plugins: {
        upload: {
            serverPath: '/upload',
            fileFieldName: 'image',
        }
    }
}); 

NOTE: in the plugin segment the serverPath is the POST path that you have created to handle the file uploading process. A typical path will be like this in express. Please note the response format.
The response object should be in the format below to work with the default trumbowyg.upload.min.js file

  router.post ("/uploader", function(req, res) {
   //do other handling here for multipart middleware like multer
  res.status(200).send({"file": "path/to/file/" + req.file.originalname, "success":true});
});

and just leave the fileFieldName option like that (I didn't bother to modify it);
before you can get the files in NodeJs environment you will need to install multer module and config it. The config info is on their github page
https://github.com/expressjs/multer

**Comment by toddmark** [comment]
```js
let editor = $('#editor-dropdown')
    .trumbowyg({
        btnsDef: {
            // Create a new dropdown
            image: {
                dropdown: ['insertImage', 'upload'],
                ico: 'insertImage'
            }
        },
        // Redefine the button pane
        btns: ['viewHTML',
          '|', 'formatting',
          '|', 'btnGrp-semantic',
          '|', 'link',
          '|', 'image',
          '|', 'btnGrp-justify',
          '|', 'btnGrp-lists',
          '|', 'horizontalRule',
          '|', 'fullscreen'],
        plugins: {
          upload: {
            serverPath: '123'
          }
        }
    })
    .on('tbwchange', (e) => {
      this.props.onChange(e)
    })
```
but I set the upload'serverPath as option , it's worked.
