### ISSUE TITLE
Include compiled dist

### ISSUE THREAD

**Issue by garygreen** [Alex-D/Trumbowyg#204]
It would be good if the compiled dist could be included in the npm build. I know you can run `gulp` and compile it from the sass, but installing this through npm should include the compiled dist just like the bower one does. I don't use sass or bower so it's a bit of a nuisance atm.

**Comment by patrickml** [comment]
+1

**Comment by Alex-D** [comment]
It juste need to add a `.npmignore` to avoid npm to use .gitignore which ignore `dist` folder.

**Comment by Alex-D** [comment]
I've just publish 2.0.0-beta.7 with dist folder for npm :)

**Comment by garygreen** [comment]
Nice, thanks ! :)
