### ISSUE TITLE
better plugins documentation

### ISSUE THREAD

**Issue by madebycambiamentico** [Alex-D/Trumbowyg#205]
i refer mainly on the upload plugin (the others are self-explanatory). there's nowhere any documentation to understand what data can be passed on upload success?
it seems that - by default - you should pass only `message` (success/custom error(?)) and url called `file`, but i really don't understand the function `getDeep`...

PS - what is the purpose of `upload.success`? it doesn't seems to pass any parameter to possible user-defined function

-- great work by the way! --

**Comment by balashovka** [comment]
response from server must be an json ["success": 0||1, "file" : "path/to/file" ]

**Comment by Alex-D** [comment]
I've just updated upload plugin, so I don't take the time to write a correct documentation. Don't care about `getDeep`.

That's the basic usage from https://github.com/Alex-D/Trumbowyg/blob/gh-pages/js/main.js#L5 (used by demo page).

    $.extend(true, $.trumbowyg.upload, {
        serverPath: 'https://api.imgur.com/3/image',
        fileFieldName: 'image',
        headers: {'Authorization': 'Client-ID 9e57cb1c4791cea'},
        urlPropertyName: 'data.link'
    });

Here `data.link` is the property of your JSON response from server which contains the image path.

In this case, server response means look like that:

```
{
    "data": {
        "link": "http://domain.com/example.jpg"
    },
    "message": "Error or success message"
}
```

`fileFieldName` is the name of field which contains the file. Upload plugin use it to build AJAX request. In the above case, imgur server wait for a request with `image` attribute which contains image data.

I hope it's help you. I need to write a better doc than that, but I need time.

**Comment by minkwe** [comment]
I want to write a plugin which pops a modal with a text field and and inserts whatever text is entered into the current position of the editor after wrapping the text with configurable styles. I have two questions:

1. Which of the included plugins could be a base something like this?
2. How do get my plugin to show up on the menu.

**Comment by sandydonor** [comment]
The upload file is only for php and in absence of any documentation of the plugin, I am unable to run this for asp.net. I have created a .vb file, and the image gets uploaded correctly, but the JSON that I return is probably not playing it correctly.

Can someone please guide me with this.

Thanks

**Comment by Alex-D** [comment]
Soon online with the 2.8.0 :)
