### ISSUE TITLE
v2.0.0-beta.5 CSS breaks fullscreen mode

### ISSUE THREAD

**Issue by philbertphotos** [Alex-D/Trumbowyg#206]
I back tracked the CSS to version v2.0.0-beta.0 and that fixed the problem. Full-screen opens up but you cant close it with out refreshing . None of the buttons work.

**Comment by Alex-D** [comment]
Have you got try other beta.x?

**Comment by Alex-D** [comment]
I've just deploy 2.0.0-beta.7 which fix that bug :)
