### ISSUE TITLE
Add CDN version

### ISSUE THREAD

**Issue by montogeek** [Alex-D/Trumbowyg#208]
Hi Alex!
Great editor!

Can you please provide a CDN link? Yes, there are still project that dont use Bower or anything related :(

**Comment by montogeek** [comment]
I solved it using your same solution: rawgit.
But I am talking about specialized services like https://cdnjs.com/

**Comment by Alex-D** [comment]
There is a PR in progress since a while for the 1.1.7

I think make a PR for the 2.0.0 ASAP.

**Comment by Alex-D** [comment]
All versions are here now: https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/Trumbowyg

**Comment by montogeek** [comment]
Thanks!
