### ISSUE TITLE
autogrow fails in Mozilla v 24

### ISSUE THREAD

**Issue by rrphotosoft** [Alex-D/Trumbowyg#209]
Hi, 
I tried using the plugin in Mozilla v.24.
The autogrow feature does not work. The text does not flow over to the next line, instead, a horizontal scrollbar is seen.
Is Mozilla v 24 supported, if not, what is the minimum supported version.
Thanks,
RR.

**Comment by Alex-D** [comment]
Hi!

autogrow option is for vertical autogrow, not horizontal and works for me in 41+

I don't know why any other version since Firefox 5 could not works.

Thanks

**Comment by rrphotosoft** [comment]
Hi Alex,
First of all, thank you for the great work with the plugin!! It is the best WYSIWYG editor out there.
I will send you a screenshot of the problem. I think it is do with FF handling of contenteditable elements. You can try it with any contenteditable element, the word wrap occurs on word breaks(spaces), so if you type a very long word ,without spaces, there is no word break, and new line is not created.
I will try to debug and get back to you.
Thanks again.
RR.

**Comment by Alex-D** [comment]
Oh, OK, but that's not really a bug... If you do that in your page, your body get a scrollbar too :/
