### ISSUE TITLE
Blur and Change events not firing

### ISSUE THREAD

**Issue by jfreak53** [Alex-D/Trumbowyg#210]
I've tried with beta4 and also with the most recent version downloaded from your page, using the `tbwblur` event and the `tbwchange` event, neither one fires at all.

How can I fix this?

```
$('#typingpadarea').trumbowyg({
		fullscreenable: false,
		closable: false,
		removeformatPasted: true,
		btns: [ 'formatting', '|', 'btnGrp-design', '|', 'btnGrp-justify', '|', 'btnGrp-lists' ]
	}).on('tbwblur', function () {
		console.log('Changed Editor');
		padSave();
	});
```

**Comment by Alex-D** [comment]
This code : https://github.com/Alex-D/Trumbowyg/blob/master/index.html#L290

works for me in Firefox and Chrome so I don't know what is your bug/problem :/

Can you give me more information about browser/OS ?

**Comment by jfreak53** [comment]
I am using Chrome Version 46.0.2490.86 and it is on Linux OS. But the OS shouldn't matter, JS is browser based so if it works in Windows Chrome it should work in Linux Chrome.

**Comment by Alex-D** [comment]
Can you send me a zip with an isolated example of your bug please?

Thanks!

**Comment by jfreak53** [comment]
I can't, it's NDA software. I can however send you the link to the exact JS file we are using so you can test using it?

http://writercb.com/libraries/js/trumbo/trumbowyg.js

Then the "only" code we use to implement it is what I posted above. So in essence that's it, not really any other code to show really.

**Comment by jfreak53** [comment]
Nevermind, close this please :) found the error on our end. Thanks for the help!

**Comment by Alex-D** [comment]
Be sure to use last version of Trumbowyg which is [2.0.0-beta.7](https://github.com/Alex-D/Trumbowyg/tree/2.0.0-beta.7)

**Comment by jfreak53** [comment]
I tried with the latest version also and it did the exact same thing. I downloaded it from your front page then replaced what I had with it.

**Comment by EternityForest** [comment]
I am now having this same issue, so perhaps whatever it was is common enough to document?
