### ISSUE TITLE
Meteor package support

### ISSUE THREAD

**Issue by malkesh** [Alex-D/Trumbowyg#213]
Hi @Alex-D 

Thanks for developing this plugin.

I used this plugin in a meteor app. So, I created a meteor package using version(tag) 1.1.7, last stable version as master branch is unstable and dist. files aren't available. And it is working quite well with 1.1.7. But i can't publish this package on meteor packages(https://atmospherejs.com) due to in-stable master branch of trumbowyg.

So, i would like to know when will master branch be stable and dist files available ?

**Comment by Alex-D** [comment]
Hi!

dist folder never be on master branch. master is my development branch. What do you need for this publication?

**Comment by malkesh** [comment]
We just need to add package.js file in repo. The package.js file contains information about files required by meteor to build its package. 

Check package.js file in this repo. https://github.com/twbs/bootstrap. You will get idea.

I cloned your repo. and tested package on my local environment by following this guide.
http://www.smashingthingstogether.com/make-your-first-meteor-js-package. It is working.

But i can't pushed package to atmospherejs due to dist. files.

**Comment by Alex-D** [comment]
Can you redirect package manager to a tag? `dist` folder is only in production build https://github.com/Alex-D/Trumbowyg/tree/2.0.0-beta.7

Maybe I need to change that and include dist folder into master and dev on a develop branch...

**Comment by malkesh** [comment]
Nope. I can't. 

Actually, you should keep master branch production ready and create new branch for your changes. Once you find that your changes are ready for production then merge your branch to master.

**Comment by Alex-D** [comment]
Yep so I'm forced to apply gitflow... I do that ASAP.

**Comment by malkesh** [comment]
Ha ha :)

Thanks in advance.

**Comment by Alex-D** [comment]
Step 1 done : split develop and master branches.
So now, I just need to release builded versions of Trumbowyg on master if I have understand your explanations :) I do that really soon.

**Comment by Yonben** [comment]
hi,
I'm using the current package I found on atmosphere: https://atmospherejs.com/malkesh/trumbowyg , ho can I add plugins to it? :)

Thanks a lot !

**Comment by malkesh** [comment]
HI @Yonben,

I didn't get you. May you explain detail, what you exactly like to do ?

Thanks,
Malkesh

**Comment by terenceng2010** [comment]
@malkesh Let's say, the color plugin?
