### ISSUE TITLE
Formatting Buttons don't work as expected

### ISSUE THREAD

**Issue by benSn** [Alex-D/Trumbowyg#216]
If you click the bold button in FF (v43) and start typing just some characters are printed in bold face and then the editor switch back to the normal font-weight. 
If you click the bold Button in IE 11 the button works as expected and every character you hit is printed in bold face. The same happens for the other formatting buttons (italic, underline) expect the line-through button which don't work in correct in any browser.

**Comment by Alex-D** [comment]
I'm using browser native execCommand, so It's a bug of the browser :( If I want to fix it, I need to recode Trumbowyg in another way.
