### ISSUE TITLE
Semantic Option Not Working Unless You Click the HTML Source Button

### ISSUE THREAD

**Issue by tovic** [Alex-D/Trumbowyg#218]
Also with the `<p>` tag insertion. See:

![bug](https://cloud.githubusercontent.com/assets/1669261/12619705/d0356ab0-c54b-11e5-93c2-fa5c62ed684e.gif)

**Demo:** https://jsfiddle.net/vj90s9fb

**Comment by Alex-D** [comment]
It's also fired at blur :)

**Comment by tovic** [comment]
But then my form has a **Trumbowyg** plugin, when I submit the form, it still use `<b>` tag, not `<strong>`, so the saved form data will still not _semantic_ &rarr; https://jsfiddle.net/vj90s9fb/3

![bug](https://cloud.githubusercontent.com/assets/1669261/12634088/356845c6-c5a9-11e5-8e67-fc111509cc5f.gif)

I&rsquo;m on Windows 8.1, Firefox.

This should be marked as a bug.
