### ISSUE TITLE
SCSS variables overriding

### ISSUE THREAD

**Issue by simon-jouet** [Alex-D/Trumbowyg#221]
Hi,

I have been running into some issues with trumbowyg and the way the icon path are hardcoded into the SCSS, My grunt pipeline copies all the assets to different folders based on their types and it works for almost all libraries but Trumbowyg has an hardcoded path such as ```$icons-white: "./images/icons-white.png";``` which prevents the variables to be overriden.

Suggestion would be to either simply add !default after the variable definition or define a new variable which is the image page that can be overidden.

```
  $icons-path: "./images/" !default;
  $icons-white: $icons-path + "icons-white.png";
```

Thanks,
Simon

**Comment by Alex-D** [comment]
I've just updated the `develop` branch. If you're familiar with gulp, npm and other, you can build via : 

```shell
npm install
gulp build
```

in root folder.

If you need a builded version, I will build it soon.

**Comment by simon-jouet** [comment]
Hi @Alex-D thanks for the update! I'm familiar with the tools but I find it more practical to only manage the dependencies through bower, I will just wait for the next release, for the time being I just used CSS !important to override the background-image :)

Thanks,
Simon
