### ISSUE TITLE
Insert link

### ISSUE THREAD

**Issue by Feduch** [Alex-D/Trumbowyg#222]
Hi!

If selected the text includes quotes, then in modal window "text" is empty.

![libs24](https://cloud.githubusercontent.com/assets/5888590/12820779/9e87a0ce-cb71-11e5-9550-90970e3c8a4a.png)
![libs25](https://cloud.githubusercontent.com/assets/5888590/12820782/a2f39258-cb71-11e5-9bba-a7921b0c855a.png)
![libs26](https://cloud.githubusercontent.com/assets/5888590/12820780/a0fc2f28-cb71-11e5-89f5-0c45154865b4.png)

**Comment by Alex-D** [comment]
Thanks for reporting this bug. I've fix it and will be soon in the next release.
