### ISSUE TITLE
Create Link doesn't work

### ISSUE THREAD

**Issue by ra100** [Alex-D/Trumbowyg#224]
When trying to insert link, I select text, click insert link, fill url, nothing changes. Console shows no errors.
Last working commit is 3dd6cc1c76ce048ad7c05d3037fa80c321844a0e and editlink plugin is a bit broken too.
I tried it in Opera, Vivaldi, Chrome, Firefox.

**Comment by Alex-D** [comment]
Thanks for your feedback. I need to take the time to check that. As you can see, I work hard to release v2 asap. But when I fix a bug, another is created :(

It's not usefull to test in Opera, Vivaldi and Chrome. They use the same Blink+V8 build, so there is no differences :)

**Comment by ra100** [comment]
Seems like it's everywhere, fix one bug, create two. And I think it's in a way selection works. But I haven't got more time to look at how it works. 

And from my experience, sometimes not everything works same in O/V/Chrome and Opera is my primary browser, so if something doesn't work there, I try other "Blink wrappers". But in general, you're right.

**Comment by Alex-D** [comment]
It's seems like fixed with this commit. If you can test this patch you will make me happy :)

**Comment by ra100** [comment]
Create link works fine. But I'll have to fix editlink plugin, to work with new selection behaviour.
