### ISSUE TITLE
Toolbar/Button pane wrapping

### ISSUE THREAD

**Issue by pclancy** [Alex-D/Trumbowyg#225]
Hi,

Currently the tool bar  isn't wrapping nicely.  This happens on the project homepage if you shrink the browser size small you'll notice the tool bar and content are overlapping (FF & chrome).

![image](https://cloud.githubusercontent.com/assets/211053/12898198/6b0293b4-cea3-11e5-962a-0cc0d605e3e1.png)

`.trumbowyg-button-pane` probably needs to lose absolute positioning to allow the textarea to be pushed down.

Possibly something like this...

`.trumbowyg-button-pane {
	height: auto;
	overflow: hidden;
  width: 100%;
  min-height: 37px;
  background: #ecf0f1;
  border-bottom: 1px solid #d7e0e2;
  margin: 0;
  padding: 0;
  list-style-type: none;
  line-height: 10px;
  -webkit-backface-visibility: hidden;
          backface-visibility: hidden; }`

**Comment by Alex-D** [comment]
It's a duplicate of #134. Trumbowyg is just not yet responsive :/

**Comment by kerwan** [comment]
Using flexbox like this seems to do the trick. But it might be problem for older navigators like ie < 10

  .trumbowyg-box {
  	display: flex;
  	flex-direction: column;
  	padding-top: 0px;
  }
  
  .trumbowyg-button-pane { 
  	height: auto; 
  	overflow: hidden; 
  	width: 100%; 
  	min-height: 37px; 
  	background: #ecf0f1; 
  	border-bottom: 1px solid #d7e0e2; 
  	margin: 0; padding: 0; 
  	list-style-type: none; 
  	line-height: 10px; 
  	position: relative;
  	-webkit-backface-visibility: hidden; 
  	backface-visibility: hidden; 
}

**Comment by Alex-D** [comment]
Works with modals?

**Comment by kerwan** [comment]
Not as is, but i tried some adaptations for the image modal (as referenced in issue #134) because i needed it to be responsive and i think they are not perfect but they work.

I just saw that this issue is closed because of it beeing a duplicate of #134 so i put my answer on the thread there so it could be discussed.
