### ISSUE TITLE
Links in a link

### ISSUE THREAD

**Issue by groenroos** [Alex-D/Trumbowyg#226]
Since the link tool is a dropdown menu, with insert and edit functions always available, it's possible to create links within links; just select a portion of text inside an existing link, and insert another link.

I'd also say it's kind of confusing for the end user to receive the option of editing a link where none exists, or is selected.

This is why other similar editors only offer a single link button without a dropdown of choices; if the cursor is in a link, it displays an edit form, if not, it displays a create form. The "delete link" option could be tucked into the edit form as well, to eliminate the need of the whole dropdown.

**Comment by Alex-D** [comment]
I will close this because it will be fixed by the fix of #12 as you said.

I think it's a "duplicate" so I prefer just link this in the other thread :)

Thanks for you interest and the quality of your description of the bug, it's really helpful!

**Comment by Alex-D** [comment]
I've fix it on `develop` branch by merging @ra100 's edit link plugin. So there is no "Edit link" anymore, this feature is in "Insert link" button.

So, if you insert a link in a link, insert link panel open with actual link infos and edit it if you confirm.
