### ISSUE TITLE
Cut, undo, redo is not working properly

### ISSUE THREAD

**Issue by saggiyogesh** [Alex-D/Trumbowyg#227]
After Cut, undo, redo, `tbwchange` event is not giving correct html.

**Comment by Alex-D** [comment]
Curious. I need to check that. Which version do you use? Last beta release or develop branch?

**Comment by saggiyogesh** [comment]
latest. as i see code there is no handler for cut event.

**Comment by Alex-D** [comment]
Nope. It's managed by the browser :)

**Comment by Alex-D** [comment]
I've found a workaroud which is to listen Ctrl+Z / Ctrl+Y keyup events and `cut` event.

It's only on `develop` branch for now. I hope it was what you expected.
