### ISSUE TITLE
Can't set formatting before writing

### ISSUE THREAD

**Issue by ra100** [Alex-D/Trumbowyg#230]
When I click bold/italics buttons or use shortcuts it doesn't change formatting when nothing is selected. Formatting can be changed only afterwards.

**Comment by Alex-D** [comment]
Yep, it's normal. It's the content editable. I can't do anything to that without amount of code like watching changes and apply style :(

**Comment by ra100** [comment]
I am not sure if it doesn't breat anything else, for now it seems it does what I wanted. 06505ded97a851200482c731c238a29a4bf4d202

**Comment by Alex-D** [comment]
This break some others use cases :/
