### ISSUE TITLE
Various heading style bugs when inside a container

### ISSUE THREAD

**Issue by garygreen** [Alex-D/Trumbowyg#231]
![trumboy bug](https://cloud.githubusercontent.com/assets/1702638/13014765/60a76770-d1ad-11e5-9039-9e7582a5c410.gif)

The same thing happens when inside numeric list, or block quote. Possibly others. Using 2.0.0-beta7

**Comment by Alex-D** [comment]
Oh! Pretty!

Non blocking, but It will be interesting to fix it.

**Comment by Alex-D** [comment]
It's a contenteditable bug :/
Can't do anything without recode all the plugin, sorry...
