### ISSUE TITLE
Upload plugin not working 

### ISSUE THREAD

**Issue by alekspetrov** [Alex-D/Trumbowyg#232]
Hey, spent all day trying to make this plugin work. 
You have different versions from bower and git. 
Bower version (1.0) has no settings for plugin. 
From git master (1.1) modal window for uploading is not open at all, your own uploader example not work.

**Comment by Alex-D** [comment]
Hey!

Take a look at demo page: http://alex-d.github.io/Trumbowyg/ and switch to the "With all plugins" to see it in action. It works here. Consider https://github.com/Alex-D/Trumbowyg/tree/2.0.0-beta.7 insteed of master.

**Comment by alekspetrov** [comment]
Alpha upload example also not open upload modal.  
Try it `git clone --> bower i && npm i --> gulp build ` then open examples/upload.html and hit image upload button 😕

**Comment by Alex-D** [comment]
The upload.html isn't up to date. Take a look to index.html at the root of the project insteed.

**Comment by alekspetrov** [comment]
:root --> index.html from alpha branch, uploader modal doesn't work. 
This is alpha.7 but on your demo site you using alpha.5 and it works.

**Solution:** download js code from DevTools (`trumbowyg.min.js` & `trumbowyg.upload.min.js`) right from [demo](https://alex-d.github.io/Trumbowyg/) site, and now it works fine 🙃

**Comment by Alex-D** [comment]
Strange but OK. I will check that.
