### ISSUE TITLE
Insert link doesn't work on Firefox

### ISSUE THREAD

**Issue by ra100** [Alex-D/Trumbowyg#233]
Tested on Firefox 44.0.2. After selecting text a clicking insert link modal doesn't show up. Just text changes to link with `href="createLink"`.
I'm looking into it, but wanted to notify about this bug.

**Comment by ra100** [comment]
Seems Firefox doesn't provide in selection `extentNode`

**Comment by ra100** [comment]
Fixed by 9ebe4cf4b7392b1b822fe3edace99d9d77a9b54c

**Comment by Alex-D** [comment]
Fix'd by your PR :)
