### ISSUE TITLE
Question: Have a link in button toolbar

### ISSUE THREAD

**Issue by morningtoast** [Alex-D/Trumbowyg#237]
I'd like to add a direct link in the toolbar dropdown...just a link to another web page. I have an image gallery for users and in the "Image" dropdown I have "Insert image" and "Upload image" (via the plugin), and I want to add a plain link for "Image gallery" - can't quite figure out how to do this. 

The docs highlight how to do modals and things but I just need this to be a link that opens in a new window. 

No bug here. Just a question or possible enhancement suggestion. Otherwise, I'm have great luck with Trumbo, so thank you for all the effort!

**Comment by Alex-D** [comment]
It's possible, but not via a link. Maybe via a button and JS code which opens a new tab.

I take a look at that asap.

Thanks for the suggestion :)

**Comment by Alex-D** [comment]
More doc to come to cover plugin creation which solve this kind of need. See 2.8.0: https://github.com/Alex-D/Trumbowyg/pull/613
