### ISSUE TITLE
2.0-beta7 issues

### ISSUE THREAD

**Issue by timint** [Alex-D/Trumbowyg#239]
I have some issues with 2.0-beta7. The main js file says beta5 and after uploading (replacing the old files) the toolbar looks like this:

![image](https://cloud.githubusercontent.com/assets/359192/13381319/4c62be3c-de59-11e5-8159-be598946aaef.png)

No errors logged, no network errors. I refreshed content.

Any ideas?

**Comment by Alex-D** [comment]
Browser and his version ? Retina ?

I work on SVG icons for the final release, but it would be works.

**Comment by timint** [comment]
Latest Chrome 64-bit on Win 10

I figured there were issues as the package stated beta5 but the download button beta7.

**Comment by Alex-D** [comment]
Do you see this bugs here: http://alex-d.github.io/Trumbowyg/ ?

It's the beta.7 so if it works, I don't know what's the bug.

**Comment by timint** [comment]
There is no bug in http://alex-d.github.io/Trumbowyg/.

I figured this could be a cache issue so I tried incognito and I tried emptying cache. Didn't work. Are there any new mandatory config params, because all I did was replacing the old files with the new from the beta7 download. I managed to upgrade 4 sites before I noticed this issue in all of them.

**Comment by Alex-D** [comment]
Have you got replace sprite file too?

**Comment by timint** [comment]
I just used WinMerge and compared all the files in the package, and they are all binary identical with the release of beta7.

**Comment by Alex-D** [comment]
Can I have access to a demo page?

**Comment by timint** [comment]
http://demo.litecart.net/admin/?app=pages&doc=edit_page&page=1&pages_id=4
http://demo.litecart.net/admin/?app=pages&doc=edit_page&page=1

**Comment by Alex-D** [comment]
You CSS override Trumbowyg CSS, but it works for me on the first link. I've got all icons and I can go fullscreen, etc.

It's buggy on the second one because there is no content and your CSS reset something in Trumbowyg.

**Comment by timint** [comment]
The first link in my browser displays the same as the attached image in the first post.
The second link shows me a collapsed view of ~20px width.

What is the code you are refering to by CSS overriding?

**Comment by Alex-D** [comment]
Can't reproduce.

**Comment by Alex-D** [comment]
2.0.0-beta.8 introduce new SVG icons. Hope this fix your bug.

**Comment by timint** [comment]
I will try and let you know. Thanks for getting back to this.

**Comment by timint** [comment]
Okay problem solved by the latest version. There are some cosmetic issues as Trumbowyg inherits some button-styling from the app itself although parsed lastly. I'm gonna do some customizing. A small advice is to define the whole margin and not just margin-bottom (i think it was) in .trumbowyg-button-pane button as that will prvent the other three sides from inheriting the styling. I also discovered some redundant styles here and there. I can attach my changes later so you can cherrypick whatever you find of value.
