### ISSUE TITLE
Add event for when initialized

### ISSUE THREAD

**Issue by garygreen** [Alex-D/Trumbowyg#243]
At the moment there's no way of plugging into when an editor is initialized. My use case is I want to create my own 'image insert' plugin and override the default double click event on the images. I can turn off the default event by `this.$ed.off('dblclick', 'img');` and add my own, but because there's no events fired when an editor is initialized, it makes it difficult to hook into.

**Comment by Alex-D** [comment]
Maybe I need to make it as an option. I will try to check that asap.

**Comment by garygreen** [comment]
Also for some reason `insertImage` is a function and not used, it's duplicated in the event handler. If you search for it you'll see what I mean.

**Comment by Alex-D** [comment]
I've added an `tbwinit` event in develop branch. It will be OK for v2 stable :)

Thanks for suggestion.

**Comment by garygreen** [comment]
Thanks.

**Comment by Alex-D** [comment]
I've also added a handler, but I think to rename it so be careful on update:

https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L341
