### ISSUE TITLE
Images and some HTML code no save

### ISSUE THREAD

**Issue by thelatinspirit** [Alex-D/Trumbowyg#244]
Hello. 
I have installed, Trumbowyg , and when I insert html codes containing images, the images are not saved,  texts and formats are saved, but does not save images,

How do I enable  save images option?

Thank you for your help

**Comment by Alex-D** [comment]
I did not understand your problem. How do you insert images ?

**Comment by Alex-D** [comment]
Without example on demo I can't help you :/

Feel free to reopen it you have some new elements.
