### ISSUE TITLE
Not responsive or mobile browser friendly

### ISSUE THREAD

**Issue by genyded** [Alex-D/Trumbowyg#245]
First and foremost - BEAUTIFUL control that is lightweight and fast!! Any chance you could add media-queries or at least 'rows' for the toolbar and content so that it display nicely and can be used in mobile browsers too? Also probably hide full screen below laptop size.

Right now it displays like the attached screenshot and the top of the content goes under the toolbar on smaller devices. We could make the changes ourselves, but then they would be wiped out by any updates...

![image](https://cloud.githubusercontent.com/assets/3081676/13909537/3253ad36-eee3-11e5-8588-006e17bdb48f.png)

Thanks for a great control and consideration to make it even better!

**Comment by Alex-D** [comment]
That's the same problem as #134

I work on it for the v2 :)

Thanks!
