### ISSUE TITLE
Upload plugin: demo code to integrate to Responsive Filemanger

### ISSUE THREAD

**Issue by absalomedia** [Alex-D/Trumbowyg#247]
Is there any way of making Trumbowyg talk to [https://github.com/trippo/ResponsiveFilemanager](https://github.com/trippo/ResponsiveFilemanager) using the current Upload plugin?

I've managed to replace in place an entire TinyMCE build except for the image upload process that links to Responsive Filemanager.

**Comment by Alex-D** [comment]
I don't think the upload plugin can talk to this without change, but I think it could be done with some adaptations.
