### ISSUE TITLE
How to use upload plugin and  integration with another jquery script

### ISSUE THREAD

**Issue by rtcunningham1** [Alex-D/Trumbowyg#248]
I'm not familiar with jquery at all. I have no idea how to add the upload plugin and make it work. Any help would be appreciated.

Also, this plugin, http://qwertypants.github.io/jQuery-Word-and-Character-Counter-Plugin/, is supposed to append a div, but it ends up inside the Trumbowyg text area (at the bottom) and doesn't work. Any idea how I can still use it?

**Comment by Globulopolis** [comment]
@rtcunningham1 for your second question I've create an issue in plugin repo at [jQuery-Word-and-Character-Counter-Plugin
](https://github.com/qwertypants/jQuery-Word-and-Character-Counter-Plugin/issues/17)

**Comment by rtcunningham1** [comment]
Thanks. I don't know what all that stuff means but I appreciate the help.

**Comment by Globulopolis** [comment]
@rtcunningham1 plugin was updated. Now you can use it with Trumbowyg.
Just add a `<div/>` for counter and use another selector for plugin init. Something like this:

```
// Init editor
var editor = $('#form_review').trumbowyg({
	lang: 'ru',
	removeformatPasted: true,
	btns: [ 'formatting', '|', 'btnGrp-design', '|', 'btnGrp-justify', '|', 'btnGrp-lists', '|', 'viewHTML' ]
});
// Init counter
$('.trumbowyg-editor').counter({ // this is a class from the div with contenteditable="true"
	append: false,
	target: '#word-counter'
});
<textarea id="form_review"></textarea>
<div id="word-counter"></div>
```

PS! Be aware when you setup `prefix` option. You need to update selectors.

**Comment by rtcunningham1** [comment]
@Globulopolis Thanks for the help. Things moved faster than I expected.

**Comment by Alex-D** [comment]
Seems to be resolved

**Comment by Fer-Marival** [comment]
nice, but if i want to put 2 or more?

**Comment by Globulopolis** [comment]
@Fer-Marival you mean multiple editors on one page?
If yes - use loop.
