### ISSUE TITLE
Roadmap for v2.0.0

### ISSUE THREAD

**Issue by cenobitedk** [Alex-D/Trumbowyg#250]
Thank you for a great editor!

Do you have a roadmap for when v2 goes out of beta?

I pulled the latest from npm (2.0.0-beta7), but it seems some parts haven't been implemented yet when looking in the documentation. Eg. I stil have to use `fullscreenable: false` and the event `tbwinit` didn't seem to fire.

**Comment by Alex-D** [comment]
Thanks!

I work on the new landing page and update/improve docs.

The last beta is `2.0.0-beta.8`, not 7.

For fullscreen option : http://alex-d.github.io/Trumbowyg/documentation.html#fullscreen

For `tbwinit`, it's strange. Try with beta 8 maybe.

**Comment by cenobitedk** [comment]
Yeah I know beta 8 is the latest, but I get beta 7 from NPM.

I read the documentation about fullscreen which is why I found it odd that I had to use the `fullscreenable` option.

**Comment by Alex-D** [comment]
> but I get beta 7 from NPM.

This is strange :/

**Comment by cenobitedk** [comment]
Did you publish beta.8 to npm?

**Comment by Alex-D** [comment]
I've just published the v2.0.2 to bower and npm

**Comment by cenobitedk** [comment]
Thanks!
