### ISSUE TITLE
How to redefine buildEditor method? 

### ISSUE THREAD

**Issue by 6pm** [Alex-D/Trumbowyg#251]
I write Trumbowyg component for vue.js. And i need redefine method buildEditor for attach vue model for two way binding.
How best way to do it?

**Comment by Alex-D** [comment]
Why do you need to change buildEditor exactly?

**Comment by 6pm** [comment]
Need for add two way binding for textarea.

**Comment by Alex-D** [comment]
So base your code on the textarea, then launch Trumbowyg on this textarea and you will be able to have 2 way binding work like a charm :)

If you want, there are Angular and Angular 2 directives:

https://github.com/lizardK/trumbowyg-ng
https://github.com/MuhammedHasan/ng2-trumbowyg

**Comment by Alex-D** [comment]
I stay here but want to close to keep issues clean :)
