### ISSUE TITLE
Image upload callback

### ISSUE THREAD

**Issue by JordyPouw** [Alex-D/Trumbowyg#252]
The upload functions allows you to upload an image which then again shows up in your editor. 
But where in your code can i find the callback that sets the img element with the right src. 

As example: I want to add a class to every image that is uploaded.
All i can find is this line:
`$('img[src="'+v.url+'"]:not([alt])', t.$box).attr('alt', v.alt);`

Which is for the insert image function and not the upload image function... 
Am I missing something?

Thnx in advance!

**Comment by JordyPouw** [comment]
(The example is purely a example, I want to change the img element to a html5 video element and make it possible to upload videos.)

**Comment by Alex-D** [comment]
You need to create a new plugin, maybe create a new function "insertVideo" which call `execCmd` with "insertImage" then find the inserted image like:

`$('img[src="'+v.url+'"]);` and work on this element.

Your request is not trivial :/
