### ISSUE TITLE
SCV icons path problem

### ISSUE THREAD

**Issue by akupiec** [Alex-D/Trumbowyg#253]
### Informations
It's quite problematic to load icons through javaScript.
The only reason i decided to user trumbowy was clean way to replace all css and icons.

So pleas add easy way to give relative path for icons inside *.scss. (for example variable with path like it was till 2.0.0-beta.8)
(it it's already possible please mention this in documentation)

Moreover not setting `svnPath `is throwing error in console.

**Browser + version**: chrome/ie10
**OS**: win
**Resolution**: 2.0.0+

### How to reproduce the bug?
try to use Trumbowyg without setting path to icons through js.

**Comment by RespectTheCoder** [comment]
Use `svgPath`, also see #256.

**Comment by Alex-D** [comment]
I've just added a global `$.trumbowyg.svgPath` option which can be set to false to disable SVG js loading.

I can't just hide network error and I can't put SVG management in CSS due to actual support of SVG features sucks, e.g. I

**Comment by briansanchez** [comment]
this works, thank you Alex.
//2019-08-16 angularjs fix, when minimizing will help to avoid >> You must define svgPath: https://goo.gl/CfTY9U
$.trumbowyg.svgPath = '/static/bower_components/trumbowyg/dist/ui/icons.svg';
