### ISSUE TITLE
Refresh trumbowyg

### ISSUE THREAD

**Issue by sreinoso** [Alex-D/Trumbowyg#255]
### Informations

**Browser + version**:chrome 49.0.2623.75 (64-bit)
**OS**:Linux 3.19.0
**Resolution**:1600x900(16:9)

### How to reproduce the bug?

I've got a textarea that I want to refresh content, but trumbowyg does not update the data.
There are any way to refresh trumbowyg?

Thanks

**Comment by Alex-D** [comment]
Insteed of change the textarea content, use the .trumbowyg('html', 'your HTML here') API method.

See doc: http://alex-d.github.io/Trumbowyg/documentation.html#manage-content

**Comment by sreinoso** [comment]
Thanks!
