### ISSUE TITLE
How can I apply jquery validation plugin to the Trumbowyg?

### ISSUE THREAD

**Issue by meshekhar** [Alex-D/Trumbowyg#259]
How can I apply jquery validation plugin to the Trumbowyg, for simple validation such as empty, maxlength, etc.

**Comment by Alex-D** [comment]
Run validation on the textarea like there is no Trumbowyg. It will work.

**Comment by meshekhar** [comment]
I will give it a try.

**Comment by paulgabronis** [comment]
@Alex-D no it doesn't work when you leave editor it throws this error:
Uncaught TypeError: Cannot read property 'replace' of undefined

**Comment by pedroct92** [comment]
I am having the same issue on my application. I've checked here and it is like Trumbowyg has the input from the user when access via get `$('#temp').trumbowyg('html')` but when I access the value on the textarea itself it is empty.

**Comment by maxehhh** [comment]
Same happens to me, when i start typing on the trumbowyg textarea i start getting Cannot read property of undefined. Trying to fix it but i think it might be a validate problem.

**Comment by Dhiarllon** [comment]
With each new textarea, insert a new line assigning an id to the generated div: 
 $("div.trumbowyg-editor.trumbowyg-reset-css").eq(0).attr('id', 'S1');
 $("div.trumbowyg-editor.trumbowyg-reset-css").eq(0).attr('id', 'S2);
...

**Comment by cilipe** [comment]
```
$('#submitbutton').click(function() {
    if ($('textarea[name="mytextarea"]').val() == '') {
        $('.showmessage').css("display", "block");
        return false;
    } else {
        $('.showmessage').css("display", "none");
    }
});
```

**Comment by dearsina** [comment]
@Dhiarllon let me to the following solution that has helped me, as I was getting the following error whenever jQuery validation tries to work a Trumbowyg element:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
```

Try adding a random value to an `id` attribute in the `trumbowyg-editor` div. Something like this will work although I'm sure there are more elegant solutions:

```
$(".trumbowyg").find(".trumbowyg-editor").attr("id", Math.random());
```
