### ISSUE TITLE
Bold/Strikethrough

### ISSUE THREAD

**Issue by luetge** [Alex-D/Trumbowyg#264]
### Informations

**Browser + version**: Chrome 50 and FF 45
**OS**: OSX El Capitan
**Resolution**: 2880 x 1800

### How to reproduce the bug?
Go to https://alex-d.github.io/Trumbowyg/, add a newline, click on "Bold" and start typing. This "resets" the "Bold" button and the text is in regular font, same with italics, strikethrough.

Also: select a word, click strikethrough twice, then the text stays strikedthrough. Interestingly, this is not a problem for bold and italics.

**Comment by Alex-D** [comment]
These bugs are from Content Editable browser feature. I can't fix them :/
