### ISSUE TITLE
Only able to set bold, italic, etc on selected text

### ISSUE THREAD

**Issue by mikerockett** [Alex-D/Trumbowyg#265]
### Information

**Browser(s)**: Tested with Firefox 45 and Vivaldi 1
**OS**: Windows

### How to reproduce the bug?

If you press the 'bold' toolbar button and then type in the editor, the text is not bold. You actually need to highlight the text that you want, and then select 'bold'.

My specific page setup is not applicable to this, as the issue is apparent on the demo site as well.

**Comment by Alex-D** [comment]
I think it is not a bug. It simplify state management and you should write before apply any style.

**Comment by mikerockett** [comment]
That's not how other editors work. If I want to switch to bold in Word or *any* other HTML editor, I need only press Ctrl+B. Sure, it's not a bug, but it is a missing feature.

**Comment by Alex-D** [comment]
It's so hard to implement with other semantic features. And Trumbowyg is not a Word-like WYSIWYG.
If you want that, you can turn to other big WYSIWYG with ton of code and features :)

**Comment by mikerockett** [comment]
Okay - I have switched to the newest TinyMCE; I see much has changed since I used it last.
