### ISSUE TITLE
SVG path issue, Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by channelriyas** [Alex-D/Trumbowyg#266]
Hi Alex,
Thanks for this lite editor,

I am getting "_Uncaught TypeError: Cannot read property '1' of null_" on trumbowyg.js line 166.
this line contain `svgPath = stackLines[Number(i)].match(/((http[s]?:\/\/.+\/)([^\/]+\.js)):/)[1].split('/');` 

Is it familiar? please help me on this!

**Chrome + 50.0.2661.94 m**:
**Windows 8**:
**1366 X 768**:

Thanks!

**Comment by rajamohammed** [comment]
Specify the path to the SVG icons in init options 

eg 
`$('textarea').trumbowyg(
{svgPath:'ui/icons.svg'}
);`

**Comment by channelriyas** [comment]
Wow its worked, Thanks Rajamohammed, 
'svgPath' too in init thats really helpful, without touching core js.

Again thanks for your valuable time :)

**Comment by Alex-D** [comment]
See the 2.1.0 updated doc for more informations:

https://alex-d.github.io/Trumbowyg/documentation.html#svg-icons
