### ISSUE TITLE
implement setDisabled method

### ISSUE THREAD

**Issue by misaon** [Alex-D/Trumbowyg#267]
Hi, i miss function as: 

`<textarea disabled></textarea>`

Can you implement some like this?
Thanx

**Comment by Alex-D** [comment]
I did not understand the request :/
Maybe you should run Trumbowyg on non-disabled fields?

```js
$('textarea').not(':disabled').trumbowyg();
```

Or maybe you want all toolbar button disabled and read-only text field?

**Comment by misaon** [comment]
Yes, read-only option.

**Comment by Alex-D** [comment]
I've added on `develop` branch:

- support of `disabled` attribute
- `disabled` option
- `enable` and `disable` API calls (e.g. `$('.editor').trumbowyg('disable');` which change state of editor to disabled)

I hope it was you want :)

**Comment by Alex-D** [comment]
Check the updated doc for more informations: 

https://alex-d.github.io/Trumbowyg/documentation.html#disabled
https://alex-d.github.io/Trumbowyg/documentation.html#enable-disable-edition
