### ISSUE TITLE
Better Plugin Documentation

### ISSUE THREAD

**Issue by AdamHess** [Alex-D/Trumbowyg#268]
Howdy, Would you add more documentation as to how to add a trumbowyg specific plugin. It seems heavily read existing plugins and hope for the best. 

(maybe even give examples of building one using the concepts for an existing plugin)

**Comment by Alex-D** [comment]
I work on writing more doc asap, but that was not easy before v2 to make a plugin, I have completly rewrote plugins implementation.

So now, I can work on a clean doc.

This issue is a duplicate of #205 which have the exact same title, so I close this issue.
