### ISSUE TITLE
Fullscreenable option is not working?

### ISSUE THREAD

**Issue by EnzoEghermanne** [Alex-D/Trumbowyg#269]
### Information

**Browser + version**: Google Chrome 50.0.2661.94 (64-bit)
**OS**: MAC OS X El Capitan 10.11.3
**Resolution**: 2560x1440

### How to reproduce the bug?
![image](https://cloud.githubusercontent.com/assets/6171742/15145995/1314a634-16b9-11e6-85f8-fb14d699c8e5.png)

![image](https://cloud.githubusercontent.com/assets/6171742/15146085/a261e1da-16b9-11e6-8fe1-a90042e774ba.png)

```
$('#trumbowyg').trumbowyg({
            fullscreenable: false
        });
```
The `fullscreenable` option still produces a button on the editor when set to `false`, and the button still maximizes the editor to fullscreen.

**Comment by Alex-D** [comment]
Hey!

Fullscreenable option was removed in v2.

> Since 2.0.0, 'fullscreen' is a button like others. You can add/remove it from button pane configuration

So you need to specify your custom `btns`, you can base your list on: https://alex-d.github.io/Trumbowyg/documentation.html#button-pane

Hope it was what you find :)

**Comment by EnzoEghermanne** [comment]
Allright, thanks for the clarification. 

I suggest you remove it from the example in the "Getting started" section on your presentation page at https://alex-d.github.io/Trumbowyg/#get-started as well then."

Keep up the good work, Trymbowyg = :thumbsup:

**Comment by Alex-D** [comment]
Ah yep, in fact. I work on a redesign on the page, I will change that :)
