### ISSUE TITLE
Trumbowyg does not load icons[Webpack]

### ISSUE THREAD

**Issue by DiegoGallegos4** [Alex-D/Trumbowyg#270]
I im currently trying to use the library but when it loads all the library loads the textarea as the it should but without the icons. I loaded css, icons and then js. I  tested in on chrome(49^) and safari(9.0.3) and it has the same behavior. Im on Capitan OSX. 

On the console I have the following error: 

**trumbowyg.js:189 Uncaught TypeError: Failed to execute 'serializeToString' on 'XMLSerializer': parameter 1 is not of type 'Node'.**

To reproduce the bug: 
1. Create a textarea
2. Then $('textarea').trumbowyg(). Used classes and ids as well.

**Comment by Alex-D** [comment]
Your problem is from this lines: https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L177-L179

I think icons.svg file is not correctly loaded. Maybe you should fix SVG path using this option: https://alex-d.github.io/Trumbowyg/documentation.html#svg-icons

**Comment by bharani91** [comment]
I ran into this issue today. 

Here's how I solved it - 

```
import icons from "vendor/trumbowyg/ui/icons.svg"
import "vendor/trumbowyg/ui/trumbowyg.min.css"
import "vendor/trumbowyg/trumbowyg.min.js"
$.trumbowyg.svgPath = icons
```

Then you can use the editor as you would. I am using React here - 

```
export default class RichTextEditor extends Component {
  componentDidMount () {
    $("#editable").trumbowyg();
  }
  render () {
    ...
  }
}
```

Another thing to note when using Trumbowyg (or any jQuery library) is that we have to expose jQuery and $ variable as a global. Assuming that you are putting your jQuery libs in a directory called `vendor`. Add this to your webpack loader - 
```
{ 
  test: /vendor\/.+\.(jsx|js)$/,
  loader: 'imports?jQuery=jquery,$=jquery,this=>window'
}
```

**Comment by istrau3** [comment]
@bharani91 Which loader are you using to load icons.svg. I have tried your solution using the file file-loader, url-loader and svg-inline to load .svg files. None worked.

**Comment by bharani91** [comment]
@istrau3 Here's my webpack config for loading svg files. 
```
{ 
    test: /\.svg/,
    loader: 'url?limit=10000&mimetype=image/svg+xml'
}
```

**Comment by mostlyjason** [comment]
Wow I spent a few hours trying to figure out how to get this to work with webpack and I wish I saw this first. I think I didn't see it because it was marked as closed and was not included in the documentation. I don't see a way to contribute to the documentation through GitHub, but I'd be happy to contribute if needed.

By the way my approach was slightly different because I'm using Typescript, server-side rendering and CopyWebpackPlugin.

I added these static assets to webpack because they are not included in the npm module.
```
new CopyWebpackPlugin([
      { from: 'node_modules/trumbowyg/dist/ui/icons.svg', to: 'images'},
      { from: 'node_modules/trumbowyg/dist/ui/trumbowyg.min.css', to: 'css'}
    ]),
```
I import the CSS in the head
```
<link rel="stylesheet" href="/public/css/trumbowyg.min.css" />
```
I declare an interface for typescript:
```
interface IJQueryTrumbowyg extends JQuery {
  trumbowyg(): void;
  trumbowyg(Object): void;
}
```
I only require the library when the window is defined so that it's not loaded on the server side
```
    // Jquery is only available on the client side so don't try to load trumbowyg on the server
    if (typeof window !== 'undefined') {
      require('trumbowyg');
      
      const content = $('#articleContent') as IJQueryTrumbowyg;
      content.trumbowyg({
        // The library allows JavaScript to be loaded from webpack but not images
        svgPath: '/public/images/icons.svg',
      });
    }
```
