### ISSUE TITLE
Setting witdh and height

### ISSUE THREAD

**Issue by eguvenc** [Alex-D/Trumbowyg#271]
How can i set witdh and height of textarea ?

**Comment by Alex-D** [comment]
In CSS, you design your textarea, then you plug Trumbowyg on it and it's done :)

**Comment by Surt** [comment]
Actually I'm triying to set the height and can't make it work. I setted the textarea `height`, even the `rows` attributte. I overrided the `.trumbowyg-box`min-height with `!important` and setted a fixed height with important too, but nothing works, the editor doesn't take it into account.

**Comment by dep** [comment]
I am having the same issue.  Textarea has 100px height on init, but trumbo trumps it with a height of 300px.

**Comment by Alex-D** [comment]
I will check that asap. This is weird.

**Comment by dep** [comment]
Thanks! In the meantime I was able to simply pop in to the library CSS and
adjust two min-height rules from 300px.

**Comment by Alex-D** [comment]
Check SCSS:

- here: https://github.com/Alex-D/Trumbowyg/blob/develop/src/ui/sass/trumbowyg.scss#L41
- and here: https://github.com/Alex-D/Trumbowyg/blob/develop/src/ui/sass/trumbowyg.scss#L59

**Comment by josephadah** [comment]
This was helpful.
i used
#my-textarea .trumbowyg-box, #my-textarea .trumbowyg-editor {
	min-height: 100px !important;
}
#my-textarea .trumbowyg-editor, #my-textarea .trumbowyg-textarea {
	min-heigh: 100px !important;
}
