### ISSUE TITLE
Missing icons.svg

### ISSUE THREAD

**Issue by fruitbatinshades** [Alex-D/Trumbowyg#272]
Before report an issue, be sure to put these informations. Thanks :)

on line 168 of trumbowyg.js is the following line:

svgPathOption = svgPathOption.join('/') + '/ui/icons.svg';

there is no file in the repository called icons.svg. Has it been missed from the last update? Only individual icon files are there

**Comment by Alex-D** [comment]
https://github.com/Alex-D/Trumbowyg/blob/master/dist/ui/icons.svg

**Comment by fruitbatinshades** [comment]
Thank you, I downloaded develop by mistake
