### ISSUE TITLE
DLT tag remove format support

### ISSUE THREAD

**Issue by sharifzadesina** [Alex-D/Trumbowyg#274]
Hi
Remove format of some semantic tags like DLT and INS (which will be insert by pr #273) are not support by browsers.
I think we must write this tags commands manually if we want this action.
tnx for good editor.

**Comment by Alex-D** [comment]
Sorry, but I don't want to add lot of code to fix little thinks like this. If you need some features like this, go to a more complete WYSIWYG.

If I accept all small queries like that, I do what Redactor.js has do : start at 35ko and go to 150ko :/
