### ISSUE TITLE
Editor is not updating content in Chrome after removing tags

### ISSUE THREAD

**Issue by pacoleyva** [Alex-D/Trumbowyg#275]
Before report an issue, be sure to put these informations. Thanks :)

### Informations

**Browser + version**: Chrome Version 50.0.2661.102 (64-bit)
**OS**: OS X El Capitan
**Resolution**:

### How to reproduce the bug?
I wrote a plugin based in preformatted plugin, in fact is very similar. I have to set default data to editor containing tags that can be removed with the custom button, apparently if try to remove the tags with the button all works ok in Chrome Inspector but when I get the editor value ( using  $(selector_name).trumbowyg('html') or  $(selector_name).val()  ) the tags still are there. In Firefox the content is updated correctly.

**Comment by Alex-D** [comment]
Idk, It's a browser issue I think. I don't have the time to solve it sorry :/
