### ISSUE TITLE
Unable to delete some elements in firefox

### ISSUE THREAD

**Issue by rmills** [Alex-D/Trumbowyg#276]
Tested both in a local test and on: https://alex-d.github.io/Trumbowyg/ .

Chrome works as expected. However in firefox `<hr>` tags can no be deleted in most cases. If you use the html view to clear all the content, switch back to the design view, use the toolbar to add an `<hr>` you can not back space to delete it. Unordered lists created the same issue where you could not backspace to remove the first element once it was created. 

Example resulting code copy pasted from the html view:

`<ul><li><br><hr></li></ul><p><hr></p>`

### Informations

**Firefox + 46.0.1**:
**Win 7**:

**Comment by Alex-D** [comment]
It's a Firefox bug and Idk how to fix it. I don't have the time to search more, sorry.
