### ISSUE TITLE
Strip Formating from copy paste by default.

### ISSUE THREAD

**Issue by rmills** [Alex-D/Trumbowyg#277]
**Feature Request**: A very common issue I have is when users are copy pasting copy from rich text editors into the editor when its used in a CMS. This ends up forcing inline styles leading the user to try and use the editor to fix it leading to very messy HTML and forced styles. It would be great to have an option that could be call on init to call the "remove formatting" option on the content as its copy/pasted every time.

**Comment by timint** [comment]
Already present. Set your config to:

  removeformatPasted: true

**Comment by Alex-D** [comment]
If you looked at the documentation you will probably find the [remove format pasted option](http://alex-d.github.io/Trumbowyg/documentation.html#remove-format-pasted) as @timint said ;)

I just post to add the link to the documentation.
