### ISSUE TITLE
enableObjectResizing not supported in IE10- browsers

### ISSUE THREAD

**Issue by michaelsoriano** [Alex-D/Trumbowyg#278]
Trying to implement in our intranet - which unfortunately requires IE10-. It's inside a bootstrap modal box and when initializes, it breaks at line 447:

 **t.doc.execCommand('enableObjectResizing', false, false);**

![trumbog1](https://cloud.githubusercontent.com/assets/5881081/15516771/3794a478-21a9-11e6-89d0-ef80ca0ec502.jpg)

It's a known bug: https://dev.ckeditor.com/ticket/4208, but I'm wondering how I can fix so it is ignored in IE10. 
### Informations

**Browser + version**: IE 10-
**OS**: Windows 7
**Resolution**:

### How to reproduce the bug?

I have a jsfiddle: https://jsfiddle.net/mks6804/rbk7sgkr/7/ - again, it has to run in stupid IE10-.  

Any help is appreciated.

**Comment by Alex-D** [comment]
This bug is only in IE10 -, not IE10+

So IE11, Edge 12 and 13 are OK.

So maybe I should try catch this line... but I don't know if Trumbowyg works on IE10. I've optimized it for recent browsers.

**Comment by michaelsoriano** [comment]
yes a try catch is good. 

also on line 1183 

**t.doc.execCommand('styleWithCSS', false, forceCss || false);**

I'm using it in IE 10 w/ those 2 lines commented out and it seems to work fine.

**Comment by Alex-D** [comment]
Note: IE9 and IE10 should have auto update option enabled and update to IE11. Idk why you are on IE10 :/

**Comment by michaelsoriano** [comment]
Our intranet runs legacy stuff. So upgrades are disabled. 
I'm fine with the try catch. You can close issue if you like.

**Comment by michaelsoriano** [comment]
closed by accident.

**Comment by rlems** [comment]
@michaelsoriano You didn't have this issue with "defaultParagraphSeparator" one line later? I'm getting the same error there too in IE10.

**Comment by michaelsoriano** [comment]
@rlems - not that I know of.

**Comment by rlems** [comment]
@michaelsoriano I put that part in the try catch block too. Don't know if this is an issue though.
