### ISSUE TITLE
DIV gets replaced by P

### ISSUE THREAD

**Issue by timint** [Alex-D/Trumbowyg#279]
Customers report an unexpected behavior of divs being transformed to p tags. The expected behavior was to remain div.

**Comment by Alex-D** [comment]
You need to set `semantic` option to `false`. Cf. http://alex-d.github.io/Trumbowyg/documentation.html#semantic

**Comment by timint** [comment]
Thanks Alex. I made no note of div in the documentation but I will see if that does the trick.

**Comment by zanozik** [comment]
`div`s still keep changing to `p`, even though `semantic: false`

**Comment by artus9033** [comment]
Experiencing the same problem, though semantic is set to false; any solution?
