### ISSUE TITLE
Missing release note for 2.1.0

### ISSUE THREAD

**Issue by cenobitedk** [Alex-D/Trumbowyg#280]
I would love to know what has changed/been added/been fixed for version 2.1.0. Do you have a release note?
Digging through the git changes doesn't really tell me much.

**Comment by Alex-D** [comment]
I've just added a note here: https://github.com/Alex-D/Trumbowyg/releases/tag/v2.1.0
Hope it helps you :)

**Comment by cenobitedk** [comment]
Thank you :-)
