### ISSUE TITLE
Electron SVG bug: TypeError: Failed to execute 'serializeToString' on 'XMLSerializer'

### ISSUE THREAD

**Issue by linux-man** [Alex-D/Trumbowyg#283]
I'm using Trumbowyg (2.1.0) on Electron (v0.37.8). Strangely, I can only use svg icons if I change line 189:
```
            var div = t.doc.createElement('div');
            div.id = trumbowygIconsId;
            t.doc.body.insertBefore(div, t.doc.body.childNodes[0]);
            $.get(svgPathOption, function (data) {
                div.innerHTML = data; // <-- THIS line
            });

```
or else I get
> TypeError: Failed to execute 'serializeToString' on 'XMLSerializer': parameter 1 is not of type 'Node'.

**Comment by Alex-D** [comment]
In Electron I think you will manually add the #trumbowyg-icons div via automatization (gulp-inject for example) to avoid this part of code.

I don't have any Electron app to test that :/

**Comment by linux-man** [comment]
No need for that. The question is why on Electron $.get() returns a String, not an Object. A simple if solve the problem, something like 
```
if(jQuery.type(data) === "object") div.innerHTML = new XMLSerializer().serializeToString(data.documentElement)
                else div.innerHTML = data;
```
This is not a Trumbowyg bug, so this issue is just a reference.
