### ISSUE TITLE
error on $(ele).trumbowyg();

### ISSUE THREAD

**Issue by jeffreybasurto** [Alex-D/Trumbowyg#286]
Installed, reinstalled, confirmed

I'm using bower.  Everything is up to date.  

`trumbowyg.self-458e258….js?body=1:178 Uncaught TypeError: Cannot read property '1' of null(…)`

Any idea what's going on?   Confirmed in console that the element being selected exists and is being passed.   I've tried it on textarea and on div (documentation is unclear which is the right way) with same error.

**Comment by jeffreybasurto** [comment]
To answer my own question, this seems to be what happens when the icons.svg asset cannot be found and you need to either disable them or set the path manually.   Maybe surface this error?

**Comment by Alex-D** [comment]
Hi! I think this could be helpful for futur devs: http://alex-d.github.io/Trumbowyg/documentation.html#svg-icons
