### ISSUE TITLE
Good way to use <div> instead of <p>

### ISSUE THREAD

**Issue by gammons** [Alex-D/Trumbowyg#287]
Hi there,

First off, we love Trumbowyg and are using it in a large project.  We were wondering how easy it would be to replace Trumbowyg's default of using `<p>` tags with `<div>`.  The reason is we are using trumbowyg as a mail client, and the default functionality when hitting the enter key is to create blocks of text within a `<div>` tag.  

Any insight on how to do this would be greatly appreciated.  Thanks again for this awesome plugin!

**Comment by Alex-D** [comment]
Hi! I've worked in an agency specializing in email and I don't think using `<div>` is a great idea.

In Trumbowyg, the goal is to get a semantic final result, use div insteed of paragraph make no sens.

You can disable the semantic part of Trumbowyg by switching `semantic` to `false`.

View more: http://alex-d.github.io/Trumbowyg/documentation.html#semantic

**Comment by gammons** [comment]
Hi Alex-D,

Yup mainly we want to emulate the functionality of what Google does when creating an email.  So when I create an email that looks like this in gmail:

![image](https://cloud.githubusercontent.com/assets/38560/15717019/0e81da92-27f3-11e6-9f12-704998feb399.png)

and I look at the source, they are using `<div>` tags:

![image](https://cloud.githubusercontent.com/assets/38560/15717050/37b686ec-27f3-11e6-898b-26c096b799aa.png)

That's what we'd like to accomplish using Trumbowyg.  Thus far here's what we tried:

1.  Setting [defaultParagraphSeparator](https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L437) to `div`, although this had no effect, either with `semantic` set to `true` or `false`.
2. Forcefully calling this below, during the `tbwchange` event:

```javascript
jQuery(this.props.editor).data("trumbowyg").doc.execCommand("formatBlock", false, "div")
```
While this worked, it had unintended side effects when using ordered or unordered lists.  Also, it's more of a band-aid than anything, as the `<p>` tag gets generated before `tbwchange` gets called.  Therefore hitting enter will write a `<p>` tag, and then my code to force-format it to `<div>` gets called.  Clearly this is not ideal.

Ideally I need to get direction on how the `<p>` tag gets created, but thus far I haven't been able to crack that code.  Trumbo is only ~1500 lines of code, and I have studied it carefully, but I still can't figure out where the `<p>` comes from. 

Any help here would be appreciated!  Thanks!

**Comment by Alex-D** [comment]
> Ideally I need to get direction on how the <p> tag gets created

Trumbowyg is based on the browser contenteditable. If defaultParagraphSeparator does not work, you need to change all <p> into <div> like I do in semantic, but for your case.

Maybe try to change: https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L1013

**Comment by trendhim** [comment]
I actually also needed to change this behavior for an email client, which i also wanted to do the same as gmail which the divs. 

An easy fix is changing: https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L1063

to:

`                    t.semanticTag('p', 'div', true);
`

**Comment by aswzen** [comment]
for current version use `t.semanticTag('div', false);` or just comment that line

**Comment by Alex-D** [comment]
Hey!

Now you can customize the semantic behaviour. Check out the doc here: https://alex-d.github.io/Trumbowyg/documentation/#semantic
