### ISSUE TITLE
saveRange, restoreRange saving cursor position

### ISSUE THREAD

**Issue by aha5811** [Alex-D/Trumbowyg#289]
Hi,

just yesterday I started adding Trumbowyg to my project. I am now trying to use saveRange and restoreRange to save the editors state (on every keyup):

```
$('.trumbowyg-editor')
  .on('keyup click', function () {
    var state = this.getState();
    if (state) {
      // store away and
      this.setState(state);
    }
}.bind(this));

getState:
  this._ta.trumbowyg('saveRange');
  var data = this._ta.data('trumbowyg');
  var state = { range: data.range, metaRange: data.metaRange };
  data.range = null; data.metaRange = null;
  return state;

setState(state):
  this._ta.data('trumbowyg').range = state.range;
  this._ta.data('trumbowyg').metaRange = state.metaRange;
  this._ta.trumbowyg('restoreRange');
```

(`this._ta` is the trumbowyg'ed textarea)

That was working fine (although it could be easier with something like `getRange -> { range, metaRange }` and `setRange({ range, metaRange })`) - but it was not restoring the cursor position. I changed your `restoreRange` method from:
```
if (metaRange && metaRange.start !== metaRange.end) {
```
to
```
if (metaRange) {
```
and it is now saving the cursor position, too - but only in Chrome, in Firefox and IE11 it throws an exception in `getTagsRecursive` like this:

```
buildEditor:
.on('mouseup keydown keyup', function () {
  t.updateButtonPaneStatus();
})
->
updateButtonPaneStatus:
tags = t.getTagsRecursive(t.doc.getSelection().focusNode.parentNode),
-> 
getTagsRecursive:
var tag = element.tagName;

element is null
```

Maybe this cursor saving is something you find useful and maybe you could make it work in Firefox & IE, too?

Cheers
Alexander

**Comment by Alex-D** [comment]
`saveRange` and `restoreRange` are for plugins and core.
If you want to save cursor position for anything that not directly for the editor (bold, italic, insert video or any feature like that) you should not use that functions.

As you see, `saveRange` is here to save a selection range, not the cursor position. If you want that, you should add that features as a plugin or something like that, but not by using these function directly.

What is your goal by saving cursor position anytime? Maybe there is a better solution to do what you want :)

**Comment by aha5811** [comment]
> As you see, saveRange is here to save a selection range, not the cursor position.

It's just that e.g. here: [http://stackoverflow.com/questions/6249095/how-to-set-caretcursor-position-in-contenteditable-element-div](http://stackoverflow.com/questions/6249095/how-to-set-caretcursor-position-in-contenteditable-element-div) it's stated that the range could be used to save the cursor position, so I thought I could use this. And I could save the cursor position successfully for the (previously ordinary) textareas with something like this:

```
        // https://stackoverflow.com/questions/2897155/get-cursor-position-in-characters-within-a-text-input-field
        var selection = undefined;
        try {
            if ($.isNumeric(input.selectionStart))
                selection = {
                    direction: input.selectionDirection,
                    start: input.selectionStart,
                    end: input.selectionEnd
                };
        } catch (e) { /* happens in chrome with <input type='number'> */ }
```

which is also mainly used to save a range (and not just the position). And it's working in Chrome, so ... :)

> What is your goal by saving cursor position anytime? Maybe there is a better solution to do what you want :)

I have textareas on different 'pages' and the user can switch between them - and because of the architecture of the app these pages get (re-)created on each access. And because the content may be huge I want to save the scroll and cursor position everywhere.

If I'd want to write a plugin, can you give me some hint where to start or which existing plugin I should look at to get the general idea? I could not find any documentation about it ...

cheers
Alexander

**Comment by Alex-D** [comment]
> And it's working in Chrome, so ... :)

Web is not only Chrome ^^ Firefox, Edge and Safari are sometimes differents.

All existing plugins are here: https://github.com/Alex-D/Trumbowyg/tree/develop/plugins

Especially: https://github.com/Alex-D/Trumbowyg/blob/develop/plugins/colors/trumbowyg.colors.js#L93

Maybe you should use the `tagHandler` mechanism which is run at each selection change (that what's you need I think). You just need to return an empty array in your case.

There is no doc for the moment :/ I need to work on it.

**Comment by aha5811** [comment]
>> And it's working in Chrome, so ... :)

> Web is not only Chrome ^^ Firefox, Edge and Safari are sometimes differents.

my simpler selection code is working in all (modern) browsers, what I meant was "with the change I made to your code the cursor storing seems to be working in chrome, so [maybe with a few tricks it is also working in all other modern browsers]". :-)

thanks for your links - I will look further into it :+1:
