### ISSUE TITLE
Key Code 229 prevents to trigger tbwchange

### ISSUE THREAD

**Issue by nomfecris** [Alex-D/Trumbowyg#290]
### Informations

Hi,

To start with, I am really enjoying the use of Trumbowyg! 

Now I know that from reading some of the comments on other issues logged and the github pages that mobile is not supported. Though it's not supported, from all the WYSIWYG, this is literally the best one out there (without paying an arm and a leg) for great simply editing on mobile!

With that being said I have small issue, on Android Browsers It looks like Android browsers were considered in the past, as at this part of the [code](https://github.com/Alex-D/Trumbowyg/blob/master/src/trumbowyg.js#L530), there are checks done agains the even code for key 229, which is a dreaded issues and long outstanding with [google](https://bugs.chromium.org/p/chromium/issues/detail?id=118639). I was wondering if we would be able to either remove the check or add a check against the browser. In short right now on line [530](https://github.com/Alex-D/Trumbowyg/blob/master/src/trumbowyg.js#L530) it gets checked and on line [550](https://github.com/Alex-D/Trumbowyg/blob/master/src/trumbowyg.js#L550) it prevents that key from being able to trigger a `tbwchange`

**Browser + version**:
Chrome 50.0.266
**OS**:
Android 6.0.1
**Resolution**:
### How to reproduce the bug?
- Open the demo page http://alex-d.github.io/Trumbowyg/ in a Chrome browser on Andriod
- Enter new text
- Observe that `tbwchange` never gets reached.

**Comment by zspitzer** [comment]
have you considered using the HTML5 **input** event instead of keyup and keydown?

https://developer.mozilla.org/en/docs/Web/API/GlobalEventHandlers/oninput

**Comment by Alex-D** [comment]
Yep, but it didn't works anywhere :(

**Comment by zspitzer** [comment]
you mean everywhere? don't all major browsers support it, IE9 is dead

**Comment by Alex-D** [comment]
Feel free to make a pull request if you thing I've wrong :)

**Comment by zspitzer** [comment]
ok, can do, is IE 11 now the oldest browser which needs to be supported?

**Comment by Alex-D** [comment]
It should not crash on IE9 and 10 if possible, but the bug can stay on these versions.

**Comment by danieloprado** [comment]
Pull Request #445
