### ISSUE TITLE
tbwchange not fired when dragging text into the box

### ISSUE THREAD

**Issue by jsiulian** [Alex-D/Trumbowyg#291]
### Informations
Hello,

I have been playing with the WYSIWYG on a form and I have added a feature that would allow you to drag text into it. However after submitting the form i noticed that if the last input was text that has been dropped, it wouldn't go through. I have been able to confirm this behaviour by adding a handler for the 'tbwchange' event and it did not trigger for dragged text.

I have added a fix by changing .on('keyup') to .on('keyup input') inside the trumbowyg.js and it appears to have been fixed. According to specifications, oninput is supported by all major browsers and is supposed to catch any change to the content. Hope this helps.

**Browser + version**: Chrome 50.0.2661.94
**OS**: Windows 10
**Resolution**: 1920x1080

Best regards,
Sergiu

PS: Great WYWIWYG btw.

**Comment by Alex-D** [comment]
Hi!

Thanks for that, I have not tested this use case. I will try that asap.
