### ISSUE TITLE
Two quick suggestions for the XHR request to get the SVG icons

### ISSUE THREAD

**Issue by christophe** [Alex-D/Trumbowyg#292]
Hi there,

I would like to make two suggestions concerning the loading of the SVG icons via XHR request:

1. When the svgPathOption is neither correct nor disabled, the script issues a rather cryptic JS error. It would be helpful if this was caught and a comprehensible error message put into the console.

2. More importantly, I had some problems with the XHR request itself because, in my application, I set a lot of default options using $.ajaxSetup(), to avoid having to repeat them for every XHR request. (Such as dataType:"json", which causes a parser error in the callback of your XHR request.) Rather than making the dangerous assumption that all the $.ajax() default options remain unaltered, you should spell your AJAX request out, like this (trumbowyg.js:188 (2.1.0)):

```
$.ajax({
	async: true,
	type: 'GET',
	contentType: 'image/svg',
	dataType: 'xml',
	url: svgPathOption,
	data: null,
	beforeSend: null,
	complete: null,
	success: function (data) {
		div.innerHTML = new XMLSerializer().serializeToString(data.documentElement);
	}
});
```

Thank you very much for your amazing editor and, possibly, these small modifications.

Best regards,

Christophe

**Comment by Alex-D** [comment]
I will take a look at that asap.
Thanks for this note :)

**Comment by Alex-D** [comment]
I've fixed the second point.

I will try the first point later.

Thanks for your suggestions :)

**Comment by christophe** [comment]
Thanks for the changes!
