### ISSUE TITLE
Bug Report for Firefox (fix included)

### ISSUE THREAD

**Issue by christophe** [Alex-D/Trumbowyg#294]
Hi there,

Some of my users had an "NS_ERROR_FAILURE" JavaScript error in Firefox, on line 463 of trumbowyg.js (2.1.0). After preceding that line with `t.doc.designMode = 'on';`, as suggested in this post (http://stackoverflow.com/questions/2901759/how-to-i-disable-the-moz-resizing), the error seems to be gone.

Best regards,

Christophe

**Comment by christophe** [comment]
Unofrtunately, it isn't as easy to fix. Setting designMode to 'on' seems to remove the NS_ERROR_FAILURE, but it messes with all the controls (links, buttons) outside of the editor.

**Comment by Alex-D** [comment]
As the issue template ask, can you give me Firefox version where this bug is present?
Thanks for your researches :)

**Comment by christophe** [comment]
I'm sorry but I do not know. I get automated emails from my application on server and JS errors, but they do not include the browser version. All I cann tell you is that with my version (FF 46.0.1), the error  didn't happen.

**Comment by Alex-D** [comment]
Ok, so it's seems to be an old unsupported version of Firefox. So, I close this issue, because like I don't support IE6, I don't want support old Firefox/Chrome/...

**Comment by OneBitAhead** [comment]
We can confirm that error on Firefox 38, which is the previous LTS / ESR version and still used by our customers.
