### ISSUE TITLE
Event Handlers are not removed on 'destroy'

### ISSUE THREAD

**Issue by linux-man** [Alex-D/Trumbowyg#296]
Editor call:
```
$('#editor').trumbowyg()
.on('tbwfocus', function(){ console.log('Focus!'); })
.on('tbwblur', function(){ console.log('Blur!'); });
```
The problem arises if one intend to create/destroy the editor multiple times on the same element: the events are called n + 1 times (n = number of previous editors).

Fix: destroy function should end with
```
t.$c.trigger('tbwclose');
t.$ed.off(); //not sure if $ed is the right option, but it works
```

**Comment by Alex-D** [comment]
Thanks for this fix. I will add it to the next version.

**Comment by Alex-D** [comment]
I've check, it's on your side to do this.

It's your code which add listener, not mine, so you need to perform a .off() after a .destroy().

It allows you to create an editor, add listeners, destroy editor, create editor and keep your old listeners. If you don't want that, you need to remove listeners before/after destroy.

Hope it helps you, sorry for delay.
