### ISSUE TITLE
Apply custom classes on content ?

### ISSUE THREAD

**Issue by gbourgneuf** [Alex-D/Trumbowyg#298]
Hi,

is there a way to setup some custom classes to apply to HTML tags when editing content ?
For example: If I put a text as Header 1 (h1), can I automatically add classes to the h1 tag ?
example: `<h1 class="custom_class">Title 1</h1>`

Regards

**Comment by Alex-D** [comment]
Hi!

Nope, there is no option for that. Sorry :/
