### ISSUE TITLE
Plugins are not applied to the editor

### ISSUE THREAD

**Issue by jtrost** [Alex-D/Trumbowyg#299]
### Informations

**Browser + version**: Firefox 46
**OS**: OS X
**Resolution**: 1920x1080

### How to reproduce the bug?
I'm trying to add two plugins to my editor. Unless I'm missing something, this is not covered in the [documentation](http://alex-d.github.io/Trumbowyg/documentation.html). I am including both [trumbowyg.upload.js](https://github.com/Alex-D/Trumbowyg/blob/develop/plugins/upload/trumbowyg.upload.js) and [trumbowyg.colors.js](https://github.com/Alex-D/Trumbowyg/blob/develop/plugins/colors/trumbowyg.colors.js) on my page.

Here is my initialization code.

```javascript
<script type="text/javascript">
  $(document).ready(function(){
    $('#trumbowyg-demo').trumbowyg({
      svgPath:'/assets/trumbowyg/images/icons.svg',
      plugins: {
        colors: {},
        upload: {}
      }
    });
  });
</script>
```
I would expect to see the upload and color buttons on the editor, but they do not appear.

**Comment by Alex-D** [comment]
You need to add plugins buttons to your editor: https://github.com/Alex-D/Trumbowyg/blob/gh-pages/js/main.js#L17

**Comment by jtrost** [comment]
Thanks! You should add this to the documentation.
