### ISSUE TITLE
Changes made on 'View HTML' are lost if container is not a textarea

### ISSUE THREAD

**Issue by linux-man** [Alex-D/Trumbowyg#300]
You can see the added text disappear before the HTML window close.

**Comment by linux-man** [comment]
I can make it work with
`.on('tbwchange', function(e) {$("#container").html($("#container").trumbowyg('html'))})`

**Comment by linux-man** [comment]
This is no solution. At normal editing, the cursor jumps to the beginning.

**Comment by linux-man** [comment]
This do the trick:
`.on('tbwchange', function(e) {if($(".trumbowyg-textarea").attr("tabindex") != -1) $("#container").html($("#container").trumbowyg('html'))})`

**Comment by Alex-D** [comment]
Hi!

I can't reproduce your bug on my index.html page of this repository. For me all examples are OK.

Can you give me browser and version?

Through I don't have the bug, I close this issue. Feel free to reopen it if you have more infos ;)
