### ISSUE TITLE
Question - Possible to insert text via javascript?

### ISSUE THREAD

**Issue by Elindalyne** [Alex-D/Trumbowyg#302]
Is it possible to insert text via javascript at the current cursor position? Basically something like $('#editorName').trumbowyg('insert', 'sometext').

Currently we're looking for something we can add tokens to and the insert UI cannot be in a modal (otherwise I'd just write a plugin)

**Comment by ra100** [comment]
I'm not sure if this is right way, how to do that, but you can add your own $ed.on() event, and then you can call it. I've done something similar in module I've done.

simplified:
```js
(function ($) {
  'use strict';

  $.extend(true, $.trumbowyg, {
    
    plugins: {
      my_plugin: {
        init: function (trumbowyg) {
          trumbowyg.o.plugins.cro = $.extend(true, {}, defaultOptions, trumbowyg.o.plugins.my_plugin || {});

          function hook() {
            if (trumbowyg.$ed == undefined) {
              setTimeout(hook, 100);
              return;
            }
            trumbowyg.$ed.on('showcode', function () {
                // Do some magic with trumbowyg
                console.log(trumbowyg);
            });
          };

          hook();
          
          ...
          
    }
  }
})(jQuery);
```

**Comment by Elindalyne** [comment]
Thanks for the example. This works perfectly with a few modifications for what I'm trying to do (wyswyg mail merge editor)
