### ISSUE TITLE
Cut-and-paste rich text content show reverse order in Edge browser

### ISSUE THREAD

**Issue by jimmyjou** [Alex-D/Trumbowyg#303]
Before report an issue, be sure to put these informations. Thanks :)

### Informations

**Browser + version**: Microsoft Edge 25.10586.0.0
**OS**: Windows 10
**Resolution**: 
Has not found a work around yet

### How to reproduce the bug?
In Edge browser, bring up Trumbowyg page (https://alex-d.github.io/Trumbowyg/), then cut some rich text with indented bullet items from any editor (One Note, Word, or Outlook) and paste it to the editor. The paragraph will be displayed in reverse order. Although it does not happen all the time, it happens more often than not. IE, Chrome, and Firefox work fine.

**Comment by Alex-D** [comment]
Sorry but I don't manage very well paste from editor like Word. There is [an option to disable it if you want](https://alex-d.github.io/Trumbowyg/documentation.html#remove-format-pasted), but I let the browser make the translation between Word and HTML.
