### ISSUE TITLE
Imagepaste plugin, doesn't paste from mac os clipboard

### ISSUE THREAD

**Issue by djagya** [Alex-D/Trumbowyg#310]
### Informations

**Browser + version**: Chrome 51
**OS**: macOS
**Resolution**:

Hi,
Firstable thank you for this great editor! 

I have a problem with inserting an image from the mac clipboard (not sure whether it's only a macOS problem or not).
The reason is that in your plugin only the first pasting entity is checked. Looks like when I copy an image from the mac Finder it fills my clipboard with two entities: 1 - image filename, 2 - image itself.

```js
var items = (pasteEvent.originalEvent || pasteEvent).clipboardData.items,
    reader;

if (items[0].type.match(/^image\//)) { // <-- here only the first entity is checked, what is just a filename in my case
    ...
 }
```

That's what I have in `items` after I pressed Cmd+c on the image in Finder:

```
[
  {kind: 'string', 'type': 'text/plain'},
  {kind: 'file', 'type': 'image/png'}
]
```

So what if we iterate through the items instead of checking only the first one? It shouldn't break anything, right?

**Comment by Alex-D** [comment]
Maybe we need to loop yep.

**Comment by fpanettieri** [comment]
This is the version I'm using. Feel free to copy and modify it!
```js
(function ($) {
  'use strict';

  function handlePaste(ev, trumbowyg){
    try {
      let items = (ev.clipboardData || ev.originalEvent.clipboardData).items;

      for(let index in items) {
        let item = items[index];
        if(item.kind !== 'file') { continue; }

        let blob = item.getAsFile();
        let reader = new FileReader();
        reader.onload = function(event){
          trumbowyg.execCmd('insertImage', event.target.result, undefined, true);
        }
        reader.readAsDataURL(blob);
      }
    } catch (c) {
      console.log('oh-oh', c);
    }
  }

  $.extend(true, $.trumbowyg, {
    plugins: {
      pasteImage: {
        init: function(trumbowyg) {
          trumbowyg.pasteHandlers.push(function(ev){ handlePaste(ev, trumbowyg) });
        }
      }
    }
  });
})(jQuery);
```
