### ISSUE TITLE
Throttle updateButtonPaneStatus

### ISSUE THREAD

**Issue by djagya** [Alex-D/Trumbowyg#311]
### Informations

**Browser + version**: Chrome 51
**OS**: macOS
**Resolution**:

### How to reproduce the bug?

Every time user types something `updateButtonPaneStatus()` is called:

```js
// line 570
.on('mouseup keydown keyup', function () {
     t.updateButtonPaneStatus();
})
```

It's a problem if user types fast, because redactor starts freezing. Can we add a throttle (like 100-200ms) to the event so it will not update button states every keyup/down?

Something like this (simplest implementation):

```js
var throttleTimer;
...
.on('mouseup keydown keyup', function () {
    clearTimeout(throttleTimer);
    throttleTimer = setTimeout(t.updateButtonPaneStatus(), 100);
})
```

**Comment by Alex-D** [comment]
Hi!

I can do that yep, but I don't have any lag problem :/

Have you got a long text or something? It's just to try to reproduce that on my browser.

**Comment by djagya** [comment]
Usually it happens if there are few base64 encoded images, but the problem is not persistent. Anyway the throttle will be useful here I think.
