### ISSUE TITLE
CTRL + X  is not reflecting on text-area(#game_description). 

### ISSUE THREAD

**Issue by rahul8sharma** [Alex-D/Trumbowyg#313]
```js
    $('#game_description').trumbowyg({
        resetCss: true,
        removeformatPasted: true,
        autogrow: true,
        svgPath: trumbowygIcons
    }).on('tbwchange', function(contents, $editable){
        $('#game_description').val(contents.target.value);
    });
```

Whenever i pressed CTRL + X then Textarea not updated.

**Comment by rahul8sharma** [comment]
Still not fixed because it cut value from the editor after "tbwchange" event performed.  So "contents.target.value" return the same value as previous.

**Comment by Alex-D** [comment]
Need to add a setTimeout 0 hack :/

**Comment by rahul8sharma** [comment]
We can use
.bind('input propertychange', function() {
    t.semanticCode(false, true);
    t.$c.trigger('tbwchange');
})

instead of 

.on('cut', function () {
    t.semanticCode(false, true);
    t.$c.trigger('tbwchange');
})

**Comment by manaswigirlscollege** [comment]
Thank you.. :) Now it is working.

**Comment by supercharlez** [comment]
Hello, I don't understand how to fix this issue I have too with Ctrl-X not updating the content. Can someone help ? thanks

**Comment by Alex-D** [comment]
It should works in the latest version. Are you up to date?

**Comment by supercharlez** [comment]
Yes silly me I was using the last version on a cdn and not the one on Github. Thank you so much
