### ISSUE TITLE
Do not react to the Japanese(multibyte character)

### ISSUE THREAD

**Issue by rosiro** [Alex-D/Trumbowyg#315]
Before report an issue, be sure to put these informations. Thanks :)
### Informations

**Chrom**:
**OS**:　windows
**Resolution**:
### How to reproduce the bug?

Since the value even if after input in Japanese (double-byte characters) post (submit) is not turned on, such as the textarea, value even if the post (submit) does not reach the server side.

Incorrect value When you enter, such as input after a space enters the value of the textarea, it seems to correctly post can be.

**Comment by Alex-D** [comment]
Hi!

Can you give me a sample page or something like that? It the textaera content is OK. Try without Trumbowyg, if it does not works, it's not Trumbowyg.

I can't type japanese chars :/

**Comment by Alex-D** [comment]
Without more information, I can't fix it.

If you have more infos, feel free to reopen this issue.

**Comment by plageoj** [comment]
Hi there,
I have same problem.
The attachment is a demo reproducing the bug, on [alex-d.github.io/Trumbowyg](http://alex-d.github.io/Trumbowyg/).

In the gif, Japanese letters I typed didn't appear in console. I need switch to HTML editing mode, or input some alphabets to be recognized. This happened only on typed characters, not on pasted.
![trumbowyg](https://cloud.githubusercontent.com/assets/10688301/19238133/0eb9bf7a-8f3b-11e6-9ce5-44fb9ca8d3a2.gif)

**Comment by Alex-D** [comment]
Can you give me keycode that are trigged when you do that?
There is a keycode that tell "OK, that word is ended, you can sync with textarea"?

**Comment by plageoj** [comment]
On IE and Webkit, the key code 229 at keydown event tells "user is typing a Japanese character".
On Firefox, the key code 13 at keyup event indicates end-of-word.

**Comment by vanquang9387** [comment]
I got same problem.
