### ISSUE TITLE
textarea and big contents are problematic

### ISSUE THREAD

**Issue by koffeinfrei** [Alex-D/Trumbowyg#320]
When handling big contents, using a textarea is not the right choice. Textareas with big contents are really slow and will hang the browser with 100% cpu usage.

For a project of mine I'm using your editor, and the contents tend to get big quickly. I quickly hacked together a version (which breaks some stuff currently) that doesn't use a textarea for storing the contents. Before converting this hack into a proper version I wanted to hear your thoughts on this.

IMO, when instantiating the editor on a non-textarea element it should be fine to not create a dynamic textarea element, but just always use the original element which was used to instantiate the editor. Alternatively, a non-textarea-mode could also be a possibility, so it's less magic.

**Comment by Alex-D** [comment]
Hi!

What do you use insteed of textarea? It is cool to have it dynamicly create to edit HTML code, but, you're right, it could be not created when `viewHTML` is not in the buttons list.

So, it depends of the impact of this hack on the weight of the lib. If it's a small and light patch, I'm OK. If not, it depends :/

**Comment by koffeinfrei** [comment]
> What do you use insteed of textarea?

I'm just using the element I initialized the editor on (`t.$ed`).

> it could be not created when viewHTML is not in the buttons list.

Viewing the html should still be possible, just not by showing the textarea's value but the inner html of the `t.$ed`.
Using a textarea to store the editor contents is not required. A textarea is only necessary when posting the form. But in my case I have a custom change handler on the editor and post the changes by ajax, so I don't need a valid form element.

> If it's a small and light patch, I'm OK

I absolulety want to keep this patch light, it's one of the main assets of your editor.

Is there a way to maybe unite `t.$ed` and `t.$ta`? Is this separation absolutely necessary?

**Comment by Alex-D** [comment]
>  Is this separation absolutely necessary?

If you have a better idea, I'm OK :) I've just use a textarea for classical forms and to edit HTML. If you think you can do the same thing without that separation, I'm OK.

If you have a demo page where your performance appears, link it :)

**Comment by Alex-D** [comment]
That will need a total rewrite of Trumbowyg. Maybe in a v3, but I don't have the time right now, sorry :/

**Comment by ryanwalters** [comment]
+1 for fixing this issue.
