### ISSUE TITLE
Редактор остаётся заблокированным

### ISSUE THREAD

**Issue by mishantrop** [Alex-D/Trumbowyg#321]
Thanks for editor.

I have textarea with attribute «disabled». 
`<textarea data-richeditor="1" disabled>Foo bar</textarea>`
Then I initialize plugin. 
`$('[data-richeditor="1"]').trumbowyg();`
Then I remove attribute «disabled» by jQuery, but editor still be disabled.
`$('[data-richeditor="1"]').removeAttr('disabled');`

![disabled](https://cloud.githubusercontent.com/assets/5341208/16602577/fad44e62-431d-11e6-9396-051d1ccbbe79.png)

**Comment by Globulopolis** [comment]
@mishantrop уважайте других пользователей гитхаба! Здесь не только англоязычная аудитория и ваш скриншот выглядит глупо!
По вашему вопросу достаточно прочитать документацию http://alex-d.github.io/Trumbowyg/documentation.html#enable-disable-edition

@mishantrop respect other users from Github! Here, not only English-speaking audience and your screenshot, with curse words, looks stupid!
In your question to read the documentation is sufficient http://alex-d.github.io/Trumbowyg/documentation.html#enable-disable-edition

**Comment by Alex-D** [comment]
Thanks @Globulopolis for the response :)
And yeah, jQuery is not double binding tool, so you need to call the enable/disable in the Trumbowyg API ;)
