### ISSUE TITLE
How to handle image upload

### ISSUE THREAD

**Issue by AttitudeMonger** [Alex-D/Trumbowyg#324]
The Trumbowyg example page shows the editor where user can upload an image, and then the image is rendered in the editor. On inspecting the HTML, the image seems to be hosted in imgur. For me, it will be in my host. How to handle the image upload event so that it can be uploaded to my server, and the image rendered in the editor with the path to the image path in my server?

**Comment by Globulopolis** [comment]
@AttitudeMonger see these options https://github.com/Alex-D/Trumbowyg/blob/develop/plugins/upload/trumbowyg.upload.js#L14

These options is not covered in documentations:
`serverPath` - an URL where to upload. See http://api.jquery.com/jQuery.ajax/
`fileFieldName` - the name of the input file field which will send to server.
`data` - additional POST data. Array. See http://api.jquery.com/jQuery.ajax/
`headers` - additional HTTP headers. Object {'my_header: 'value'}. See http://api.jquery.com/jQuery.ajax/
`xhrFields` - additional xhr data. See http://api.jquery.com/jQuery.ajax/
`urlPropertyName` - ?
`statusPropertyName` - ?
`success` - callback function on success. See http://api.jquery.com/jQuery.ajax/
`error` - same as `success` but for `error`. See http://api.jquery.com/jQuery.ajax/

**Comment by AttitudeMonger** [comment]
Thanks mate. I will try it  out. :)

**Comment by AttitudeMonger** [comment]
I am not able to understand the exact format of the Ajax request to be sent. Going by the source code of [this page](view-source:http://alex-d.github.io/Trumbowyg/js/main.js), the code appears to be:

```
upload: {
                        serverPath: 'https://api.imgur.com/3/image',
                        fileFieldName: 'image',
                        headers: {
                            'Authorization': 'Client-ID 9e57cb1c4791cea'
                        },
                        urlPropertyName: 'data.link'
                    }
```

And on inspecting the Ajax request response, I can see that the "link" key holds the value of the image URL, which maps to the data.link value for the urlPropertyName key above. But what about the uploading part? What do I specify in the fileFieldName and headers keys? This is what I am trying to have a basic image upload:

```
// Add events
$('input[type=file]').on('change', prepareUpload);

// Grab the files and set them to our variable
function prepareUpload(event)
{
  files = event.target.files;
}

var data = new FormData();
$.each(files, function(key, value)
{
    data.append(key, value);
});

$.ajax({
    url: 'submit.php?files',
    type: 'POST',
    data: data,
    cache: false,
    dataType: 'json',
    processData: false, // Don't process the files
    contentType: false
});
```

Where in this code do I use `fileFieldName` ?

**Comment by Globulopolis** [comment]
`fileFieldName` value will be append to data variable.

> what value do I put for Authorization

I'm think you should search this in google.

**Comment by AttitudeMonger** [comment]
I am getting a 403 forbidden error with my localhosted Django script. I searched for solution, most of the solutions say that I have to add a custom **csrfmiddlewaretoken** value in my Ajax request. How do I set the value here, and what value?

**Comment by Globulopolis** [comment]
@AttitudeMonger you can add it into URL or add into `data` like:
`data: data + '&variable=value&variable1=value1'` or even add it into beforeSend. See http://api.jquery.com/jQuery.ajax/

**Comment by AttitudeMonger** [comment]
I am returning a JSON response with only one key value:

`{"link": "https://www.gravatar.com/avatar/5b984e34330d801c7ba96f53c2a312e9?s=32&d=identicon&r=PG"}`

Nothing is happening, the modal dialogue still stays, whereas it should vanish and the image referred to in the link key in the above response should display. The image upload is happening correctly though, my backend script is getting the image and storing it elsewhere successfully.

**Comment by vinodrightpath** [comment]
Hoe to get image upload description in php
