### ISSUE TITLE
Create custom font-size and font-family button

### ISSUE THREAD

**Issue by beyer-johannes** [Alex-D/Trumbowyg#326]
Hi,

how I can create a font-family or font-size button?

I only ask because I can´t set style attributes, classes or data-attributes to the dropdown array.

> btnsDef: {
>                     // Customizables dropdowns
>                     formattingTest: {
>                         dropdown: [
>                              'h1[data-style=10]', // Not allowed
>                              'h1.editor-font-size-10', // Not allowed
>                              '.editor-font-size-10' // Not allowed
>                         ],
>                         ico: 'formatting'
>                     }
> }

Can you tell me, how I can write this?

Thanks!

**Comment by Alex-D** [comment]
Trumbowyg is a semantic WYSIWYG. So you should not change font family and font size. That's the CSS/Design role.

So if you want that features, you should use a non-semantic WYSIWYG.

Idk where you have see that:

> 'h1[data-style=10]', // Not allowed
> 'h1.editor-font-size-10', // Not allowed
> '.editor-font-size-10' // Not allowed

But that's not supported and it never will.

More informations: http://alex-d.github.io/Trumbowyg/documentation.html#button-pane
