### ISSUE TITLE
Trumbowyg: data not posted if only an <iframe> tag

### ISSUE THREAD

**Issue by AlexandrBasan** [Alex-D/Trumbowyg#327]
### Informations

If I'm trying to add just iframe tag without any text and Trumbowyg clear it and do not send it to the background so variable is nil.  So I can not use just iframe tag (Video from Youtube like example) as a text.
Tested on Firefox and Chrome. Last version of the editor. Editor integrated to GitHub page has the same problem.
Same code with some letter after iframe tag works perfectly
    
    
    <iframe src="https://embed-ssl.ted.com/talks/amy_cuddy_your_body_language_shapes_who_you_are.html" width="560" height="315" frameborder="0" scrolling="no" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
    
Same code with some letter after iframe tag works perfectly    
    
    <iframe src="https://embed-ssl.ted.com/talks/amy_cuddy_your_body_language_shapes_who_you_are.html" width="560" height="315" frameborder="0" scrolling="no" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe><p>sometext<p>
    
    
### How to reproduce the bug?
This Gif shows editor behaviour
http://g.recordit.co/dNwi1uJgNa.gif

**Comment by Alex-D** [comment]
https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L972

I have forget the `iframe` tag here. It's on my TODO.
