### ISSUE TITLE
link on image doesn't work

### ISSUE THREAD

**Issue by GabrielePorro** [Alex-D/Trumbowyg#328]
If you upload an image and then try to put a link on it, the image disappears. I tried also on the homepage of the plugin and it also happen there. I think having the links on images is very important. 
Hope someone solve this issue.

**Comment by GabrielePorro** [comment]
Any news for this issue?

**Comment by Alex-D** [comment]
Nope... it's seems to be not trivial :/

**Comment by youradds** [comment]
Shame - this bug has just made trumbowyg unusable for me :( Otherwise, a very cool script.. but I can't expect my users to edit the HTML to put links around stuff :(

**Comment by zolotykh** [comment]
Guys, I've found solution, but it's not elegant.

Use this plugin:

`(function($) {
    'use strict';

    $('body').prepend(`<div style="display: none">
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
        <symbol id="trumbowyg-img-link" width="16" height="16" viewBox="0 0 16 16">
            <path fill="#444444" d="M14 16v-11l-1 1v9h-12v-12h9l1-1h-11v14z"></path>
            <path fill="#444444" d="M16 0h-5l1.8 1.8-6.8 6.8 1.4 1.4 6.8-6.8 1.8 1.8z"></path>
        </symbol>
    </svg>
</div>`);

    $.extend(true, $.trumbowyg, {
        langs: {
            ru: {
                imgLink: 'Img Link',
            },
            en: {
                imgLink: 'Img Link',
            },
        },

        plugins: {
            imgLink: {
                init(trumbowyg) {
                    trumbowyg.addBtnDef('imgLink', {
                        fn(cmd) {
                            const alt = prompt('Enter image\'s "description" field');

                            const $img = trumbowyg.$ed.find('img').filter(`[alt="${alt}"]`);

                            if ($img.length) {
                                const src = $img.attr('src');
                                const href = prompt(`Enter a href for image with description "${alt}"`);
                                const $parent = $img.parent();

                                if ('A' === $parent[0].tagName) {
                                    $parent.attr('href', href);
                                }

                                else {
                                    $img.wrap(`<a href="${href}"></a>`);
                                }

                                alert('Success!');
                            }

                            else {
                                alert('Image not found.');
                            }
                        }
                    });
                },
            }
        }
    });
})(jQuery);`

**Comment by zolotykh** [comment]
**UPD**, it's not complete solution… There is a problem. After plugin reinitialization it cats out the link.

**Comment by zolotykh** [comment]
Also can be useful run `trumbowyg.$ta.trigger('tbwchange')` after `trumbowyg.syncCode();`

**Comment by Alex-D** [comment]
I keep that in mind for v3 (See #875 for more details)

I close this for now since I want to keep issues clean and this one is old.
