### ISSUE TITLE
IE11 Paragraph and shift+Enter bug

### ISSUE THREAD

**Issue by tonvanalebeek** [Alex-D/Trumbowyg#329]
Hi,

I'm using Trumbowyg in a couple of my projects. Really like it so far. Today I discovered a weird bug in Internet Explorer 11. I thought it was a bug in my project, so I tested it on the demo-page of Trumbowyg, and got the same result.

### How to reproduce the bug?

1. Type something in the editor on: http://alex-d.github.io/Trumbowyg/ using IE11 on Windows platform.
2. Press 'Enter'
3. The cursor jumps to the next paragraph, and immediately jumps back up. When you start to type the text does start on the new paragraph. (but this is weird behaviour).
4. When you use Shift + Enter to make a line-break the editor makes a new paragraph (this is a bug).
5. When you type a couple of Enters after each other, the cursor keeps jumping back up.

### Informations

**Browser**: IE11
**OS**: Windows 8

**Comment by Alex-D** [comment]
I know. But it's IE... some stranges/weird behaviours are from IE itself :/

> When you type a couple of Enters

I don't want cover this use case, that I judge non-semantic.

**Comment by tonvanalebeek** [comment]
So this won't be fixed? It's quite a breaking bug right now for the project I'm using it in. Please let me know if this will be on the buglist, otherwise I need to look for an alternative plugin. Thanks!

**Comment by Alex-D** [comment]
Idk how to fix it. So you can check another WYSIWYG... :/

**Comment by tonvanalebeek** [comment]
Too bad, thanks for your effort though :+1: 
Will try to find an alternative. Issue can be closed.

**Comment by dwittner** [comment]
Even though, this issue is already closed, i want to make some notes about it.
The cause of the problem is the following code fragment:
```javascript
// Remove empty <p>
t.$ed.find('p:empty').remove();
```
In Chrome, the css selector ```p:empty``` doesn't select a ```<p>``` tag with a ```<br>``` tag inside, but in IE it does. To prevent __trumbowyg__ from deleting ```<p>``` tags with a ```<br>``` tag inside also for IE, the code could rewritten like this:
```javascript
// Remove empty <p>
t.$ed.find('p:empty').each(function () {
  var p = $(this);
  if (p.html() !== '<br>') {
    p.remove();
  }
});

```

**Comment by paulJanssenFuturelab** [comment]
I noticed the following. If you don't use the semantic version, this bug doesn't appear.
`semantic: false,`
Hope this helps you
