### ISSUE TITLE
Multiple Instances with different plugin options

### ISSUE THREAD

**Issue by vasileioslaios** [Alex-D/Trumbowyg#330]
Hi,

i have the following problem and i cannot find a way to solveit. Maybe you can propose a solution. I have created a plugin that sends the content of the editor in my server. That was easy. But i would like to have multiple instances of the editor in the same page, with each one containing also an identifier which would be send with the from plugin together with the html to the server. If i extend the trumbowyg options with $.extend(true,$.trumbowyg.options {}); as you have already mentioned in previous posts and try to pass the id like this, only the last id will be saved in the plugin options . What i would really like is, to pass plugin options  directly to the instance. For example i have two instances of trumbowyg in my page one will send the html to the server with id:1 and the other with id:2. Is it possible?

**Comment by vasileioslaios** [comment]
Well i though that $.trumbowyg.options is the prototype and if you have multiple instances in the same page then the last instance will overwrite the plugin options. But this is not the case. Although i don't understand why it seems to work fine if the options are extended before the instantiation of Trumbowyg. Probably we change the prototype options and when the instance is created it uses the correct values. This seems to do the trick

**Comment by Alex-D** [comment]
You can set plugin options for one instance only: https://github.com/Alex-D/Trumbowyg/blob/develop/index.html#L202

**Comment by Globulopolis** [comment]
@vasileioslaios how about each() loop and data-* attributes?

```html
<textarea class="editor"
	data-buttons="'formatting', 'btnGrp-design', 'btnGrp-justify', 'btnGrp-lists', 'foreColor', 'backColor', 'viewHTML'" ...>...</textarea>
<textarea class="editor"
	data-buttons="'formatting'" ...>...</textarea>
```
```javascript
$('.editor').each(function(index, element){
	var $this = $(element);
	$this.trumbowyg({
		btns: [ $this.data('buttons') ]
	});
});
```

**Comment by vasileioslaios** [comment]
Well, it has to do with the plugin and the extra options you have to pass through $.extend mostly. Your proposal will only work for multiple instances without extra plugins

**Comment by vasileioslaios** [comment]
Thank you Alex-D this will also do the trick!
