### ISSUE TITLE
Trumbowyg notification on image upload popup and complete

### ISSUE THREAD

**Issue by AttitudeMonger** [Alex-D/Trumbowyg#333]
The editor shows an image upload dialog when user wants to upload an image. However, it is not modal. The problem is that, because it is not modal, and because the code has no access to the callback function resulting from the image upload, it gives the user the option to save/submit the form when the upload is still happening by clicking the "Save" button client provides to accept the user's text inputted in the editor.

Is it possible to receive some kind of event/notification when the image upload starts and completes, so that I can tap into that to disable to form submission and reenable it respectively when the events fire?

Alternately if the alert can be made modal (I guess Javascript does not allow that), that won't be needed.

I tried the "ugly" way, by adding click handlers to the trumbowyg-insertImage-dropdown-button class and disabling my form submit buttons explicitly. However, the handler never fires, I don't know why. Here's what i tried:

```
    $(".trumbowyg-insertImage-dropdown-button").on("click", function() {
//        $(".submit-button").disable();
        alert("Cool");
    });
```

The alert never appears, only the image form dropdown slides down as usual.

**Comment by AttitudeMonger** [comment]
Never mind. Got this cleared as well. Just set up global `ajaxPrefilter` and `ajaxComplete` handlers, and based on the url the handlers return, if the url matches the url to which **Trymbowyg** is uploading the image to (as set in the init settings), then I am enabling or disabling the buttons.

**Comment by yokesharun** [comment]
@AttitudeMonger Can you explain briefly?
