### ISSUE TITLE
Replace text-align: center with center-tag

### ISSUE THREAD

**Issue by beyer-johannes** [Alex-D/Trumbowyg#334]
Hi,

how I can call the justifyCenter to use the center-tag instead of style="text-align: center"?

Because the style attributes will be removed on saving the content.

Thanks!

**Comment by Alex-D** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center

https://www.w3.org/TR/html5/obsolete.html#center

`<center>` is deprecated, it is part of past. This WYSIWYG is turn to the future.
