### ISSUE TITLE
CMD+B, CMD+I, CMD+U don't enable, disable bold, italic, underline while typing

### ISSUE THREAD

**Issue by dep** [Alex-D/Trumbowyg#335]
Before report an issue, be sure to put these informations. Thanks :)

### Informations

**Browser + version**: Chrome latest
**OS**: OSX
**Resolution**: Standard MBPro

### How to reproduce the bug?
Start typing in the wysiwyg, type CMD+B to enter 'bold' mode and continue typing.  Bold does not occur.

***

Pretty much every wysiwyg ever allows you to simply enable/disable bold/italic/underline while the user is typing.  Ex:  This is [cmd+b]very[cmd+b] important. Please advise.

**Comment by Alex-D** [comment]
You need to select text, then hit CMD+B to bold it. Idk why enter bold mode does not work :/

**Comment by Alex-D** [comment]
Did you try with `semantic: false` option?
http://alex-d.github.io/Trumbowyg/documentation.html#semantic

**Comment by dep** [comment]
I did. Just looking at the example at https://alex-d.github.io/Trumbowyg/ as well, I noticed if I use CMD+b/i/u while typing, it doesn't enable those modes there either.  Selecting and then using those shortcuts works, but enabling/disabling while typing does not. Thanks for your help!

**Comment by Alex-D** [comment]
So I can't do anything, it's a contenteditable bug, sorry :/
