### ISSUE TITLE
Fullscreen button does not work inside bootstrap modal

### ISSUE THREAD

**Issue by Aleksandr-ru** [Alex-D/Trumbowyg#336]
Occasionally I found out that fullscreen button does not works correctly when trumbowyg is set inside a bootstrap modal box. In my case the autogrow option is set to false, but I think it does not matters.

### Informations

**Browser + version**: Mozilla Firefox 47
**OS**: Linux (Elementary OS Freya)
**Resolution**: 2560x1080

### How to reproduce the bug?
Put trumbowyg inside a bootstrap modal. Open modal, press fullscreen button and see the buggy output.

**Comment by Alex-D** [comment]
You should use events to customize the editor depends of the environement: http://alex-d.github.io/Trumbowyg/documentation.html#events

See `tbwopenfullscreen` and `tbwclosefullscreen` events

**Comment by jmonday** [comment]
Maybe I'm missing something, but can't this be solved with simple CSS?

```
body.trumbowyg-body-fullscreen .modal-dialog {
    height: 100%;
    margin: 0 -15px 0 0;
    width: inherit;
}
```

_Note: I'm currently using Bootstrap v3, not sure if the styles would need to be modified for Bootstrap v4._
