### ISSUE TITLE
File Upload & File Manager

### ISSUE THREAD

**Issue by KiarashS** [Alex-D/Trumbowyg#338]

**Comment by Alex-D** [comment]
You do not even bother to make a sentence... That's not cool!

And if you RTFM you will see there is a plugin for file upload : http://alex-d.github.io/Trumbowyg/#plugins or here : https://github.com/Alex-D/Trumbowyg/tree/master/dist/plugins/upload

So next time, please read the doc. I see your activity arround others GitHub repositories and you are not cool with all of them. Each time, all responses are on the homepage of the project.

**Comment by dsmithco** [comment]
I would recommend that you put the plugin list in the documentation. I would expect the documentation to be all inclusive (getting started, install, etc).  In KiarashS's defense the list of plugins are easily missed.

Looking forward to using Trumbowyg

**Comment by Alex-D** [comment]
Feel free to make a PR. It's open source. If you have some ideas, they are welcome.
