### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by KiarashS** [Alex-D/Trumbowyg#339]

**Comment by Alex-D** [comment]
Already available. You need to define this in language file like here: https://github.com/Alex-D/Trumbowyg/blob/develop/src/langs/ar.js

**Comment by MosheTzvi** [comment]
Is there a way the user can enter one paragraph RTL and another one LTR?  This is fairly common in applications where the user needs to produce bilingual text.  It seems from the localization options, the LTR or RTL only applies to the text as a whole.  Most editors support this by having a button that changes text direction for the text to by typed.
