### ISSUE TITLE
Link insertion doesn't work

### ISSUE THREAD

**Issue by weecka** [Alex-D/Trumbowyg#34]
If you try to insert the link using editor when there is no text selected (when area is empty or there is a new line), then nothing is happening and no link is inserted.

This only happens with FireFox browser on Windows or Iceweasel on Linux, so this might be a browser specific issue.

Tested on FireFox v30.0 and Iceweasel v24.6.0.

Can anybody confirm that this problem exists? And is there a way to fix this problem?

Regards,
-Vytautas

**Comment by notno** [comment]
I can confirm that this happens in ie9 and ie8 (not surprisingly).

Additionally, on ie8, when you open the insertLink modal, it shows up:
![screen shot 2015-01-07 at 5 50 28 pm](https://cloud.githubusercontent.com/assets/3149184/5656731/09189b9e-9696-11e4-8ca1-d2f3c8b7b123.png)

Naturally, the [object TextRange] gets used as the text/alt if you don't change them.

**Comment by notno** [comment]
I think the solution may be similar to the solution for #58

**Comment by Alex-D** [comment]
Fix thanks to @lizardK :)
