### ISSUE TITLE
Access to the keydown event in the editor change event

### ISSUE THREAD

**Issue by SvetlinStaev** [Alex-D/Trumbowyg#345]
Hi,

I have a textarea field which is restricted to inputing the text only in cyrillic characters. To enforce is, I have created a map of all the English keys and when a key is pressed based on the `e.charCode` I render the cyrillic character. In a plain input or textarea it works perfectly fine but when I use the trumbowyg editor I do not seem to have access to the charcode of the keydown even when the change event is triggered by the editor. Is there a way to get it and change the character typed in real-time?

**Comment by Alex-D** [comment]
https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L542

I don't emit event on keydown and I don't give event to tbwchange in keyup :/

Maybe you could add some things here in a Pull Request :)
