### ISSUE TITLE
Documentation demo broken

### ISSUE THREAD

**Issue by ryanwalters** [Alex-D/Trumbowyg#346]
### Information

**Browser + version**: Chrome, Firefox, Edge
**OS**: Windows 10
**Resolution**: 1920x1280

### How to reproduce the bug?

Go to http://alex-d.github.io/Trumbowyg/

The demo is not displaying. Rawgit CDN is reporting `403 Forbidden`.

**Comment by Alex-D** [comment]
It works again.
