### ISSUE TITLE
Placeholder Text Issues

### ISSUE THREAD

**Issue by duiker2** [Alex-D/Trumbowyg#347]
In Firefox, there is a bug with placeholder text. When you click to focus the textarea, then click again the cursor will jump to the far right and you can't enter text. 

In Internet Explorer, when focusing the textarea it will put the cursor at the end of the placeholder text rather that the beginning. This is less annoying that the Firefox issue because you can still input the text.

I attached a modification of your examples/index.html file to recreate the issues.
[placeholder.zip](https://github.com/Alex-D/Trumbowyg/files/388563/placeholder.zip)

Firefox 47.0.1
Internet Explorer 11
Windows 8.1

**Comment by Alex-D** [comment]
I've tested it. It's not linked to the placeholder but I can reproduce the bug, so I try to fix it. :(

**Comment by NicolasPion** [comment]
Fix : https://github.com/Alex-D/Trumbowyg/pull/357

**Comment by NicolasPion** [comment]
This is a Firefox bug
https://bugzilla.mozilla.org/show_bug.cgi?id=904846

JSFiddle :
1 : http://jsfiddle.net/xdht9o0s/
2 : http://jsfiddle.net/m5zDU/

You can edit the trumbowyg CSS to fix this, but the placeholder disappear on focus... its a choice :)

`.trumbowyg-editor[contenteditable=true]:empty::before`

to :

`.trumbowyg-editor[contenteditable=true]:empty:not(:focus):before`

Exemple : http://jsfiddle.net/mfjntwu6/
