### ISSUE TITLE
Add custom button to trumbowyg editor

### ISSUE THREAD

**Issue by ohid** [Alex-D/Trumbowyg#348]
**Has there any option to add custom button to the editor?** 

Like I want to add a button, when user click on it and write something those text will be wrapped by &lt;pre>&lt;code> texts here &lt;/pre>&lt;/code> tags. 

Thanks

**Comment by Alex-D** [comment]
There is already the [preformatted](https://github.com/Alex-D/Trumbowyg/tree/develop/plugins/preformatted) plugin for that :)

**Comment by staleo** [comment]
Hi Alex,
If you dont mind, I'll post here, my issue is pretty relevant to the topic. The topic starter mentioned a **pre** tag, but how about any other custom tag?
In my case, I need a button which could wrap a selected text by _<span uk-tooltip title="blabla">_ and _</span>_, and moreover, I need to input that _blabla_ thing on the fly, just like i can do with your beautiful popup for _a_ tag.
Is it possible?
Anyway, Alex, just wanted you to know, your editor demonstrates amazing performance, thank you for it.
Best, Stas.

**Comment by Alex-D** [comment]
Hi!

You should create a custom plugin, some doc coming soon: https://github.com/Alex-D/Trumbowyg/pull/613

**Comment by staleo** [comment]
Cheers pal, will try to make it now.

**Comment by Alex-D** [comment]
https://alex-d.github.io/Trumbowyg/documentation/#custom-buttons
