### ISSUE TITLE
jQuery 3.0 support

### ISSUE THREAD

**Issue by jsvini** [Alex-D/Trumbowyg#350]
### Informations

**Browser + version**: Any
**OS**: Any

### How to reproduce the bug?

With jQuery >= 3.0 if you try to use any button from the editor you get the error:

`Uncaught TypeError: $from.nextUntil(...).andSelf is not a function`

Thats because the jQuery function `.andSelf()` was deprecated in 1.8 and removed in 3.0.

Source: https://api.jquery.com/andself/

**Comment by Alex-D** [comment]
Hey!

Already fixed in master, I just need to release a new version :)

**Comment by Alex-D** [comment]
Check the new 2.1.1, it should works now :)

**Comment by jsvini** [comment]
Thank you very much! 👍
