### ISSUE TITLE
Multiple editors one toolbar.

### ISSUE THREAD

**Issue by dees040** [Alex-D/Trumbowyg#351]
I've read the documentation and tried to find my question on 'the internet'. But couldn't really find the answer for Trumbowyg.

Basically I want to have multiple textareas but only one toolbar. [This](http://stackoverflow.com/questions/2959272/multiple-tinymce-editors-but-only-one-toolbar) question on Stackoverlflow describes my question. But that's for an older version of TinyMCE.

Is it possible to have multiple editors and only have one toolbar. Or do I need to hack to much code to make this possible?

**Comment by Alex-D** [comment]
That's not supported at this time. I did not see a use case of that :/

You can use events to do what you want I think: http://alex-d.github.io/Trumbowyg/documentation.html#events
