### ISSUE TITLE
Your CDN is returning 403 - cannot view demo 

### ISSUE THREAD

**Issue by lukepolo** [Alex-D/Trumbowyg#352]
### Informations

**Browser + version**:
ALL
**OS**:
ALL
**Resolution**:
ALL

### How to reproduce the bug?
Go to your demo site

**Comment by Alex-D** [comment]
Can't do anything. I've tryed some things, but it depends on rawgit :/

**Comment by lukepolo** [comment]
Damn , well hope that gets fixed soon
