### ISSUE TITLE
Strikethrough cannot be undone

### ISSUE THREAD

**Issue by sbunciak** [Alex-D/Trumbowyg#353]
Before report an issue, be sure to put these informations. Thanks :)

### Informations

**Browser + version**: Safari 9.1.2, Chrome
**OS**: Mac OS X El Capitan
**Resolution**:

### How to reproduce the bug?
Select text in editor (even demo on your page), make it strikethrough. There is no way of un-doing it. Clicking again on the 'strikethrough' nor 'remove formatting' button work.

**Comment by L3CC** [comment]
As a temporary solution, it will work if you set 'semantic: false'.
