### ISSUE TITLE
Fullscreen Button causes error in Firefox when trumbowyg is diabled

### ISSUE THREAD

**Issue by Yogi66** [Alex-D/Trumbowyg#359]
Hi there,
I run into an issue that the Firefox (38.0.1) throws an error if I click on the "fullscreen" button in the editor when I set the editor to disabled ( $('#wysiwyg').trumbowyg('disable'); )

The error message is:
NS_ERROR_FAILURE: 	
t.doc.execCommand('styleWithCSS', false, forceCss || false);
trumbowyg.js (line 1196)

This error only occurs if the editor is disabled and only in Firefox. IE works fine and also in the "enabled" state Firefox is fine. (I use version 2.1.2 of trumbowyg)

Am I unique with this issue or might this be a bug ?

Juergen

**Comment by Alex-D** [comment]
Which version of Trumbowyg ? latest ?

**Comment by Yogi66** [comment]
According to package.json it is version 2.1.2...


Am 11.08.2016 um 17:08 schrieb Alexandre Demode:

**Comment by Alex-D** [comment]
Sorry, I just see you have say it in your OP ^^'
