### ISSUE TITLE
Esc-key doesn't work in document after initialization

### ISSUE THREAD

**Issue by Duncank** [Alex-D/Trumbowyg#360]
After including Trumbowyg in our dashboard, all window.onkeydown actions that use the escape key (27) won't work.

I'm not sure what the best way to fix this is, but for now I've deleted the `return false` that follows `t.closeModal()` on line 629.
Maybe it should check if a modal is open and return true if it is not.

Browser: Chrome 54
OS; Windows 10
Resolution: 1920x1080

**Comment by Alex-D** [comment]
> Maybe it should check if a modal is open and return true if it is not.

I think yes. Sorry for this mistake. I will check that asap.
