### ISSUE TITLE
Undo/Redo buttons not in IE and Firefox

### ISSUE THREAD

**Issue by duiker2** [Alex-D/Trumbowyg#361]
The undo and redo buttons do not appear in Internet Explorer and FireFox, even on the demo site. http://alex-d.github.io/Trumbowyg/

Also great work on this tool :)

### Informations

**Browser + version**: FireFox 47.0.1 and Internet Explorer 11
**OS**: Windows 8
**Resolution**: 1920x1080

### How to reproduce the bug?
http://alex-d.github.io/Trumbowyg/

**Comment by duiker2** [comment]
Just looked into the code a bit, and it looks like this is just supported in Chrome? Is there a reason?

**Comment by Alex-D** [comment]
It's juste because it's not possible to undo/redo via execCommand (content editable API) on IE and Firefox :/

**Comment by duiker2** [comment]
Ah, makes sense. Thanks. One more thing though, idk if you officially support MS Edge (25.10586.0.0 Microsoft Edge) yet for Windows 10. The undo/redo buttons appear there, but do not work. As a workaround, I added:
`&& !navigator.userAgent.includes("Edge/")`

**Comment by Alex-D** [comment]
Thanks, I will check that :)
