### ISSUE TITLE
Toolbar buttons not active when style is applied to text

### ISSUE THREAD

**Issue by ryanwalters** [Alex-D/Trumbowyg#364]
### Information

**Browser + version**: Chrome 52
**OS**: Windows 10
**Resolution**: 1920x1280

### How to reproduce the bug?

&nbsp;1. Initialize the plugin, specifying a custom set of buttons

```js
$editable.trumbowyg({
  btns: [['bold', 'italic', 'superscript', 'subscript']]
});
```

&nbsp;2. Bold some text within the editor
&nbsp;3. Highlight the text that was just bolded

**Expected result**
The `bold` button in the editor's toolbar should be active

**Actual result**
The `bold` button in the editor's toolbar is not active

See example:
http://codepen.io/ryanwalters/pen/bZkxqX

**Comment by Alex-D** [comment]
Use `strong` insteed of bold. It should works. It's a workaround but I don't have the time to fix Trumbowyg yet.

**Comment by ryanwalters** [comment]
Thanks, that works. Also, using `em` instead of `italic` fixes the same issue with italic text.
