### ISSUE TITLE
Demo not working when https (Mixed Content)

### ISSUE THREAD

**Issue by zoxon** [Alex-D/Trumbowyg#366]
Mixed Content: The page at 'https://alex-d.github.io/Trumbowyg/' was loaded over HTTPS, but requested an insecure stylesheet 'http://cdn.rawgit.com/Alex-D/Trumbowyg/v2.2.0/dist/ui/trumbowyg.min.css'. This request has been blocked; the content must be served over HTTPS.

### Informations

**Browser + version**: Chrome 52.0.2743.116 m
**OS**: Windows 7 x64
**Resolution**: 1920x1080

### How to reproduce the bug?
View demo with https https://alex-d.github.io/Trumbowyg/

**Comment by Alex-D** [comment]
Arf, fail :/

**Comment by Alex-D** [comment]
Fixed. Thanks :)
