### ISSUE TITLE
problem with line breaks

### ISSUE THREAD

**Issue by FFxSquall** [Alex-D/Trumbowyg#367]
There is a case: 
1. Begin putting in the empty area (text is not wrapped in a paragraph is not press enter).
2. Press shift+enter to get br
result:
    `<div class="trumbowyg-editor" contenteditable="true" dir="ltr" style="height: 334px;"><p>dsaasdasdsad</p>
<br>
</div>`
I would like to receive the br in paragraph. If you start typing a new line, br disappears and appears the second paragraph, but I wanted to get a line break in one paragraph.
I think this is due to the fact that at the beginning of the input text is not immediately wrapped in a paragraph, but only after you enter

**Comment by Alex-D** [comment]
It's a bug from content editable API. I don't have the time anymore to improve things like that. Sorry :/
