### ISSUE TITLE
Errors in the Arabic translation

### ISSUE THREAD

**Issue by chadidi** [Alex-D/Trumbowyg#369]
/*****************************************************************

@Alex-D This is the correct translation of some Arabic words

******************************************************************/

```
jQuery.trumbowyg.langs.ar={
	formatting:"تنسيق",
	header:"رأس",
	insertImage:"إدراج صورة",
	insertVideo:"إدراج فيديو",
	horizontalRule:"إدراج خطّ أفقي",
	fullscreen:"كامل الشاشة",
	reset:"إعادة تعيين"
};

```

**Comment by Alex-D** [comment]
Can you make a Pull Request insteed? Thanks :)
