### ISSUE TITLE
Images Gallery

### ISSUE THREAD

**Issue by ramezrafla** [Alex-D/Trumbowyg#373]
@Alex-D 

This editor is beyond amazing, so slick and well-designed! Well done!

I am seeking your advice to create more complex images handling. In Google docs, you get a tabbed modal with the option to upload, chose from existing gallery, or enter a link.

I'd like to create a plugin that does that. Any advice on how to proceed, which plugin to get inspired from?

Also, do you offer commercial support? Thanks!

**Comment by Alex-D** [comment]
I'm sorry for the lack of documentation for plugins, but you can found a lot of things by reading [plugins code](https://github.com/Alex-D/Trumbowyg/tree/develop/plugins) and [core code](https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js) which are relatively shorts.

Good luck, you can make a pull request with your plugin if you want :)

> Also, do you offer commercial support?

On each project you can found a licence file at the root, for Trumbowyg it's here: https://github.com/Alex-D/Trumbowyg/blob/develop/LICENSE

So yes, it's MIT licenced, you can do what you want, but you could be cool if [you make a donation on Trumbowyg webpage](http://alex-d.github.io/Trumbowyg/#amount) :)

**Comment by ramezrafla** [comment]
Hi @Alex-D 
Absolutely we could make a donation as we use it! Thanks for such great code.

My question about commercial support: can you help us do some development for the images gallery? 

We then don't mind if you push it to the repo to share with the rest of the community. The images gallery is the last feature we need that is currently not there (and I feel this feature could be very welcome and expand the community).

**Comment by Alex-D** [comment]
Ah ok, hum. You can send me an email at **contact@alex-d.fr** and detail your need / API to use / ...

**Comment by ramezrafla** [comment]
Closing issue, as we were able to figure out how the API works from the template examples. Well done Alex!
