### ISSUE TITLE
Button not active with a click

### ISSUE THREAD

**Issue by joshuaruesweg** [Alex-D/Trumbowyg#377]
### Informations

**Browser + version**: Google Chrome 52.0.2743.116 (64-bit)
**OS**: OSX 10.11.5
**Resolution**: 2880 x 1800

### How to reproduce the bug?
If I click on a button (e.g. Bold), the button isn't active. See: https://www.youtube.com/watch?v=SsUFdtkcXbs

**Comment by joshuaruesweg** [comment]
Thanks for the quick answer! 👍

**Comment by sagaritrockz** [comment]
Can I expect a fix any time sooner ?

**Comment by Alex-D** [comment]
Nope, I say that need a complete rewrite, I don't have the time yet.
