### ISSUE TITLE
tbwChange triggered on cut before content is changed

### ISSUE THREAD

**Issue by istrau3** [Alex-D/Trumbowyg#380]
Basically, the tbwChanged event is fired after cutting text out of the editor. In the event handler if I get the html inside the editor, it is still equal to what it was before I did the cutting. Note that this bug only exists in wysiwyg mode. If I switch to source mode and cut, the html inside the editor is an empty string (as it should be).

### Information

**Browser + version**: Latest Chrome
**OS**: Windows 10

### How to reproduce the bug?

1. Add an event handler to the editor like so: 

```
.on('tbwchange', function() {
                let text = vm.$textArea.trumbowyg('html');
            },)
```

2. Add some text to the editor
3. Add a breakpoint inside the event handler
4. Cut the text out of the editor
5. When the breakpoint gets hit notice that text is not null or "" rather the text that you had in the editor before cutting.

**Comment by Alex-D** [comment]
Do you have the latest Trumbowyg version? 
I've already made a patch for this here: https://github.com/Alex-D/Trumbowyg/commit/b4f8ad0e8d45455a3412ca3671d64edc88d1c2e4

**Comment by istrau2** [comment]
@Alex-D I have the latest that is on npm: 2.1.1.

I just checked the code. It looks like that commit is not part of the latest version on npm. Did you publish after that commit?

**Comment by Alex-D** [comment]
Arf... I have forget to publish versions to npm, sorry for that.

**Comment by Alex-D** [comment]
I just publish the 2.3.0 :)
