### ISSUE TITLE
Remove gulpfile from 'color' plugin folder

### ISSUE THREAD

**Issue by Globulopolis** [Alex-D/Trumbowyg#382]
In latest release I see two unwanted files in `dist` folder

```
dist\plugins\colors\Gulpfile.js
dist\plugins\colors\Gulpfile.min.js
```

It's a bug?

**Comment by Alex-D** [comment]
These files are for build. Useless in production. I will check to remove them in next releases.

**Comment by Alex-D** [comment]
Done in 2.4.4. Thanks :)
