### ISSUE TITLE
Super slow performance with lots of text or base64 inline image

### ISSUE THREAD

**Issue by Droeftoeter** [Alex-D/Trumbowyg#383]
When you have a lot of text in your editor or a base64 inline image, it takes more than 1 second for text to appear after typing. The cause for this is the semanticCode function which gets executed on every keyup event.

My suggestion is to set and reset a timeout on typing, and then execute the semanticCode function when the user is actually done typing.

**Comment by JSteunou** [comment]
More important, it also happens on **empty** textarea with Chrome android (chrome is partially faulty, it sends a lot of events for one stroke).

**Comment by lerzenit** [comment]
I had the same issue. It can be solved by just putting `display: none;` on the textarea element.

**Comment by Alex-D** [comment]
If you hide textarea, HTML5 validation cannot works. That's why I did not hide it.

**Comment by Alex-D** [comment]
The only case when it is useful to keep the text area visible is to make the `required` attribute working.
If you are not using it, then you can hide the text area and get rid of this input delay :)

Maybe I should add something to hide when the required attribute is not present.
