### ISSUE TITLE
Entering new line only works the first time on IE

### ISSUE THREAD

**Issue by Alex-D** [Alex-D/Trumbowyg#389]
Using IE11 and Edge, if you press enter once, it works correctly adding a new line.
However, if you press enter again, it does not add a new line. Looking at the source, in IE it's adding `&nbsp;` for enter instead of `<br>` (in Chrome).

See PR #308

**Comment by Gui11aum3** [comment]
@Alex-D : Any reason why this PR hasn't been merged? 
https://github.com/Alex-D/Trumbowyg/pull/308
