### ISSUE TITLE
What does "strong problem" mean on the home page?

### ISSUE THREAD

**Issue by dandv** [Alex-D/Trumbowyg#390]
> SVG icons issue?
> If icons do not load:
> 
> "check if you did not have strong problem;"

**Comment by Alex-D** [comment]
Ah ah, that's a typo... Idk what I've got in mind when I write that ^^'

**Comment by Alex-D** [comment]
This will be fixed in the 2.8.0 docs refactor: https://github.com/Alex-D/Trumbowyg/pull/613
(I did not push all modifications ATM)
