### ISSUE TITLE
Remove jQuery dependency?

### ISSUE THREAD

**Issue by dandv** [Alex-D/Trumbowyg#391]
Just wondering, in the light of [this post](https://ponyfoo.com/articles/why-i-write-plain-javascript-modules), how difficult it would be to remove the dependency on jQuery.

**Comment by Alex-D** [comment]
If I remove jQuery (and it should be possible in v3) I will rewrite the plugin and do not base Trumbowyg on buggy `execCommand`.

I know that is not possible/hard yet to remove the dependency on jQuery :/

**Comment by SmoshySmosh** [comment]
@Alex-D Have you thought about replacing jQuery with something like [cash](https://github.com/kenwheeler/cash)? It seems to cover most of what jQuery does but at a fraction of the size. I believe around 3kb~ gzipped.

Would this be a difficult task?

**Comment by Alex-D** [comment]
There is no AJAX support, so it's hard yep :/

**Comment by SmoshySmosh** [comment]
You're right... Although there is a pull request on the repository that we could try to give a little shove... I may be bias, but I love this WYSIWYG editor and I would love it even more if I didn't have to require jquery due to its size... Let me know of you need any help, I wouldn't mind contributing.

**Comment by DoomyTheFroomy** [comment]
@SmoshySmosh 👍 
@Alex-D is this only the line [177](https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L177)? Or are there more problems? Because a request is also pretty simple in VanillaJS. I would also help, because this would made this WYSIWYG editor more awesome! And save loading time 😏

**Comment by Alex-D** [comment]
>  Because a request is also pretty simple in VanillaJS

I know. I'm not fan of jQuery anymore. But if the ajax support could be supported by cash it could be cool. Upload plugin use it too.

**Comment by DoomyTheFroomy** [comment]
@Alex-D sorry what I meant, was not to switch from one library to another, I would recommend to use [Vanilla JS](http://vanilla-js.com/) or better say pure JS. Without any use of extra library. I think this should also work?!

**Comment by Alex-D** [comment]
I know what is Vanilla JS. But XHR Request are not so easy to support on each browsers, especially IE/Edge :(

**Comment by SmoshySmosh** [comment]
I believe we have a few options for XHR, remember the goal is to keep the final size down.

https://github.com/pyrsmk/qwest - 2.2kb
https://github.com/dimitrinicolas/marmottajax - 1.8kb
https://github.com/typicode/fetchival - 0.6kb

Thoughts?

**Comment by DoomyTheFroomy** [comment]
@Alex-D 👍 
@SmoshySmosh fetchival looks great and close to this, what I would have in mind.

**Comment by richardtallent** [comment]
I recommend Axios as an option for XHR requests. It's the standard library AJAX requests for Vue, which I also use. (Trumbowyg is one of the few non-Vue components I still use, and the only one that depends on JQuery.)

**Comment by DoomyTheFroomy** [comment]
@Alex-D if you need any help with anything let me know

**Comment by pwFoo** [comment]
Axios and axios.all() is nice, but I like the minimal size of fetchival.

**Comment by aguilera51284** [comment]
[unfetch](https://github.com/developit/unfetch)

**Comment by Alex-D** [comment]
I plan to remove jQuery dependency in version 3.

See #875 for more informations.
