### ISSUE TITLE
Customization of modal

### ISSUE THREAD

**Issue by sneila** [Alex-D/Trumbowyg#393]
Hi, 
is there a way to add checkboxes or radio buttons for the modal, currently only input field is allowed/generated.

I would like to add the option to choose some custom styles (classes) for the image upload, to allow the user to decide sizes (large, medium, small), as well as position (left, center, wide, right)

It's possible if he enters the text manually but i would like him to choose some radio buttons, or dropdown.

**Comment by Alex-D** [comment]
Dropdown and radio are not supported because useless for the core.

Checkbox are implemented.

I you case, you should generate the form yourself in your plugin and use: http://alex-d.github.io/Trumbowyg/documentation.html#modal-box

**Comment by sneila** [comment]
Is there a way to pass like "values: ['a', 'b', 'c']" to the checkbox, since now it takes the name of the class as the value. And does not allow multiple options. (also multiple labels would be nice):
Example:
Position: [] Left, [] right, [] middle

label: 'Position',
values: { 'left': 'Left', 'right': 'Right', 'center': 'Middle'},
type: checkbox (or radio, since it works too)

**Comment by Alex-D** [comment]
Nope. In the core, only checkbox logic is supported. Radio works yep but are not used / tested.

You can't pass an array of values. You need to create a radio for each item :/

**Comment by sneila** [comment]
I am aware that currently it's not possible, it's just a few extra lines of code to support $.each on values (around line ~1380). I will give it a try. Should not increase the codebase so much.

**Comment by Alex-D** [comment]
> Should not increase the codebase so much.

**Comment by sneila** [comment]
I will need to refine the code but it looks like this:
http://b3.ms/06j9d0YO9abK

Also, i will propose a new CSS at some point (removed dark theme too).
Modals should not be harcoded fonts and fontsizes, since you use it already in a skinned environment.

**Comment by Alex-D** [comment]
I just offer a default theme built-in. Feel free to made your own.

If your modification cannot be merged, it's OK. Do not feel obliged to make a pull request.
