### ISSUE TITLE
Add indentation plugin to core

### ISSUE THREAD

**Issue by minkwe** [Alex-D/Trumbowyg#395]
It would be nice to have an indentation plugin as part of the core. This will allow indented blocks of text as well as nested lists to be easily created without resorting to editing the html code.

**Comment by Alex-D** [comment]
As you can see here: https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand
Firefox does not have the same behaviour as other browsers. So it's too complexe to patch in the core.

You can make a separate plugin for that and PR it :)
