### ISSUE TITLE
Doubleclick on picture is hardcoded to Insert Picture, makes upload/other plugin useless for editing

### ISSUE THREAD

**Issue by sneila** [Alex-D/Trumbowyg#396]
Inserting a picture with an upload plugin, double clicking it shows the same Insert Picture. 
It's even hardcoded in the JS, aka cloned behavior for the insert image (not the same, just a copy of it)

Makes the functionality of plugins obsolete, just to insert, not to edit.

There is a way to insert with the new picture some sort of 'data-button' and trigger the same button again, yet i need a way to know what picture was clicked, to allow edit.

**Comment by Alex-D** [comment]
Since dblClickHandler is an option: https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L379

Feel free to override with what you want.

**Comment by 2braincells2go** [comment]
@sneila Did you ever come up with a solution to this issue?

Really like to use this for kids CMS (school blogs) but not being able to align image left/right to text is killer for us.

Thanks!
