### ISSUE TITLE
Embed video with noEmbed not working

### ISSUE THREAD

**Issue by Leodime** [Alex-D/Trumbowyg#397]
### Informations

**Browser + version**:  Mozilla Firefox 48.0.2
**OS**: Windows 10
**Resolution**: 1366x768

### How to reproduce the bug?
When I click on the noEmbed button and paste a valid link, nothing happens. But when I paste a non video link it says it's not valid. How can I solve it? 

EDIT: The noEmbed button on the demo has the same behaviour

**Comment by Alex-D** [comment]
In fact :/
Idk why.

**Comment by jeffreybasurto** [comment]
Any solution to this?    Pretty big issue for us.

**Comment by Alex-D** [comment]
Debug the plugin and make a PR? :D

I just don't have the time yet. I will take a look ASAP.

**Comment by carloswbarros** [comment]
Replace line 68 with `trumbowyg.execCmd('insertHTML', data.html);` in trumbowyg.noembed.js, mine seems to be working now.

**Comment by Leodime** [comment]
Gonna try that tomorrow. Thx @carloswbarros for your time!

**Comment by Alex-D** [comment]
Thx for the fix :)
