### ISSUE TITLE
Issue with removeFromPasted option

### ISSUE THREAD

**Issue by mbaudry** [Alex-D/Trumbowyg#400]
Hello !

First, thank you for your great plugin :) very easy to use !!

However, I have an issue with the removeFromPasted option. When I write text into the text area, and I add space between two paragraphs, if I make backspace from a paragraph to the previous, the font size of the text change (the plugin add an inline style of 1.6em font-size)

The original text:

![1](https://cloud.githubusercontent.com/assets/15127641/18587090/6f59b944-7c20-11e6-8709-a5ffadf802ea.png)

When I apply a backspace on the last paragraph to the second one:

![2](https://cloud.githubusercontent.com/assets/15127641/18587091/6f5a2aaa-7c20-11e6-95c1-637ef8894d43.png)

Thank you for your help

Chrome 52 on Ubuntu 16.04

**Comment by Alex-D** [comment]
I thinks it is a Chrome Ubuntu bug :(

**Comment by mbaudry** [comment]
It also appears on Chrome Windows

**Comment by mbaudry** [comment]
We used our own CSS to use the plugin, we add a **font-size: 16px; important!** on all the children of  trumbowyg-box. It removed the wrapping span with the inline style of 1.6em font-size and it fixed the issue. May be it can help you to find the problem...

**Comment by Alex-D** [comment]
Thanks for your feedback!
The reason that I can't reproduce the bug is I have `normalize.css` on my dev page.
So I need to add something like that in the doc or in the core default CSS.

I think that could resolve the #203 too.

Thanks!

**Comment by mbaudry** [comment]
You're welcome

**Comment by Alex-D** [comment]
Need to add a section in documentation to tell to Trumbowyg users to define a font-size.
