### ISSUE TITLE
Menu item name override

### ISSUE THREAD

**Issue by eradin** [Alex-D/Trumbowyg#401]
I need to override the menu text for the base64 plugin.  Insert Base64 is to techy for my users.  Something like Embed Image would be better.

I'm not suggesting you change it in the plugin.  I'd like to change it from the options but overriding lang:en doesn't seem to work.  Is this even possible?

**Comment by Alex-D** [comment]
You can do it in a JS *after* loading jQuery, Trumbowyg and Trumbowyg plugins by overriding `$.trumbowyg.lang.en.base64`

**Comment by eradin** [comment]
Thanks Alex.  That worked.  Although, for anybody who stumbles across this question, the correct syntax is:

$.trumbowyg.**langs**.en.base64 ='new title';

**Comment by Alex-D** [comment]
Thx, I fix it :)
