### ISSUE TITLE
Clean Office Paste

### ISSUE THREAD

**Issue by eradin** [Alex-D/Trumbowyg#402]
Hi Alex.  A real annoyance for my users is when they paste text from office apps like word or email.  The paste command will insert all this office stylesheet garbage which can really cause havoc in trumbowyg.

I have created a plugin that I would be glad to contribute that cleans all the office garbage before pasting.  
Questions:

1. Would you be interested?
2. What's the best way to send it to you?

**Comment by Globulopolis** [comment]
@eradin yeap, please make PR.

**Comment by Alex-D** [comment]
Hi! What do you mean by "cleans all the office garbage"?

There is already a option for cleaning pasted formated content: http://alex-d.github.io/Trumbowyg/documentation.html#remove-format-pasted

**Comment by eradin** [comment]
No, remove format pasted removes everything and reduce the paste to text only.  That is useful but many times too harsh.  My plugin removes all the MS Office style sheet stuff that has no use and only bloats the html (at best) and at worst, causes editor confusion.  I'll try to PR it when I have time this weekend.

**Comment by Alex-D** [comment]
So your plugin could be a must have :)

**Comment by Alex-D** [comment]
I will publish that in next release. I did not use Word, so I can't test it.

**Comment by joaomelont** [comment]
Hi guys, how can I use this plugin? Couldn't find it on github.

**Comment by Alex-D** [comment]
Did you try *Clean paste* plugin?

https://alex-d.github.io/Trumbowyg/documentation/plugins/#plugin-cleanpaste

https://github.com/Alex-D/Trumbowyg/blob/master/plugins/cleanpaste/trumbowyg.cleanpaste.js
