### ISSUE TITLE
Title of Base64 is poor name choice

### ISSUE THREAD

**Issue by eradin** [Alex-D/Trumbowyg#403]
When you activate the base64 plugin, the default name given to the menu item is Insert Base64.  That is meaningless to most users (although technically correct).  I have changed it to Embed Image for my users.  I suggest the default title be changed.

**Comment by Alex-D** [comment]
You can make a pull request to update that if you think it's better :)
Thanks!

**Comment by PapsOu** [comment]
@eradin : You can change the label this way :

```javascript
jQuery.trumbowyg.langs.en.base64 = 'Picture';
```
