### ISSUE TITLE
Error when instantiating Trumbowyg before Foundation plugins

### ISSUE THREAD

**Issue by silentmiles** [Alex-D/Trumbowyg#404]
This isn't really a bug with Trumbowyg, as it can probably be argued that it's more of an issue with Foundation: Trumbowyg creates an element with a "data-dropdown" attribute. If Foundation is initialised on HTML content _after_ Trumbowyg, then Foundation will interpret the "data-dropdown" element as a Foundation dropdown, and try to initialise its Dropdown plugin on that element, which results in an error.

Of course one workaround is to initialise Trumbowyg after Foundation, but it my case this is not possible (or not very practicable).

Even though this should arguably be fixed in Foundation, it might be easier to "fix" it here in a more reasonable time frame. Instead of 'data-dropdown', a more unique name could be used, such as 'data-trumbowyg-dropdown'. In fact, it might be a good idea to prefix all dom attributes, just as the CSS classes are prefixed.

**Comment by Alex-D** [comment]
You right. I will update that ASAP.
