### ISSUE TITLE
How to manipulate the 'formatting' list

### ISSUE THREAD

**Issue by aadjemonkeyrock** [Alex-D/Trumbowyg#405]
I would like to remove the 'quote' option from the formatting list. Is there a way to do this?

**Comment by Alex-D** [comment]
That the original definition of formatting.
You just need to override it in your option:

```js
$('.my-editor').trumbowyg({
    btnsDef: [
         formatting: {
             dropdown: ['p', 'h1', 'h2', 'h3', 'h4'],
             ico: 'p'
         },
    ]
});
```

I didn't test this code, but I think it should be work.

**Comment by Alex-D** [comment]
I keep that open to add some docs on that.

**Comment by timdiacon** [comment]
I'd like to do this too but above code doesn't seem to work for me :-(

**Comment by danman1234** [comment]
How to do this with no dropdown, but just a button with custom icon?
