### ISSUE TITLE
How to disable image pasting?

### ISSUE THREAD

**Issue by hurricane766** [Alex-D/Trumbowyg#407]
I just want to have a text editor without the ability to embed images. Is it possible to disable image pasting?

**Comment by pekpon** [comment]
Add the "remove format pasted" option:

`$('.text-editor').trumbowyg({removeformatPasted: true});`

**Comment by hurricane766** [comment]
That will prevent images from being pasted in, but it also prevents bold, italics, etc.

I'm still looking for a solution to this problem... is there someway to blacklist or whitelist tags?

**Comment by Alex-D** [comment]
You need to create a simple plugin.

You can give a "pasteHandler" in options: https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L377

Example of use: https://github.com/Alex-D/Trumbowyg/blob/develop/plugins/pasteimage/trumbowyg.pasteimage.js

There is no option for white/blacklisted elements because it should be managed in backend or in a plugin.

**Comment by hurricane766** [comment]
Ok, that sounds reasonable, thank you.

**Comment by Tagmar2** [comment]
he error persists and is at https://alex-d.github.io/Trumbowyg

Steps to reproduce:
1) Go to a webpage that has an image

2) over the image, use the context menu to do a "copy image"

3) Go to https://alex-d.github.io/Trumbowyg

4) Click "With plugins"

5) paste from clipboard

Realize that the first image is just the internet link. The second is the embebed 64

`<img src="https://cdn2.iconfinder.com/data/icons/diagona/icon/16/150.png" alt="Resultado de imagem para close icon"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACRUlEQVQ4EaWTTWsTURSG35nJJGMam3QMNDabgDWUgMaIIgraollmYd0YEKsUEv0JXdWaX6EVRHSTnVlkqxsXhVJNKyISNN2YLzGZhCTNZD4ycq6doa2udGAYOPd53nPnci7wnw931Lce3IjB4tOAlQKQ2F8vAVwR3DjPPX3z+aBzKMBYvp7h3K4cNzMT4qangamp36yiwGo2YdVqDUszVl3P3z6zQ5wA7f7VDHzH14VoFJ1qFe2dHXTLZcb5o1HI8TgC4TBMqvV7WfeLdyyEJ2J051LMtJATIhH82N7G90JhY6+ye+9CBRy9g91KQVYU8KEQiCGWHHJZgDrS0pDlUK9WQ2tra4MXvXfjZf0lAVY2uRafX7iJZBLvV1ZADLHMsQN0zUi5JicxqFQgSZ4nZz51v9kygEe27A8GC8QQS46zA2OkJlyiCFNRMLvZcjoflC3g8enNn4vEEEuOE6BrGjAcwuP1Uo1t+6h8sYI1WmPMcAjmAHBRUR+NSmqzmZiQZXRunXsNwPln6mzLymJiSfRKUJtN5pDLDtHQtWKvXockSfAHg3+V1dtXTnmOuR8SQyw5ToBuaPl2vdZQaWAiEXba8YX5gt3ZWL62JHjFVx6PdJkYYsmhAGeQPs5JGckrrZ8Mh+GjCRRFQBCIAUwT0HX0FQX1ahXqnpo9+0Vlg+QEEFeKChmeF3InZDnkDwTgm5hgfn8wQLfTQavdbozH5mqibP45yowE8GEWsbGJNIAUuP3LZKEEoMgLyJ//ikOXyfb++fsLkiQUXnILVLMAAAAASUVORK5CYII=">`

**Comment by oza75** [comment]
@hurricane766 have you find a way to disable image pasting ?

**Comment by hurricane766** [comment]
@oza75 This was a while ago, but I believe we did as Alex-D suggested. In the end we moved away from Trumbowyg to a different editor, so I can't say for sure if this still works.

**Comment by VrbovskyM** [comment]
> @oza75 This was a while ago, but I believe we did as Alex-D suggested. In the end we moved away from Trumbowyg to a different editor, so I can't say for sure if this still works.

What other editor ? I so far couldnt find better WYSIWYG editor for free

**Comment by hurricane766** [comment]
> What other editor ? I so far couldnt find better WYSIWYG editor for free

I believe we used ckeditor (4) at the time. It looks like v5 might still offer the core features for free.

**Comment by Alex-D** [comment]
https://github.com/Alex-D/Trumbowyg/discussions/1371#discussioncomment-4939375
