### ISSUE TITLE
<div> being removed and replaced with <p>

### ISSUE THREAD

**Issue by leightongrantham** [Alex-D/Trumbowyg#410]
### Informations

**Chrome + Version 53.0.2785.116 m**:
**Windows 10**:
**1920x1080**:

### How to reproduce the bug?
Grab html and throw into new tab after editing. 

Basically, i have created a "preview" function that allows the user to preview their changes in a new tab when they click the button. If only simple text changes are made, the preview is fine however if you use any of the plugins like Bold text or change color of text, all the div classes are replaced with "<p>" classes which causes the page to break.

This is my code: 

```
// -----------------------------
// Preview Function
// -----------------------------
function printClick() {
    var w = window.open();
    var html = $(".previewWrapper").html();
    w.document.write("<html><head><title>Preview</title><link rel='stylesheet' type='text/css' href='../css/templates.css'><link rel='stylesheet' type='text/css' href='../css/smartpages.css'<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.css'> <link rel='stylesheet' type='text/css' href='https://fonts.googleapis.com/css?family=Open+Sans'><script type='text/javascript' src='../js/smart_pages.js'></script> <script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js'></script><script type='text/javascript' src='../vendor/materialize.js'></script><?php include('../layout/builder.phtml');?></head></html>");
    // Write html to new window
    $(w.document.body).html(html);
}

$(function () {
    $("a#previewBtn").click(printClick);
});
```

image of whats broken

![capture](https://cloud.githubusercontent.com/assets/17552119/18950103/24f3a19c-8636-11e6-9599-c508bb317c05.PNG)

**Comment by m-hagberg** [comment]
I believe this has something to do with the `semantic` option being set to `true` by default. For some reason, `<div>` elements are being replaced with `<p>`. This is a bit confusing, since we're not really talking about semantics here - divs and paragraphs serve completely different purposes.

I recently ran into this issue a little while ago, and I would really like this to be a separate option. Using div elements _and_ semantic tags (`<strong>` etc.) should not be an issue, but the workaround as of right now is `semantic: false`.

**Comment by leightongrantham** [comment]
Thank you :)

**Comment by Alex-D** [comment]
The problem is: some browsers inserts div insteed of p, so I need to transform them and I can't make the difference between div added by browser and div added by user :/

**Comment by aswzen** [comment]
This issue still happening hmm..
