### ISSUE TITLE
What is the composition variable for? (trumbowyg.js:542)

### ISSUE THREAD

**Issue by hurricane766** [Alex-D/Trumbowyg#411]
There's a demo here: https://api.jquery.com/event.which/ , that will log e.which as you type, and when using trumbowyg in Chrome on an Android device, the 229 code is fired for each key press (except enter). 

I tracked the issue back to trumbowyg.js:568 and the composition boolean variable. Because the 229 keydown is detected, composition is set to true on line 548 and then line 568 prevents regular key presses from firing the tbwchange event.

**Comment by Alex-D** [comment]
This event is for languages that need multiple keys to write one symbol like chinese or some languages with non-latin symbols.

I know it's buggy on Android, maybe I need to make an option to disable that...

**Comment by hurricane766** [comment]
Perhaps an option you could add to the language definitions? So if the language needs multiple keys it could be turned on.

**Comment by Alex-D** [comment]
Maybe.

**Comment by hurricane766** [comment]
Looks like this is a duplicate issue [#290](https://github.com/Alex-D/Trumbowyg/issues/290)
