### ISSUE TITLE
Adding spaces on paste, not selected on cut/copy

### ISSUE THREAD

**Issue by bentito** [Alex-D/Trumbowyg#412]
### Informations

**Browser + version**:Chrome Version 53.0.2785.116 (64-bit)
**OS**: Mac OS 10.10.5 (14F27)
**Resolution**: Not sure what "Resolution" refers to
### How to reproduce the bug?

With Trumbowyg v2.3.0 I am having the following issue:
Select a freestanding word from text: "Mary had a **little** lamb" <-- select just '**little**'
Your selection will show just the word 'little' select without the spaces on either side.
Choose cut or copy. I'lll use cut here.

Paste your selection, between some other text so you can see what's going on: 
"Ma little ry had a lamb"

Note the spaces (they are \20 hex) added around 'little' they were not in the selection shown to the user.

Additional info:
If you make the selection from within a word (i.e. not with whitespace on either side of the selection) you will not see the added spaces. So "Mary had a little lamb" <-- select just 'ar' from Mary, choose cut. Paste back inside the word 'little' like: "My had a litartle lamb." No spaces added.

**Comment by Alex-D** [comment]
Did you try in another brother?

**Comment by bentito** [comment]
Does not seem to reproduce in  Firefox 47.0, same OS, etc.

**Comment by Alex-D** [comment]
So it's maybe a behaviour of Chrome on macOS :/

**Comment by bentito** [comment]
Do not see it using same all else (Chrome, Mac, etc) and same steps to reproduce:
http://ckeditor.com/demo
So it's an interaction with Chrome for sure, but still an issue related to Trumbowyg I think,

**Comment by Alex-D** [comment]
I close this to keep issues clean since this issue is inactive since a long time.
