### ISSUE TITLE
Caret isn't visible when user first click the text area

### ISSUE THREAD

**Issue by idansh** [Alex-D/Trumbowyg#413]
When I click on the designated editable area, the flashing caret that you usually get when a textarea gets focus is not visible in the editable area. Only when I start typing a letter the caret appears. So the problem is that when the user clicks the designated text area with his mouse, it looks like the text area loses focus because there is not visual cue showing the user that he can start typing text.

![untitled-2](https://cloud.githubusercontent.com/assets/2001050/19020023/b727480e-88a5-11e6-9758-9e6cac400223.jpg)

Chrome latest version
Windows 7
1920x1080

**Comment by TenMediaBln** [comment]
Hi, it's just a guess, but is your textarea inside a html label? And if so, did you try to move it out of the label container?

**Comment by sagive** [comment]
Thank you!!! that saved me a lot of time!

**Comment by wayferer** [comment]
I can also confirm this was an issue we were having and it was due to the textarea being wrapped in a label.

**Comment by Alex-D** [comment]
So you should use:

`<label for="my-textarea">...</label><textarea id="my-textarea" class="editor"></textarea>`
