### ISSUE TITLE
No Color Buttons When Trying To Use Colors Plugin

### ISSUE THREAD

**Issue by feeekkk** [Alex-D/Trumbowyg#414]
### Informations

**Browser + version**: Chrome
**OS**: OS X
**Resolution**:

I have required `trumbowyg.js` and `trumbowyg.colors.js` onto my page. I'm instantiating a trumbowyg with the following:

```
this.$el.trumbowyg({
					autogrow: true,
					btns: [
						['viewHTML'],
						['undo', 'redo'],
						['formatting'],
						'btnGrp-semantic',
						['superscript', 'subscript'],
						['link'],
						['insertImage'],
						'btnGrp-justify',
						'btnGrp-lists',
						['foreColor', 'backColor'], // this isnt working right now
						['horizontalRule'],
						['removeformat'],
						['fullscreen'],
					],
				});
```

Expected: The fore color / back color buttons would be visible and able to be used.
Actual: the buttons are not added to the editor.

I'm noticing that `loadedPlugins` and `$.trumbowyg.plugins` are empty. Is there something else I have to do other than including the colors script on my page?

**Comment by Alex-D** [comment]
You need to include

trumbowyg.min.css
trumbowyg.colors.min.css

jquery.min.js
trumbowyg.min.js
trumbowyg.colors.min.js

Then, run your script.

In this order.

**Comment by feeekkk** [comment]
Ah, I didnt realize that you have to require `trumbowyg.js` before `trumbowyg.colors.js`. Maybe that should be more explicit in the docs? thank you!

**Comment by Alex-D** [comment]
For most libraries in most languages, you should follow this order :)
