### ISSUE TITLE
Ctrl+Z does not work without the Undo button

### ISSUE THREAD

**Issue by ilpoli** [Alex-D/Trumbowyg#417]
Chrome 53, Trumbowyg 2.3.0
1. Configure Trumbowyg without Undo button.
2. Type some text
3. Use Ctrl+Z to undo last changes

**Expected**: Textarea values is updated.
**Actual**: Textarea still contains value as before Ctrl+Z.

As workaround we added the Undo button and hided it.

**Comment by Alex-D** [comment]
Undo feature is not stable and the button only works on Blink/V8 browsers.

**Comment by ilpoli** [comment]
Thanks for explanation. Are you planning to improve this logic closer time or it is not a priority feature?

**Comment by Alex-D** [comment]
That's not a priority.

**Comment by Alex-D** [comment]
Since 2.10.0, you can use history plugin to get an improved and cross-browser history management.

https://alex-d.github.io/Trumbowyg/documentation/plugins/#plugin-history
