### ISSUE TITLE
Can't provide max length for entering characters of Trumbowyg

### ISSUE THREAD

**Issue by vrushalip** [Alex-D/Trumbowyg#418]
Hi, 
We are currently not able to restrict for number of characters for this editor.

**Comment by Alex-D** [comment]
It's hard to do, so I can't do that, sorry :/

**Comment by Alex-D** [comment]
See #316

**Comment by vrushalip** [comment]
But it won't stop typing after maxlength limit is reached.

**Comment by Alex-D** [comment]
That's not possible since the edit zone is not a form field but a contenteditable div.

**Comment by grandecomplex** [comment]
We will likely validate server side ,but you can certainly use javascript to grab only the content of the html tags in the contenteditable and count the length.

**Comment by Alex-D** [comment]
Feel free to do it on your side, based on the `tbwchange` event :)
