### ISSUE TITLE
Improve link creation when user leaves Text field empty

### ISSUE THREAD

**Issue by nilsteampassnet** [Alex-D/Trumbowyg#423]
### Informations

**Browser + version**: Chrome 53.0.2785.143 m
**OS**: Win7 64bits
**Resolution**: 1366 \* 768
### How to reproduce the bug?

Simply create a new link by just filling in the URL field.
The link is created but unvisible.
### Change proposal

A suggestion would be to add the url as text.

Replace

``` js
            }, function (v) { // v is value
                var link = $(['<a href="', v.url, '">', v.text, '</a>'].join(''));
                if (v.title.length > 0) {
```

by

``` js
            }, function (v) { // v is value
                if (v.text === "") {
                    var link = $(['<a href="', v.url, '">', v.url, '</a>'].join(''));
                } else {
                    var link = $(['<a href="', v.url, '">', v.text, '</a>'].join(''));
                }
                if (v.title.length > 0) {
```

**Comment by jesperavot** [comment]
I would suggest to use a logical operator in this case:
`var link = $(['<a href="', v.url, '">', v.text, '</a>'].join(''));`
becomes:
`var link = $(['<a href="', v.url, '">', v.text||v.url, '</a>'].join(''));`

**Comment by Alex-D** [comment]
Why not, You can make a Pull Request if you want :)
