### ISSUE TITLE
Upload progress bar

### ISSUE THREAD

**Issue by Neverstone** [Alex-D/Trumbowyg#425]
Google Chrome 53

``` javascript
function addXhrProgressEvent() {
    if (!$.trumbowyg && !$.trumbowyg.addedXhrProgressEvent) {
```

`addXhrProgressEvent` would not setup the event listener because `!$.trumbowyg` would always return `false`. I mended this by just removing it from the if statment.

Then the progress bar it self wouldn't move, I found that 

``` javascript
//original
progressUpload: function (e) {
    $('.' + prefix + 'progress-bar').stop().animate({
        width: Math.round(e.loaded * 100 / e.total) + '%'
    }, 200);
},
```

this animate function was doing some weird things so I removed it and just set the width, there is already a transition style on the progress bar so it will still animate.

``` javascript
//modified
progressUpload: function (e) {
    $('.' + prefix + 'progress-bar').width(Math.round(e.loaded * 100 / e.total) + '%');
},
```

**Comment by Alex-D** [comment]
Fixed thanks for you :)
