### ISSUE TITLE
Can we create custom shortcuts as an option?

### ISSUE THREAD

**Issue by varun-raj** [Alex-D/Trumbowyg#426]
How about defining custom keyboard shortcuts that will call our functions?

**Comment by Alex-D** [comment]
What's your goal? You can attach shortcuts to any core function/plugin function.

**Comment by varun-raj** [comment]
I want to have a shortcut that will trigger my submit action.

**Comment by Alex-D** [comment]
Code it ^^ That's not a WYSIWYG feature.

**Comment by Alex-D** [comment]
That's something like that:

```js
$('#your-form').on('keypress', function(e) {
    if (e.which === 13) { // 13 is ENTER key
        $('#your-form').submit();
    }
});
```

**Comment by mrmnmly** [comment]
btw. is it possible to add easily custom keyboard shortcuts for existing toolbar buttons?

**Comment by Alex-D** [comment]
Nope.

You need to redefine them by yourself.
