### ISSUE TITLE
Cannot Delete Inserted Table using Table Plugin

### ISSUE THREAD

**Issue by frankbeerstein** [Alex-D/Trumbowyg#427]
After inserting a table with the table plugin, there is no WYSIWYG way to delete it. 

If the source code button is enabled, of course you can remove the table by editing the source. But I don't consider that a solution. The whole reason I'm implementing a rich text editor is to prevent people from coding HTML.
### Informations

**Browser**: Firefox 47
**OS**: Ubuntu 14

**Comment by Alex-D** [comment]
Ping @absalomedia did you have an idea?

**Comment by frankbeerstein** [comment]
It could be handled the same way as IMG, where a double-click/tap brings up the relevant dialog. At the bottom of the TABLE dialog, to the left of Confirm, there could be a Delete button. I like this because there is also a need for a way to delete columns and rows. Once the table dialog is up, the user can add or subtract the number of columns and rows, and the DOM can be manipulated accordingly. What do you think?

Double-click is a mobile-compatible action. The only other one that would be good for mobile is long-press. Here's a long press action that works in my testing on both mobile and desktop.
```
    var timer;
	$('.trumbowyg-table').on("mousedown",function(){
	    timer = setTimeout(function(){
	        alert("display table dialog");
	    },1*750);
	}).on("mouseup mouseleave",function(){
	    clearTimeout(timer);
	});
```

**Comment by absalomedia** [comment]
Double click/tap should work I think. It's still displaying the borders visually in the editor, correct?

**Comment by forelabs** [comment]
@Alex-D I guess this one can be closed
