### ISSUE TITLE
HTML export does not gives add attributes for image

### ISSUE THREAD

**Issue by varun-raj** [Alex-D/Trumbowyg#428]
When I try to get the HTML code of the content `trumbowyg('html')` , no attributes other than src for image is been exported.

**Comment by Alex-D** [comment]
Context? Example? I can't do anything. I didn't have the time to try all possibilities :/

**Comment by varun-raj** [comment]
Like I need to export data attributes and few basic attributes like id, alt.

If I try to generate a image in editor like the below
`<img src="/hills.jpg" data-id="124" alt="Blue Hills" id="124">`

It generates the below. 
`<img src="/hills.jpg" >`
