### ISSUE TITLE
Bold, Italic, Strikethrough not working on demo site

### ISSUE THREAD

**Issue by hurricane766** [Alex-D/Trumbowyg#430]
### Informations

Chrome 54
Windows 8.1
1920x1024

### How to reproduce the bug?

1. Go to the [Trumbowyg demo page] (http://alex-d.github.io/Trumbowyg/)
2. Put the cursor in the editor. Click bold, italic, or strikethrough. 
3. Start typing but the text is not formatted to what you selected.

It sort of looks like the buttons aren't staying active?

You can select text and then click bold and the selected text will change.

**Comment by Alex-D** [comment]
I'm sorry but I can't fix that. This seems to be a content editable bug.
