### ISSUE TITLE
Show full screen even in modal div

### ISSUE THREAD

**Issue by idansh** [Alex-D/Trumbowyg#431]
Is it possible to allow full screen to work in a popup modal box. When I use the plugin in a comment box inside a modal DIV, it doesn't show it on the entire page, just inside the modal div, and it just shows a white space without even the icon to close it.

Is it possible to make and adjustment so that the full screen will appear on the entire screen no matter where it is used, even in a modal dialogue box?

**Comment by Alex-D** [comment]
Nope, it's not possible because fullscreen is just a lot of CSS tricks and I don't want to change that for now.
