### ISSUE TITLE
Should I create a wrapper for React?

### ISSUE THREAD

**Issue by sochix** [Alex-D/Trumbowyg#432]
Hello! Thanks for your awesome library, it's blazing fast and stable. I want to create a wrapper for React. 

* Should I do it? Or you already have one?
* Can I somehow avoid using Jquery?

Waiting for your answer.

**Comment by Alex-D** [comment]
Hi!
There is no React wrapper for now.
jQuery is used anywhere in the core so you can't remove it :/

**Comment by sochix** [comment]
Hi! I'm happy to announce that our team developed a react-wrapper for Trymbowyg. 

Link - https://github.com/RD17/react-trumbowyg

It'll be **supernice** if you can provide link to a wrapper somewhere on Trumbowyg documentation page. 
Thanks!

**Comment by Alex-D** [comment]
Wow!
I will add this to the home page ASAP :)

**Comment by sochix** [comment]
Thanks! Awaiting for your changes 👍

**Comment by sochix** [comment]
ping

**Comment by sochix** [comment]
ping

**Comment by Alex-D** [comment]
Finally updated!
http://alex-d.github.io/Trumbowyg/

**Comment by sochix** [comment]
Woo-hoo! Thanks @Alex-D 👍
