### ISSUE TITLE
Plugin not working in Firefox

### ISSUE THREAD

**Issue by idansh** [Alex-D/Trumbowyg#434]
The plugin doesn't work on my site using Firefox. In chrome is works.

You can try to write an opinion and fill in text in the "more detailed information". You can see that no letters appear.

Where can you check:

http://phoneproscons.com/675/huawei-mate-9/

- Signup for the website (sorry but that's how the website works)
- click the Add Opinion button
- In Firefox (I'm using 49.0.1), enter text in the "More detailed information" section
- No text appears

Running Windows 7

**Comment by Alex-D** [comment]
Plugin works here for you on Firefox: http://alex-d.github.io/Trumbowyg/ ?

**Comment by idansh** [comment]
It works. So it's specific to my website :(

**Comment by idansh** [comment]
How can identify the problem. Any recommendation?

**Comment by idansh** [comment]
The problem was with the textarea wrapper with <label> element. Problem solves.
