### ISSUE TITLE
removeformatPasted “middle ground”

### ISSUE THREAD

**Issue by texelate** [Alex-D/Trumbowyg#438]
I love this plugin, does just what I've always wanted, _almost_.

`removeformatPasted: true` obviously removes everything  and `false` leaves way too much (like other editors) — often allowing clients to ruins your front-end design via the CMS. :)

What I personally have always wanted is for most of the dross to get removed but for some of the basic markup left in. I have managed to get this functionality working with some code tweaked from a couple of online code samples (referenced below).

So, what it does is on paste strip tags against a white list and then removes all attributes. So pasting results in nice clean syntax that is unlikely to interfere with your front-end design.

What about incorporating this into the source and having something like `pasteMode: 'plain' | 'basic' | 'rich'` and an extra option for `allowedTags: '<br><br /><div><p>...<h1><h2><h3><h4><h5><h6>'`

Here's the relevant part of my code, not yet thoroughly tested.

``` javascript
on('tbwpaste', function() {
      
    var $self = this;
   
    // Strip tags - http://locutus.io/php/strings/strip_tags/
    var html = $self.trumbowyg('html'); 
    
    var allowed = '<br><br /><div><p><h1><h2><h3><h4><h5><h6><strong><em><sup><sub><pre><code>';
    
    allowed = (((allowed || "") + "").toLowerCase().match(/<[a-z][a-z0-9]*>/g) || []).join('');
    
    var tags = /<\/?([a-z][a-z0-9]*)\b[^>]*>/gi;
    
    html = html.replace(tags, function($0, $1) {
        
        return allowed.indexOf('<' + $1.toLowerCase() + '>') > -1 ? $0 : '';
        
    });
    
    // Remove attributes: http://stackoverflow.com/a/12360574
    var walk_the_DOM = function walk(node, func) {
        
        func(node);
        
        node = node.firstChild;
        
        while (node) {
            
            walk(node, func);
            
            node = node.nextSibling;
            
        }
    };
    
    var wrapper = document.createElement('div');
    wrapper.innerHTML= html;
    walk_the_DOM(wrapper, function(el) {
        
        if(el.removeAttribute) {
            
            el.removeAttribute('id');
            el.removeAttribute('style');
            el.removeAttribute('class');
            
        }
        
    });
    
    html = wrapper.innerHTML;
    
    $self.trumbowyg('html', html);
    
});
```

**Comment by texelate** [comment]
I'm currently improving this code; I'll post when it's finished. 

One question: is it possible to get _just_ the pasted text on `tbwpaste` before it's added to the textarea. I'm just thinking it'll be more performant when working with large amounts of text.

**Comment by Alex-D** [comment]
You should use `pasteHandlers`, not `tbwpaste` event.
https://github.com/Alex-D/Trumbowyg/blob/develop/plugins/cleanpaste/trumbowyg.cleanpaste.js#L162

You get the event from here:
https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L622

So I think you can get the content via this code.

Feel free to make a PR to the core if you think it can be better :)

Take a look at this plugin too: https://github.com/Alex-D/Trumbowyg/blob/develop/plugins/pasteimage/trumbowyg.pasteimage.js#L18

**Comment by Cessquill** [comment]
I'd +1 this.  I've got people populating forms with content copied from Word documents that obviously add their own markup, etc.  I don't want to paste anything that would over-ride the site's stylesheet, but I do want to let basic formatting through (paragraphs, bold, italic, etc.).

At the moment I'm running a function against the field when I save it to strip the extraneous content back out, but it's a bit of trial and error and hacky.  It also only really applies to the document that they're converting from.

**Comment by texelate** [comment]
I pretty much have this working but haven't had time to finish it off yet, sorry. You can use the code I posted above though in the interim.

**Comment by Alex-D** [comment]
Should be resolved with the new allowTagsFromPaste plugin.
