### ISSUE TITLE
Disable Keyboard Shortcuts?

### ISSUE THREAD

**Issue by Anatolie** [Alex-D/Trumbowyg#439]
Google Chrome 53 (Windows + Mac)

Not sure if this is a bug or a missing feature, but I'm looking for a way to disable shortcuts for bold (ctrl+b), italics (ctrl+i), etc.

I set `removeformatPasted: true` in my editor and removed the option for bold/italic/underline buttons in the button pane (`btns`), however if I select text and hit a shortcut key (ctrl+b, for example), the editor still bolds the text.

I'm using HTMLPurifier to strip out tags such as `<b>` and `<i>` on the back-end, but it would be nice to have the ability to disable this on the front-end to prevent user confusion.

**Comment by Alex-D** [comment]
It's a content-editable feature :/
Chrome automaticly add this shortcuts...
