### ISSUE TITLE
Pasting an image in firefox throws NS_ERROR_NOT_IMPLEMENTED 

### ISSUE THREAD

**Issue by zspitzer** [Alex-D/Trumbowyg#440]
Firefox 49.0.2 (Win10) will throw NS_ERROR_NOT_IMPLEMENTED if you paste an image with the following config. Works fine (i.e. ignores and does nothing) in Chrome and Edge

```js
$('textarea').trumbowyg({
  autogrow: true,
  fullscreenable: true,
  fixedBtnPane: true,
  removeformatPasted: true,
  btns: ['viewHTML',
         '|', 'formatting',
         '|', 'btnGrp-design',
         '|', 'link',
         '|', 'btnGrp-justify',
         '|', 'btnGrp-lists',
         '|', 'horizontalRule',
         '|', 'removeformat',
         '|', 'fullscreen']
});
```

`NS_ERROR_NOT_IMPLEMENTED: 
Trumbowyg.prototype.execCmd() trumbowyg.js:1223
Trumbowyg.prototype.buildEditor/<() trumbowyg.js:626`

https://jsfiddle.net/5e6a2yw4/3/

**Comment by Alex-D** [comment]
Did you try the pasteplugin?
https://github.com/Alex-D/Trumbowyg/blob/develop/plugins/pasteimage/trumbowyg.pasteimage.js

**Comment by zspitzer** [comment]
just tried adding it in, same error 
https://jsfiddle.net/5e6a2yw4/5/

**Comment by zspitzer** [comment]
Firefox fixed this for an empty string with insertHTML, seems insertText has the same problem
https://bugzilla.mozilla.org/show_bug.cgi?id=309731

**Comment by Alex-D** [comment]
So it's a Firefox bug, I can't do anything here, sorry.

**Comment by zspitzer** [comment]
fixed in FF 55 https://bugzilla.mozilla.org/show_bug.cgi?id=1352144
