### ISSUE TITLE
Escaped HTML (code) is converted to HTML Symbols

### ISSUE THREAD

**Issue by mydnic** [Alex-D/Trumbowyg#442]
Hello Alex
This is more a question than an actual bug I guess.

I use your wysiwyg on my blog to write web dev tutorials. Sometimes I need to write example code, for that I wrap the code example between `<pre><code>` tags.
It usually works fine except when the example code contains HTML.

If I store actual HTML in my database like this : 

```
<pre><code class="html">
<p class="panel-heading">
    <a href="/link">Text</a>
</p>

<p class="panel-body">
    Content Text
</p>
<p class="panel-footer text-right">
    <a href="/link">
        Button
    </a>
</p>
</code></pre>
```

When I render the content of my blog post, the HTML is rendered as well and the example code does not appear.

So far, it's quite normal, so I usually convert it like that : 
```
<pre><code class="html">
&lt;p class="panel-heading"&gt;
    &lt;a href="/link"&gt;Text&lt;/a&gt;
&lt;/p&gt;

&lt;p class="panel-body"&gt;
    Content
&lt;/p&gt;
&lt;p class="panel-footer text-right"&gt;
    &lt;a href="/link"&gt;
        Button
    &lt;/a&gt;
&lt;/p&gt;
</code></pre>
```

And it works fine because it's not rendered in my views so the HTML symbols is visible.

The problem is after that, when I edit my blog post, all the escaped HTML like this `&lt;/p&gt;` is converted by the wysiwyg into actual `<p>` HTML symbols.

And then of course if I save the content I get back to the initial problem.

Do you see any solution for this ?

### Informations

**Browser + version**: Chrome 54
**OS**: Windows
**Resolution**: n/a

**Comment by richardtallent** [comment]
Here's some further background on this issue, which is indeed a limitation of browsers:

http://stackoverflow.com/questions/16252931/getting-inner-html-without-escaping-or-decoding-anything-with-jquery

One workaround might be to set .html(), then find any <code> blocks within the editor content and escape any &lt;, &gt;, and &amp; within them. I haven't had a chance to play with this idea to see if it is viable.

**Comment by Alex-D** [comment]
Thanks for your researches :)

We can't escape code: it can be voluntary escaped... we can't do the difference :/
