### ISSUE TITLE
tbwchange doesn't fire on mobile devices

### ISSUE THREAD

**Issue by danieloprado** [Alex-D/Trumbowyg#443]
The event _**tbwchange**_ doesn´t fire while type in a mobile device, only when I click in a button at the toolbar or hit enter.

### Informations

**Browser + version**: Chrome 54.0.2840.85
**OS**: Android 4.4.4 - Xaiomi Redmi 2 

### How to reproduce the bug?
http://codepen.io/danieloprado/details/ObbXdv/
Open this link on mobile

**Comment by Alex-D** [comment]
See #290

**Comment by danieloprado** [comment]
Pull Request #445

**Comment by Alex-D** [comment]
I closed this to keep only one issue, I take a look at your PR ASAP :)
Thanks!
