### ISSUE TITLE
Bold and Italic buttons not highlighted green when active

### ISSUE THREAD

**Issue by haggismcbean** [Alex-D/Trumbowyg#447]
### Informations

**Browser + version**: Chrome 54.0.2840.98
**OS**: OSX 10.11.6

### How to reproduce the bug?

If you change text to bold or italic in the editor, the button does not highlight green. When you change text to underlined, the underlined button highlights green, same with strikethrough. If you then click away and re-highlight the text it's green for underlined and strikethrough, but not for bold or italic. It would be nice to have this consistent. I think this is related to https://github.com/Alex-D/Trumbowyg/issues/12

**Comment by Alex-D** [comment]
I've tested it, strong and emphasis buttons works.

Did you have disable semantic option?

**Comment by Alex-D** [comment]
Inactive.

**Comment by haggismcbean** [comment]
Hi sorry for the late reply.

I've managed to reproduce the bug on https://alex-d.github.io/Trumbowyg/ on my mac in firefox and chrome, see screenshots attached - the first one shows the underline button highlighted white, the second one shows the italic button **not** highlighted white

![screen shot 2016-12-08 at 10 10 52](https://cloud.githubusercontent.com/assets/11638169/21006038/18791b60-bd2f-11e6-86e2-b86d813252e9.png)

![screen shot 2016-12-08 at 10 14 42](https://cloud.githubusercontent.com/assets/11638169/21006065/2d701514-bd2f-11e6-82d2-75a24bcbc6ca.png)

**Comment by Alex-D** [comment]
Ok, so it's tricky ^^"

**Comment by haggismcbean** [comment]
Would you be able to remove the closed tag? I don't seem to have the option.

**Comment by panaak** [comment]
Hi, i just came across this issue. When i disable the semantic option, the highlighting of the pane buttons starts working again. Is this the correct behaviour?

**Comment by Alexander3** [comment]
Actually for me after disabling **semantic** option, flow like  pressing Ctrl+B and typing bold characters started working, but buttons aren't highlighted at all.

**Comment by patrickRocketVisor** [comment]
Highlighting on the buttons depends on the option selected within the toolbar `btns` argument on startup. Since the `semantic` option is on by default, this should be how you define your toolbar to get the buttons to highlight correctly.
```javascript
btns: [
    ['strong', 'em', 'underline'],
]
```

This works because `getTagsRecursive` is looking for the `strong` and `em` tags to match to the button.
