### ISSUE TITLE
$from.nextUntil(...).addBack is not a function(…)

### ISSUE THREAD

**Issue by ZeoNish** [Alex-D/Trumbowyg#450]
WTF? ... 
http://image.prntscr.com/image/d25dfdcf30a841a4a351b72eab86c462.png

thx.

**Comment by Alex-D** [comment]
jQuery version please ?

**Comment by ZeoNish** [comment]
1.7.2

**Comment by Alex-D** [comment]
So you need to upgrade to 1.8+

**Comment by ZeoNish** [comment]
ok 1.9.1 work

ps. Create a new worker demo project. 
ps. ps. NICE EDITOR!

**Comment by Alex-D** [comment]
Doc updated: http://alex-d.github.io/Trumbowyg/
