### ISSUE TITLE
How to use emoji plugin ?

### ISSUE THREAD

**Issue by mtechdev01** [Alex-D/Trumbowyg#451]
Any doc or info to use the emoji plugins?

**Comment by Alex-D** [comment]
That's a plugin by a contributor so I can't write doc for him. Check that: https://github.com/Alex-D/Trumbowyg/issues/323#issuecomment-237235056

**Comment by NicolasPion** [comment]
Hi @mtechdev01 , check this PR : https://github.com/Alex-D/Trumbowyg/pull/464 !

**Comment by Alex-D** [comment]
Merged :)
