### ISSUE TITLE
Can't use emoji scroll bar

### ISSUE THREAD

**Issue by muyiwaoyeniyi** [Alex-D/Trumbowyg#458]
Testing in:
Chrome 54.0.2840 and Latest Firefox
Ubuntu 16.04

Using version 2.3.0 but I replicated this issue in 2.4.2

You can't click on the emoji scroll bar. When you do so, the emoji dropdown goes away. I believe this is happening because the dropdown as a whole has a close on click event attached to it. But that affects the scroll bar. The emojis themselves probably need a container separate from the dropdown container. 

I tried to track down where this is done in you code but I couldn't. If you point me in the right direction, maybe I can fix it. Thanks.

Taiwo

**Comment by NicolasPion** [comment]
This https://github.com/Alex-D/Trumbowyg/pull/459 resolve your isssue

**Comment by Alex-D** [comment]
Merged :) Thanks for report @muyiwaoyeniyi and thanks @NicolasPion for your fix!

**Comment by muyiwaoyeniyi** [comment]
@Alex-D My pleasure.
