### ISSUE TITLE
Override default button groups

### ISSUE THREAD

**Issue by fahmilatib** [Alex-D/Trumbowyg#460]
How to elegantly override default button groups option? Let say I wanna override the `semantic` key to not show the `del` button, what I've tried:

```
var options = {
    btnsGrps: {
        // semantic: ['strong', 'em', 'del']
        semantic: ['strong', 'em']
    }
};
```

However, `del` button will still show up. The only way to overcome this is to explicitly set it to `null` e.g. `semantic: ['strong', 'em', null]`.

Is there any way to do this without doing the `null` thing?

**Comment by Alex-D** [comment]
Create your own group, don't override defaults ;)

**Comment by fahmilatib** [comment]
Ah okay, just wanted to be sure. Thank you.
