### ISSUE TITLE
Initial height option

### ISSUE THREAD

**Issue by istrau3** [Alex-D/Trumbowyg#466]
Is there an option to set the initial height of the editor (in the case of autoGrow)?

**Comment by razzbee** [comment]
I need that too , any solution??

**Comment by Alex-D** [comment]
CSS : min-height :)

**Comment by istrau3** [comment]
@Alex-D I already tried that solution, it does not work in the case of auto grow. Can you reopen this issue?

**Comment by istrau3** [comment]
@Alex-D Any progress on this? Do you want me to submit a PR?

**Comment by Alex-D** [comment]
If you have the fix, make a PR for sure :)

I don't have the time to check the bug, but I can review and merge PRs :)

**Comment by istrau2** [comment]
@Alex-D Ok, I will make an effort to submit one within the next week or so (my users are complaining about this so I am forced to =) )

**Comment by istrau2** [comment]
@Alex-D @razzbee For me, the solution is (as Alex hinted at), to play with these two:

.trumbowyg-box.trumbowyg-editor-visible, .trumbowyg-editor {
  min-height: 150px;
}

**Comment by Alex-D** [comment]
Aaah :)
Thanks for your test/validation !

**Comment by SamGoody** [comment]
Am having this issue still.

My textarea has an initial height of 100px.

Trumbowyg forces it to 300px initially, and doesn't autogrow.

Here is the whole setup
```
<textarea id='trumb' style='height:100px'></textarea>
<script src="//ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="js/vendor/jquery-3.3.1.min.js"><\/script>')</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.21.0/trumbowyg.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.21.0/ui/trumbowyg.min.css">
<script>$('#trum').trumbowyg({tagsToRemove: ['script'], autogrowOnEnter: true});</script>
