### ISSUE TITLE
when i destory the editor, div‘s  height not remove

### ISSUE THREAD

**Issue by zeroone2005** [Alex-D/Trumbowyg#468]
when i destory the editor, div‘s height not remove

<div class="richeidtor"></div>
$('.richeidtor').trumbowyg({
            btns: [['undo', 'redo'],'btnGrp-semantic'],
        });

then
$('.richeidtor').trumbowyg('destroy');  
html:
<div class="richeidtor" style="height:480px"></div>

**Comment by Alex-D** [comment]
#441
