### ISSUE TITLE
trumbowyg('html'); lost content

### ISSUE THREAD

**Issue by zeroone2005** [Alex-D/Trumbowyg#469]
```html
<div id="richEditor">
 <p>1、this is test</p>
 <p>2、this is test</p>
</div>
<button id="btnSave">save</button>
<script>
  $(‘#richEditor’).trumbowyg({
            btns: [['undo', 'redo'],'btnGrp-semantic'],
        });
  $('#btnSave').click(function(){
     console.log( $(‘#richEditor’).trumbowyg('html'));
 })
</script>
```

then i add  content:
`3、this is test`

when i click button #btnSave , i get html :
```html
 <p>1、this is test</p>
 <p>2、this is test</p>
 <p>3</p>
```

**Comment by Alex-D** [comment]
I think your strange character after the "3" make browser crazy.

https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L985

Can you try with another char to check?

**Comment by zeroone2005** [comment]
yes, u right,  strange character after the "3" make browser crazy.
