### ISSUE TITLE
Semantic attribute doesn't turn off in IE11.

### ISSUE THREAD

**Issue by worldofsites** [Alex-D/Trumbowyg#470]
**Browser**: IE 11.0.9600.18537
**Version**: 2.0.0

```
$('.trumbowyg').trumbowyg({
     btns: ["bold", "italic", "underline"],
     autogrow: true,
     removeformatPasted: true,
     semantic: false
});
```

Result text:
`<p><strong>test</strong><em>test</em><u>test</u></p>`

Should be: (as in Chrome)
`<b>test</b><i>test t</i><u>test</u>`

**Comment by Alex-D** [comment]
So, IE11 is semantic by itself ^^ can't change that, sorry :/
