### ISSUE TITLE
[Question] Handle urls that have been pasted ?

### ISSUE THREAD

**Issue by Reekoj** [Alex-D/Trumbowyg#474]
Hello,

that's not really an issue, but more about a feature request. 
Is it possible to create a plugin that converts urls (text that starts with http:// or https://) that the user copy / paste from his browser to clickable links `<a href="..."></a>` ?

If it's doable, that could be great to handle pictures too, when the url ends with ".png" or ".jpg" for example

**Comment by Alex-D** [comment]
For links, it's not possible because it's too complexe.
For images: https://github.com/Alex-D/Trumbowyg/blob/develop/plugins/pasteimage/trumbowyg.pasteimage.js
