### ISSUE TITLE
JS error after closing editor instance

### ISSUE THREAD

**Issue by damogingcidanrana** [Alex-D/Trumbowyg#477]
### Informations

**Browser + version**: Chrome last version
**OS**: Ubuntu
**Resolution**: Maybe, add exception from undefined data in function.

**Text of error**:
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at trumbowyg.js:1514
    at Function.each (jquery.min.js:2)
    at Trumbowyg.updateButtonPaneStatus (trumbowyg.js:1513)
    at trumbowyg.js:595
(anonymous) @ trumbowyg.js:1514
each @ jquery.min.js:2
updateButtonPaneStatus @ trumbowyg.js:1513
(anonymous) @ trumbowyg.js:595

### How to reproduce the bug?

Click on the close button of editor
![trumbowyg by alex-d - google chrome_003](https://cloud.githubusercontent.com/assets/10835343/22177785/4d8a9d04-e036-11e6-873f-934507b921be.png)

**Comment by Alex-D** [comment]
This bug should be fixed in 2.8.0 which will be released soone.
