### ISSUE TITLE
Question about tag stripping behavior...

### ISSUE THREAD

**Issue by Dadsaster** [Alex-D/Trumbowyg#478]
### Information

**Chrome +  55.0.2883.95**
**OS X 10.11.6**

If I type or paste in HTML with tags such as `<html> <body>` or `<div>` they are either stripped out or replaced with `<p>` tags.  Is this intended behavior?  Is there a flag or other undocumented way to prevent this?

**Comment by Alex-D** [comment]
Yep it's the correct behavior. You can try disable it by put `semantic` to `false`, but it could not works since Trumbowyg is based on content editable. So it can be buggy in browser.

**Comment by toreyheinz** [comment]
I had this same question as my `<div>` tags were being converted to `<p>` tags, then removed because it's not semantically correct to wrap a table with a `<p>` tag.

I can understand removing/change most tags, but I really think we should leave `<div>` tags alone. What's unsemantic about them?

**Comment by Alex-D** [comment]
I try to uniformize the tag between browsers. Chrome use `<p>` for paragraph, but IE use `<div>` and that the point. Using div for paragraph makes no sense.

If you don't care about that, disable semantic mode :)

**Comment by toreyheinz** [comment]
Hi @Alex-D, to make it work I did turn off semantic mode, and I agree using a `<div>` for a paragraph doesn't make sense. I am a firm believer in writing semantically correct code.

My understanding is `<div>` tags should have no semantic meaning at all, they are simply a container, so to turn them into a `<p>` changes their meaning.

Overall no big deal, I really like the editor, and I threw you a couple bucks to "motivate you to keep this project going"
