### ISSUE TITLE
`.trumbowyg('html')` not work well while using input methods.

### ISSUE THREAD

**Issue by hsfzxjy** [Alex-D/Trumbowyg#480]
It seems that data cannot be synced in time while using input methods.

**Comment by Alex-D** [comment]
What do you call "input methods"?

**Comment by hsfzxjy** [comment]
Some softwares used to enter non-English characters such as Chinese.

**Comment by Alex-D** [comment]
It should works if you disable `semantic` option.
http://alex-d.github.io/Trumbowyg/documentation.html#semantic

**Comment by hsfzxjy** [comment]
Still not working. It seems that `syncTextarea` cannot be executed in time. I've temporarily solved in a rather hacky way: `$('textarea').data('trumbowyg').$ed.html()`

**Comment by Alex-D** [comment]
Seems fixed since.
