### ISSUE TITLE
Default text should be a paragraph

### ISSUE THREAD

**Issue by ramezrafla** [Alex-D/Trumbowyg#482]
### Information

**Browser + version**: All
**OS**: All
**Resolution**: All

### How to reproduce the bug?

Start new instance of Trumboyg in a blank div, then start typing. The text node is not wrapped (i.e. its parent is the Trumboyg editor div). If it's not a heading, it should revert to a &lt;p> automatically. I don't mind helping with this, if you are interested. Guidance would be appreciated on where to start. Thanks

**Comment by Alex-D** [comment]
The <p> tag is added on next ENTER.

**Comment by dpazuic** [comment]
I agree. On focus of the editor, whatever is typed should automatically be wrapped by default as a `<p>`.  We would be remiss to expect users to press enter once within the editor in order for their content to be truly wrapped in wysiwyg goodness.

**Comment by ptisdel** [comment]
The <p> tag is not added to the first paragraph on next ENTER; this should be reopened.

**Comment by marvc1** [comment]
![trumbo paragraph bug](https://user-images.githubusercontent.com/2427797/36299344-745bb0e8-12f4-11e8-987d-8ebc14b18278.gif)

**Comment by marvc1** [comment]
This can be worked around, by always giving Trumbo some default content:

`
$textarea.trumbowyg("html", myHtml || "<p></p>")
`

**Comment by Geniekort** [comment]
@marvc1 that will fill the editor with a paragraph tag indeed, however the cursor will still be positioned before the `p` tag, so when you start typing aaa, the value will be `aaa<p></p>`. Any suggestions on how to move the cursor to within the tag?

**Comment by marvc1** [comment]
@Geniekort unfortunately not... overall it's a great lightweight editor, but we moved away from it because of formatting issues like this.

**Comment by Geniekort** [comment]
@marvc1 sad to hear. To what editor did you move?

Btw. I found a solution by doing this: https://github.com/Alex-D/Trumbowyg/pull/688#issuecomment-417820741

**Comment by Alex-D** [comment]
Trumbowyg now has a `<p>` at init :)

So you do not need to hack it anymore.

**Comment by Geniekort** [comment]
Ah that's nice @Alex-D , from which version?

**Comment by Alex-D** [comment]
The last one: 2.20.0, check the changelog: https://github.com/Alex-D/Trumbowyg/releases/tag/v2.20.0
