### ISSUE TITLE
An (un)ordered list shouldn't be wrapped inside a paragraph

### ISSUE THREAD

**Issue by davidkmenta** [Alex-D/Trumbowyg#484]
### Informations

**Browser + version**: Chrome 55.0.2883.95 (64-bit)
**OS**: OS X 10.10.5
**Resolution**: 1440x900
But I think it's independent...

### How to reproduce the bug?
Create (un)ordered list after paragraph.

An (un)ordered list shouldn't be wrapped inside a paragraph: http://stackoverflow.com/a/5681796/4520643

**Comment by Alex-D** [comment]
Sorry, but I don't want to fix that.

**Comment by danreg** [comment]
This is really bad, because server side components like HTMLAgilityPack will throw a parsing error. Please consider to change this and make it w3c conform.

**Comment by Alex-D** [comment]
I can't, it's a browser-level bug, I will do my best to fix that in v3, in few months.
