### ISSUE TITLE
em tag is added outside the <i> tag upon clicking "View HTML" button. 

### ISSUE THREAD

**Issue by kxxe93** [Alex-D/Trumbowyg#487]
### Informations

**Browser + version**: Chrome Version 55.0.2883.87
**OS**: Ubuntu 16.04
**Resolution**:1920 x 1080

### How to reproduce the bug?
Enter a html markup using trumbowyg editor: 
```html
<h3 class="ui blue header"><i class="small info circle icon"></i>Information</h3>
```

Toggle "View HTML" button. When checking the html again, the markup turns into this: 
```html
<h3 class="ui blue header"><em><em><i class="small info circle icon"></i></em></em>Information</h3>
```

And, the more I toggle the "View HTML" button, the more <em> tag will be added.

**Comment by Alex-D** [comment]
You should disable semantic mode if you use `<i>` tag
