### ISSUE TITLE
Option to enable/disable automatic <p> tags

### ISSUE THREAD

**Issue by brainfoolong** [Alex-D/Trumbowyg#488]
Hi!

If i don't want to wrap every text in a `<p>` tag, i currently have no option to make this possible.
So, i need to reverse case, adding `<p>` tags only when i decide to do so.
Otherwise, in a plain, multiline text, there should only be `<br/>` tags.

I think about an option on initialization, something like tinymce does http://archive.tinymce.com/wiki.php/Configuration3x:forced_root_block

Possible or someone agree with me?

Greetz

**Comment by brainfoolong** [comment]
Anyway, i've create a pull request for just disable automatic `<p>` tags. https://github.com/Alex-D/Trumbowyg/pull/489

**Comment by Mohamm6d** [comment]
There is no way for this. Just make sure you delete all P tags when they are saving
