### ISSUE TITLE
Disable tab event

### ISSUE THREAD

**Issue by J2BB** [Alex-D/Trumbowyg#494]
Hi,

Is there a way to handle the action when the focus point on a trumbowyg textarea and the tabulation keyboard button is pressed ?

First, I would like to disable the tabulation.
Then, if it is possible, I would like to call a customized plugin function when I press the tab button.

Does somebody has any idea to that ?

Thanks,

**Comment by patrickRocketVisor** [comment]
The easiest way to get this to work is to add a keyevent listener to the Trumbowyg editor you define.

```javascript
$('#my-editor').trumbowyg({
	// trumbowyg definition here
}).on('keydown keypress', function trumbowygKeydownKeypressEvent(event){
	if (event.keyCode === 9) { // tab key
		event.preventDefault(); // prevent the tab key event from bubbling up
		if(event.shiftKey){
			// Call plugin function for the 'outdent' key here
		}
		else{
			// Call plugin function for the 'indent' key here
		}
	}
});
```

Having the ```event.preventDefault();``` will disable the default action of leaving the textarea. Then all you have to do is detect if the keystroke was a tab or shift+tab (indent/outdent) and call your plugin function.
