### ISSUE TITLE
Get caret postion for multiple line text

### ISSUE THREAD

**Issue by JohnHZheng** [Alex-D/Trumbowyg#495]
I have special need to insert text template at cursor position. So I hook up tbwblur event as below to remember the cursor position (this is in IE 11): 

```js
.on('tbwblur', function () {
		        // Remember the cursor position
			    $(ed).trumbowyg('saveRange');
			    var range = $(ed).trumbowyg('getRange');
                if(range)
                    cursorPosition = range.startOffset;
```

This work well when I have only one line of text. The saved position can be used later when I invoke a method to insert the text. 
However, if I have multiple lines, and the cursor is at lines other than first line. The range.startOffset gives the offset of current row. Example below

```
Line 1
Line <Cursor here>2
```

I expect to get 11, but it gives me 5. It seems to be a common problem with multiple line text area. I see there are function allow to get caret position on text area. But I cannot get text area from trumboWyg. 
Currently trumboWyg is put in a simple html page. I tried to bind(this), access ._ta, etc. Nothing is working

Any suggestions? Thank you!

**Comment by Alex-D** [comment]
Idk how you get two lines in same block. Default Trumbowyg behaviour is to have 2 paragraphs, so you can't have multiple lines in one block.

**Comment by JohnHZheng** [comment]
You hit enter to get multiple lines. The html is something like <p>Line 1</p><p>Line 2</p>
