### ISSUE TITLE
Set text align problematically 

### ISSUE THREAD

**Issue by AfarsheziF** [Alex-D/Trumbowyg#501]
Is it possible to programmatically set the editor to a specific Text align?

**Comment by Alex-D** [comment]
What's your goal?

**Comment by AfarsheziF** [comment]
Hi Alex. Thank you for answering :)

Seems that the editor is center aligned by default, i will like to change it to be **left - aligned**. My goal is to ensure that the user inputs text while it's already left aligned.
In some cases the editor load a text from sorce, that should be also left aligned.

**Comment by Alex-D** [comment]
Trumbowyg use your CSS. If you want the text left-aligned by default, you just have to wrap it with: 

```css
.your-wrapper {
    text-align: left;
}
```
