### ISSUE TITLE
Editor create new line for each character

### ISSUE THREAD

**Issue by jeffreybasurto** [Alex-D/Trumbowyg#502]
### Informations

if you create new lines with enter a few times, then position cursor back somewhere in those newly created lines, typing without hitting enter or breaking manually again will put characters 1 per line.

Behavior is observable on example page.

**Browser + version**:  Chrome Version 56.0.2924.87
**OS**:  Windows 10
**Resolution**:  everywhere

![screenshot_022417_051824_am](https://cloud.githubusercontent.com/assets/300655/23279548/a9e647ae-fa50-11e6-8c77-7ed4fbe97279.jpg)

**Comment by pypetey** [comment]
I had the same - it happened for me with bootstrap 4 alpha 6.
Browser - Firefox

**Comment by Alex-D** [comment]
While this bug is not fixed, you can rollback to the previous release: 2.4.4

**Comment by Alex-D** [comment]
I've published the v2.5.1 that fix this bug and others bugs due to composition support.
