### ISSUE TITLE
Simple Plugin Example

### ISSUE THREAD

**Issue by camdagr8** [Alex-D/Trumbowyg#503]
Dude, the documentation for creating a plugin and/or a new button is lacking. I looked at the example plugins and I'm even more confused than before I started this quest. 

Maybe a simple (and I stress the word SIMPLE) hello world plugin would be more useful. 

Anyways......

I'm trying to produce a plugin that adds a button to the buttons pane and injects some text into the editor. 

Can you point me in the right direction or even better, create a SIMPLE well documented example?

**Comment by artus9033** [comment]
Any progress with the documentation...?

**Comment by Alex-D** [comment]
Hi!

You right... I need to take some time to work on documentation, I will do that ASAP, I put that on my TODO :)

**Comment by camdagr8** [comment]
As a follow up to this.. I did however figure out how to create a plugin.

**Comment by nilsi** [comment]
@camdagr8 if you created a "hello world" plugin it would be awesome if you would submit it. Thanks.

**Comment by Alex-D** [comment]
Added into the 2.8.0 doc which will be released soon.

**Comment by camdagr8** [comment]
Awesome.. Thanks!
