### ISSUE TITLE
Problem on Firefox browser

### ISSUE THREAD

**Issue by gsin11** [Alex-D/Trumbowyg#504]
Before report an issue, be sure to put these informations. Thanks :)

### When you launch editor on firefox it behaves wired.

**Firefox + 51.0.1 (64-bit)**:
**MAC Sierra 10.12**:

### How to reproduce the bug?
<img width="1036" alt="image" src="https://cloud.githubusercontent.com/assets/3865313/23308237/cb44e4c8-faaa-11e6-85b2-9f508b950c34.png">

**Comment by Alex-D** [comment]
See #502
