### ISSUE TITLE
Edge - Typing always creates new line 

### ISSUE THREAD

**Issue by lukepolo** [Alex-D/Trumbowyg#505]
Before report an issue, be sure to put these informations. Thanks :)

### Informations

**Browser + version**:
Edge : 20.102240.16384.0
**OS**:
Windows 10 Pro
**Resolution**:
1920x1080

### How to reproduce the bug?
Just start typing on your homepage 

![feb-24-2017 10-33-49](https://cloud.githubusercontent.com/assets/2066668/23309648/85840b30-fa7d-11e6-8572-fb7b4225b59c.gif)

**Comment by Alex-D** [comment]
See #502
