### ISSUE TITLE
How to create a Custom button

### ISSUE THREAD

**Issue by rogervila** [Alex-D/Trumbowyg#511]
**Browser + version**: any, latest
**OS**: any
**Resolution**: any

Hello, I want to add my own button, that adds some html content. 

I can't find it on the documentation. Is it a feature yet? If not, I'd like to work on a PR.

Thank you.

**Comment by quvion** [comment]
I think you have to write a plugin.

**Comment by Alex-D** [comment]
Hello!

You should create a new plugin, check existant plugins to see how to do :)

**Comment by Alex-D** [comment]
Check new doc :)
