### ISSUE TITLE
Semantic html and unproper styles

### ISSUE THREAD

**Issue by MusicalEcho** [Alex-D/Trumbowyg#512]
Hi there!
I use this plugin for editing email that will be send to users. Problem is with incorrect tags nesting like this:
```html
<p style="text-align: right;">
  <ol>
    <li>lorem<br></li>
    <li>ipsum</li>
    <li><br></li>
  </ol>
</p>
```

It's not semantic, right? Besides, "text-align: right'; for li element is very ugly (that's why for `<li>` I replace it with regexp, but it`s not the option because of active button highligting).
How I see it, I should be able to do one of things:

1. set some option, which I didn`t find
2. handle events on buttons before action and simply prevent it
3. other stuff

Will be thankfull for your advice in this case

**Comment by Alex-D** [comment]
Hi!

What did you expect as output?

For me it's OK, just the `<br/>` are useless, but it's OK.

**Comment by MusicalEcho** [comment]
According to spec, we can`t put ul/ol inside p. (http://stackoverflow.com/a/5681796/7398441)
So when I click to list button, I expect, that empty `<p>` will be removed, also that `<br>` won`t be alone inside `<li>`. At least,it will be great the `$('#editor').trumbowyg('html'); ` to return semantic code. Is it possible?

**Comment by Alex-D** [comment]
It's hard and heavy to do.
I do not have the time to do that for now :/

**Comment by MusicalEcho** [comment]
Sad to read

**Comment by edwinveldhuizen** [comment]
Also getting different results in Chrome:
<img width="390" alt="screen shot 2018-02-06 at 17 55 03" src="https://user-images.githubusercontent.com/1787915/35872553-6a83a362-0b67-11e8-8995-361e43bb007d.png">
Versus firefox:
<img width="230" alt="screen shot 2018-02-06 at 17 55 22" src="https://user-images.githubusercontent.com/1787915/35872567-72a67cae-0b67-11e8-80cf-449f92c4c982.png">

Seems the library really needs do more thorough code-cleanup

**Comment by Alex-D** [comment]
Due to `contenteditable` different behaviours.

If you want a perfect markup, do not use Trumbowyg. Check some bigger projects like CKEditor or TinyMCE (which is not so tiny, ahah). But it will cost you at least 100+kB.

I think one day I will restart a new WYSIWYG based on shadow DOM in vanilla and without any framework to be portable. But it's hard to keep it light with that in mind...
