### ISSUE TITLE
H4 tag issue

### ISSUE THREAD

**Issue by Hardcorewithin** [Alex-D/Trumbowyg#514]
### Informations

Firefox 52.0, Chrome Version 56.0.2924.87 (64-bit), IE 11
Windows 7 Enterprise 64-bit
Resolution : 1680x1050

### How to reproduce the bug?
Mark a text with the H4 tag, the text won't be displayed as an h4
This only occurs with the h4 tag (h1-h6 is fine)
![h4_issue](https://cloud.githubusercontent.com/assets/17457746/23699056/b7edba46-03e5-11e7-92bd-c4689d9cb9f1.png)
![h4_issue_html](https://cloud.githubusercontent.com/assets/17457746/23699080/c8c78720-03e5-11e7-9c6f-2ed8efd74604.png)

Thanks!

**Comment by Alex-D** [comment]
That's just my style on demo page, and I want a bigger H4 that H3, That's it :)
