### ISSUE TITLE
How to handle image upload description in php

### ISSUE THREAD

**Issue by vinodrightpath** [Alex-D/Trumbowyg#515]
Before report an issue, be sure to put these informations. Thanks :)

### Informations

**Browser + version**:
**OS**:
**Resolution**:

**Comment by Alex-D** [comment]
Upload plugin can't do that as is.

**Comment by vinodrightpath** [comment]
how can i get image description

**Comment by lmleon19** [comment]
el problema es que el json de respuesta tiene que ser:

`{
    success: true,
    data{
           file: 'https://example.com/myimage.jpg'
    }
    
}`
