### ISSUE TITLE
Table plugin broken

### ISSUE THREAD

**Issue by Grawl** [Alex-D/Trumbowyg#518]
### Informations

**Browser + version**: Chrome 56
**OS**: macOS Sierra
**Resolution**: 1920x1080

### How to reproduce the bug?

1. Get Trumbowyg 2.5.1

2. Add Table plugin:

```js
require('trumbowyg')
require('trumbowyg/dist/plugins/table/trumbowyg.table')
$('.textarea').trumbowyg({
  btns: [
    …
    'table',
    …
  ],
})
```

3. Try to add a table inside Trumbowyg.

Nothing inserted.

If I select some text this second `<p>` for example:

```html
<p>zxc</p><p>asf</p><p>asd</p>
```

and then click on table button and choose some rows, cols and table CSS class, it removes this text and adds some strange instead:

```html
<p>zxc</p><table class="asf"><tbody><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr></tbody></table><p>asd</p>
```

But nothing visible in WYSIWYG.

**Comment by Alex-D** [comment]
I'm not the author of the Table plugin, so Idk how it works (or not, in this case).

**Comment by Danbardo** [comment]
Did you ever get this working?

**Comment by ChrisRomp** [comment]
You can also set your stylesheet to include a border on the table <td> elements within the editor, e.g.: 

```
.trumbowyg-editor table td {
    border: 1px dotted black;
    min-width: 10px;
}
```

**Comment by forelabs** [comment]
@Alex-D I guess this one can be closed
