### ISSUE TITLE
Is it possible to use jquery autocomplete?

### ISSUE THREAD

**Issue by MerzGH** [Alex-D/Trumbowyg#519]
I have tried with the tbwchange event but it didn't work.

**Comment by Alex-D** [comment]
Idk. I think it's possible but I don't have the time to investigate :/

**Comment by MerzGH** [comment]
It works if I am in viewHTML mode. I am trying now to find out how the entered data (preview) can be passed to the textarea.

**Comment by Alex-D** [comment]
Check if the plugin is content-editable compatible.

**Comment by CristhianUNSa** [comment]
It is posible. I use a combination with jQuery mentions plugin [https://github.com/ivirabyan/jquery-mentions](link). Is a fork, but works really well for me for mentioning people with '@' just as an example
