### ISSUE TITLE
 I discovered a weird bug in Internet Explorer 11. I thought it was a bug in my project, so I tested it on the demo-page of Trumbowyg, and got the same result.When text is selected from the beginning, cannot use the vertical scroll bar

### ISSUE THREAD

**Issue by pr14anka25** [Alex-D/Trumbowyg#522]
Before report an issue, be sure to put these informations. Thanks :)

How to reproduce the bug?
1.If you write the long passage on editor so that vertical scrollbar will occur .
2. select the text and make your scrollbar is also in the range of selected text 
3. when you scroll down in between this paste the text

# Informations

Browser: IE11
OS: Windows 8

**Comment by Alex-D** [comment]
So it's a IE11 bug. I can't fix it.

Please, next time you create an issue on GitHub, make your title smaller and put details into the message.
