### ISSUE TITLE
background-color: initial span added to joined paragraphs

### ISSUE THREAD

**Issue by gavindphillips** [Alex-D/Trumbowyg#523]
Before report an issue, be sure to put these informations. Thanks :)

### Informations

**Browser + version**: Chrome 56.0.2924.87
**OS**: macOS Sierra 
**Resolution**: 2560 x 1440

### How to reproduce the bug?

Firstly, thanks for Trumbowyg, excellent piece of work.

I'm not sure if the issue I've noticed is anything to do with Trumbowyg as I can't find any reference to it in the source. 

When you delete a line between two paragraphs the second paragraph is wrapped with `<span style="background-color: initial;"></span>`

Any subsequent paragraph is then also wrapped in this span.

If you highlight the paragraph and click the remove format button the span is removed, the p tag remains. Incidentally the remove format button doesn't seem to work on other tags.

Here are the options it's loading with

```
 $(function() {
     $('#body').trumbowyg(
     	{ 
     		svgPath: '/vendor/trumbowyg/icons/trumbowygicons.svg',
     		semantic: false,
     		resetCss: true,
     		removeformatPasted: true
     	}
     );
});
```

This is version: "2.5.1" bundled by webpack.

Cheers

**Comment by gavindphillips** [comment]
Been looking into this. Ignore the comment about the remove format button not working, it's fine.

This issue only seems to affect Chrome. It also only seems to happen when resetCSS is true.

I can't make the connection between the reset css styles and what's being inserted 

`<span style="background-color: initial;"></span>`

Hit a brick wall there I'm afraid.

**Comment by Alex-D** [comment]
Can't reproduce :/

**Comment by scabros** [comment]
it's happening to me also

chrome: Versión 69.0.3497.32 (Build oficial) beta (64 bits) in windows 7
Trumbowyg-2.10.0

the only strange setting active is, also, resetCss: true.

it produces this html:


`<div class="entry-content">
      mmm, raro todo esto...<br><br><p>-<span style="background-color: initial;">-</span></p><p>
Roberto Scattini<br>
Sistemas - DGTALPG</p>    </div>`


original text included a "signature" like this:
`--<br />Roberto Scattini<br />Sistemas - DGTALPG`

**Comment by Alex-D** [comment]
So, I should remove this option...
