### ISSUE TITLE
Formatting buttons have no effect unless text is selected

### ISSUE THREAD

**Issue by adamvleggett** [Alex-D/Trumbowyg#524]
Before report an issue, be sure to put these informations. Thanks :)

### Informations

Chrome 56.0.2924.87
Windows 7
1920x1080

### How to reproduce the bug?

On the github.io demo page, start typing and press the bold, italic, or underline buttons without any text selected. They have no effect. Also, Ctrl+B etc also have no effect.

**Comment by Alex-D** [comment]
Know issue, won't fix.

**Comment by adamvleggett** [comment]
Please reconsider. This makes or breaks the decision to use this product, not just for me but probably also for others.

**Comment by Alex-D** [comment]
I don't have the time to work on Trumbowyg.

**Comment by adamvleggett** [comment]
Ok. I may do this myself on a fork. If so I will let you know.

**Comment by Alex-D** [comment]
You can make a PR, I check and merge PR. But I don't have the time to search and debug myselft :)

**Comment by julianlam** [comment]
@adamvleggett Did you have any luck fixing this? I echo your sentiment that this is a make-or-break bug because of the expectation that if you hit bold... it should... you know... bold. Even if no text is selected.

If the issue has not been fixed via a fork... @Alex-D, would you be open to being sponsored to resolve this bug?

**Comment by Alex-D** [comment]
Nope. I did not have the time to investigate on that.

I can fix it in a v3 but it should be a complete rewrite of the plugin, without jQuery, based on virtual DOM, etc. But I did not have the time for now. I have a plain time job and an another side project called [Colllect](http://getcollect.io).

**Comment by gomonkey** [comment]
Still same bug. Someone solved?

**Comment by oza75** [comment]
Does someone found a solution to work around this ?
