### ISSUE TITLE
Full-Screen Detection

### ISSUE THREAD

**Issue by Platips** [Alex-D/Trumbowyg#527]
Hi all...

How I can use similar with this (un-working) code :
`$(".trumbowyg-fullscreen-button").on("click",function(){alert("This Clicked");});`

"or" if we can detect any Full-Screen like this :
`$("#Trumbowyg-Editor").on("trumbowyg-fullscreen", function(){alert("This is Full-Screen Dude!")});`

any help..?

Thanks

**Comment by Alex-D** [comment]
Read the doc :)
http://alex-d.github.io/Trumbowyg/documentation.html#events

You've got 2 events: `tbwopenfullscreen` and `tbwclosefullscreen`

```js
$('#editor').on('tbwopenfullscreen', function(){ console.log('Open fullscreen!'); })
```
