### ISSUE TITLE
question: Pasting custom code outside of <p> tag

### ISSUE THREAD

**Issue by Mehrdad-Davoudi** [Alex-D/Trumbowyg#529]
Hi
Is there any way to paste custom code like: "[gallery: 11]" ?
I'm using Trumbowyg in my CMS to replace "[gallery: 11]" with my html code before display in page.
Is there anyway to insert Custom code by jquery?

any help..?

Thanks

**Comment by Alex-D** [comment]
I don't think so, sorry :/

I do not have handle this case, maybe in v3 ^^'
