### ISSUE TITLE
Allow setting only a couple formatting options

### ISSUE THREAD

**Issue by lstrzebinczyk** [Alex-D/Trumbowyg#53]
Right now formatting options allows to use p, blockquote, h1, h2, h3 and h4. It would be beneficial for me to only allow using p and h1. 

Is such change possible?

**Comment by abdallahmaali** [comment]
how i can  custom list style   
could u help me

**Comment by Alex-D** [comment]
I thinks your problem is different from the original post. I invite you to create a new issue. Then, I don't know what you mean.
