### ISSUE TITLE
Is it possible to undo <blockquote> 

### ISSUE THREAD

**Issue by koh0727** [Alex-D/Trumbowyg#532]

**Comment by koh0727** [comment]
Is it possible to undo <blockquote>

**Comment by Alex-D** [comment]
It should be possible

**Comment by koh0727** [comment]
Thank you for your reply.

Is it possible to make blockquote-tag undo by second click.

**Comment by bootscafe** [comment]
I've got a same situation.
I tried to erase blockquote style on this editor but doesn't work.
Do you have an option to do this?

**Comment by Alex-D** [comment]
Nope :/

**Comment by Faks** [comment]
inserting line break works,because it inserts next item with p tag

**Comment by Faks** [comment]
here is example ` <p><hr></p><blockquote>asdasdad</blockquote><blockquote><br></blockquote><blockquote><hr>sadasd</blockquote><blockquote><br></blockquote><blockquote>sad</blockquote><p><hr>asdasdasd</p>
        `

**Comment by Chickenbreadlp** [comment]
I don't know, if it's in any way related, but I can't disable the deleted tag. Even for text, where I just added the tag. and unlike the quote, I can't disable it by selecting paragraph

**Comment by abrambailey** [comment]
Same issue.

**Comment by abrambailey** [comment]
Actually, I can't even remove a blockquote using the remove formatting button. I promise to buy you some beers if you can make this work :)

**Comment by abrambailey** [comment]
It seems like the remove styling button doesn't work on the demo either https://alex-d.github.io/Trumbowyg/demos/

**Comment by abrambailey** [comment]
Any updates on this?

**Comment by Alex-D** [comment]
With more details: it's a contenteditable browser-level bug. So I can't make it work without adding tons of code. Solution can be to code it as a plugin, or wait some months for v3: #875
