### ISSUE TITLE
Image upload : sanitize filename ?

### ISSUE THREAD

**Issue by Ydalb** [Alex-D/Trumbowyg#533]
### Informations

**Browser + version**: Chrome & Safari, latest version
**OS**: MacOS Sierra
**Resolution**: Retina screen (13")

When you upload a file with some special characters, the picture doesn't not show up in Safari, but it works in Chrome.

Is there a way to sanitize filename before sending file to the server ?

### How to reproduce the bug?
Upload a picture named "Capture d’écran 2017-04-10 à 15.42.37.png", and it will work on Chrome, but not on Safari.

**Comment by Alex-D** [comment]
You should do that server side.

**Comment by Ydalb** [comment]
Hm, but what if I'm directly uploading to S3 or another object storage service ? I don't have access to the server side part, and can't implement a sanitize script.

Can't we setup a hook or something in the plugin to rename the file ?

**Comment by Alex-D** [comment]
You should make a proxy. Never trust client.
