### ISSUE TITLE
Official Safari support status?

### ISSUE THREAD

**Issue by jpodwys** [Alex-D/Trumbowyg#536]
I'm trying to choose an editor. On trumbo's github.io page, it says:

> Compatible with all recents browsers like IE9+, Chrome, Opera and Firefox.

I'm just curious if trumbo also officially supports Safari.

Thank you!

**Comment by Alex-D** [comment]
I don't have Mac so I can't test it. Safari is on WebKit... Chrome and Opera are now Blink + V8

**Comment by jpodwys** [comment]
OK thank you for the fast response.
