### ISSUE TITLE
Creating a @-username/mention plugin

### ISSUE THREAD

**Issue by vannut** [Alex-D/Trumbowyg#537]
I really love the basic- and lightweightness of Trumbowyg! I now found myself in the place I want to extend the basic functionality of Trumbowyg.

For a project I need to be able to '@-mention' a username in the textfield. Just like here on GitHub.
The list of users should be looked up by means of an Ajax request.

But I can't find any documentation on the different parts of the plugin. E.g. for my use case I need to somehow 'listen' to the typed characters, and asses them for an @-sign.

I found this ['basic' setup](https://github.com/Alex-D/Trumbowyg/issues/288#issuecomment-244157182), but was wondering if someone could point me in the right direction. Or even built a similar plugin.

The backend looks at the whole message, and finds `@xyz` and matches them with the database. So the plugin merely is needed to insert 'valid' `@names`.

**Comment by Globulopolis** [comment]
@vannut im' not sure about how to implement this, but basic steps look like:
Check pressed key code for `@` && check if editor in focus
when run request
on success, bind event on menu click and paste text in editor.

**Comment by vannut** [comment]
That's also the 'structure' I want to achieve, but I can't find _where_ in the plugin file I should register the event etc

**Comment by Globulopolis** [comment]
@vannut editor should support(but not supported) binding custom event or native JS events.

**Comment by vannut** [comment]
Ah ok. Then ill just ga for a native solution instead of a binding to the trumbowyg editor
