### ISSUE TITLE
Question : be able to switch to wysiwyg mode

### ISSUE THREAD

**Issue by aimansawan** [Alex-D/Trumbowyg#539]
Hello,
I am using the editor, among other info, in a wizard like form (edit, validate, submit). I need the editor to be in wysiwyg mode when leaving the edit mode. I did a hack locally that works by exposing the toggle action :
```
if (this._msgEditor.closest('.trumbowyg-box').hasClass('trumbowyg-editor-hidden')) {
  this._msgEditor.trumbowyg('toggle');
}
```
Is there a nicer way to accomplish this?
if not, are you interested that I make a pull request?

Thanks for the nice work :+1:

**Comment by Alex-D** [comment]
You can make a PR yep :)
It's juste an entry in this switch: https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L83
