### ISSUE TITLE
How to add line breaks instead of paragraphs while entering return?

### ISSUE THREAD

**Issue by debiprasad** [Alex-D/Trumbowyg#541]
This is not a bug report, but a question. When someone hits return, it creates a new paragraph. When the user hits Ctrl+Enter, it creates a line break. Is there any option, which will help it to create new line (`<br>`) instead of a paragraph (`<p>`)?

**Comment by Alex-D** [comment]
You can't actually, sorry :/

**Comment by jitbit** [comment]
Too bad, makes it impossible to use this editor with existing HTML code that has `<BR>` tags, editing those breaks things.

**Comment by webarthur** [comment]
+1

**Comment by jotajotaramos** [comment]
Hello everbody:

any updates on this? Is it possible to do it with the actual version?

Thanks.

**Comment by syfer-darknight** [comment]
if anyone's still interested in this above, one way to simulate a line break in the editor is to change

`.wrapAll('<p/>')`
to
`.wrapAll('<p style="margin:0; padding:0;"/>')`

So now every time a user presses enter or return, the paragraph has a zero margin and padding.

**Comment by smalos** [comment]
This will create <br> instead of <p> tags:

`    var input = document.getElementById("your_trumbowyg_id");
    input.addEventListener("keypress", function(event) {
        if (event.keyCode === 13) {
            event.preventDefault()
            document.execCommand('insertLineBreak')
        }
    });
`

**Comment by syfer-darknight** [comment]
> document.execCommand()

The support is pretty good for this but its obsolete. Might be good to use something different/recent for this. (sorry not being an ###)

**Comment by smalos** [comment]
The problem with my code is also that when you are at the very bottom of the editor and press enter, the scrollbar does not scroll down.

**Comment by juspriet** [comment]
> The problem with my code is also that when you are at the very bottom of the editor and press enter, the scrollbar does not scroll down.
> 
> After hours of trial and error without success, I felt forced to switch to another editor where everything works out of the box.



To solve this problem :

  var input = document.getElementById("publication_description");
    input.addEventListener("keypress", function(event) {
        if (event.keyCode === 13) {
            event.preventDefault()
            document.execCommand('insertLineBreak');
            document.execCommand('insertText', '');
        }
    });

**Comment by mkrecek234** [comment]
I would love to have this option as well - why? I often type bullet lists and want to force a line-break inside the bullet and not create a new bullet paragraph. So Trumbowyg would need to distinguish between normale "Enter" press and e.g. "Shift-Enter" which then would insert a <br> and not a <p>.

- Item1 kjdfglkjdfg
asfdasdfsadfasdf

- Item 2l sdlfgjk dslfgj dsfg
Second line

- Item 3
Second line

@Alex-D Any chance to implement this?
