### ISSUE TITLE
<strike> is obsolete since HTML 5. <s> should be used.

### ISSUE THREAD

**Issue by bernardobelchior** [Alex-D/Trumbowyg#544]
### Informations

**Browser + version**: Google Chrome Version 57.0.2987.133 (64-bit)
**OS**: Arch Linux x86_64 Kernel: 4.10.9-1-ARCH
**Resolution**: 1920x1080

### How to reproduce the bug?

1. Create the trumbowyg text editor, with default options
2. Write some text
3. Select the text
4. Click the strikethrough button

The [`<strike>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strike) tag is deprecated in HTML4 and obsolete in HTML5. The [`<s>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/s) tag is its replacement in the current HTML standard. 

Trumbowyg is marketed, in its homepage, as: 

> Editor and generated code are optimized for HTML5 support.

As such, I think it should update its code to match the HTML5 standard.

**Comment by Alex-D** [comment]
With defaults, you should have semantic to true, so you should not have a strike but a del button :/

A line is missing here: https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L1041

`t.semanticTag('strike', 'del');` idk why.

**Comment by Alex-D** [comment]
Must be fixed in 2.8.0 soon :)
