### ISSUE TITLE
SVG not loading when using a prefix

### ISSUE THREAD

**Issue by JaKhris** [Alex-D/Trumbowyg#545]
Hey there,

I'm having issues displaying SVGs using Trumbowyg with a custom prefix, here's what's going on:

I first call the JS et CSS files needed, then I call the SVG path:
```$.trumbowyg.svgPath = '../img/trumbowyg/icons.svg';```

After that, I instantiate Trumbowyg:
```
$('textarea').trumbowyg({
    prefix: 'custom-prefix-'
});
```
Now, what happens is that Trumbowyg goes looking for the SVGs at the path I indicated, but then tries to call the various ```<symbol>```s using the SVG's ID with the prefix, but it doesn't have a prefix as the SVG is named ```trumbowyg-SYMBOL``` and not ```CUSTOMPREFIX-SYMBOL```.

To fix this, I've had to make changes in the code of ```trumbowyg.js```. I've added a variable called ```svgPrefix``` which is defined inside ```buildBtn: function (btnName)``` (line 718) and ```buildSubBtn: function (btnName)``` (line 777), containing the default prefix option, as such: ```svgPrefix = 'trumbowyg-',``` which is used in the changed code below:

729/730:
```
html: t.hasSvg && hasIcon ?
  '<svg><use xlink:href="' + t.svgPath + '#' + svgPrefix + (btn.ico || btnName).replace(/([A-Z]+)/g, '-$1').toLowerCase() + '"/></svg>' :
```

795:
```
html: t.hasSvg && hasIcon ? '<svg><use xlink:href="' + t.svgPath + '#' + svgPrefix + (btn.ico || btnName).replace(/([A-Z]+)/g, '-$1').toLowerCase() + '"/></svg>' + (btn.text || btn.title || t.lang[btnName] || btnName) : (btn.text || btn.title || t.lang[btnName] || btnName),
```

Now, this might be me doing something wrong, but it's the only way I found to make the SVG show up again. If this happens for others, should this be fixed in the next update of Trumbowyg?

Thanks for reading!

Take care,
Chris

**Comment by Alex-D** [comment]
Change prefix is usefull when you want use different or multiple "skins" on Trumbowyg.
As you can have different icons on different skins, you should rewrite SVG with your own prefix if you want keep the same icons.

**Comment by JaKhris** [comment]
Hey Alex,

Thank you for your quick response. I prefer having the same icons overall, and then style them differently using the fill CSS property, but if one does need alternate icons, I suppose that makes more sense. Thus, making my post a non-issue!

Thanks!
