### ISSUE TITLE
Emoji plugin with custom images (contains fix for default list showing up in custom list)

### ISSUE THREAD

**Issue by chriskirknielsen** [Alex-D/Trumbowyg#547]
Hello there,
While working on my project, I sought to add some custom emoji to the editor. Currently, it uses the emojify.js list, I presume? In an effort to improve this, I have changed the code so that you can now specify an array instead of a single emoji code, along with a fix I'll detail below.

### Customisation
I customised the code so that one can specify the custom images for the emoji in an array when instantiating Trumbowyg, like so:
```javascript
$('textarea').trumbowyg({
    btns: [
        ['emoji']
    ],
    plugins: {
        emoji: {
            emojiList: [
                [':)', '../img/smileys/smile.png'],
                [':D', '../img/smileys/smile-big.png'],
                [':^^:', '../img/smileys/hehe.png'],
                [':happy:', '../img/smileys/happy.png']
            ]
        }
    }
});
```

And the changes in ```trumbowyg.emoji.js``` are as follows, replacing the block from line 925 to 936:
```javascript
$.each(trumbowyg.o.plugins.emoji.emojiList, function (i, emoji) {
    if ($.isArray(emoji)) { // Custom emoji list
        var emojiCode = emoji[0],
            emojiUrl = emoji[1],
            emojiHtml = '<img src="' + emojiUrl + '" alt="' + emojiCode + '">',
            btnDef = {
                hasIcon: false,
                param: emojiHtml,
                fn: function () {
                    trumbowyg.execCmd('insertImage', emojiUrl, false, true);
                    return true;
                }
            };
        trumbowyg.addBtnDef(emojiHtml, btnDef);
        dropdown.push(emojiHtml);
    } else { // Default behaviour
        var btn = emoji,
            btnDef = {
                param: emoji,
                fn: function () {
                    trumbowyg.execCmd('insertText', emoji);
                    return true;
                }
            };
        trumbowyg.addBtnDef(btn, btnDef);
        dropdown.push(btn);
    }
});
```
_Note: you can still use regular emoji if you use a string instead of an array_
I imagine there is room for improvement on this. For instance, when adding an emoji after text, it wraps in a new ```<p>``` tag, so I might have to dig deeper to understand how Trumbowyg works a bit better.

### Fix
The fix I mentioned is the following: just like the ```colors``` plugin ([in this comment](https://github.com/Alex-D/Trumbowyg/issues/454#issuecomment-267283186)), an issue led to the default list being merged with the custom list. Fixed by changing line 912 from:
```trumbowyg.o.plugins.emoji = $.extend(true, {}, defaultOptions, trumbowyg.o.plugins.emoji || {});```
to:
```trumbowyg.o.plugins.emoji = trumbowyg.o.plugins.emoji || defaultOptions;```

Maybe at least the above fix might be worth implementing in a future update? I realise I am proposing an edit that makes the editor a bit more customisable, which might not be great for the lightweightness of Trumbowyg. Anyway, that's just my two cents.

Take care!

**Comment by Alex-D** [comment]
Thanks!

Can you make a pull request? :)

**Comment by JaKhris** [comment]
Yes, done with PR #548 👍 (first Pull Request I ever do, I hope that's how you're supposed to do it).

**Comment by danman1234** [comment]
It works, but still, after reloadig the apge a couple of sometimes, sometimes the smiley cion disappears then after reloading it aprears:

	function handleEmoji()
	{
		emojify.setConfig({
		 img_dir : '<?=HTML_ROOT?>images/smiley',
		});
		emojify.run();  
	}
	
	$('.trumbowyg-editor').bind('input propertychange', function() {
		handleEmoji();
	});	
	
	


	$('#write_blog').trumbowyg({
		  btns: [['bold', 'italic','h2'], ['link'],['emoji'] ],
		autogrow: true,
		semantic: false,
		removeformatPasted: true,
		plugins: {
				emoji: {
					emojiList: [
						[':)', '<?=HTML_ROOT?>images/smiley/8ball.png'],
						[':D', '<?=HTML_ROOT?>images/smiley/8ball.png']
					]
				}
			}
					
	
	});	

handleEmoji();`

`

With all smileys before this method it all works and loads, but i dont want to use all smileys

**Comment by NicolasPion** [comment]
@danman1234 with the "old" method, you can remove some lines of the emojiList array if you want : 

[Trumbowyg/plugins/emoji/trumbowyg.emoji.js](url)


With the "new" method, try to remove this first (dont needed anymore) : 

```
function handleEmoji()
{
	emojify.setConfig({
	 img_dir : '<?=HTML_ROOT?>images/smiley',
	});
	emojify.run();  
}

$('.trumbowyg-editor').bind('input propertychange', function() {
	handleEmoji();
});	

handleEmoji();

```

**Comment by danman1234** [comment]
Well nice, but this way the smiley icon is not showing up anymore:

`

	$('#write_blog').trumbowyg({
		  btns: [['bold', 'italic','h2'], ['link'],['emoji'] ],
		autogrow: true,
		semantic: false,
		removeformatPasted: true,
		plugins: {
 		emoji: {
            emojiList: [
               [':)', '<?=HTML_ROOT?>images/smileys/smile.png'],
			    [':)', '<?=HTML_ROOT?>images/smileys/smile.png']
            ]
        }
		}
					
		
	});
`
Trumbowyg.emoji.js is changed the way that is witten. not working.

And your link also not working:https://github.com/Alex-D/Trumbowyg/issues/url

**Comment by NicolasPion** [comment]
Use the new method I think (because the old one, use emojify.js, and "parse" the entire page to replace emoji :code: with image)

New newest method just "load" images.
 
For your bug with the new method, can you check in firebug / console if images are loaded please (to check if its not a image path related problem) ?

![path](https://cloud.githubusercontent.com/assets/11868633/26198688/5018d63e-3bc7-11e7-8cc1-a73c12776438.jpg)

**Comment by danman1234** [comment]
I did check the path, which is correct, otherwise i would not see the  smileys anyway,
My pproblem i mentioned are the ['emoji'] in the pane:

btns: [['bold', 'italic','h2'], ['link'],**['emoji']** ],

Also, why i cant use the sprite in this way? i cant get the sprite to work. The point is, serverload in many images is not good.

**Comment by NicolasPion** [comment]
@danman1234 
Try this plz : [exemple.zip](https://github.com/Alex-D/Trumbowyg/files/1010854/exemple.zip)
