### ISSUE TITLE
'formatting' not show

### ISSUE THREAD

**Issue by danman1234** [Alex-D/Trumbowyg#549]
```
$('#write_blog').trumbowyg({
    btnsDef: {
        // Customizables dropdowns
        formattingLight: {
            dropdown: ['h2'],
             ico: 'formatting'
        }
    },	
      btns: [['bold', 'italic'], ['link'], ['formattingLight']],
    autogrow: true
});
```

This is a custom formatting, since i want to show only h2, well the icon is empty, all other icons, if i change  ico: 'formatting' to  ico: 'insertImage' it shows fine. What is the problem here?

**Comment by Alex-D** [comment]
https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L334

**Comment by danman1234** [comment]
No you dont understand what i want. I need to use h2 in my element, not p in this case.
So i need an ico of h2, of use an cio of p but paste the h2 tag

**Comment by Alex-D** [comment]
So directly use h2 as a button:

`btns: [['bold', 'italic'], ['link'], ['h2']],`

or 

```
    formattingLight: {
        dropdown: ['h2'],
        ico: 'h2'
    }
```
