### ISSUE TITLE
Sugestion to include colors.

### ISSUE THREAD

**Issue by angelieri** [Alex-D/Trumbowyg#55]
Great component!
Adding some color and baground color would be awesome!

**Comment by hakim89** [comment]
can you advice on where to put the two svg files (fore-color.svg, back-color.svg) for the color plugin. I have the main icons.svg set in svgPath but I am not able to load the colors svg files.
I tried the ui folder relative to the trumbowyg.colors.css file and to the JS files but both did not wrok

**Comment by Alex-D** [comment]
They are included in icons.svg
