### ISSUE TITLE
cant put html smily 

### ISSUE THREAD

**Issue by danman1234** [Alex-D/Trumbowyg#551]
I try to connect unicode into the field, but its not possible with emojify.
I followed the docs and i want that the image will be shown inside the div. Even if i edit the code in trumbowyg.emoji.js  to place the html img tag:

 function buildDropdown(trumbowyg) {
        var dropdown = [];

        $.each(trumbowyg.o.plugins.emoji.emojiList, function (i, emoji) {
		var bobert = emoji.substring(1, emoji.length-1);
		var is = '<img src = "http://localhost/dateasianz/images/smiley/'+bobert+'.png" />';
						console.log(is);
            var btn = emoji,
                btnDef = {
                    param: emoji,
                    fn: function () {

                        trumbowyg.execCmd('insertText',is);
                        return true;
                    }
                };
            trumbowyg.addBtnDef(btn, btnDef);
            dropdown.push(btn);
        });

        return dropdown;
    }`

`

Well i get it inside the source after i clikc a smiley like this

<p>&lt;img src = "http://localhost/domain/images/smiley/blush.png" /&gt;</p>

How to get the HTML?

**Comment by Alex-D** [comment]
https://github.com/Alex-D/Trumbowyg/issues/323#issuecomment-302198958
