### ISSUE TITLE
Dragdrop Text can't update Textarea

### ISSUE THREAD

**Issue by sanishan** [Alex-D/Trumbowyg#552]
### Informations

**Browser + version**: Chrome Latest
**OS**: Windows 10.1
**Resolution**: 1440x1080

### How to reproduce the bug?
I have a small problem, I have to drag and drop text, its working and display in editor, but when i submit data drag and drop text won't submitted due to editor won't update textarea. which is working behind the editor.

Only way i found is to click twice "View HTML" to update the textarea.

Any body have solution to update textarea when "focus" trigger?

Thanks,

**Comment by Alex-D** [comment]
Try something like this:
`$('#my-editor').trumbowyg('execCmd', 'syncTextarea')`

:)
