### ISSUE TITLE
Emoji smilies really sucks

### ISSUE THREAD

**Issue by danman1234** [Alex-D/Trumbowyg#553]
I use the emoji plugins like mentioned in the plugin with Thumbowyg:
https://github.com/Ranks/emojify.js

```
function opensmiley()
{
('#write_blog').trumbowyg({
		  btns: [['bold', 'italic','h2'], ['link'],['emoji'] ],
		autogrow: true,
		semantic: false,
		removeformatPasted: true,
		plugins: {
 		emoji: {
            emojiList: [
   [':+1:',HTML_ROOT+'images/smiley/small/+1.png'],
   [':-1:',HTML_ROOT+'images/smiley/small/-1.png'],
   [':airplane:',HTML_ROOT+'images/smiley/small/airplane.png'],
   [':angry:',HTML_ROOT+'images/smiley/small/angry.png']
            ]
        }
		}
					
		
	});
}

opensmiley();
```

Well it works, but not loaded every time. I need to reload all the time.

so this emoji button:

`<button type="button" class="trumbowyg-emoji-button  trumbowyg-open-dropdown trumbowyg-active" title="Add an emoji" tabindex="-1"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#trumbowyg-emoji"></use></svg></button>`

Is not always present.

I have made an interval to check if the icon exists:

`
					var replai = setInterval(function() {
					   if ($('.trumbowyg-button-pane div:nth-child(3)').children().hasClass('trumbowyg-emoji-button')) {
						
						  // content.next().children().prepend('<a href="'+delink+'" class="tag reply-to" type="button" data-role="none" target="_blank" title="Go to profile">@'+naamm+' </a>');
						  clearInterval(replai);
					   } else {
 						var button = '<button type="button" class="trumbowyg-emoji-button  trumbowyg-open-dropdown trumbowyg-active" title="Add an emoji" tabindex="-1"><svg><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#trumbowyg-emoji"></use></svg></button>';
// creates the smiley button 						
$('.trumbowyg-button-pane div:nth-child(3)').html(button);

						console.log('not good');
						opensmiley(); doesnt reload
						clearInterval(replai);
					   }
					}, 100); // check every 100ms
`

the console log gives "no good" when the class is not present. it created the smiley button, but no click event works anymore.

Very annoying, does anyone knows how to fix it?

**Comment by NicolasPion** [comment]
@danman1234 
1: You dont need anymore emojify.js
2: Do you can try this page and post results plz ? I have make an exemple with your code : http://inketa.free.fr/exemple/
and after 100 loop, I haven't any "not good"

![emoji](https://cloud.githubusercontent.com/assets/11868633/26222652/28b5f50a-3c1b-11e7-9ce0-1b65fb800d17.gif)

**Comment by danman1234** [comment]
Hi there, thanks, i have removed "emojify.js"

I still get the issue, but i guess it has to do with certain conflicts with other libs, if i test it with only the needed libs , it works as expected... let me try to figure out what can be the conflict and i will update it once i found it.

**Comment by NicolasPion** [comment]
> if i test it with only the needed libs , it works as expected...

Good to know that is not really sucks 👍

**Comment by danman1234** [comment]
THanks, But to be honest, it still doest always work, and i can't seem to find out why.

I still after a couple of reloads get:

console.log('not good');

and the ico is not shown. But all the other icons : ['bold', 'italic','h2'], ['link'] are always shown.
Could you explain what the difference is with loading the smiley['emoji'] ?

Also for some reason in my script the opensmiley is not loaded if there is a no good.

**Comment by NicolasPion** [comment]
@danman1234 before "console.log('not good');" add this line : 

`console.log($.trumbowyg.plugins);`

And post result please

**Comment by danman1234** [comment]
HI the result is:

> Object {}
> __proto__
> :
> Object
> constructor
> :
> function Object()
> hasOwnProperty
> :
> function hasOwnProperty()
> isPrototypeOf
> :
> function isPrototypeOf()
> propertyIsEnumerable
> :
> function propertyIsEnumerable()
> toLocaleString
> :
> function toLocaleString()
> toString
> :
> function toString()
> valueOf
> :
> function valueOf()
> __defineGetter__
> :
> function __defineGetter__()
> __defineSetter__
> :
> function __defineSetter__()
> __lookupGetter__
> :
> function __lookupGetter__()
> __lookupSetter__
> :
> function __lookupSetter__()
> get __proto__
> :
> function __proto__()
> set __proto__
> :
> function __proto__()

**Comment by mysuf** [comment]
Hi, emoji img tags are copied to textarea and it probably should not. It should be distributed like img tags -> $ed for preview while raw emoji keys -> $ta. Can you describe some approach how to do that? I am trying to implement https://github.com/twitter/twemoji. Thank you
