### ISSUE TITLE
Chrome Warning about Selection.addRange()

### ISSUE THREAD

**Issue by btbjosh** [Alex-D/Trumbowyg#557]
I get this warning in Chrome (Version 57.0.2987.133 (64-bit)) now when using the editor in any form.
Will there be an update to this or a workaround? 

> The behavior that Selection.addRange() merges existing Range and the specified Range is deprecated and will be removed in M58, around April 2017. See https://www.chromestatus.com/features/6680566019653632 for more details.

Thanks!

**Comment by Alex-D** [comment]
Check v2.6.0

**Comment by PeterPlucinski** [comment]
I get the same error while adding an input field to a custom popup

**Comment by Alex-D** [comment]
Did you use any plugin? Or just the core? Can you give me a minimalist reproduction?
