### ISSUE TITLE
<script> being executed before being removed with tagsToRemove

### ISSUE THREAD

**Issue by ffaubry** [Alex-D/Trumbowyg#559]
When using 'tagsToRemove' with 'script', the script is still executed before being removed.

- use 'viewHtml'
- copy paste: <script>alert('hello');</script>
- switch back to normal editor (not htmlView)

You will see that the code is executed. This is a security hole in my opinion.

I don't think that #160 was correctly fixed.

We will submit a PR to fix this.

**Comment by Alex-D** [comment]
I do not want fix that.
Again, it's to your backend to secure that. Before that, only the user itself is annoyed.

**Comment by ffaubry** [comment]
Alex,
The issue is that users don't know what they copy/paste. 
When they switch the context from viewHtml to not viewHtml, the scrip is executed and malicious things can happen. At that moment it is not just an issue of being annoyed. Bad things could have happened under the domain that is hosting the app.
I'm asking you to reconsider this issue.
I speak french too. We can have a phone call if you want.
This a serious issue. We really want to make Trumbowyg safe.

**Comment by Alex-D** [comment]
Ok, so make a PR and I will check that :)

**Comment by ffaubry** [comment]
@Alex-D Thanks for considering the PR we just submitted.
This is a big deal us. Thanks in advance.
