### ISSUE TITLE
METHOD - Manage Content

### ISSUE THREAD

**Issue by wesleywong** [Alex-D/Trumbowyg#561]
Is there any method that i can set the content with particular style.

e.g. 

`$('#editor').trumbowyg('strong', "<p>Your content here</p>");
$('#editor').trumbowyg('center');`

**Comment by Alex-D** [comment]
You can call execCmd: https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L85

`$('#editor').trumbowyg('execCmd', { cmd: 'justifyCenter', forceCss: true })`
