### ISSUE TITLE
Align buttons break after randomly clicking them

### ISSUE THREAD

**Issue by ItsT-Mo** [Alex-D/Trumbowyg#562]
### Informations

**Browser + version**: Google Chrome 58.0.3029.110 (64-bit)
**OS**: Manjaro
**Resolution**: -

### How to reproduce the bug?
When using the align buttons on text, after randomly clicking these buttons and selecting text randomly during this (and unselecting text), after a while, the align buttons don't work as expected.

**Steps to reproduce:**
1. Write a line of text
2. Apply some formatting to the text (Bold, italic etc. Don't know if that causes it but that's what I did)
3. Now randomly click the align buttons while selecting und unselecting text randomly between the clicks
4. After a while the buttons don't work as expected

**Comment by Alex-D** [comment]
I can't fix that, sorry :/
