### ISSUE TITLE
$.trumbowyg('html', '...new content..') No longer works after 2.6.0

### ISSUE THREAD

**Issue by robinfhu** [Alex-D/Trumbowyg#567]
### Informations

**Browser + version**: Chrome latest
**OS**: Mac OS
**Resolution**:  Default

### How to reproduce the bug?
**Using Trumbowyg version 2.6.0:**

If you try to do `$('textarea').trumbowyg('html',"Hello World");`, it will not update the text area with the new content.

This used to work in older versions.

**Comment by fdelayen** [comment]
Same here, seems like this part of the api is broken :/

**Comment by arabsight** [comment]
yeah, same here.

**Comment by benpoulson** [comment]
Same issue here. Works if you roll back to `2.5.1`.

**Comment by Alex-D** [comment]
I've checked the diff, I did not understand what's the change, if you could investigate too, it could be cool :)

**Comment by wygodad** [comment]
Did the problem have been resolved?

**Comment by benpoulson** [comment]
@Alex-D I can't spot any obvious causes. I assume it's something to do with lines 1017 [here](https://github.com/Alex-D/Trumbowyg/compare/v2.5.1...v2.6.0#diff-a57e0e52aed1451208c5f2010cd3b537).

My issue does involve the WYSIWYG being hidden when instantiated, and the code here does check for visibility beforehand.

I'll have a play about with the source this evening.

**Comment by OlivierB-OB** [comment]
Hi @Alex-D ,

I managed to fixthis issue.
I made a pull request with my fix proposal: [https://github.com/Alex-D/Trumbowyg/pull/569](https://github.com/Alex-D/Trumbowyg/pull/569)

Rgds,
Olivier

**Comment by richardtallent** [comment]
An hour of my life wasted thinking this was a problem in wiring up Vue properties... :(

**Comment by srinudhulipalla** [comment]
I am also facing the same issue. Is there a way to fix this 2.6 or shall we go back to 2.5?

**Comment by srinudhulipalla** [comment]
I went back to 2.5.1 version. I works great..

**Comment by OlivierB-OB** [comment]
Hello @Alex-D  !

Did you find time to have a look at my fix proposal?
https://github.com/Alex-D/Trumbowyg/pull/569

**Comment by OlivierB-OB** [comment]
Thanks a lot!
