### ISSUE TITLE
Focus at the end of text

### ISSUE THREAD

**Issue by thekrotek** [Alex-D/Trumbowyg#570]
Is there any way to set cursor at the end of editor content, when focus() is called? Been struggling for this issue in several WYSIWYG editors for quite a while.

**Comment by Alex-D** [comment]
I think it's possible, but idk how. Maybe by manipulating ranges.

**Comment by thekrotek** [comment]
@Alex-D yes, ranges. Some time ago I've tried to implement this in one of my extensions, but no matter what I did and which solution uses, it didn't work. Maybe you will succeed.

Can you add this to agenda and implement in the next release? It would be a nice addition to your already great editor.
