### ISSUE TITLE
javascript in code

### ISSUE THREAD

**Issue by tilibrafx** [Alex-D/Trumbowyg#573]
Hello Alex!
Is there any way to save scripts in javascript within the editor?
It is a very useful function for CMS and more elaborate pages.

Thanks for the attention and congratulations from the excellent editor.

**Comment by Alex-D** [comment]
You can use the first icon "<>" to add any HTML code you want. :)

**Comment by tilibrafx** [comment]
But when I return to visual mode, all the <script> code I've created disappears.
