### ISSUE TITLE
Set value method doesnt work

### ISSUE THREAD

**Issue by zahedkamal87** [Alex-D/Trumbowyg#575]
When i try to set some value inside the editor, it just doesnt work. Please look at this JSFiddle.
[https://jsfiddle.net/zahedkamal87/04bfxq1a/1/](https://jsfiddle.net/zahedkamal87/04bfxq1a/1/)

If i click on the "To Textarea" button, it works. But "To Editor" doesnt work. Can anybody tell me what i'm doing wrong?

These are the codes applied on the buttons - 
```
$('#to-editor').click(function(){
	var codes = $('textarea').val();
  $('#editor').trumbowyg('html', codes);
});

$('#to-textarea').click(function(){
	var codes = $('#editor').trumbowyg('html');
  $('textarea').val(codes);
});
```

**Comment by bblok11** [comment]
I got this problem as well in the latest version

**Comment by Alex-D** [comment]
Did you try with the develop branch version?

I need to check it out, but I did not have the time for now.

**Comment by zahedkamal87** [comment]
I actually solved the issue in a different way, here is what i did - 

`
$('#to-editor').click(function(){
	var codes = $('textarea').val();
        $('#editor').trumbowyg('destroy');
        $('#editor').html(codes);
        $('#editor').trumbowyg(options);
});
`

Destroy the editor -> Append HTML inside the editor div/textarea -> Apply Trumbowyg on it again...

**Comment by Alex-D** [comment]
You should use previous version (2.5.1) insteed of dirty patch the latest buggy version ^^

**Comment by alvipeo** [comment]
same here! nasty bug!

**Comment by Alex-D** [comment]
I think it's linked to #567

**Comment by alvipeo** [comment]
It is!
