### ISSUE TITLE
Get keycode in Trumbowyg

### ISSUE THREAD

**Issue by thekrotek** [Alex-D/Trumbowyg#576]
I can't seem to understand, how to get keycode in Trumbowyg. I've tried tbwchange event, but it doesn't seem to return anything. The event itself is fired, but how can I get the pressed key char code?

I searched the issues, but found nothing about it. I also looked in the code and also can't seem to understand, what's wrong.

Could you, please, clarify this?

**Comment by Alex-D** [comment]
What's your goal?

**Comment by thekrotek** [comment]
I need to capture Enter or Ctrl + Enter keys and submit the form with Trumbowyg. I have all the code and only need to capture the keys.

**Comment by Alex-D** [comment]
You can juste use the parent element like that:

```js
$('#trumbowyg-demo').parent().on('keydown', function (e) {
    if (e.ctrlKey && e.which === 13) {
        // send your form
    }
})
```

**Comment by thekrotek** [comment]
Ah, I see... I've tried to use it directly on ".trumbowyg-editor" class, but apparently it didn't work, because editor is created dynamically. Should've guessed that. Thanks for the tip. it works now.
