### ISSUE TITLE
Undo works with right alt + z

### ISSUE THREAD

**Issue by dmnp1** [Alex-D/Trumbowyg#578]
Before report an issue, be sure to put these informations. Thanks :)

### Informations

**Browser + version**: chrome latest, not checked others
**OS**: windows 7
**Resolution**: full hd

### How to reproduce the bug?
Almost always right alt behave like ctrlKey, you can test it out here https://css-tricks.com/snippets/javascript/javascript-keycodes/ and since in example polish, left alt is really important to actually write something, this should be fixed.

### fix
find
Core, buildEditor function, line 560
`if (e.ctrlKey) {`
replace
`if ( e.keyCode === 17  ) {`

**Comment by Alex-D** [comment]
If I press alt on your demo page, that's OK, I have ctrlKey: false.

So, I can't reproduce and I'm not sure using keyCode solves the problem.

**Comment by dmnp1** [comment]
https://scr.hu/p90Z9G

it's behave really strange, if you press first left alt, and then right alt everything works OK, if you press first right alt that's what happens (scr), updated code works for me and user.

Same thing, on win and latest firefox, maybe it have something to do with system language, i dont know, but it works for me now.

**Comment by Alex-D** [comment]
The right `Alt` is `Alt gr` and is not the same like the left one. So it's "normal".

Did you use Synergy?

**Comment by dmnp1** [comment]
Dont use it, btw in the last comment i made mistake
this
And like i said **left alt** is require for all kinds of letters, żółś...
to
And like i said **right alt** is require for all kinds of letters, żółś...

Sorry.

**Comment by Alex-D** [comment]
I think the fix is more something like that: 

`if (e.ctrlKey && !e.alKey) {`

**Comment by dmnp1** [comment]
You made a typo
> if (e.ctrlKey && !e.al**t**Key) {

i checked the code and also work fine for me, no suprise here both code do the "same" thing, but prefer my way for visibility and only one thing to check.

**Comment by Alex-D** [comment]
Your code did not works because the catched event here is when you already have your Ctrl key down and you press another key.

So only my solution can do the job.

**Comment by dmnp1** [comment]
Are you sure u talk about line 560 ? Read your code, it's the same event as your's in the same place, ctrl key get true after the first hold down key.

And trust me, it was tested and works.
win7 latest chrome,ff,opera,opera neon
win 10 latest chrome, ff, opera, opera neon
win 10 edge 
(on every of these, your code fix [`if (e.ctrlKey && !e.altKey) {`], and mine [`if ( e.keyCode === 17 ) {`] works)
main repo don't

**Comment by Alex-D** [comment]
Next line: 

`var key = t.keys[String.fromCharCode(e.which).toUpperCase()];`

uses `e.which` (equivalent of keyCode). If I put your code, sortcuts won't works anymore. Ctrl + Z is browser managed, so it will works. But if you add some custom shortcut, it will not working anymore.

So yep, I'm sure I'm reading the right line :)

**Comment by Alex-D** [comment]
Added the fix in develop, soon in a release :)
