### ISSUE TITLE
IE11 paste does not trigger change event like it does in other browsers

### ISSUE THREAD

**Issue by marvc1** [Alex-D/Trumbowyg#579]
### Information

**Browser + version**: IE11
**OS**: Windows
**
### How to reproduce the bug?

The change event `tbwchange` is not called in IE11 when pasting in a value. It is called when using Chrome via the internal `execCmd` function.

Unfortunately I don't understand the code well enough to fix the issue, but for some reason in the below snippet IE11 and below bypass the internal `execCmd` function which triggers the change event.
````
.on('paste', function (e) {
                    if (t.o.removeformatPasted) {
                        e.preventDefault();

                        try {
                            // IE
                            var text = window.clipboardData.getData('Text');

                            try {
                                // <= IE10
                                t.doc.selection.createRange().pasteHTML(text);
                            } catch (c) {
                                // IE 11
                                t.doc.getSelection().getRangeAt(0).insertNode(t.doc.createTextNode(text));
                            }
                        } catch (d) {
                            // Not IE
                            t.execCmd('insertText', (e.originalEvent || e).clipboardData.getData('text/plain'));
                        }
                    }

                    // Call pasteHandlers
                    $.each(t.pasteHandlers, function (i, pasteHandler) {
                        pasteHandler(e);
                    });

                    setTimeout(function () {
                        t.semanticCode(false, true);
                        t.$c.trigger('tbwpaste', e);
                    }, 0);
                });
````

### Workaround

The workaround that seems to work for me is to hook your change handler into both `tbwchange` and `tbwpaste`, but note that this causes your change event handler to be called twice in all browsers except IE.

**Comment by Alex-D** [comment]
So we just need to add

`t.$c.trigger('tbwchange', e);`

at the bottom of the `try`

**Comment by marvc1** [comment]
Yeah, that would definitely fix it from my point of view.

**Comment by Alex-D** [comment]
Done in develop branch, soon in a release :)
