### ISSUE TITLE
strip format before paste?

### ISSUE THREAD

**Issue by 9mm** [Alex-D/Trumbowyg#58]
I'm having an extremely challenging time trying to find an wysiwyg editor that supports this :(

It seems relatively simple? 

http://jsfiddle.net/HBEzc/343/

Is there a way I can do this with Trumbowyg?

**Comment by Alex-D** [comment]
It was not so easy... IE8,9,10 are not the same like 11 and not the same like others... my brain is broken... but it's works!

The code : https://github.com/Alex-D/Trumbowyg/blob/5809e0c3a0f0f0634c824351e292d23b96dd5f34/src/trumbowyg.js#L406

Soon in a release.

**Comment by Alex-D** [comment]
I've just released the [`v2.0.0-beta.0`](https://github.com/Alex-D/Trumbowyg/releases/tag/2.0.0-beta.0) if you want check that the feature is correctly implemented.

Thanks!
