### ISSUE TITLE
How to make a wordpress like read-more plugin.

### ISSUE THREAD

**Issue by farebord** [Alex-D/Trumbowyg#580]
So, I'm making a plugin, but I'm not able to make this thing right. See, in wordpress when you press read-more button, a horizontal bar appears on the editor and on the invisible textarea a `<!--more-->` tag is added.
I've tried making this with template plugin, but I was no able to make it work. So I'm trying to make a plugin to do this.

How do I achieve this with a html tag like `<!--more-->`

**Comment by Alex-D** [comment]
That's not a tag, that's a comment and I don't know if browser keep them or remove them in contenteditable.

What's going wrong with template plugin?

**Comment by farebord** [comment]
It doenst show the read more when I click
