### ISSUE TITLE
A separate prefix for icons would be nice

### ISSUE THREAD

**Issue by Hoet** [Alex-D/Trumbowyg#581]
I have added a separate prefix for icons to the sources. But it seems I'm unable to push the changes to a new branch. So I have added the changes down here

Line: 351:

        // Defaults Options
        t.o = $.extend(true, {}, {
            lang: 'en',

            fixedBtnPane: false,
            fixedFullWidth: false,
            autogrow: false,

            prefix: 'trumbowyg-',
            prefixIcon: 'trumbowyg-',

Line: 722

        buildBtn: function (btnName) { // btnName is name of the button
            var t = this,
                prefix = t.o.prefix,
                prefixIcon = t.o.prefixIcon,
                btn = t.btnsDef[btnName],
                isDropdown = btn.dropdown,
                hasIcon = btn.hasIcon != null ? btn.hasIcon : true,
                textDef = t.lang[btnName] || btnName,

                $btn = $('<button/>', {
                    type: 'button',
                    class: prefix + btnName + '-button ' + (btn.class || '') + (!hasIcon ? ' ' + prefix + 'textual-button' : ''),
                    html: t.hasSvg && hasIcon ?
                      '<svg><use xlink:href="' + t.svgPath + '#' + prefixIcon + (btn.ico || btnName).replace(/([A-Z]+)/g, '-$1').toLowerCase() + '"/></svg>' :

line:  788

        buildSubBtn: function (btnName) {
            var t = this,
                prefix = t.o.prefix,
                prefixIcon = t.o.prefixIcon,
                btn = t.btnsDef[btnName],
                hasIcon = btn.hasIcon != null ? btn.hasIcon : true;

            if (btn.key) {
                t.keys[btn.key] = {
                    fn: btn.fn || btnName,
                    param: btn.param || btnName
                };
            }

            t.tagToButton[(btn.tag || btnName).toLowerCase()] = btnName;

            return $('<button/>', {
                type: 'button',
                class: prefix + btnName + '-dropdown-button' + (btn.ico ? ' ' + prefix + btn.ico + '-button' : ''),
                html: t.hasSvg && hasIcon ? '<svg><use xlink:href="' + t.svgPath + '#' + prefixIcon + (btn.ico || btnName).replace(/([A-Z]+)/g, '-$1').toLowerCase() + '"/></svg>' + (btn.text || btn.title || t.lang[btnName] || btnName) : (btn.text || btn.title || t.lang[btnName] || btnName),

**Comment by Alex-D** [comment]
You should insteed rework the CSS and replace all `trumbowyg-` parts with your own prefix if you want do that.

The goal of prefix is to switch between themes.
