### ISSUE TITLE
Problem with dragging image

### ISSUE THREAD

**Issue by Libertaro** [Alex-D/Trumbowyg#587]
### Informations

**Browser + version**: Google Chrome Version 59.0.3071.115
**OS**: Windows 10
**Resolution**: Full HD

### How to reproduce the bug?

Hello. 
After uploading image i need to wrap it in tag <a> with styles, it works fine. But if I upload 2 images and then drag second image above first one, my tags around image that was dragging are totally disappeared. Can you help me please which way is better to wrap image or how to resolve issue with drag?

**Comment by Alex-D** [comment]
Drag'n'drop is not supported in Trumbowyg. If it works, it's a browser feature so I can't fix that.
Sorry :/
