### ISSUE TITLE
Insert code at cursor position

### ISSUE THREAD

**Issue by RiRe** [Alex-D/Trumbowyg#588]
How can I insert code to my Trumbowyg instance via JS at the current cursor position?

**Comment by zahedkamal87** [comment]
+1

**Comment by Alex-D** [comment]
Check this plugin: [/plugins/template/trumbowyg.template.js@`develop`](https://github.com/Alex-D/Trumbowyg/blob/develop/plugins/template/trumbowyg.template.js)

:)

**Comment by Alex-D** [comment]
> [@Alex-D](https://github.com/alex-d) , I really dont find the link between my question and the Template plugin. What i see is that plugin creates some button/dropdown of already created template to insert.

You right, I don't know how to insert html code in a multi-browser way.

Check `insertHTML` here: https://developer.mozilla.org/fr/docs/Web/API/Document/execCommand

**Comment by JulioMunozc** [comment]
Please see: https://github.com/Alex-D/Trumbowyg/issues/629
