### ISSUE TITLE
Append at cursor position

### ISSUE THREAD

**Issue by zahedkamal87** [Alex-D/Trumbowyg#589]
Is there any way to append HTML at cursor pointer position?

**Comment by Alex-D** [comment]
Check this plugin: https://github.com/Alex-D/Trumbowyg/blob/develop/plugins/template/trumbowyg.template.js

:)

**Comment by Alex-D** [comment]
#588

**Comment by zahedkamal87** [comment]
@Alex-D ,  I really dont find the link between my question and the Template plugin. What i see is that plugin creates some button/dropdown of already created template to insert.

**Comment by Alex-D** [comment]
Yep, so you should found your solution in the plugin code :)
