### ISSUE TITLE
Tab within the textarea not working

### ISSUE THREAD

**Issue by buddythumbs** [Alex-D/Trumbowyg#592]
Before report an issue, be sure to put these informations. Thanks :)

### Informations

**Browser + version IE11:
**OS**: Windows 7
**Resolution**: 1080

### How to reproduce the bug?
Initialize the library

Hey, great library! Just wondering, is there support for tab spacing in the textarea? I initialize the the editor with the following code (by the way the html setting doesn't work for me) : 

```
$('#logbook').trumbowyg({
      btns: [
        ['formatting'],
        'btnGrp-semantic',
        ['link'],
        'btnGrp-justify',
        'btnGrp-lists',
        ['horizontalRule'],
        ['removeformat'],
        ['fullscreen']
      ]
    });
```
But when I click tab in the editor to indent the text it just leaves the editor (like normal tab behaviour).

Do I need to do something to change this behaviour?

Thanks

**Comment by Alex-D** [comment]
I did not support this kind of behaviour, but if you want to do that by yourself, you should add a listener on keydown, prevent default for the tab key and insert tab char.

Good luck :D

**Comment by buddythumbs** [comment]
Thanks!
