### ISSUE TITLE
Fixed button pane

### ISSUE THREAD

**Issue by Vinze** [Alex-D/Trumbowyg#593]
First of all, great editor! Really enjoy using it and it's much better than the alternatives in my opinion. I just have one question, on my application the header is fixed to the top with a height of 36px. When enabling the fixed button pane for Trumbowyg by setting `fixedBtnPane: true` the header overlaps. By default the element `.trumbowyg-button-pane` is positioned 0px from the top, is there anyway to override this with my own value (36px) ?

**Comment by Alex-D** [comment]
There is no option at this time :/

Value is here: https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L901

Maybe you can send a Pull Request to add a option for that :)

**Comment by Vinze** [comment]
That doesn't look to difficult! I will look into this shorty and when I added this I'll create the PR :)
