### ISSUE TITLE
Search functionality 

### ISSUE THREAD

**Issue by py4ka** [Alex-D/Trumbowyg#594]
Hi,
I couldn't find any search plugins available for editor :( I wrote my own function but there is an issue with if text splitted by html tag:

Example i need to find **sample** word but that's splitted by span tag
`sam<span>ple</span>`

Can you help or provide search functionality in your editor?

Thanks,
Regards.

**Comment by Furnicarium** [comment]
ctrl+f (facepalm.jpeg)

**Comment by py4ka** [comment]
so funny.... if you don't understand the question please don't spam.
I meant popup with find for this area with editor
![image](https://user-images.githubusercontent.com/4036980/28315307-2e8c29b8-6bbe-11e7-8f5d-2d8e9dd76744.png)

**Comment by Alex-D** [comment]
I did not plan to dev something like that. I do not want that in core, but if anyone is interested in dev that as a plugin, I'm ok with that :)
