### ISSUE TITLE
Issue with tbwchange and custom plugin

### ISSUE THREAD

**Issue by krve** [Alex-D/Trumbowyg#595]
I've made my own plugin that wraps the selected text in a span with some special classes. The issue appears when I try to fetch the HTML from the trumbowyg editor. If i select the text, click my plugin-button and try to fetch the contents via `$(element).trumbowyg('html')` the html does NOT contain the span I just inserted.

However if I change anything in the editor after that by either adding a space or something else, it does contain the span. Could this have something to do with the way I insert the span using my plugin?

Here's the code that I use to wrap the contents in a span.

```JavaScript
if (isInSpan) {
    trumbowyg.range.startContainer.parentNode.remove();
}

trumbowyg.range.deleteContents();
trumbowyg.range.insertNode(
    $(`<span title="${values.tooltipText}" class="text-underline" data-toggle="tooltip">${values.text}</span>`)[0]
);

trumbowyg.$c.trigger('tbwchange');
```

**Comment by Alex-D** [comment]
I think you just need to call `trumbowyg.syncCode()` insteed of trigger the event.

**Comment by krve** [comment]
It seems that did the trick. Though I still needed the `trumbowyg.$c.trigger('tbwchange');` for the listener to trigger.

Thanks!
