### ISSUE TITLE
SSR issue

### ISSUE THREAD

**Issue by rgnevashev** [Alex-D/Trumbowyg#598]
### Informations
Im using SSR

### How to reproduce the bug?
In node enviroment I got error jQuery is not defined
![2017-07-21_08-37-44](https://user-images.githubusercontent.com/123600/28450418-ea8fff3a-6def-11e7-94bf-e52901e8fbcf.png)

**Comment by Alex-D** [comment]
You need to import jQuery before Trumbowyg.
