### ISSUE TITLE
Firefox link never ends after the insertion

### ISSUE THREAD

**Issue by asparkam** [Alex-D/Trumbowyg#601]
### Informations
**Trumbowyg version**: 2.7.0, 2.6.0 and lower to 2.0.0 
**Browser version**: Firefox 51.0.1 (32-bit)
**OS**: Windows 7

### How to reproduce the bug?
1. Insert a link
2. Try to typing after link anything
3. Also sometimes after Enter (for new paragraph) it is making duplicate of the link in this paragraph (I can't track how it is reproduced)
[Demo](https://jsfiddle.net/s3Lyx4na/) (also can reproduce on official [demo page](http://alex-d.github.io/Trumbowyg/) ): 

**Firefox:**
![firefox](https://user-images.githubusercontent.com/30487905/28657071-75d0a1d8-72cf-11e7-8ee6-a6992ae5a4e3.gif)

_Expected_: Link area is ended and typing plain text
_Actual_: Link is still here when try typing after link. Only **Remove link** helped.

In Chrome all is right. I think it's may be some browser feature with contenteditable area.

**Chrome for comparison:**
![chrome](https://user-images.githubusercontent.com/30487905/28657078-7fcf9482-72cf-11e7-8424-cf795008dda2.gif)

**Comment by Alex-D** [comment]
Can't do anything since it seems to be a browser bug.
Trumbowyg is based on content editable which is native, so :/
