### ISSUE TITLE
Removing options from Formatting drop down buttons

### ISSUE THREAD

**Issue by sanjayojha** [Alex-D/Trumbowyg#604]
How to tailor the Formatting drop down buttons? I don't want to use all the options, instead I want to enable **H3** and **H4** tags only and remove rest of them.

**Comment by Alex-D** [comment]
http://alex-d.github.io/Trumbowyg/documentation.html#button-pane

**Comment by sanjayojha** [comment]
Thank you for replying. I have already read the whole documentation. I can control the buttons. But there is no documentation to customize the formatting drop down button .
I am talking about `['formatting']` option. It can not be adjusted by removing some of value form list, for example I want to remove `H1, H2, quote`. How Can I achieve this ?

**Comment by Alex-D** [comment]
You can check an example of custom dropdown here: https://github.com/Alex-D/Trumbowyg/blob/develop/examples/plugins/upload.html#L92

You can do the same for your own dropdowns :)

**Comment by sanjayojha** [comment]
Thank you for pointing it. Though that link does not solve the problem.
But during hit and trial, I figured we can also pass, h3, h4 and other formatting option (available in default drop-down of  `['formatting']` ) to show them individually in button pane.
Show for someone who is looking for solution you can try following if you want to show only one or more option
pass `['h3', 'h4']` to `btns` array along with other option , this will show only `H3` and `H4`. Likewise you can do for `H1`, `H2`, `blockquote` and `p`

**Comment by Alex-D** [comment]
Yep, dropdown are just group of buttons, so you can do what you want :)

So, did you solve your problem?

**Comment by sanjayojha** [comment]
Yes in this case, better if you can add that to documentation also

**Comment by Alex-D** [comment]
Yep I know documentation is not complete :/ I will work on in ASAP.
