### ISSUE TITLE
Image Upload plugin use in ASP.net

### ISSUE THREAD

**Issue by sandydonor** [Alex-D/Trumbowyg#605]
There is only a php version of the trumbowyg.upload.php file, I would request you to consider creating a trumbowyg.upload.vb and trumbowyg.upload.cs files for asp.net users as well. I do not have an access to php server and thus unable to use the functionality.

Though not really a bug, but it can be considered something as missing in functionality. I created a .vb file for uploading the image and it does upload the image, but my JSON string to be returned to the editor is creating a problem and not getting read properly. May be I did some thing wrong here as I am not so good with JSON/AJAX.

I created many possible variations of the json text, but none worked. Please help

**Comment by sandydonor** [comment]
As of now, I have created a temporary fix. Not sure how correct it is or will it create any problems later. Providing it here for others, who might be having a problem

                                                var objJSON = JSON.parse(data);
                                                if (objJSON.success) {
                                                    var url = objJSON.file;
                                                    trumbowyg.execCmd('insertImage', url);
                                                    $('img[src="' + url + '"]:not([alt])', trumbowyg.$box).attr('alt', values.alt);
                                                    setTimeout(function () {
                                                        trumbowyg.closeModal();
                                                    }, 250);
                                                    trumbowyg.$c.trigger('tbwuploadsuccess', [trumbowyg, data, url]);
                                                } else {
                                                    trumbowyg.addErrorOnModalField(
                                                        $('input[type=file]', $modal),
                                                        trumbowyg.lang[data.message]
                                                    );
                                                    trumbowyg.$c.trigger('tbwuploaderror', [trumbowyg, data]);
                                                }
//this is commented as it wasnt working for me
                                                //if (!!getDeep(data, trumbowyg.o.plugins.upload.statusPropertyName.split('.'))) {
                                                //    var url = getDeep(data, trumbowyg.o.plugins.upload.urlPropertyName.split('.'));
                                                //    trumbowyg.execCmd('insertImage', url);
                                                //    $('img[src="' + url + '"]:not([alt])', trumbowyg.$box).attr('alt', values.alt);
                                                //    setTimeout(function () {
                                                //        trumbowyg.closeModal();
                                                //    }, 250);
                                                //    trumbowyg.$c.trigger('tbwuploadsuccess', [trumbowyg, data, url]);
                                                //} else {
                                                //    trumbowyg.addErrorOnModalField(
                                                //        $('input[type=file]', $modal),
                                                //        trumbowyg.lang[data.message]
                                                //    );
                                                //    trumbowyg.$c.trigger('tbwuploaderror', [trumbowyg, data]);
                                                //}

JSON text used is             '{"success":1, "file":"/Images/ContentImages/ImageName.jpg"}' - The format of the JSON is very important and I could find it in a very long time.

**Comment by Alex-D** [comment]
I've added a lot of documentation actually. You should be able to create your server side script now :)
