### ISSUE TITLE
disable image resize in editor Trumbowyg

### ISSUE THREAD

**Issue by sanjayojha** [Alex-D/Trumbowyg#606]
Currently, When we insert an Image. The inserted image is resizable by user. Is there a way to disable this option?

![trumbowyg-issue](https://user-images.githubusercontent.com/3258151/28970668-041b673e-7947-11e7-8603-ced66e304455.jpg)

**Comment by Alex-D** [comment]
I can't it's a native browser feature. Sorry :/

**Comment by sanjayojha** [comment]
Editor like Froala and Redactor, allow simple configuration to disable this

`imageResize: false;`

**Comment by Alex-D** [comment]
I've already disabled that by default: https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L461

But seems not working in your case, also you did not respect the issue template so I do not have informations on browsers which are concerned :/

**Comment by sanjayojha** [comment]
Sorry for not providing the enough detail earlier

**Firefox V 54.0.1**:
**Windows 10**:
**1366 x 768**:

That line of code is not working, for now I am using css hack for this
```
.trumbowyg-editor img {
        -webkit-user-select: none; /* Chrome, Opera, Safari */
        -moz-user-select: none; /* Firefox 2+ */
        -ms-user-select: none; /* IE 10+ */
        user-select: none; /* Standard syntax */
        border: 0;
 }
```
but after double clicking on image it also stop working

**Comment by johncloud200** [comment]
I didn't see this library can resize image on their demo page.
How to do that?

**Comment by Alex-D** [comment]
I do not want support image resizing. IF you want do that, you should not use Trumbowyg.
