### ISSUE TITLE
Image upload plugin missing WIDTH & HEIGHT

### ISSUE THREAD

**Issue by sandydonor** [Alex-D/Trumbowyg#607]
Hi

Although the images uploaded on the browser are mostly the optimized ones. But we should still have an option of specifying the image width and height as a good HTML code ethic. This way even if someone doesn't want to optimize the image, he can make minor changes on the real image size through the view source of the editor.

Thanks
Sandy

**Comment by AbdelElrafa** [comment]
Don in the new merge #663

**Comment by Alex-D** [comment]
Nope, you only have fixed for core image, not upload plugin ^^ But a copy paste should works :)
