### ISSUE TITLE
Cursor is moving left after selecting formatting and no formatting applied

### ISSUE THREAD

**Issue by rizhoff** [Alex-D/Trumbowyg#61]
1. Start typing a text
2. Select Bold or Italic
3. Type a character

Expected: 
All signs typed from here are in the chosen formatting

Actual:
Only the first sign is in the chosen formatting. Then the cursor is moved before the last typed character and all the typing form here is done before this character and with no formatting

Tested on Chrome, Firefox and IE. In IE there is no such bug

**Comment by Alex-D** [comment]
Keyboard shortcuts are now supported by Trumbowyg, so it's OK :)
