### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by rgeraldporter** [Alex-D/Trumbowyg#610]
Hello,

I noticed on http://alex-d.github.io/Trumbowyg/documentation.html#svg-icons that the following line has a typo:

```
$.trumbowyg.svgPath = false:
```

It should be:

```
$.trumbowyg.svgPath = false;
```
(semicolon to end line)

I don't see a repo for the docs so I assume you'll have to make this fix yourself.

Thanks for a great plugin!

**Comment by Alex-D** [comment]
Doc is on a branch: https://github.com/Alex-D/Trumbowyg/tree/gh-pages
Thanks for report :)
