### ISSUE TITLE
Enclosing editor within a <label> tag causes editor to be unable to gain focus in Chrome

### ISSUE THREAD

**Issue by rgeraldporter** [Alex-D/Trumbowyg#611]
### Informations

**Browser version**: Chrome 60
**OS**: MacOS 10.12.6
**Screen resolution**: 1440x900

### How to reproduce the bug?
Surround the element being used as your editor with `<label>` tag. 

For example, using the "example" folder in the Trumbowyg repo, do this:

```
            <label>
                <div id="editor">
                    <h2>This editor is the default build of Trumbowyg.</h2>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Possimus, aliquam, minima fugiat placeat provident optio nam reiciendis eius beatae quibusdam!
                    </p>
                    <p>
                        The text is derived from Cicero's De Finibus Bonorum et Malorum (On the Ends of Goods and Evils, or alternatively [About] The Purposes of Good and Evil ). The original passage began: Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit (Translation: &quot;Neither is there anyone who loves grief itself since it is grief and thus wants to obtain it&quot;).
                    </p>
                </div>
            </label>
```

What happens?

You can't click into the editor easily as it'll unfocus right away, and the first UI button will be perpetually selected. You can work around by selecting text and replacing, but I've found that sometimes in doing this eventually the browser will freeze and crash.

Yes this is a weird bug, probably not the highest of a priority, but was one I dealt with as for some reason the editor we're replacing this with had a label tag around it and swapping this editor in caused this issue. I figure you'd appreciate knowing in case anyone else has encountered these symptoms.

**Comment by Alex-D** [comment]
That's not valid HTML... that a non-sense...
I can't do anything about that, that's a browser-level feature. Wrapping Trumbowyg in a label is not possible and will never be.

Sorry for that :/

**Comment by rgeraldporter** [comment]
That's ok! I thought it was weird too, but hey, now that it's been posted somewhere, if someone else has the same issue (somehow) it's now documented. :)

**Comment by Globulopolis** [comment]
@rgeraldporter it's documented in https://www.w3.org/TR/html5/forms.html#the-label-element
