### ISSUE TITLE
Errors when working with Input elements in the editor in Firefox

### ISSUE THREAD

**Issue by nilievski85** [Alex-D/Trumbowyg#612]
### Informations
Looks like Firefox is handling input elements differently with permission when try to access them.
I am using readonly input elements that represent placeholders in a template system.

**Browser version**: 55.0.2 (32-bit)
**OS**: Windows 10 (64-bit)
**Screen resolution**:  1920x1080

### How to reproduce the bug?
1. Put input element in the editor
2. Try to navigate the cursor to reach the input. 
3. When you touch the input with the cursor an error occurred:
'**Permission denied to access property "tagName"'** - This is within the "**getTagsRecursive**" funciton

**Comment by Alex-D** [comment]
When you tell "input" you mean `<textarea>`? If not, it's not supported.

**Comment by nilievski85** [comment]
No, I mean input text html element in the editor. Chrome has no problem with it but FF is restricting the element properties and throws an error. In order to fix that temporary,  I have try-catche "getTagsRecursive" and "saveRange" functions. This is not perfect solution, but works for now. 

The main reason I put input element in the editor is that I need the user to add placeholder elements for an template system. For example <client_name>. So I want to add some kind of non-editable block in the editor with a text label on it. I can use <img>, but I needed dynamic text label on it (in fact it can be done with svg to img, but I am leaving that for a last solution). So I put input element with readonly attribute and everything works great (excepts in FF).

**Comment by Alex-D** [comment]
Wow, that's a strange use case ^^
I've make some search on Web, but it seems to be a Firefox bug :(
It can be due to Firebug also.

**Comment by michaeldrob** [comment]
was this ever fixed?

**Comment by Alex-D** [comment]
Nope. And it will be not (at least, not by me).
