### ISSUE TITLE
CMD + delete doesn't trigger update event

### ISSUE THREAD

**Issue by mccambridge** [Alex-D/Trumbowyg#615]
If I have a single line of text and use CMD + delete (backspace key on Mac) to clear the line -- as opposed to just hitting the delete key letter by letter -- then the trumbowyg data is not updated.

Chrome 60 on Mac

Steps to repeat:
1. Enter some text on the first line only.
2. Make sure the cursor is at the end of the line.
3. Clear the line by pressing CMD + delete.
4. Log out the current value, e.g. $('#editor').trumbowyg('html'), via button or whatever.
5. Notice the value is still the same as it was before you cleared the line.

It looks like whatever event should update the data isn't firing.

**Comment by Alex-D** [comment]
I will keep this in mind for v3 (See #875 for more details)
