### ISSUE TITLE
Duplicate paragraph tags

### ISSUE THREAD

**Issue by FrancoisH** [Alex-D/Trumbowyg#616]
### Informations

**Chrome 60.0.3112.101 x64**:
**OS: Windows 10**:
**1920x1080**:

### How to reproduce the bug?

Edit text with Trumbowyg, placed on a textarea with default value and use `<strong>` or `<em>` button.
Each time you add a new style, it add a new set of `<p>` around the content.

### Expected behavior ?

The text should be only once encompassed by `<p>` tags.

**Comment by vsindylek** [comment]
Should be fixed by adding `contents()` to this line: `t.$ed.html(safe.html());` in trumbowyg.js

The above line should look like this: `t.$ed.html(safe.contents().html());`

Unfortunately I don't know how to work this gulp and node thing so I hope someone can put it on the code instead of me O:-)

**Comment by FrancoisH** [comment]
@vsindylek As you can see above, I mirrored suggested changes in a new fork. Hope you don't mind I did it for you...

As for yourself, you can always made the change into node_modules, but it this isn't included in the next release of Trumbowyg, the change will be lost when using `npm update`.

Anyway, thanks, it seems to work nicely.

**Comment by vsindylek** [comment]
Thank you @FrancoisH! I'm happy others can use the solution also ;-)

**Comment by Alex-D** [comment]
I've merge your fix. It will be in the next release soon :)

**Comment by vsindylek** [comment]
Awesome, thanks! ;-)

**Comment by Alex-D** [comment]
v2.7.2 published now :)
