### ISSUE TITLE
Can I override making new line with "ctrl+Enter" key?

### ISSUE THREAD

**Issue by jayraj** [Alex-D/Trumbowyg#617]
### Informations

**Browser version**: Chrome 60.0
**OS**: Windows10
**Screen resolution**:

### How to reproduce the bug?

Actually not a bug, but I want to override the key   which takes the user to next line. I want this functionality with "Ctrl+Enter" key. SO could you please help me?

**Comment by Alex-D** [comment]
You can't without fork and modifying source code since Trumbowyg listen some things on the enter key.

**Comment by mrmnmly** [comment]
I'm not sure how valid my solution is for this issue, but I've managed to add such functionality: https://stackoverflow.com/a/49920323/1004946
