### ISSUE TITLE
The cursor is before the formatted text after applying format to a selection

### ISSUE THREAD

**Issue by rizhoff** [Alex-D/Trumbowyg#62]
1. Select a text
2. Press 'CTRL+ B' or 'CTRL + I'
3. The text is formated
Expected:
The cursor is at the end of the formatted text
Actual:
The cursor is before the formatted text

**Comment by Alex-D** [comment]
Shortcuts are now supported by Trumbowyg on master branch. Soon in a release.

**Comment by Alex-D** [comment]
I've just released the [`v2.0.0-beta.0`](https://github.com/Alex-D/Trumbowyg/releases/tag/2.0.0-beta.0) if you want check that the bug is correctly fixed.

Thanks!
