### ISSUE TITLE
Remove unnecessary div removal

### ISSUE THREAD

**Issue by vsindylek** [Alex-D/Trumbowyg#621]
I have a suggestion for removing this line of code: `t.semanticTag('div', 'p', true);`

All that it does as I can see from my testing was to remove multiplying divs caused by issue #616. Since this issue is solved I don't see any more reason for having it there. All it does is that it makes it unable to use any kind of div inside the code area for formating purposes - all of them are automatically turned into paragraph which is not always desirable.

Or is there some other reason why this line is used there?

Thanks! :-)

**Comment by Alex-D** [comment]
It's here because some browser use div insteed of p to wrap new bloc of text, which is not desirable.
