### ISSUE TITLE
Trumbowyg doesn't update ngModel

### ISSUE THREAD

**Issue by TheBobo** [Alex-D/Trumbowyg#622]
I am using Trumbowyg in my Angular2
I try to update my object property [(ngModel)]='scene.description'

trumbowyg doesn't work 
<trumbowyg 
                 [(initialContent)]="scene.description" [options]="options1" 
                 [(ngModel)]="scene.description"
                (savedContent)="scene.description=$event">
</trumbowyg>

How I can update my model from Trumbowyg ?

**Comment by Alex-D** [comment]
Did you check that: https://github.com/monad98/ng2-lazy-trumbowyg ?

I do not use Angular, and I did not know what's your code behind your trumbowyg component, so I cannot help you as is.
