### ISSUE TITLE
<p> tag doesn't encompass first line.

### ISSUE THREAD

**Issue by FrancoisH** [Alex-D/Trumbowyg#623]
### Informations

**Browser version**: Chrome Windows 60.0.3112.101 x64:
**OS**: Windows 10 Pro x64 
**Screen resolution**: 1920x1080

### How to reproduce the bug?
Just type a text, only the next lines are encompassed by a <p> tag.
Displaying source resolve the issue...

### Expected behavior
The first line should be encompassed in <p> tag as well.

**Comment by Alex-D** [comment]
Duplicate #516
