### ISSUE TITLE
Nbsp when typing in the editor

### ISSUE THREAD

**Issue by SvetlinStaev** [Alex-D/Trumbowyg#624]
### Informations

**Browser version**: Chrome 60
**OS**: Mac OS
**Screen resolution**: 1920x1080

### How to reproduce the bug?
When I am typing into the editor and then saving the text to the database the spaces in the text are represented as `&nbps;` rather than ` `. Is there a setting to have the spaces represented as non-breaking spaces as I need to wrap the text into a div and it doesn't collapse well when width is enforced on the container element because of the non-breaking spaces?

**Comment by Alex-D** [comment]
Did you have a demo page? I can't reproduce.

**Comment by SvetlinStaev** [comment]
Sorry for blaming it to the editor, it was another plugin which was accidentally converting the spaces to nbsp

**Comment by SvetlinStaev** [comment]
It was actually not the editor, I had another plugin which was causing it but before I figured it out I was stripping that from the processing in the backend.
