### ISSUE TITLE
syncCode wraps content into two divs

### ISSUE THREAD

**Issue by mysuf** [Alex-D/Trumbowyg#625]
syncCode wraps textarea content into two divs, inserting html of parent. So when textarea is empty t.$ed contains `<div></div>` and next tbchange copy it to textarea..)

Expected behavior:
Only one div wrapper could fix it

Usecase:
Using multiple instances of tbw on page. Editor can be hidden on page load.

Options:
autogrow: true
semantic: false

**Comment by ghostika** [comment]
@mysuf is this happens only with multiple instances on the same page? I have something similar problem. If i have only a text with `p` like:  `<p>Text</p>` then the editor keeps adding a `<div>` wrapper around it and it keeps getting bigger and bigger as it adds an other `<div>` on every save.

Options:
resetCss: true
removeformatPasted: true
autogrow: true

**Comment by mysuf** [comment]
I described usecase only as additional info. This is common bug affecting every instance. I wrote emoji plugin based on tweemoji and had to override syncTextarea and extend syncCode functions so I included fix inside (removing every div), but it is temporarily solution. Maybe time to pull something on github ;)

**Comment by mysuf** [comment]
my fault. This issue is already resolved by [#616](https://github.com/Alex-D/Trumbowyg/issues/616). Description of that issue was only side effect. Just pull current version...

**Comment by Alex-D** [comment]
Good to ear :)
