### ISSUE TITLE
Template Plugin Button Broken?

### ISSUE THREAD

**Issue by MACscr** [Alex-D/Trumbowyg#626]
### Informations

Chrome 60.x
OSX Sierra
1080p

### How to reproduce the bug?
The template plugin button seems to be missaligned in the nav as you can see here https://jsfiddle.net/vj90s9fb/105/. I do not see this issue with older versions like 2.01beta. Should be easy to fix with css, but maybe its because I need sleep, but I havent figured out what is causing the problem and how to resolve it. Thanks!

**Comment by Alex-D** [comment]
Nope, you right, it's due to an IE9 fix ^^'

**Comment by MACscr** [comment]
No need to support IE9 anymore. Easy fix. =P

**Comment by amakh** [comment]
It's not only template button, it's all dropdown's.
@MACscr What is your easy fix ?

**Comment by Alex-D** [comment]
> @MACscr What is your easy fix ?

It's a troll... his fix is "drop IE9 support".

But you can also stay on the previous release if the latest is not OK for you.

**Comment by amakh** [comment]
Oh I see.
It's fine, i'll use the previous release then. I tried to fix with some css but that was very ugly :p

Nice project btw! 🍺

**Comment by MACscr** [comment]
Ie9 is EOL and most major projects have dropped support for it. Heck, IE 10 barely even has any market share anymore. It's not ridiculous to drop support for it. Especially when you consider that right now you are only supporting IE9 since every other browser is broken with it.

- Mark

**Comment by Alex-D** [comment]
It's just a CSS bug, Trumbowyg is JS before CSS I think...

Some users uses Trumbowyg because because of IE9 support.

**Comment by MACscr** [comment]
Disable CSS and tell me again that Trumbowyg is mainly JS.

- Mark

**Comment by amakh** [comment]
But which change(s) exactly have broken the dropdown styling?

**Comment by Alex-D** [comment]
> It's not only template button, it's all dropdown's.

I cannot see any bug on other dropdowns :/

**Comment by Alex-D** [comment]
Fixed in 1.8.1:
https://jsfiddle.net/vj90s9fb/113/

 :)
