### ISSUE TITLE
pasteimage: insert image twice

### ISSUE THREAD

**Issue by Globulopolis** [Alex-D/Trumbowyg#628]
### Informations

**Browser version**: Firefox 52.3.0 (64bit) ESR
**OS**: Win 7
**Screen resolution**: 1366x768

### How to reproduce the bug?
Init editor, paste image from clipboard.

**Comment by geek876** [comment]
Hi any update on progress with this one ?

**Comment by Alex-D** [comment]
Not on my side.

**Comment by Globulopolis** [comment]
Tested in Firefox 52.5.3 (64bit) ESR and seems to be ok. The image not duplicated.

**Comment by samirhshaikh** [comment]
We have been facing the same issue in chrome browser in our mac and windows environment. Along with pasting image, the problem also happens when we copy and paste a table from MS excel. 

Environment details for mac:
OS: macOS High Sierra (v 10.13.2) 
Browser: Chrome (Version 63.0.3239.132)

Environment details for Windows 10:
OS: Windows 10 (64bit) 
Browser: Chrome (Version 63.0.3239.84)

We have been using this product since a long time and really like it. We will appreciate if you can please resolve these issues.

Thanks for your support.

**Comment by Alex-D** [comment]
Did you use the last version?

**Comment by samirhshaikh** [comment]
Thanks for the reply.

We are using v2.5.1. However we tried and successfully replicated the same problem on your website https://alex-d.github.io/Trumbowyg/ as well. So we feel that this problem is still there in the latest version of the plugin as well.

**Comment by Alex-D** [comment]
Is this bug still here with 2.10.0?

**Comment by samirhshaikh** [comment]
Sorry for the delayed reply. I was out of work for a month.

Provided that your website https://alex-d.github.io/Trumbowyg/ uses v 2.10.0, the issue is still there. I tried to copy and paste an image in the editor provided there, and the it got pasted twice.

**Comment by nicrf** [comment]
I got the same bug, on Windows with Chrome Version 67.0.3396.99 (Build officiel) (64 bits).

Not only on website but into your example to.

**Comment by heniotierra** [comment]
I get this problem when I import the pasteimage plugin explicitly. But if I don't import it, the pasteimage functionality works as expected.

**Comment by Tagmar2** [comment]
he error persists and is at https://alex-d.github.io/Trumbowyg

Steps to reproduce:

Go to a webpage that has an image

over the image, use the context menu to do a "copy image"

Go to https://alex-d.github.io/Trumbowyg

Click "With plugins"

paste from clipboard

Realize that the first image is just the internet link. The second is the embebed 64

<img src="https://cdn2.iconfinder.com/data/icons/diagona/icon/16/150.png" alt="Resultado de imagem para close icon"><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACRUlEQVQ4EaWTTWsTURSG35nJJGMam3QMNDabgDWUgMaIIgraollmYd0YEKsUEv0JXdWaX6EVRHSTnVlkqxsXhVJNKyISNN2YLzGZhCTNZD4ycq6doa2udGAYOPd53nPnci7wnw931Lce3IjB4tOAlQKQ2F8vAVwR3DjPPX3z+aBzKMBYvp7h3K4cNzMT4qangamp36yiwGo2YdVqDUszVl3P3z6zQ5wA7f7VDHzH14VoFJ1qFe2dHXTLZcb5o1HI8TgC4TBMqvV7WfeLdyyEJ2J051LMtJATIhH82N7G90JhY6+ye+9CBRy9g91KQVYU8KEQiCGWHHJZgDrS0pDlUK9WQ2tra4MXvXfjZf0lAVY2uRafX7iJZBLvV1ZADLHMsQN0zUi5JicxqFQgSZ4nZz51v9kygEe27A8GC8QQS46zA2OkJlyiCFNRMLvZcjoflC3g8enNn4vEEEuOE6BrGjAcwuP1Uo1t+6h8sYI1WmPMcAjmAHBRUR+NSmqzmZiQZXRunXsNwPln6mzLymJiSfRKUJtN5pDLDtHQtWKvXockSfAHg3+V1dtXTnmOuR8SQyw5ToBuaPl2vdZQaWAiEXba8YX5gt3ZWL62JHjFVx6PdJkYYsmhAGeQPs5JGckrrZ8Mh+GjCRRFQBCIAUwT0HX0FQX1ahXqnpo9+0Vlg+QEEFeKChmeF3InZDnkDwTgm5hgfn8wQLfTQavdbozH5mqibP45yowE8GEWsbGJNIAUuP3LZKEEoMgLyJ//ikOXyfb++fsLkiQUXnILVLMAAAAASUVORK5CYII=">

**Comment by Alex-D** [comment]
Fixed in v2.16.0
