### ISSUE TITLE
Insert at caret

### ISSUE THREAD

**Issue by MACscr** [Alex-D/Trumbowyg#629]
### Informations

Chrome 60.x
OSX Sierra
1080p

### How to reproduce the bug?
I am trying to figure out a way to interact with the editor externally and be able to insert values at the current position of the cursor. There is a jquery plugin called insertatcaret, but it works with textareas and not with the editor, so cant use that.

This is what I currently have: https://jsfiddle.net/vj90s9fb/106/ (I removed that plugin since it wasnt relevant).

There must be an internal function of Trumbowyg that I could use. Thanks so much for your time!

**Comment by Alex-D** [comment]
I did not understand your need. Why did you not create a Trumbowyg plugin for that?

**Comment by MACscr** [comment]
Because it's not going to be integrated into the toolbar itself and I want more flexibility on its layout, etc. I only provided a basic example in the fiddle.

- Mark

**Comment by patrickRocketVisor** [comment]
@MACscr 
I believe what you're looking for is the `execCmd` function within Trumbowyg.

Heres an example of how to use the `insertText` command to insert text at the current cursor location.
```javascript
$('#my-editor').trumbowyg('execCmd', {
	cmd: 'insertText',
	param: 'TextToInsert',
	forceCss: false,
});
```
The `param` argument should contain the text you wish to add.

In the future, you should know that you can use any Commands from the official documentation for `Document.execCommand()` [found here](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand#Commands).

**Comment by ChinLeung** [comment]
@patrickRocketVisor 

The problem with `execCmd` is that it does not insert at the current cursor location if you trigger it on click.

In my scenario, I have tried to execute it via the Google Console, and it works properly. However, if I trigger the `execCmd` on a click event of a button, it no longer works.

For example, if I have the following button:

```
<span id="button" class="button" data-text="Hello World">Click</span>
```

Then I bind the event with JavaScript:

```
const btn = document.getElementById('button');
btn.addEventListener('click', function(event){
    $('#my-editor').trumbowyg('execCmd', {
        cmd: 'insertText',
        param: event.target.getAttribute('data-text'),
        forceCss: false
    });
});
```

Now when I click on my button... no matter where the caret position was previously, it will append the text at the beginning of the editor.

**Comment by Alex-D** [comment]
Yep, because when you click on the button you blur the content editable and you lost your selection.

So, you need to use 'saveRange' and 'restoreRange' APIs before use the 'execCmd' one.

**Comment by ChinLeung** [comment]
@Alex-D So we have to `saveRange` on blur or does it do that automatically?

**Comment by ChinLeung** [comment]
I'm leaving this here for those who are having the same issue as me.

```
const btn = document.getElementById('button');
btn.addEventListener('click', function(event){

    // Restore the previous position
    $('#my-editor').trumbowyg('restoreRange');

    // Insert text at the current position
    $('#my-editor').trumbowyg('execCmd', {
        cmd: 'insertText',
        param: event.target.getAttribute('data-text'),
        forceCss: false
    });
});
```

**Comment by JulioMunozc** [comment]
Sorry for comment in a closed ticket but I am wondering @Alex-D if exists the way to insert HTML code instead plain text?

**Comment by JulioMunozc** [comment]
This is the way to insert a HTML tag if anyone needed to do that

    this.trumbowygInstance.trumbowyg('saveRange');
    let value = this.trumbowygInstance.trumbowyg('getRangeText');
    this.trumbowygInstance.trumbowyg('restoreRange');
    value = value !== '' ? value : 'Write your note...';
    const htmlValue = '</br><p class="ms-rteElement-Note-default">' + value + '</p></br>';
    this.trumbowygInstance.trumbowyg('execCmd',
    {
      cmd: 'insertHTML',
      param: htmlValue,
      forceCss: false
    });

Thank you @Alex-D your control is awesome!!
