### ISSUE TITLE
Firefox display bug

### ISSUE THREAD

**Issue by MrMarco2017** [Alex-D/Trumbowyg#634]
### Informations

**Browser version**:  Firefox 55.0.3
**OS**: Win 10
**Screen resolution**: 1920x1080

### How to reproduce the bug?

If I use the editor in the firefox I have a display bug.
I added a picture to this bug: https://prnt.sc/gpj4ao

**Comment by Globulopolis** [comment]
Try to add `svgPath` option and point it to `icons.svg` file.

**Comment by Alex-D** [comment]
Check your console and like @Globulopolis said, check the `svgPath` option: https://alex-d.github.io/Trumbowyg/documentation/#common-issues

**Comment by MrMarco2017** [comment]
Thank you for your answers, problem is solved.
