### ISSUE TITLE
Is there a way to use trumbowyg on Angular 4?

### ISSUE THREAD

**Issue by Metsuryu** [Alex-D/Trumbowyg#635]
### Informations
I'm working on an Angular 4 CLI project. 
I installed the trumbowyg npm package, imported the js and css files in .angular-cli.json, imported trumbowyg from "trumbowyg" in the TypeScript file I'm using it in, but it doesn't work.

jQuery works fine, but when I try to call :

$('#trumbowyg-demo').trumbowyg();

It doesn't even compile. 
So I tried to do:
		let editor = (<any>$("#trumbowyg-demo"));
		editor.trumbowyg();

But I get editor.trumbowyg is not a function.

I was able to get trumbowyg to work with this:
https://github.com/monad98/ng2-lazy-trumbowyg

But it doesn't look like an official version since with this plugins don't work, and it seems like it has a few bugs, so I wanted to try the official version if possible.

**Browser version**:
Firefox 55
**OS**:
Windows 7
**Screen resolution**:
1280x1024

### How to reproduce the bug?
Try to make make trumbowyg work on an Angular 4 CLI project by installing it with npm and importing it.

**Comment by Alex-D** [comment]
I did not officially supports any integration in frameworks, sorry :/

And I did not know Angular 4 (I've used the 1st version a long time ago, and I'm using Vue now).

Can't help you :/

**Comment by Metsuryu** [comment]
Oh, that's too bad, I'll see if I can make it work with ng2-lazy-trumbowyg then.

**Comment by Alex-D** [comment]
It takes me already a lot of time to maintain the core and plugins. It will take my entire life if I maintain all integrations in all world JS frameworks :D

**Comment by Metsuryu** [comment]
Don't worry about it ahah. There was just a weird bug in that version where it would add an opening and closing div tag every time I clicked ViewHTML, but I tried the demo version on your website's frontpage and it didn't have that bug, so I thought that it was just a bug of the version I was using, but I'll figure it out myself.

**Comment by Alex-D** [comment]
The landing is not up to date. You should test by cloning the repo locally. Sorry for that, but I did not update the statics for now :-°

**Comment by MasterBroki** [comment]
@Metsuryu , did you find a way to make trumbowyg work? Got the same issue here!

**Comment by Metsuryu** [comment]
@MasterBroki Yes. I downloaded it, and I'm using it from the assets folder.

If you're working with Angular CLI, you have to add the sources to the .angular-cli.json file, and additionally, you might have to use jQuery as `const jq = <any>jQuery;` or it might not work with typescript.

Hope that helps!

**Comment by MasterBroki** [comment]
Omg that works! Thanks for posting it! @Alex-D , I understand that you don't wan't to manage all the frameworks, but would it be possible to create a wiki in the project for including integration instructions? That way everybody could contribute. Thanks!

**Comment by Alex-D** [comment]
How non-owner/member can update/pull request wiki?

**Comment by MasterBroki** [comment]
I'm not quite sure, I think I saw an option for contributing outside of membership
https://help.github.com/articles/about-github-wikis/
Do you think it would be viable?
