### ISSUE TITLE
Pasting text from Word Document

### ISSUE THREAD

**Issue by saintach** [Alex-D/Trumbowyg#636]
### Informations

**Browser version**: Chrome 60.0
**OS**: Mac 10.12
**Screen resolution**: 1440 x 900

### How to reproduce the bug?
When you paste text from a MS Word doc you the text are preformatted vs when you paste HTML you can see HTML tags. `<>` mode is off for both scenarios. 

If you turn on `<>` mode, for the first scenario, you will see XML tags for the Word Doc. I think it would be nice if both show tags with `<>` off.

**Comment by Alex-D** [comment]
You should use https://alex-d.github.io/Trumbowyg/documentation/plugins/#plugin-cleanpaste
