### ISSUE TITLE
How to select image?

### ISSUE THREAD

**Issue by rgeraldporter** [Alex-D/Trumbowyg#637]
### Informations

**Browser version**: Chrome 61
**OS**: MacOS 10.13

Just wondering if there is, or can be a way of just selecting an image that has been uploaded or linked? Without this it seems unclear how to delete a photo, as the caret tends to hide pretty well around the image when you click it at the moment.

(Not asking for resize, or drag necessarily, just select.)

Thanks!
Rob

**Comment by Alex-D** [comment]
Hum, you just have to... select the image like a text :)
It works for me, just move the mouse with the left click down over the image.

Did not understand your question sorry ^^'

**Comment by rgeraldporter** [comment]
Ah, I see, drag works, but only on desktop, not mobile. I guess the problem is our use case is more tablet (iPad) than desktop, and are moving from TinyMCE which selects the image when you click/tap on it. Can't drag on a tablet at all though.
