### ISSUE TITLE
Delete/Strike-through button partially working

### ISSUE THREAD

**Issue by jpdelmundo** [Alex-D/Trumbowyg#638]
### Informations

**Browser version**: Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)
**OS**: Windows 10 Pro
**Screen resolution**: 1920x1080

### How to reproduce the bug?
1. Highlight/select text from the editor
2. Click on the delete/strike-through button (text style changed to strike-through)
3. Highlight/select the same text from the editor
4. Click on the delete/strike-through button (strike-through style not removed)

Video in the attached zip
[delete-button-bug.zip](https://github.com/Alex-D/Trumbowyg/files/1366845/delete-button-bug.zip)

**Comment by Alex-D** [comment]
I can't fix that :/

Sorry.

**Comment by jpdelmundo** [comment]
Sorry for asking. Is it because it is not a valid bug? Or just have no time fixing?

If it's latter, this issue should at least stay open for others see and probably someone might be able to fix it.

**Comment by Alex-D** [comment]
It's a browser-level bug, so I can't fix it easily :/

**Comment by jpdelmundo** [comment]
I see. I don't want to sound pushy about this but, if you can't fix it easily, can you at least leave it open for others to see?

**Comment by Alex-D** [comment]
Nope. Because if I do that with all bugs like this I get 100+ open issues which stay like that forever :/

**Comment by CharlotteBeebee** [comment]
Unless you specifically need `<del></del>` tags then this can be fixed by using `<s></s>` tags: in semanticCode function, replace t.semanticTag('strike', 'del') with t.semanticTag('strike', 's')

**Comment by tomsx** [comment]
@CharlotteBeebee: I agree. <s></s> works just fine.
e.g. https://www.froala.com/wysiwyg-editor
...but <del></del> works in other wysiwyg editors as well. https://trix-editor.org/

**Comment by davidsneal** [comment]
Changing the value of these two lines to `'s'` does the trick for me: https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L441-L442

**Comment by tyronx** [comment]
Why was a fix for this never added? Why are issues just being closed without even looking at possible fixes? So many questions...

**Comment by tomsx** [comment]
Strangely the issue only occurs when trumbowyg.min.js is used. It works all fine with  trumbowyg.js.

**Comment by darinredding** [comment]
Not working for me using either js version using zip downloaded from master today.
