### ISSUE TITLE
Base64 Image : file size

### ISSUE THREAD

**Issue by PapsOu** [Alex-D/Trumbowyg#645]
### Informations

**Browser version**: Chromium61, Firefox56
**OS**: fedora26 (Linux)
**Screen resolution**: ?

### How to reproduce the bug?

That's not really a bug but could be a security risk. Is it possible to limit the size of base64 encoded file ? I think about stupid users that will pick a huge file on their computer and will freeze their browser because the huge file use take a lot of memory in browser. On the other hand, for database, limiting image filesize would reduce the risk of reaching text field type max size (not varchar).

More globaly, it would be great to check the whole content size of the editor ?

**Comment by Alex-D** [comment]
Feel free to add a option + a check to base64 plugin via a Pull Request :)

https://github.com/Alex-D/Trumbowyg/blob/develop/plugins/base64/trumbowyg.base64.js#L111
