### ISSUE TITLE
Do you mind if I publish this to nuget?

### ISSUE THREAD

**Issue by jitbit** [Alex-D/Trumbowyg#646]
Hi. Great plugin.

NUGET is a package manager for MS Visual Studio. Do you mind if I publish and maintain this editor there through my dev account? I will keep all the (c) info, links to your website and everything. Thanks.

PS. I'm actually already in the process of publishing it, but if you mind, I'll abort/take it down. https://github.com/jitbit/TrumbowygNuget/

PPS. http://nuget.org just in case

**Comment by Alex-D** [comment]
Hi!

It's OK, don't worry :)
