### ISSUE TITLE
SVG Icons don't load

### ISSUE THREAD

**Issue by Azareal** [Alex-D/Trumbowyg#648]
### Informations

**Browser version**:
Firefox 56
**OS**:
Windows 10

### How to reproduce the bug?
Go to https://alex-d.github.io/Trumbowyg/

The SVG icons don't show up in the editor.
![image](https://user-images.githubusercontent.com/5985165/31926404-245e7d32-b886-11e7-8aa4-0214d0888fd3.png)

**Comment by nheath99** [comment]
See #647, I thought I had this issue too!

**Comment by nheath99** [comment]
Solution is #634

**Comment by megamaiku** [comment]
Is it possible to use FontAwesome icons instead?

**Comment by Alex-D** [comment]
You can, you just need to set svgPath to false and code your own CSS to put your icons on each button.

**Comment by megamaiku** [comment]
My apologies, Alex. It was one of those shotgun questions you make before your first cup of coffee on a Friday morning :) 
ps: loving the editor so far!
