### ISSUE TITLE
Russian is listed among Asian languages, omg rly?

### ISSUE THREAD

**Issue by staleo** [Alex-D/Trumbowyg#649]
### Informations

**Browser version**:
**OS**:
**Screen resolution**:

### How to reproduce the bug?
Just go to https://alex-d.github.io/Trumbowyg/ and enjoy a list of supported languages separated by region. :D

**Comment by Globulopolis** [comment]
Same with Spanish listed under America :)

**Comment by Alex-D** [comment]
...

Russian is Europe and Asia, since Europe list is really long, I've choose to put it in Asia section.

Spanish? No, "Spanish (Argentina)" yep. And Argentina is in South America.

So don't troll, and if you want to change something, feel free to make a Pull Request.
