### ISSUE TITLE
BBCode?

### ISSUE THREAD

**Issue by pasterntt** [Alex-D/Trumbowyg#65]
Heyho, I like your WYSIWYG-Editor very much, I would use it, but there is no BBCode-Support :(
Is something like this planned?
 Would be happy if this will be answered, thanks and good greetings from germany,

Tim

**Comment by timint** [comment]
WYSIWYG, but stores the value in the textarea to bbcode instead of HTML. See how SCEditor does it. http://www.sceditor.com/

**Comment by Alex-D** [comment]
Trumbowyg is based on a content editable and execComand API. So to support markdown, a complete rewrite is needed.

Maybe for an another project :)

**Comment by timint** [comment]
I use Trumbowyg for every project I can. Love your work Alex. And so does the LiteCart Community.

For BBCode I've been using SCEditor which is practically dead and full of bugs.

Would it be able to throw in a bbcode converter as a plugin that converts the Trumbowyg HTML to bbcode right before submitting? With the support of bbcode I believe there is great potential to conquer the forum market with this editor. The only option up to date seems to be the massive hypernormous CKEditor.
