### ISSUE TITLE
The del button cannot remove the strike

### ISSUE THREAD

**Issue by ChinLeung** [Alex-D/Trumbowyg#651]
### Informations

**Browser version**: Version 61.0.3163.100 (Official Build) (64-bit)
**OS**: OS X El Capitan 10.11.6
**Screen resolution**: 1920 x 1080

### How to reproduce the bug?

Initialize the editor with the `del` button:

```
$('#editor').trumbowyg({
  svgPath: false,
  btns: [
    ['bold', 'italic', 'del']
  ]
});
```

Then enter some text in the editor, for example, `Hello World`.
Highlight the entered text and click on the `S` button in the toolbar. Every thing works so far.
However, if you click on the icon again, it does not removing the strike from the text.

Side note; This used to work in previous version (**2.7.2**).

**Comment by Alex-D** [comment]
I did not have to time to fix that, but if anyone has a fix, I can review and merge it :)

**Comment by KokinSSJ** [comment]
Hi, 
Find "t.semanticTag('strike', 'del');"  in sematicCode function and use 's' instead 'del' this should help. It will use <s> tags instead of <del>.
PS. If you can add this to the trumbowyg git repository.
