### ISSUE TITLE
change the position of choose file button for uploading images

### ISSUE THREAD

**Issue by mrzeeshanplus** [Alex-D/Trumbowyg#653]
I am using this editor for q2a site https://github.com/amiyasahu/q2a-trumbowyg-editor/issues/5

when we click on image icon for uploading images then the pop up of upload comes in that we have choose file button and description now what I want is I want to remove the pop up and I want a choose file button below the editor box.... how can I do that? can you tell me what I have to change and where I have to change?

**Comment by Alex-D** [comment]
You can't without recode another plugin ^^'
