### ISSUE TITLE
Application name looks too much like the last name of a certain US president

### ISSUE THREAD

**Issue by megamaiku** [Alex-D/Trumbowyg#655]
Hi @Alex-D ,

Someone brought to my attention that the name of the application is very close to Donald's last name. Would you consider using a simpler name that won't scare our users?

Thanks a lot!

**Comment by Alex-D** [comment]
Insteed of changing my plugin name, can we change the US president last name?
My SEO is so good, I can't rename now, sorry :/

**Comment by megamaiku** [comment]
Thanks @Alex-D . I do like your suggestion :satisfied:
