### ISSUE TITLE
Paste image plugin configuration

### ISSUE THREAD

**Issue by sausin** [Alex-D/Trumbowyg#656]
First off, thanks a lot for this editor!! It fits the lightweight segment awesomely!!! :+1: 

### Informations

**Browser version**: Chromium 62
**OS**: Linux
**Screen resolution**: HD

### How to reproduce the bug?

When using the `Paste image` plugin with trumbowyg, paste an image. This works correctly as it is now. However, sometimes it is desirable to have a class added to the `<img>` tag (for eg to make it responsive).

In the current implementation, this doesn't seem to be possible. However, I think an additional string for class could be supported by configuration option when initializing trumbowyg.

My javascript skills are terrible, but if someone can give sufficient hints on how to go about it and if it is an acceptable addition I would be willing to give it a try :smiley:

**Comment by Alex-D** [comment]
Try something like that:

```javascript
$('#editor').trumbowyg(...);
$('#editor').on('tbwchange', function() {
    $('#editor img:not(.myclass)').addClass('myclass');
});
```
