### ISSUE TITLE
Multiple instances icons disappear.

### ISSUE THREAD

**Issue by jplozgom** [Alex-D/Trumbowyg#657]
Hi, first thanks for an excellent job with this editor.

I'am trying to have several instances or editors in the same page but somehow icons don't appear. Any idea? All the instances hace the same options, different ID.
<img width="1621" alt="screen shot 2017-11-10 at 6 28 27 pm" src="https://user-images.githubusercontent.com/1085345/32682791-fc1a09aa-c644-11e7-86f6-9fc4c307b2b0.png">

thanks.

**Browser version**: Chrome
**OS**: MACOS
**Screen resolution**: 1440*900

**Comment by Alex-D** [comment]
Read the docs... or give me more information like javascript error logs

https://alex-d.github.io/Trumbowyg/documentation/#common-issues

**Comment by jplozgom** [comment]
Hi Alex, I did solved it , I wanted to confirm that it was not related to Trumbowyg, but to my installation. thanks

**Comment by nandobocca** [comment]
Hi @jplozgom, could you explain me how have you solved this problem?
Thanks.
