### ISSUE TITLE
Usability improvment

### ISSUE THREAD

**Issue by Fival85** [Alex-D/Trumbowyg#660]
### Informations

**Browser version**: Google Chrome 62.0.3202.94 
**OS**: Windows 10
**Screen resolution**: 1600x900px

### How to reproduce the bug?
Hey Alex,

the usability of the wysiwyg-editor needs a little bit of improvment i think.
Most people would use it like a word program:

1. When you haven't any text before, or a new blank line, i would click e.g on the bold-button and then write bold text, but the button do nothing in this moment. I must select the text to make it bold.
2. When I have a text selected and make it bold, further typings are even bold, but i could not exit this bold-mode with a click on the bold-button. The button stays active. I must select the next words to "unbold" them 

This seems to be the case with every button

**Comment by Alex-D** [comment]
I can't do that. It's a big & hard work to do and the Trumbowyg core can't be fixed to support that, sorry :/

**Comment by Fival85** [comment]
Ok i understand Alex,

but i think you should then fix the "bug", that the selected mode stays active, when selection is make to bold. You should only allow to mark text and change them, but when the user writes anything the default mode should be activated.
