### ISSUE TITLE
Wrong render on Firefox

### ISSUE THREAD

**Issue by verysimplenick** [Alex-D/Trumbowyg#661]
### Informations
![default](https://user-images.githubusercontent.com/922660/33070600-9807a642-cec9-11e7-8d8d-d3ffd5f22d40.png)

**Browser version**:
Firefox 57.0 (64-bit)
**OS**: win 10
**Screen resolution**:
2560x1080
### How to reproduce the bug?
Open https://alex-d.github.io/Trumbowyg/

**Comment by ndesorden** [comment]
With Firefox 58.0b5 (64-bit) same issue

**Comment by Alex-D** [comment]
Duplicate of #634
