### ISSUE TITLE
Emojify CDN broken?

### ISSUE THREAD

**Issue by RwbyChan** [Alex-D/Trumbowyg#662]
When trying to add the emojify plugin it looks like the CDN is broken?
Screenshot: http://prntscr.com/hds52e

- SVG:
https://cdnjs.cloudflare.com/ajax/libs/emojify.js/1.1.0/images/basic/bowtie.svg
^ seems to return "not found"

- PNG
https://cdnjs.cloudflare.com/ajax/libs/emojify.js/1.1.0/images/basic/bowtie.png
^ seems to work

But the plugin is using SVG to load the emotes?

**Comment by RwbyChan** [comment]
Then why doesn't it work for me? Also in my "inspect element" it shows svg stuff

**Comment by Globulopolis** [comment]
@RwbyChan show your code

**Comment by RwbyChan** [comment]
It's a whole app.js so I cut out the parts from the editor
```
emojify.setConfig({
        img_dir : 'https://cdnjs.cloudflare.com/ajax/libs/emojify.js/1.1.0/images/basic/',
    });

$(".wysiwyg-editor")[0] && $(".wysiwyg-editor").trumbowyg({
            autogrow: !0,
            btns: [
                ["viewHTML"], ['emoji'],
                ["formatting"],
                ["link"],
                ["insertImage"], "btnGrp-justify", "btnGrp-lists", ["horizontalRule"],
                ["removeformat"],
                ["fullscreen"]
            ]
        }) && emojify.run(), $('.trumbowyg-editor').on('input propertychange', function() {
            emojify.run()
        })
```

**Comment by Thielo** [comment]
Try without the last Trailing Slash.
`img_dir : '//cdnjs.cloudflare.com/ajax/libs/emojify.js/1.1.0/images/basic',`
Did the trick for me.

**Comment by zugangxue** [comment]
We met the same issue!
