### ISSUE TITLE
Double click to change image src not saving

### ISSUE THREAD

**Issue by satchamo** [Alex-D/Trumbowyg#669]
Thank you for building this! I love the idea of ditching ckeditor (which weighs in at 500KB). I found a little bug while playing around.

### Informations

**Browser version**: Latest Chrome, Firefox
**OS**: Windows 7
**Screen resolution**: N/A

### How to reproduce the bug?

1. Go to https://alex-d.github.io/Trumbowyg/demos/
1. In the example text editor, add a new image with this URL: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
1. Click Confirm
1. Google's logo appears. Neat!
1. Double click Google's logo
1. Change the URL to: https://duckduckgo.com/assets/logo_homepage.normal.v107.svg
1. Click Confirm
1. Google's logo is still visible :(

**Comment by satchamo** [comment]
Simple fix in #670

**Comment by Alex-D** [comment]
Great job!
Thanks :)
