### ISSUE TITLE
Upload Plugin: Image Size

### ISSUE THREAD

**Issue by yongjiajie** [Alex-D/Trumbowyg#671]
### Informations

**Browser version**: Chrome Version 62.0.3202.94 (Official Build) (64-bit)
**OS**: ubuntu 16.04 LTS
**Screen resolution**: 1920 x 1080

### How to reproduce the bug?
Not a bug.

After uploading an image in Trumbowyg via the Upload plugin, is it possible to control the size of the image uploaded?

**Comment by Alex-D** [comment]
What did you mean by "size"? If it's width, user can set a width.
If you want put some width/height, you should use some CSS on img tag.

**Comment by yongjiajie** [comment]
Hello @Alex-D, I am interested in showing thumbnails of the image in Trumbowyg, as opposed to the entire image uploaded. Thank you for your reply.

**Comment by Alex-D** [comment]
You just had to send the URL of the resized thumbnail image, Trumbowyg do not care about the original image size :)
