### ISSUE TITLE
Can we use http://zeptojs.com/ instead of jQuery?

### ISSUE THREAD

**Issue by AGhasemzadeh** [Alex-D/Trumbowyg#674]
Hello,
Can I use http://zeptojs.com instead of jQuery?

**Comment by Alex-D** [comment]
If:
- you have `svgPath` set to false or import yourself icons into your HTML, cf: https://alex-d.github.io/Trumbowyg/documentation/#svg-icons
- you did ot use upload plugin

Yep, it should works. Otherwise, nope.
