### ISSUE TITLE
Insert Caret at end of content?

### ISSUE THREAD

**Issue by MadMikeyB** [Alex-D/Trumbowyg#675]
Hi,

On blur and focus / destroy - re-init, is there a way for the caret to be inserted at the end of the content rather than the beginning?

**Comment by Alex-D** [comment]
Nope.

**Comment by Alex-D** [comment]
Sort of duplicate of #629

**Comment by MadMikeyB** [comment]
Thanks :)

**Comment by mrmnmly** [comment]
btw. is there any way of moving caret inside the editor via js?

**Comment by guirama** [comment]
Hi,

What is the command to insert any HTML at caret .

Best Regards

**Comment by Alex-D** [comment]
That's not OK in all browsers, but you can use execCmd with insertHtml:

https://github.com/Alex-D/Trumbowyg/blob/cf3c84cef53630f933bbd19e9db0b2372cfaf4bc/plugins/pasteembed/trumbowyg.pasteembed.js#L85
