### ISSUE TITLE
mailto links?

### ISSUE THREAD

**Issue by LorenzV** [Alex-D/Trumbowyg#68]
y isnt it allowed?

**Comment by Alex-D** [comment]
It's OK on the master version, you can put `mailto:youremail@thing.com` like `http://...` or anything you want.

**Comment by Alex-D** [comment]
I've just released the [`v2.0.0-beta.0`](https://github.com/Alex-D/Trumbowyg/releases/tag/2.0.0-beta.0) if you want check that the bug is correctly fixed.

Thanks!
