### ISSUE TITLE
The option removeformatPasted crashes IE and Chrome

### ISSUE THREAD

**Issue by projekt01** [Alex-D/Trumbowyg#681]
The option removeformatPasted=true forces to crash IE and Chrom browser with long text.
the browser is asking if the script should get aborted. If not the browser freezes with 100% CPU.

**Comment by Alex-D** [comment]
What did you mean by "long text"? How much chars in the textarea?

**Comment by samparmenter** [comment]
I don't know if this is the same issue but whenever I use the cleanpaste plugin it kills the tab in chrome. Issue seems to be in the `cleanIt` function in the cleanpaste plugin. The htmlBefore & htmlAfter arguments are identical which leads to an infinite loop in the first for loop as the comparison basically keeps going until it finds a difference in two identical strings.

**Comment by Alex-D** [comment]
@projekt01 did you use cleanPaste plugin?

**Comment by projekt01** [comment]
Hi Alex, yes I was using the the editor with only the cleanup text plugin and was testing with text from a MS Word file. That's what our customer do, paste ugly formatted word text into an Editor ;-)

**Comment by Alex-D** [comment]
OK, that confirm the @samparmenter hypothesis... So did we just need to stop if before/after are the same?

**Comment by samparmenter** [comment]
removeFormatPasted seems to be a basic function to strip formatting vs cleanPaste which is the more robust/fully featured version. Is that correct?

I think its just a case of perhaps putting in the quick check on the before/after input and making it clear that the two shouldn't be used in conjunction with each other.

**Comment by Alex-D** [comment]
Hum, `removeFormatPasted` and `cleanPaste` are incompatibles?

So we just need to add some docs and throw an error in `cleanPaste` if `removeFormatPasted` is set to `true`?

**Comment by samparmenter** [comment]
I would give it a quick test but from looking at the plugin and the main plugin code that handles the paste event you are replacing the pasted input with a "clean" version and then calling any subsequent paste handlers when removeFormatPasted is enabled. The cleanPaste plugin is then working on the editor contents that has already been replaced giving rise to the identical before paste and after paste contents.

Does that sound right?

**Comment by rsmithlal** [comment]
I just tested your proposed solution by turning off `removeFormatPasted` and keeping the `cleanPaste` plugin enabled, and it still gives me the same issue locking up the tab with 100% CPU when the before paste and after paste is identical. Basically what I did was paste into an empty editor, `ctrl + a` and then paste the same text again. So it seems that the problem is not that the two things are incompatible.

**Comment by Alex-D** [comment]
Can you retry with the latest 2.10.0 version please?

**Comment by yakky** [comment]
In 2.10 disabling one of the two options fixes the issue

**Comment by Alex-D** [comment]
Thanks for the feedback!
