### ISSUE TITLE
Insert Link popout is blocked by toolbar of another Trumbowyg at the bottom

### ISSUE THREAD

**Issue by mapattacker** [Alex-D/Trumbowyg#683]
### Informations

**Browser version**: Chrome v63, Safari v11
**OS**: Mac, Windows 7
**Screen resolution**: -

### How to reproduce the bug?
1. Have two trumbowyg in two text area forms.
2. Open the top trumbowyg's insert link to show the popup.
3. Part of the popup will be hidden by the bottom trumbowyg's toolbar.
4. It can be quite bad as I have one form whereby the confirm button is totally hidden behind the toolbar. Appreciate if u can take a look into this! Thank you!

![screen shot 2017-12-25 at 9 31 12 pm](https://user-images.githubusercontent.com/13524596/34340853-918726ea-e9c6-11e7-8a20-fbaebfb6e755.png)

**Comment by Alex-D** [comment]
Did you have the last version of Trumbowyg?
It should be fixed in 2.9+
cf https://github.com/Alex-D/Trumbowyg/pull/654

**Comment by mapattacker** [comment]
Hi, I am using v2.9.2 actually~

**Comment by Alex-D** [comment]
Can you investigate on the z-index? Try to increase it and say me back if it can resolve the problem.

Thanks :)

**Comment by Alex-D** [comment]
Fixed in 2.9.3 :)
