### ISSUE TITLE
panel with buttons doesn't appear

### ISSUE THREAD

**Issue by CalvinNunes** [Alex-D/Trumbowyg#684]
### How to reproduce the bug?

 I'm using a plugin for javascript to have an HTML Editor (WYSIWYG), called Trumbowyg. no errors appear when instantiating an creating elementes with this plugin, but for some reason that I want to discover, the panel with the buttons/options doesn't show up.
My Code:

```
var editorHtmlElement = document.createElement('textarea');
        editorHtmlElement.className = "col-md-6";           
        editorHtmlElement.setAttribute('placeholder', 'placeholder...');
        var OptionsTrumbowyg = {};

        OptionsTrumbowyg.btns = [
            ['undo', 'redo'],
            ['justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
            ['formatting'],
            ['strong', 'em', 'del'],
            ['link'],
            ['insertImage'],
            ['unorderedList', 'orderedList'],
            ['horizontalRule'],
            ['removeformat'],
        ];
        OptionsTrumbowyg.autogrow = true;  

        var editorHtmljQuery = $(editorHtmlElement);

        editorHtmljQuery.trumbowyg(OptionsTrumbowyg);
```
After that, I append the editorHtmlElement to a div or whatever.
no panel with buttons appear, even if I try with no custom options just the default... Anyone knows why? 
(No errors appears when loading page or something like that)

I Also posted a question on stackoverflow, that have some images to describe better what happen.
https://stackoverflow.com/questions/47994736/panel-with-buttons-doesnt-appear-on-trumbowyg-plugin

**Comment by Alex-D** [comment]
Without full code, I can't help you.

You should load, in this order: 

- jquery.js
- trumbowyg.js
- your-script.js

Also, be sure to include CSS in your head.

**Comment by CalvinNunes** [comment]
i made an edit, if it doesn't help i'm sorry, but i'll need to leave this plugin and get another one. Hope you can help me, i liked the style of trumbowyg

**Comment by Alex-D** [comment]
Wrap your "My JS used inside VIEWMODEL:" JS part into:

```javascript
jquery.ready(function() {
    // your code
})
```

**Comment by CalvinNunes** [comment]
didn't work... :(

**Comment by Alex-D** [comment]
Did you have any error in your browser console?

**Comment by CalvinNunes** [comment]
My friend, have you read my entire post? it's there that no errors show up. 
But anyway, i managed to make it work properly changing the created element from a textarea to a div, and placing the `.trumbowyg()` to the final of all appends and CSS declarations, then it worked properly.
I'm testing the resources of the plugin right now, but it seems to be great, thanks!
