### ISSUE TITLE
autogrow: false does not work

### ISSUE THREAD

**Issue by jreynoso666** [Alex-D/Trumbowyg#685]
![screenshot](https://user-images.githubusercontent.com/2913280/34388077-4b1adec2-eaf7-11e7-8901-40bb57994a23.png)

**Browser version**: Firefox 57.0.1 (64-bits)
**OS**: Debian GNU/Linux
**Screen resolution**:1366x703

### How to reproduce the bug?
$('#mytrumbowyg').trumbowyg({
    autogrow: false
});

It sets into  div
class="trumbowyg-editor theSelector"
dir="ltr"
contenteditable="true"
style="height: 40px;"

and the classes .trumbowyg-box, .trumbowyg-editor have min-height: 300px;  so, in the editor I have a scroll with height 40px.

**Comment by Alex-D** [comment]
`.trumbowyg-box, .trumbowyg-editor { min-height: auto; }`
should do what you want.
