### ISSUE TITLE
How can i make float toolbar?

### ISSUE THREAD

**Issue by pltnkv** [Alex-D/Trumbowyg#69]
like "inline:true" param in tinymce editor

**Comment by dandv** [comment]
@pltnkv: do you mean a toolbar that appears near the user's selection, like in [AlloyEditor](http://alloyeditor.com/demo/)?

![image](https://cloud.githubusercontent.com/assets/33569/7907087/8191d314-07e9-11e5-8870-09bb6e874cfe.png)

If so, I'm interested as well.

**Comment by Alex-D** [comment]
Need to rewrite all editor build part. Maybe in a next major but I don't have the time anymore to maintain this so I prefer close. I keep your purpose in mind :)
