### ISSUE TITLE
Select image already uploaded to the server

### ISSUE THREAD

**Issue by Bouni** [Alex-D/Trumbowyg#690]
First of all, thank you so much for this excellent editor!

Is it possible to browse/select an image that already has been uploaded?
I don't want to write a plugin if there is already a way to do this.

**Comment by Alex-D** [comment]
Thanks :)

There is no plugin for that at the moment :/

**Comment by Bouni** [comment]
Would you extend the upload plugin or better create a new plugin for that purpose?

**Comment by Alex-D** [comment]
Hum, seperate plugin I think. Maybe we could allow plugins to interract between them :)

**Comment by Alex-D** [comment]
I close this to keep issues clean.

Feel free to make a Pull Request if you have some cool things :)
