### ISSUE TITLE
Buttons locks its attribute on click or after use one time

### ISSUE THREAD

**Issue by SabirHossain** [Alex-D/Trumbowyg#691]
I'm new to Trumbowyg editor, I'm Trumbowyg with ASP.NET Core everything's working fine but once I click the "Bold" button then the "Bold" button locked it's state and don't go away even I double click, also some other buttons like backgroundColor, Italic button sometimes don't work..

Browser: Firefox 57.0.4 (64-bit), Chrome, IE.
Windows 10

**Comment by Alex-D** [comment]
Did you make a selection before click/re-click on bold? Trumbowyg does not support simple clic to enable/disable bold. So, you always should write the text, then select the part you want format, then click on buttons you want.

**Comment by hfrid** [comment]
I too have this problem.. once you click the bold button its "locked" in its active state. Clicking "remove format" clears it. Using v2.9.4.

**Comment by Alex-D** [comment]
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.9.4/trumbowyg.min.js"></script>
<!-- ... -->
<script src="Trumbowyg/dist/trumbowyg.min.js"></script>
```

Why??? Same for the CSS oO

Are you sure dist files are in 2.9.4?

**Comment by hfrid** [comment]
Sorry forgot to remove them when I switched to local files. Yeah 100% sure they are 2.9.4...

**Comment by Alex-D** [comment]
Does it works on the Trumbowyg landing: https://alex-d.github.io/Trumbowyg/ ?

**Comment by hfrid** [comment]
Yes

Den 31 jan. 2018 20:36 skrev "Alexandre Demode" <notifications@github.com>:

Does it works on the Trumbowyg landing: https://alex-d.github.io/Trumbowyg/
?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Alex-D/Trumbowyg/issues/691#issuecomment-362045677>,
or mute
the thread

**Comment by Alex-D** [comment]
I can't really help you if you can't make a buggy sample code with minimum amount of code :/

**Comment by hfrid** [comment]
Your CSS is conflicting with something in this one:

https://cdnjs.cloudflare.com/ajax/libs/materialize/0.96.1/css/materialize.min.css

If I remove this from my file the bold bug is gone. However the strikethrough is present even on your demo page:

http://youtu.be/SBT7RdbLhtw?hd=1

**Comment by Alex-D** [comment]
That's the only one button which is like that, no?

**Comment by hfrid** [comment]
On the demo page, yes. But same behavior on the bold button if I include
the materialize css on the same page.

Den 3 feb. 2018 01:02 skrev "Alexandre Demode" <notifications@github.com>:

**Comment by KishorCloudAnalogy** [comment]
> ```
> <script src="https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.9.4/trumbowyg.min.js"></script>
> 
> <script src="Trumbowyg/dist/trumbowyg.min.js"></script>
> ```
> 
> Why??? Same for the CSS oO
> 
> Are you sure dist files are in 2.9.4?

I  am facing same issue in React js .
Can you help me to resolve this issues.
Button is locked and not removed on again click.

**Comment by KishorCloudAnalogy** [comment]
I am facing same issue in React js .
Any one can help me to resolve this issues.
Button is locked and not removed on again click.

**Comment by theM1st** [comment]
The bugs still here...
Look for example [https://gifyu.com/image/kAIB](url)
Can you fix it? Thank you..

**Comment by Alex-D** [comment]
Nope. Too hard to fix that. But I keep that in mind for v3 #875 :)

**Comment by Valiumm** [comment]
// Text Styles
em { font-style: italic; }
strong { font-weight: 500; }
small { font-size: 75%; }

in _typography.scss in causing issue on Editor with Bold / Italic. If you comments thoses lines, it will work normally
