### ISSUE TITLE
Angular v1 trumbowyg component

### ISSUE THREAD

**Issue by jutaz** [Alex-D/Trumbowyg#692]
### Information

I have created an angular v1 component for `trumbowyg`, would be nice if it could make it into the list. Supports all events emitted by `trumbowyg`, as well as `placeholder`, `ngDisabled`. It also supports dynamic options and `ngModel` lifecycle.

### Usage

```html
<trumbowyg ng-model="$ctrl.html"
  ng-change="$ctrl.updateHTML()"
  ng-disabled="$ctrl.isInputDisabled"
  on-blur="$ctrl.onBlur()"
  placeholder="Start typing some text..."
  options="{btns: [['bold', 'italic'], ['unorderedList', 'orderedList']]}">
</trumbowyg>
```

https://github.com/jutaz/angular-trumbowyg

**Comment by Alex-D** [comment]
Why did you not update the existing one via a Pull Request?

**Comment by jutaz** [comment]
Because this one is fundamentally different - it’s using a component, which requires anewer angular version, it has a different API too. This would essentially be a complete rewrite of the existing one, and I’m not sure if it’s a good idea to update that package like so.

I’m also planning on actively maintaining this one.

**Comment by jutaz** [comment]
Another thing is that the existing package does not support NPM and is still on Bower, which means that it either has to be installed via Bower (which is deprecated), or it has to be added as git repository to `package.json`, which is not convenient, as it will not be cached by NPM proxies, patches have to be manually bumped in `package.json` and so on.

**Comment by Alex-D** [comment]
OK. OK. :)

If you want you can do a Pull Request to edit/add the link here: https://github.com/Alex-D/Trumbowyg/blob/develop/docs/index.html#L543

I do not use Angular anymore, so I do not know how it works with components.
