### ISSUE TITLE
Way too much character returned

### ISSUE THREAD

**Issue by felixvandal** [Alex-D/Trumbowyg#693]
### Informations
Hi!
I tried to use Trumbowyg with a simple dataset.
The data have less than 2000 char and Trumbowyg return over 20 000 char.
Database wise its not ideal.
Does Trumbowyg have a way to return less char?

**Browser version**:Chrome Version 63.0.3239.132 (Build officiel) (64 bits)
**OS**: Windows 7 
**Screen resolution**: 1920 x 1080

### How to reproduce the bug?
Take those fallowing data. (French incoming!! XD)

•	 Symbolisation hydraulique et exercices de lecture de plans
•	 Notions fondamentales de l'hydraulique :
o	Pression, débit, puissance, rendement volumétrique et mécanique
•	 Description des principales composantes hydrauliques :
o	Pompes à palettes, à engrenages et à pistons
o	Accumulateurs
o	Valves directionnelles (formes, types de centre, de commande et d'application)
o	Récepteurs (cylindres, moteurs)
•	Régulation de débit (meter in/ meter out)
•	Soupapes de pression (caractéristiques, types d'application et principes de fonctionnement)
o	Soupape de sécurité
o	Soupape réductrice de pression
o	Soupape d’équilibrage (counterbalance valve)
o	Soupape de séquence
o	Etc.
•	Fluides hydrauliques, tuyauterie, raccords et réservoirs
•	Étude des principales causes de bris hydrauliques : 
o	Contamination, cavitation, température
•	Étude des solutions à apporter à un réseau afin d'éviter les principaux bris hydrauliques : 
o	Filtration, entretien et rinçage
•	Méthodes de diagnostic appliquées à l'hydraulique : 
o	Association des symptômes à des possibilités de bris
o	Méthodes de prise de données
o	Sécurité face à l'hydraulique
•	Laboratoires : 
o	Ajustements (compensateur d'une pompe, soupape de sécurité) 
o	Ajustement d’une soupape de séquence et d’une soupape réductrice de pression
o	Rendement volumétrique (vérification d'une pompe)
o	Montage d'un circuit à régulation de débit
o	Montage d'un circuit à régulation de débit à pression compensée 
o	Dépannage de systèmes hydrauliques

It come from a word document.
The small bullets are the parent list and the big one are a list in the list element.

I used $("#selector").trumbowyg("html");

I have noted 2 ways to realise that (probably do the same but is worth to point out)
https://alex-d.github.io/Trumbowyg/documentation/core/#manage-content
https://alex-d.github.io/Trumbowyg/documentation/#manage-content

I join what trumbowyg return in a separated file.
[Problem.txt](https://github.com/Alex-D/Trumbowyg/files/1633039/Problem.txt)

So far Trumbowyg is the best editor i have found.
I really dont want to change WYSIWYG editor!

### Update 1:
I did some tests and the problem come from coping and pasting text from a word document.
If the text come from a pdf its ok on a bigger dataset than the one proposed here.

Thank you in advance!!!

**Comment by Alex-D** [comment]
Hey!

You should use the clean paste plugin: https://alex-d.github.io/Trumbowyg/documentation/plugins/#plugin-cleanpaste

**Comment by felixvandal** [comment]
Hello!
Thank you for the fast and accurate support.
I followed the instruction on the site to use plugin and used cleanpaste and it work like a charm.
Thank you again for your time!
