### ISSUE TITLE
resetCSS option: add value for list-style?

### ISSUE THREAD

**Issue by larsboldt** [Alex-D/Trumbowyg#696]
### Informations
When using the resetCSS option, shouldn't Trumbowyg have a value for list-style? If set globally to none it affects Trumbowyg unordered lists as well.

**Browser version**: Chrome
**OS**: OSX

### How to reproduce the bug?
Set a global CSS value with ul { list-style: none }
Unordered list in editor now has no bullets.

**Comment by Alex-D** [comment]
You can make a Pull Request for that :)
