### ISSUE TITLE
Svg icons replaces by pilcrow symbol ¶ 

### ISSUE THREAD

**Issue by SoldierCorp** [Alex-D/Trumbowyg#698]
### Informations
I'm submiting my form with ajax to a laravel backend and after success, all the symbolbs in the editor or even the icons out there, are being replaces by the pilcrow symbol ¶.

![image](https://user-images.githubusercontent.com/1775881/35081448-cfe2d9d2-fbd9-11e7-8ad4-6f23ecb32961.png)

**Browser version**:
Chrome 63
**OS**:
macOs sierra
**Screen resolution**:
2880 x 1800

**Comment by Alex-D** [comment]
Without reproduction I can't help you.
