### ISSUE TITLE
KeyCode don't fire onChange

### ISSUE THREAD

**Issue by Themandunord** [Alex-D/Trumbowyg#700]
### Informations
Hi @Alex-D,
I don't understand why some key don't fire onchange event.

### How to reproduce the bug?
When I write a `}` character (with a `Alt Gr + }`) the onchange is not emit.

I use the https://github.com/RD17/react-trumbowyg component, but I suppose that the issue is on this package. 

Remy.

**Comment by Alex-D** [comment]
You should use `tbwchange`

https://alex-d.github.io/Trumbowyg/documentation/#events

Try it: https://jsfiddle.net/smfmsLsa/4/

**Comment by Themandunord** [comment]
Hi @Alex-D,

Yes it's work on your jsfiddle. But I don't succeed on my computer.
I see a weird behavior. Here a gif of the problem : 

![multi-btn](https://user-images.githubusercontent.com/2819925/35326796-0f64f9fa-00f8-11e8-8f8c-c966c8c28ecb.gif)

As you can see, if I write `a`, the `tbwchange` is triggered.
If I write `{` (with Alt Gr) the trigger is not fired.
And the last test it is when I write `{` many times with speed typing. And it's fired.

With my previous test, it is with slow typing.

I put a breakpoint at lines that trigger `tbwchange` event for the test.

Do you seed the problem ?

I have Windows 10, my colleagues too, and they have the same behavior.

Thanks.

**Comment by Alex-D** [comment]
WAAA I can't reproduce... What's your browser / OS / keyboard mapping / ... ?

**Comment by Themandunord** [comment]
Chrome 63.0.3239.132, Windows 10 / AZERTY (normal mode, no hack).

But, I copy paste the code from react-trumbowyg in my project, and change : 
from
```
trumbowygInstance.on('tbwchange', (e) => onChange)
```
to
```
trumbowygInstance.on('tbwchange', (e) => {
        onChange(e);
      })
```

And I update your lib to the last version.

It's weird but it's bette works.

I don't know why this behavior happened, but know `}` it's triggered a lot of times.

I suppose that your `ctrl` variable is not set very well, and depends of the time between the event is fired and the code is computed

**Comment by Alex-D** [comment]
Ah, ok. It was fixed in last version ;)

**Comment by Themandunord** [comment]
Can you link the commit ? I'm interested :)

**Comment by Alex-D** [comment]
I think it's that: https://github.com/Alex-D/Trumbowyg/commit/3bfe43f4207bd4aa81fe11d23f3390e4c9702a20#diff-a57e0e52aed1451208c5f2010cd3b537
