### ISSUE TITLE
how to use trumbowyg outside a form tag

### ISSUE THREAD

**Issue by Nazkter** [Alex-D/Trumbowyg#704]
I'm trying to use trumbowyg outside a form, I already know that I need to write the form="form_id" attribute in the textarea. there is a way to configure the init function to insert that attribute in the textarea automatically?. 

I temporally fixed it in this way:
```
$('#post_id').trumbowyg();
$('textarea[name="post_id"]').attr('form', 'form_id');
```
but it will be great if I can configure it in the init function.

**Comment by Alex-D** [comment]
You can't configure that in Trumbowyg, but your code is really fine for that :)

**Comment by Nazkter** [comment]
@Alex-D  I was thinking that this can be an enhancement. I am sure that I am not the only one that needs this configuration. If you think that it is ok, I could make a pull request and include this in the "core". I just need to know where to find the code that generates the textarea.

**Comment by Alex-D** [comment]
Yep, it should be here: https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L498
