### ISSUE TITLE
Unable to disable quote after using it for a section of text.

### ISSUE THREAD

**Issue by smjnab** [Alex-D/Trumbowyg#705]
### Informations
When using FireFox. If you use quote, the editor keeps using it and it is not possible to turn if off. Tested with Chromium and the error is not present.

**Browser version**: FireFox 58.0.1
**OS**: Linux KDE Neon
**Screen resolution**: 1920*1080

### How to reproduce the bug?
I confirmed the issue using the demo at https://alex-d.github.io/Trumbowyg/.

If you look at the html code, it keeps moving the </blockquote> to be at the end of all content.

I have tested various ways to write and press the buttons, the result is the same. Write text, select it, press quote. Text is made into a quote block. Write some more text, or hit return a couple of times, and then write text and select it and click paragraph or H1 and the text remains in quote block.

I have tested without using any FireFox addons and the result was the same.

I have tested on my own site by changing the trumbowyg options, but has not made a difference.

**Comment by Alex-D** [comment]
Hey!

I know this bug, but Idk how to fix it :/

**Comment by Faks** [comment]
setup up full debug on jquery,the it's easy to track the bug after what i see i can say one thing there must be a loop bug or last element append bug try look in to this direction if had free time i could debug and find it but now bussy on projects.

**Comment by Alex-D** [comment]
Duplicates #532

@Faks you can continue on the other issue :)
