### ISSUE TITLE
Is there an 'onchange' event?

### ISSUE THREAD

**Issue by MihailRussu** [Alex-D/Trumbowyg#71]
I'm trying to show a live preview where a partial content is being edited in "Trumbowyg". I tried multiple events including **keyup**, **change**, **twbfocus**, **twbblur** but none give the desired effect. The **keyup** event works great when a user is changing something manually in the editor but nothing else works when editor's toolbar is used (i.e. some text made bold) until user types in something. Also, the "native" event (twbfocus, twbblur) examples here don't fire at all: https://alex-d.github.io/Trumbowyg/documentation.html#events

Is there a way to know when content in the editor was changed?

Thanks!

**Comment by ktmn** [comment]
The events in the documentation http://alex-d.github.io/Trumbowyg/documentation.html#events have a typo, tbwblur not twb.

**Comment by Alex-D** [comment]
Documentation was fix'd :)

I need to add some events and document them. I prepare the future version of Trumbowyg (v2) on the master branch, I will take a look to add that.

**Comment by Alex-D** [comment]
I've add a `tbwchange` event on the master branch. Soon in a release.

**Comment by Alex-D** [comment]
I've just released the [`v2.0.0-beta.0`](https://github.com/Alex-D/Trumbowyg/releases/tag/2.0.0-beta.0) if you want check that the bug is correctly fixed.

Thanks!

**Comment by maxmironov** [comment]
```onchange``` is not fired when we cut editor contents using context menu or Ctrl-X hotkey.
