### ISSUE TITLE
It's possible to start in fullscreen ?

### ISSUE THREAD

**Issue by adalenv** [Alex-D/Trumbowyg#713]

**Comment by Alex-D** [comment]
Hum, nope :/

But it can be done by adding a `fullscreen` API which calls this method: https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L1267

**Comment by adalenv** [comment]
yes . i have done this way 
thanks

**Comment by Alex-D** [comment]
Can you Pull Request the modification?

**Comment by adalenv** [comment]
Created a Pull Request!

**Comment by wilmaribg** [comment]
use execCmd ej

el.trumbowyg('execCmd', {cmd: 'fullscreen'})

**Comment by templatetuners** [comment]
It is possible to run fullscren on focus?

**Comment by Alex-D** [comment]
You can code it ;)

**Comment by xmluozp** [comment]
It's nice to add it as a builtin. I mean, a full-screen-start-mode.
Usually, mobile users will not doing edit in a form. Because of the virtual keyboard. It will block half of your mobile phone screen.
