### ISSUE TITLE
How do you strip html tags when pasting?

### ISSUE THREAD

**Issue by cheborneck** [Alex-D/Trumbowyg#716]
I've tried using the cleanpaste and allowtagsfrompaste plug-ins and none will clean a pasted drop from a drag.

**Comment by Alex-D** [comment]
Because drop is not paste and so we maybe need to check the new event. Maybe you could help on this :)

**Comment by cheborneck** [comment]
I did try to incorporate a drop event into the main script and was able to get as far as getting the value but couldn't get the value into place into the editor. Briefly looked at making an add-on but didn't know how to integrate. Any helpful tips and I can certainly pursue further.

Regards,

Tom Hare

On Feb 17, 2018, at 7:54 PM, Alexandre Demode <notifications@github.com<mailto:notifications@github.com>> wrote:


Because drop is not paste and so we maybe need to check the new event. Maybe you could help on this :)
