### ISSUE TITLE
How to  insert checkbox in new plugin modal

### ISSUE THREAD

**Issue by Nazkter** [Alex-D/Trumbowyg#721]
I want to insert a checkbox in the modal, but I can't find a way to do this. I can see that the core supports text inputs, but no other type of input.

There is a way to create the checkbox? (in the future I will need to insert a "select").

Thanks

**Comment by Nazkter** [comment]
@edwinveldhuizen thanks!!, can you show me how to add that checkbox to the modal? I exactly need to add that checkbox to the 'createlink' function and to other plugin that I am creating.

**Comment by Alex-D** [comment]
Merged, in develop :)
