### ISSUE TITLE
Bold, Italics, Underline not active when clicked

### ISSUE THREAD

**Issue by jsw0002** [Alex-D/Trumbowyg#723]
### Information

**Browser version**: Microsoft Edge 41, Google Chrome 64, Firefox 58, IE 11
**OS**: Windows 10
**Screen resolution**: All

### How to reproduce the bug?

Click the bold/italics/underline button and it should stay active. They should function similar to the way the justify and list buttons currently work.

Thanks

**Comment by Alex-D** [comment]
Nope, I can't do that, sorry. Already closed thousands of time :/
