### ISSUE TITLE
This is not bug but a question

### ISSUE THREAD

**Issue by Faks** [Alex-D/Trumbowyg#728]
i was working on custom sizes but editor forces from base code font size names is any way to override 
![Image](https://i.imgur.com/WwMdOG6.jpg)

Bug or what ??
![Image](https://i.imgur.com/3lB5Vyw.jpg)

**Comment by Alex-D** [comment]
That's plugin is not released yet, so yep, it can be buggy ^^'

**Comment by Alex-D** [comment]
Can you retry with the new released 2.10.0 please?
