### ISSUE TITLE
.trumbowyg('html') Returns False

### ISSUE THREAD

**Issue by purplekrayons** [Alex-D/Trumbowyg#731]
### Informations

**Browser version**: Chrome Version 65.0.3325.146 (Official Build) (64-bit)
**OS**: Windows 10
**Screen resolution**: 1920x1080

### Bug Details

Possibly related to https://github.com/Alex-D/Trumbowyg/issues/164

`.trumbowyg('html')` is returning **false**. I am initializing the editor inside of a [SweetAlert2](https://sweetalert2.github.io/) modal and attempting to get the contents of the editor via a function call later on. I have made sure to use unique id's as suggested in the linked issue #164 

Example Trigger:
`<button class="myButton" data-uuid="13f824cc-21cf-11e8-b467-0ed5f89f718b">Save Stuff</button>`

Example JS:
```javascript
$('.myButton').on('click', function() {

    var uuid = $(this).data('uuid');

    swal({
        html: '<div id="trumbowyg_' + uuid + '">APPLES</div>',
        showCancelButton: true,
        showConfirmButton: true,
        confirmButtonText: 'Save',
        cancelButtonText: 'Close'
    }).then((result) => {
        if (result.value) {
            saveComments(uuid);
        }
    });

    $('#trumbowyg_' + uuid).trumbowyg();

})

function saveComments(uuid) {
    var comments = $('#trumbowyg_' + uuid).trumbowyg('html')
    console.log(comments)
}
```

Expected return from saveComments():

> APPLES

Actual return from saveComments():

> false

**Comment by Alex-D** [comment]
You are here: https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L183

It's because you don't wait for Trumbowyg to be initialized or something like this. So the editor does not exists when you try to access it.

Try that: 

```javascript
$('#trumbowyg_' + uuid).trumbowyg();
// add this line
$('#trumbowyg_' + uuid).on('tbwinit', function() { console.log('INIT') });
```

and

```javascript
function saveComments(uuid) {
    console.log($('#trumbowyg_' + uuid).length); // Should be 1
    var comments = $('#trumbowyg_' + uuid).trumbowyg('html');
    console.log(comments);
}
```

Then, you can check if Trumbowyg is init before using it and still exists when you try to call some methods on it.

**Comment by purplekrayons** [comment]
I had also assumed it was related to the element not being available in the DOM at the time I attempt to grab its value. However, it doesn't make sense because I am successfully initializing the trumbowyg editor which means the element is definitely loaded in the DOM. There is nothing that removes the editor from the DOM between the time its initialized, and the time I attempt to get the value.

> CONSOLE:   initializing swal...
> CONSOLE:   initializing trumbowyg...
> CONSOLE:   INIT
> CONSOLE:   0
> CONSOLE:   false
> CONSOLE:   {"uuid":"0e5441f9-05fe-4d43-b6d3-9c912ab2aedd","comments":false}

**Comment by Alex-D** [comment]
jQuery do not add data attributes to the DOM, it keep it in memory. So, no.

> CONSOLE: 0

You do not have any Trumbowyg running at this time. Is sweet alert dropping his content when it resolves?

**Comment by Alex-D** [comment]
Can you give more details about how did you resolve that?

**Comment by purplekrayons** [comment]
This was not a Trumbowyg issue -- sweetalert2 was destroying itself, and thus inherently the trumbowyg editor before the trumbowyg value could be captured. I corrected this issue by capturing the value and passing it as an argument to my saveComments() function.

```
$('.myButton').on('click', function() {

    var uuid = $(this).data('uuid');

    swal({
        html: '<div id="trumbowyg_' + uuid + '">APPLES</div>',
        showCancelButton: true,
        showConfirmButton: true,
        confirmButtonText: 'Save',
        cancelButtonText: 'Close'
    }).then((result) => {
        if (result.value) {
            var comments = $('#trumbowyg_' + uuid).trumbowyg('html')
            saveComments(uuid, comments);
        }
    });

    $('#trumbowyg_' + uuid).trumbowyg();

})

function saveComments(uuid, comments) {
    console.log(comments)
}
```

**Comment by Alex-D** [comment]
Good to know! :)

Thanks
