### ISSUE TITLE
[Presentation] Advanced plugins

### ISSUE THREAD

**Issue by forelabs** [Alex-D/Trumbowyg#733]
This "Issue" is just to show you what I have done with trumbowyg and if you would like to have some features of it.

Following features shown here:

* content pane bar (incl. sidebar pane)
* indentation
* image floating
* improved image resizer
* image gallery picker

![ezgif-5-fbba2c829a](https://user-images.githubusercontent.com/3809644/37147457-45a055e6-22c7-11e8-9366-00d24c59de1a.gif)

I may create PRs for the tiny plugins, e.g. floating and indentation.
Maybe I will also add the improvements for the image resizer.
But I have no clue what you think about the content pane bar or the image gallery picker,
but as far as I can see the gallery picker is in progress according to https://github.com/Alex-D/Trumbowyg/issues/690.

The content pane bar is adjusted to fit our design rules and also includes 1 or 2 addiotional features,
which may not be needed in a plugin version. As you may have noticed the content pane bar is context sensitive. But before I go for a shared plugin version I want to know if the work is worth it, because the plugin is not quite small and you said you want to keep it small (the minified plugin is still 9kb big).

Anyway, thanks for this nice editor, it is a pleassure to create custom plugins for it.

**Comment by tomsx** [comment]
Good work - looking forward to it!

**Comment by forelabs** [comment]
I need some more time, sorry. Currently a lot of other stuff to do.

**Comment by abozhinov** [comment]
Looks great!

**Comment by RakeshKailash** [comment]
Wow, that's awesome!

**Comment by Alex-D** [comment]
Feel free to reopen if there is any update.

I work on v3 now (see #875 for more details). I hope making modules (plugins) should be more easy to do.

**Comment by tucuta** [comment]
Hi i like this editor.
Where can I download these featured?

**Comment by forelabs** [comment]
The context bar can be found here:
https://github.com/brandslisten/trumbowyg_rails/tree/master/vendor/assets/javascripts/trumbowyg/vendor/plugins/contextbar 

Others are available within the plug-ins folder. 
Since this is a public library feel free to use it.

**Comment by tucuta** [comment]
> The context bar can be found here:
> https://github.com/brandslisten/trumbowyg_rails/tree/master/vendor/assets/javascripts/trumbowyg/vendor/plugins/contextbar
> 
> Others are available within the plug-ins folder.
> Since this is a public library feel free to use it.

Thank you.
;-)(y)

**Comment by clwilliams8** [comment]
I downloaded the JS file and included it in my compiled js like:

// context bar
require('./trumbowyg.contextbar')

Is there anything else I have to do? It's not working, no console errors

**Comment by forelabs** [comment]
You have to enable / load the Plugin. See general Plugin loading for this.

**Comment by alombia** [comment]
how do you enable/load the plugin?

**Comment by forelabs** [comment]
> how do you enable/load the plugin?

As you would with any other plugin
https://alex-d.github.io/Trumbowyg/documentation/plugins/

**Comment by alombia** [comment]
Still cant make it to work. Added the js file as instructed. The documentation simply says to add the js file and that's it.

**Comment by forelabs** [comment]
> Still cant make it to work. Added the js file as instructed. The documentation simply says to add the js file and that's it.

The documentation says you have to name the plugin within the plugins list as well.

```javascript
$('#my-editor').trumbowyg({
    plugins: {
      contextbar:  {}
    }
});
```

and `{}` can be options you may want to modify.
Default options are visible in the file.

```javascript
  var defaultOptions = {
      enabled: false,
      hideBtnPane: false,
      btnPaneBtns: undefined,
      centerBtnPane: false,
      sidePane: false,
      btns: {
        side: ['p','blockquote','h2','h3','h4','internalLink','createLink','upload','insertImage','insertImageFromGallery','justifyLeft','justifyCenter','justifyRight','justifyFull','table','unorderedList','orderedList','outdent','indent','horizontalRule'],
        text: ['p','blockquote','h2','h3','h4','strong','em','underline','createLink','justifyLeft','justifyCenter','justifyRight','justifyFull','unorderedList','orderedList','outdent','indent','preformatted'],
        table: ['tableAddRow','tableAddColumn','tableDeleteRow','tableDeleteColumn','tableDestroy'],
        a: ['editLink','unlink'],
        img: ['editImage','floatleft','floatright','justifyLeft','justifyCenter','justifyRight','deleteImage']
      },
      mapping: {
        td: 'table',
        tr: 'table'
      }
  };
```

**Comment by tsvetelinpetrov** [comment]
![image](https://user-images.githubusercontent.com/42267885/103484442-9232dd80-4df7-11eb-958c-c7561086b887.png)
Any ideas why is that happening? Missing styles or?
