### ISSUE TITLE
Upload Plugin with PHP server

### ISSUE THREAD

**Issue by ecsanchesjr** [Alex-D/Trumbowyg#735]
I want to use Upload plugin to save a image in my server with PHP.

I searched how to do that, but all of information which I found don't helped me.

So, sorry about a, maybe, newbie question, but...
How I do that?

**Comment by Globulopolis** [comment]
Maybe this could help https://github.com/moxiecode/plupload/blob/master/examples/upload.php

**Comment by Alex-D** [comment]
Some doc here: https://alex-d.github.io/Trumbowyg/documentation/plugins/#plugin-upload
