### ISSUE TITLE
Cordova Crosswalk Chrome new line issue

### ISSUE THREAD

**Issue by crater6000** [Alex-D/Trumbowyg#736]
### Informations
I have included this plugin for my cordova crosswalk app. I am facing this issue when i try to go to new line the text content get warped to the first line. problem here is I am not able to write multi line content.
please do the needful.

**Browser version**: Chrome 49
**OS**: Android
**Platform**: Android - Cordova with Crosswalk

**Comment by Alex-D** [comment]
Trumbowyg is not optimized for mobile. It is optimized to be light.
If I start to support all the edge cases, the plugin will become fat.

So, sorry, I cannot test your specific case and I probably never fix it.
