### ISSUE TITLE
Autocomplete popout is blocked by toolbar of Trumbowyg

### ISSUE THREAD

**Issue by liuyigh** [Alex-D/Trumbowyg#738]
### Informations

**Browser version**: Firefox 58.0.2
**OS**: macOS 10.13.2
**Screen resolution**: 1920x1200

### How to reproduce the bug?

1. a form generated by web2py SQLFORM with autocomplete widget. [web2py [book](http://web2py.com/books/default/chapter/29/07/forms-and-validators#Autocomplete-widget), [code](https://github.com/rimbi/bookcrawler/blob/master/web2py/gluon/sqlhtml.py#L395)]
2. use trumbowyg to convert one textarea in the form to rich text editor
3. type in a field with autocomplete widget above the trumbowyg
4. autocomplete popout is blocked by toolbar, as in pic:

![screen shot 2018-03-12 at 22 54 22](https://user-images.githubusercontent.com/5641850/37324946-f80233ec-2648-11e8-9606-f638d62bb5d0.png)

sorry, the issue is in a form that requires login. I cannot point you directly to the website.

**Comment by Alex-D** [comment]
You need to change the CSS of the other plugin to increase his z-index.

Can't do anything on my side.

**Comment by liuyigh** [comment]
thank you very much for the pointer to CSS z-index. I didn’t know such properties. Sorry.

TrumboWyg is really a great tool. Thank you for developing it and providing it for free.
