### ISSUE TITLE
Uploading Files (not images)

### ISSUE THREAD

**Issue by pschilly** [Alex-D/Trumbowyg#739]
This is definitely not a current "bug" or anything of the sort - more of a question. Is it possible to use the uploader to upload files and create links to said files (IE uploading a PDF) ? From what I can tell, the current uploader plugin is limited to images (which makes sense)... 

Any assistance would be great!

**Comment by Alex-D** [comment]
Hum, I've made the upload plugin for images since you can include some images into the content of the editor.

Did you want to include a PDF ready in the editor? Or just put a link to it?

If it's just a link, you should create your own file upload.

**Comment by pschilly** [comment]
Hey Alex,

Thanks for the quick response - I am looking for the latter. I will look into getting a more robust "file manager" plugin / entirely separate system. I just figured having an uploader similar to what you have now that inserts a hyperlink to the file afterwards would be useful.

Any rate - awesome plugin mate, works great! Only thing that would be a nice-to-have would be context menus (right click) for things like images / links. But thats definitely not a deal breaker.

Cheers,

**Comment by jbbpatel94** [comment]
Hey @Alex-D ,

I want same feature (upload a file instead of image) as @pschilly  mention above. The plugin upload.js is limited to image, so can we make this plugin flexible based on file type, if its image then will continue same process otherwise will add a link of file to editor
