### ISSUE TITLE
Free Color choose (html code)

### ISSUE THREAD

**Issue by thribiere** [Alex-D/Trumbowyg#74]
Hi, I need to add a button to the dropdown color plugin to permit user to use a specific html color (ex : #FF0000).
I've modified the plugin buildDropdown function, if tou want to add this to the plugin : 

      function buildDropdown(func){
      /* ... not modified : $.each ... */

        // add free color btn
        var btn = '_'+func+'_color_free';
        $.trumbowyg.opts.btnsDef[btn] = {
            func: function (params, tbw){
                tbw.openModalInsert( "Specific Color",{
                        html_value: {
                            label: 'HTML',
                        },
                    },
                    // callback
                    function(values){
                        tbw.execCmd(func,values['html_value']);

                        return true;
                    }
                );
            },
            text:'#',
            // style adjust for displaying the text
            style:'text-indent: 0px;line-height: 20px;padding: 0 5px;'
        };
        dropdown.push(btn);

        return dropdown;
    }

**Comment by Alex-D** [comment]
I've added this to the color plugin for the v2.

Thanks! :)
