### ISSUE TITLE
Custom foreground color applied as font element

### ISSUE THREAD

**Issue by TheGreenkey** [Alex-D/Trumbowyg#740]
### Informations

**Browser version**: 64.0.3282.186
**OS**: Win 8.1
**Screen resolution**: 2560x1440

### How to reproduce the bug?

1. Type text into editor and select it
2. Select custom color from foreground color dropdown
3. Enter any hex value and confirm
4. Text should now be surrounded by <font> element

It's not really a bug but I think it should be addressed. The <font> tag has been deprecated in HTML 4.01 and is obsolete since HTML5. The solution would be the same as for the predefined colors: use a span with css styling.

[MDN Page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font)

**Comment by Alex-D** [comment]
Just need to add `forceCss: true,` here:

https://github.com/Alex-D/Trumbowyg/blob/develop/plugins/colors/trumbowyg.colors.js#L176

**Comment by jobejas** [comment]
Fixed my issue by copying the file and modifying the callback in trumbowyg.color.js

```
// callback
  function (values) {
      trumbowyg.execCmd(fn, values.color, true); // <--- seems to me forceCSS is not used 
      return true;
  }
```
