### ISSUE TITLE
Upload plugin doesn't work on IE

### ISSUE THREAD

**Issue by paolo75015** [Alex-D/Trumbowyg#741]
On my website i've installed the upload plugin : 

- works fine on Firefox and Chrome
- doesn't work on IE11

When I tried to debug I noticed that the $_FILES variable is empty when sended via IE11 or IE10. var_dump($_FILES) is array(0) {}.

Any idea to fix it ? Am I missing a parameter ?

**Comment by Alex-D** [comment]
I need to check that. Idk for now :/

**Comment by philipca** [comment]
Is this "bug:plugin" found by many people? I have tested uploading images using IE10 and IE11 on my website and they work OK. I am using https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.17.0/plugins/upload/trumbowyg.upload.js

**Comment by Alex-D** [comment]
So I assume taht the upload plugin is working on IE :)

I've never checked since my comment (oops)
