### ISSUE TITLE
A terrible issue about "Emoji Plug"

### ISSUE THREAD

**Issue by zugangxue** [Alex-D/Trumbowyg#742]
### Informations
Just have a look at the image:
http://www.bluestep.cc/demos/20180317160335.png

**Browser version**:
All browsers 
**Screen resolution**:

**Comment by zugangxue** [comment]
Please do me a favor, thx a lot.

**Comment by Alex-D** [comment]
https://alex-d.github.io/Trumbowyg/demos/#plugins-emoji

Did it works here?

Don't forget the CSS file :)

**Comment by zugangxue** [comment]
Now I can add emoji now, the issue caused by I used the "textarea" HTML TAG,  I changed it with "DIV" TAG, but a new issue occured:
when we add some words in the middle of the content, the cursor always focus the start of the content.

**Comment by Alex-D** [comment]
Should work now :)
