### ISSUE TITLE
Codestyle: jshint -> eslint + prettier + precommit?

### ISSUE THREAD

**Issue by pavelloz** [Alex-D/Trumbowyg#743]
Well, this is not a bug or feature request but rather question/discussion invitation/improvement proposition.

Because you clearly have a style guide in mind (and probably in .jshintrc)
https://github.com/Alex-D/Trumbowyg/pull/737#pullrequestreview-103376167

I propose to:
a) migrate over to eslint
b) automate code style checks using `prettier-eslint --fix --write` using npm scripts and pre-commit hooks

This would eliminate time spent on thinking about code style/formatting, because it would be handled by the tools.

**Comment by pavelloz** [comment]
Yep, hook is optional, npm script (ie. test) with lint-staged (which makes checks to be run only on staged files, not the whole repo) makes it very fast.

BTW. How often someone develops code without installing dependencies (to test if the changes dont break anything) when there is no very high test coverage? I never seen anyone that brave to be honest ;)

**Comment by Alex-D** [comment]
My point is: there already is a lint which can be run via `npm run test`. It is configured in Gulpfile.

**Comment by pavelloz** [comment]
👍
