### ISSUE TITLE
Chrome new line / br inserts span

### ISSUE THREAD

**Issue by pixxelfactory** [Alex-D/Trumbowyg#744]
### Informations
If for some reason the body has a font-size: xx%; applied,
Chrome inserts spans in the editor when user goes to a new line (br)

**Browser version**: Chrome (latest)
**OS**: Osx 10.11.6, Windows 7

### How to reproduce the bug?
1.) Create a basic html5 structure
2.) Include latest jquery and trumbowyg
3.) In the page css add font-size: 90%; to the body for instance
4.) Go inside the editor, enter a text, go to the middle of a line and press shift/enter
5.) Take a look at the source

**Comment by rohantahiliani** [comment]
This happens in several scenarios. You don't have to set the font size, just enter 4 lines of text, now go to the start of the third line, hit Backspace, hit Enter, and the third line is now wrapped in a span.  Seems to add spans when hitting Backspace/Enter between two lines of text.

**Comment by Alex-D** [comment]
Should be fixed as of 2.22.0
