### ISSUE TITLE
Wrap text with image in WYSIWYG mode.

### ISSUE THREAD

**Issue by biswajitpaul01** [Alex-D/Trumbowyg#751]
### Informations
How can I wrap text on the right side of image in WYSIWYG mode? I can see that in html view mode, the image is wrapped with p tag and it is occupying full width. But my client do not like to work or change it in html view mode. Please help.
**Browser version**:
**OS**:
**Screen resolution**:

**Comment by Alex-D** [comment]
You can't. Trumbowyg does not supports that.

Sorry :/

**Comment by Karthikeyan-tv** [comment]
Hi @Alex-D, Does this editor support this feature now?

**Comment by oleteacher** [comment]
Hard to believe such a nice and useful library does not allow align image left or right. Setup and now find cannot use in the classroom :(
