### ISSUE TITLE
input delay when I inserted base64 image on Trumbowyg

### ISSUE THREAD

**Issue by Jeong-YeongMin** [Alex-D/Trumbowyg#752]
### Informations

**Browser version**: Chrome for mobile, Safari for mobile
**OS**: Android 6.0, Android7.0, iOS 11.2
**Screen resolution**: -

### How to reproduce the bug?
0. I used last version of Trumbowyg
1. insert an image as base64 on Trumbowyg
2. insert text and a blank or new line
3. It will be slow
4. it's the same in the Trumbowyg demo. if you use mobile browser.

note::  if you use latest devices, you can't reproduce it. they have enough performances to overcome this issue

note:: I found that 'syncTextarea' make this issue. I could insert text, blank and new line pleasently after commenting 'syncTextarea'

please let me know what the side effect of commenting 'syncTextarea' is.
I will call '$('#trumbowyg').trumbowyg('html');' to get html in the editor after editing contents.
is it OK to call 'syncTextarea' just before calling $('#trumbowyg').trumbowyg('html') ?;
it means 'syncTextarea' is called only once.
it is also same 'syncTextarea' isn't called while editing.

thank you :)

**Comment by Alex-D** [comment]
Duplicates #383

**Comment by Jeong-YeongMin** [comment]
Thx! It works greatly!
one more question, you said "If you hide textarea, HTML5 validation cannot works."
if HTML5 validation would not work, is there any effect?
I haven't seen any problems after making textarea to 'display:none'

thank you :)

**Comment by Alex-D** [comment]
If you did not use `required` attribute on the textarea which is wrapped by Trumbowyg, you will not see any effect :)

**Comment by netgfx** [comment]
Still the provided solution didn't solve the problem, the textarea is hidden but the input is extremely slow

**Comment by tranetsys** [comment]
I have same issue. Any other solution?

**Comment by fisfro** [comment]
maybe late but after all listed fixes haven't worked I have set the option autogrow to false and then the performance was perfect after pasting images into the editor
