### ISSUE TITLE
Error loading assets in demo page highlight plugin

### ISSUE THREAD

**Issue by kirillurgant** [Alex-D/Trumbowyg#753]
![image](https://user-images.githubusercontent.com/8190850/38484588-c6dcc794-3bdf-11e8-85be-97c2d9fe8029.png)
Error loading assets in demo page highlight plugin. Please check it )

**Comment by kirillurgant** [comment]
I think it is because highlight plugin was added in v2.10 and https://cdn.rawgit.com/Alex-D/Trumbowyg/v2.10.0/dist/plugins/highlight/ui/trumbowyg.highlight.css is awailable. On current site used v2.9.2 assets file. Please fix it.

**Comment by Alex-D** [comment]
Keep issue open since I need to fix this :)

**Comment by kirillurgant** [comment]
Thnx for fix! I close issue. :+1:
