### ISSUE TITLE
unnesscert newline \n and tab or whitespace?

### ISSUE THREAD

**Issue by juicycool92** [Alex-D/Trumbowyg#754]
### How to reproduce the bug?
Hello, im very new at JS, so might not bug.
when editor is empty, and i log on .html() its always appear

`\n^^^^^^^^^^^^^^^^^^^^`
(16 byte of whitespace after \n)

seems like okay if i write anything.
is it just happening to me? or bug?

used lastest version of Trumbowyg btw.

Thankyou for ready my poor english ;_;

**Comment by Alex-D** [comment]
I think you are using a `textarea` and you have something like that in your code:

```html
<!-- Some HTML -->
                <textarea>
                </textarea>
<!-- Some HTML -->
```

So, your textarea contains some spaces. I you do not want that, you should write:

```html
<!-- Some HTML -->
                <textarea></textarea>
<!-- Some HTML -->
```

**Comment by juicycool92** [comment]
Hello Alex-D, thanks for kind reply.

Following your comment,
`<div class="row col-12 align-content-center " id="editor"> `
`</div>`
i changed code like this
`<div class="row col-12 align-content-center " id="editor"></div>`
and now it work perfectly.
Thank you!
