### ISSUE TITLE
Is it possible to perform the following functions in a text editor?

### ISSUE THREAD

**Issue by it19862** [Alex-D/Trumbowyg#755]
Is it possible to perform the following functions in a text editor:

1. code syntax highlighting;             
               - Inserted the code into the editable text.
               - Highlighted the code
               - Press the "Code" button.
               - The code is automatically highlighted.
               Analog
                           https://tohtml.com/

2. spoiler;
 [SPOILER][/SPOILER]
![3140](https://user-images.githubusercontent.com/18245828/38505816-c8a75846-3c20-11e8-952a-b85156dff967.gif)
3. iframe;
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe
4. Insert images into text from the clipboard;
5. Insert images into text using the Drag-and-drop method;
6. Attach the file below to the text using the Drag-and-drop method;

**Comment by Alex-D** [comment]
Please, read the doc before post issues.

1, almost 3 and 4 are supported by plugins: https://alex-d.github.io/Trumbowyg/documentation/plugins/

Not for now for 2, 5 and 6.
