### ISSUE TITLE
How to reduce the distance between rows?

### ISSUE THREAD

**Issue by it19862** [Alex-D/Trumbowyg#756]
### Informations
How to reduce the distance between rows?
![3141](https://user-images.githubusercontent.com/18245828/38506246-f7ab9ec6-3c21-11e8-81df-16bee0fe5b66.jpg)

**Browser version**:
**OS**:
**Screen resolution**:

**Comment by Alex-D** [comment]
Change line height in your CSS for multiline text.

Change `p` tag `margin` in your CSS.

It's all about your CSS.

**Comment by it19862** [comment]
@Alex-D 

Sorry.
Could you please specify in which file to search?
If I understood correctly, in some of these?
c:\WEBOpSrvr\domains\editor\Trumbowyg\dist\ui\trumbowyg.css
c:\WEBOpSrvr\domains\editor\Trumbowyg\dist\ui\trumbowyg.min.css
c:\WEBOpSrvr\domains\editor\Trumbowyg\docs\css\main.css

Could you specify a specific location:
  - tag margin - a lot
- multiline - I do not find

**Comment by it19862** [comment]
@Alex-D 
I understood
I have a file:
`<link rel="stylesheet" href="Trumbowyg/dist/ui/trumbowyg.css">`

But I can not find the tag.
Could you specify more precisely which tag to correct?

**Comment by Alex-D** [comment]
No.

It's all about **YOUR** CSS file, not mine.

If you do not have any CSS file at all, you should create one and custom things like you want.

```css
p {
  margin: 0;
}
```

I Unsubscribe this issue since it's not a Trumbowyg issue but an issue on your side.
