### ISSUE TITLE
Blur trigger "issue"

### ISSUE THREAD

**Issue by Wolfhergang** [Alex-D/Trumbowyg#757]
The "tbwblur" event is getting triggered when you click the html view button when moving from text to html, but not viceversa.

**Comment by Alex-D** [comment]
You can add listener by yourself if you need them.

That's OK for me since the tbwblur/tbwfocus are on the editor itself. You want it on the textarea/div which was here before init Trumbowyg, which is kind of weird.

I will close this issue, maybe fixing this in v3 (See #875 for more details).
