### ISSUE TITLE
API feature: Trigger fullscreen mode from outside

### ISSUE THREAD

**Issue by AmitMY** [Alex-D/Trumbowyg#759]
### Informations
On mobile, I want to control the fullscreen mode, when the keyboard is up and down.
I was thinking I can do something like `trumbowygEl.trumbowyg({fullscreen: true})` but to no avail.

Is there any chance you add this functionality?

**OS**: Android, iOS, Chrome
**Screen resolution**: 425x425

**Comment by Alex-D** [comment]
Nope, need to create an API for that.

**Comment by Alex-D** [comment]
You can use: 

`$editor.trumbowyg('execCmd', {cmd: 'fullscreen'})`
