### ISSUE TITLE
noembed not working in IE11

### ISSUE THREAD

**Issue by satchamo** [Alex-D/Trumbowyg#761]
### Informations

**Browser version**: IE11 (and lower)
**OS**: Windows 7
**Screen resolution**: N/A

### How to reproduce the bug?
Visit the noembed demo in Edge. Use the button on the WYSIWYG to embed a YouTube video. When you click Confirm, the video is not embedded.

I'll look into this myself and submit a PR soon.

**Comment by Alex-D** [comment]
I will not fix IE issues in plugins anymore, so I'm closing this issue.
