### ISSUE TITLE
Pasting does not fire tbwchange

### ISSUE THREAD

**Issue by pareeohnos** [Alex-D/Trumbowyg#762]
### Informations
It seems that when you paste text into the editor, the `tbwchange` event is not fired at all unless you have the `removeformatPasted` option set to true. In the issue #579 it was reported that the `tbwchange` event was not fired for IE 11 when this flag is set to true, and the fix was to simply add the trigger but this does not resolve this issue.

I have been able to fix it on our local copy of trumbowyg by changing the code at line 690 from

```javascript
setTimeout(function () {
    t.semanticCode(false, true);
    t.$c.trigger('tbwpaste', e);
}, 0);
```

to

```javascript
setTimeout(function () {
    t.semanticCode(false, true);
    t.$c.trigger('tbwpaste', e);
    t.$c.trigger('tbwchange', e);
}, 0);
```

And removing the `t.$c.trigger('tbwchange', e);` on line 679 as this would no longer be necessary.

I am unsure whether this has any further implications to other things but this resolves the issue.

I've tested this on Chrome for Windows and Mac, both of which showed the issue. The only way to make the value actually change was to leave the input field, then give it focus again.

**Comment by vjbhaskar93** [comment]
I am too facing the issue and waiting for solution.

**Comment by geoffbeaumont** [comment]
The simple workaround is to hook your code up to the tbwpaste event as well as tbwchange (and possibly tbwblur too if you want to be fully belt and braces).

**Comment by MirazMac** [comment]
Facing the same problem. Even the `tbwpaste` event isn't fired for me when you paste something.

**Comment by soundstage** [comment]
@geoffbeaumont I tried hooking 2 events like this,
`$(DiagnoseTextBox).trumbowyg().on({
                'tbwpaste': function () {
                    textCounter(DiagnoseTextBox, CharactersRemainingLabel, 4000)
                }, 
                'tbwchange': function () {
                    textCounter(DiagnoseTextBox, CharactersRemainingLabel, 4000)
                }
            })`

It doesn't seem to work. Could you please explain how you fixed it?

**Comment by MirazMac** [comment]
@pareeohnos I tried your workaround in my local copy, but it doesn't seem to work.

**Comment by geoffbeaumont** [comment]
@MirazMac I'm pretty sure tbwpaste _did_ work in our environment. I can't remember whether I implemented onblur or updated the underlying form field from a form submit event (we have trumbowyg in a form which is submitted by clicking a button), but we've had no problems since.

**Comment by MirazMac** [comment]
@geoffbeaumont Well, no luck for me. I hope this would be fixed soon.

**Comment by Alex-D** [comment]
Make me a MR with the fix and I will merge it ASAP :)

**Comment by Alex-D** [comment]
Done in next version which will be deployed soon.
