### ISSUE TITLE
Clicking bold or italic.. buttons after writing some text return the caret to the next line

### ISSUE THREAD

**Issue by jimchild49** [Alex-D/Trumbowyg#768]
1- Go here https://jsfiddle.net/c7paxae0/

2- write some random text

3- **without selecting the text** click the bold button

As you can see the text go to the next line ! I had a slightly different behavior when I added Trumbowyg to my rails app, and instead of the text returning to the next line, only the caret did!

Tested in Firefox

**Comment by Alex-D** [comment]
Put `<p></p>` into your div/textarea.

**Comment by jimchild49** [comment]
@Alex-D same behavior ! also if you select a word and I you click the button "line-through" it will work but if you try to click it again to remove the line-through effect it won't work !

**Comment by tomsx** [comment]
@jimchild49 : This is a known issue: #638 
Although a fix/workaround has been proposed, the issue has been closed.

**Comment by Alex-D** [comment]
Only way to fix that is to remove that:

https://github.com/Alex-D/Trumbowyg/blob/ff508c01ef7d60e57ce03d784f82007ba6191953/src/trumbowyg.js#L1155-L1156

I don't think it's a big deal, that's why I close that kind of issues.
