### ISSUE TITLE
Trying to save content to mySql

### ISSUE THREAD

**Issue by WebWars** [Alex-D/Trumbowyg#769]
Hello, 

I am trying to save the content of the editor to database using this line
$('#content').trumbowyg('html');

If I enter to make a line break everything past the line break is cut. 
I also see this on the headers post send.
![untitled-1](https://user-images.githubusercontent.com/10691970/39209761-6820325e-480f-11e8-94d5-19993b684615.jpg)

Thank you in advance

**Comment by Alex-D** [comment]
Can't help you. You should use `textarea` in a form or AJAX to send that. No link with the editor.
