### ISSUE TITLE
Fullscreen mode breaks bootstrap modals

### ISSUE THREAD

**Issue by chvelkov** [Alex-D/Trumbowyg#77]
Hi Alex,
First off - great work! I have been playing with trumbowyg for the last few hours and it looks very, very promising. I can't believe I have never heard of it before.

One little problem I noticied - the fullscreen mode doesn't play nice with bootstrap modals:

1. Open a bootstrap modal with an editor in it.
2. Start fullscreen mode (the editor sets the inline style="overflow: hidden;")
3. Stop fullscren mode (the editor sets overflow: auto;)

After the 3 step the modal is broken and the user scrolls the body instead of the modal.
As a suggestion - maybe the editor can check if the overflow of the body is already set to hidden, before trying to set it.
And using a class to set the overflow would be better, because clearing the overflow:auto from the inline style="" is not that trivial and this means that until the next page reload all modals will be broken.

What do you think?

**Comment by Alex-D** [comment]
Now, on master (soon in a new version) I add/remove a class to the body, it's better and fix this bug :)

**Comment by Alex-D** [comment]
I've just released the [`v2.0.0-beta.0`](https://github.com/Alex-D/Trumbowyg/releases/tag/2.0.0-beta.0) if you want check that the bug is correctly fixed.

Thanks!
