### ISSUE TITLE
Is there a way to use the tab key to add whitespace?

### ISSUE THREAD

**Issue by asrochalp** [Alex-D/Trumbowyg#771]
So I am using the editor but I want to have the tab key to work the same way as in microsoft word for example, as in adding whitespace instead. I have tried this: 

                    // Handles keydown on the text editor
                    $('#textEditor').on('keydown keypress', function(event){
                        if (event.keyCode === 9) { // tab key
                            event.preventDefault(); // prevent the tab key event from bubbling up
                            var e = jQuery.Event( 'keypress', {
                                which: 32, 
                                keyCode:32 //Spacebar keycode
                             } );
                            $(this).find('.trumbowyg-editor').trigger(e);
                            $(this).find('.trumbowyg-editor').trigger(e);
                            $(this).find('.trumbowyg-editor').trigger(e);
                        }
                    });

but with no success. 

I have found that [summernote ](https://summernote.org/) already works like this and I wonder if this shouldn't at least be an configurable option if not the default functionality.

**Comment by Alex-D** [comment]
Not supported and no plugin for that.
