### ISSUE TITLE
Resize Image Demo not working

### ISSUE THREAD

**Issue by AsukaYuki** [Alex-D/Trumbowyg#773]
Not really important but i thought i inform you.

#### steps to reproduce
1. I called: https://alex-d.github.io/Trumbowyg/demos/#plugins-resizimg
2. Resizing doesn not work
3. Browser Console says: 
404: Not Found
https://cdn.rawgit.com/Alex-D/Trumbowyg/v2.9.2/dist/plugins/resizimg/trumbowyg.resizimg.js

#### screenshot of issue
https://imgur.com/a/IbmoHTw

**Comment by Alex-D** [comment]
Works now :)
