### ISSUE TITLE
Highlight plugin demo not working

### ISSUE THREAD

**Issue by pavelloz** [Alex-D/Trumbowyg#774]
### Informations

Im trying to make highlight plugin work, but after following the instructions and including everything i have no idea what to do next. Demo doesnt work, code that i copy from the editor is formatted the way i copy it from my editor (different theme) and there is no sign of prismjs css classes anywhere in the html so i assume its not prism's work. 

**Browser version**: Chrome 66
**OS**: OSX
**Screen resolution**:

### How to reproduce the bug?
Go to https://alex-d.github.io/Trumbowyg/demos/#plugins-highlight - button mentioned in the description is not visible at all (both visually and in html).

![image](https://user-images.githubusercontent.com/546845/39468058-88042e96-4d31-11e8-8638-c76a5216fcf1.png)

**Comment by pavelloz** [comment]
Moving forward in my implementation following example i think thats the case:
![image](https://user-images.githubusercontent.com/546845/39468600-1fb7f9aa-4d34-11e8-9498-16fd36c6f716.png)

Little offtopic:
I think ill fix image, even though all other icons were working, but im wondering - is there any way of extending default buttons with one button i want to add? Or i have to manually recreate the whole toolbar to add highlight button?

**Comment by Alex-D** [comment]
I will fix the doc.

https://alex-d.github.io/Trumbowyg/documentation/#common-issues

**Comment by pavelloz** [comment]
Thats the case, icons are loading for all features that use svgPath variable. Its highlight plugin that has separate svg icon + this icon has no <symbol> tag, so it has to be hacked and it still doesnt work especially good.

At this point im considering leaving the empty space and just forcing different color, hopefully users will figure it out...

**Comment by Alex-D** [comment]
It works now here: https://alex-d.github.io/Trumbowyg/demos/#plugins-highlight

Be sure to use the latest version of Trumbowyg to get the icons.svg file up to date :)
