### ISSUE TITLE
When editor is inside a form, buttons don't appear in Insert Link modal

### ISSUE THREAD

**Issue by ppritcha** [Alex-D/Trumbowyg#775]
Trumbowyg is a great lightweight editor, and meets my needs perfectly except for one serious problem.  When the editor is used inside a form, everything works except for the "Insert link" dialog.  The dialog appears, but the "Confirm" and "Cancel" buttons are not displayed, so the modal cannot be closed properly.

The problem appears to be that the modal dialog is a form appended to the editor container.  Because the editor is already inside a form, this results in a form inside another form (or a "nested form"), which is not valid HTML.  The fix for this problem would be to append the modal dialog to the document rather than to to editor container.

Note that this is related to issue #20 and issue #126.

**Comment by Alex-D** [comment]
As you can read in #126:

> I don't want to fix that, It need lot of works, sorry.

I will fix that in a v3, later, but I did not have the time to work on that for now.
