### ISSUE TITLE
Highlight plugin doesnt recognize all syntaxes

### ISSUE THREAD

**Issue by pavelloz** [Alex-D/Trumbowyg#776]
https://github.com/Alex-D/Trumbowyg/blob/a4b4d159cdf05dbfad583ce154d4e8b80175d2f9/plugins/highlight/trumbowyg.highlight.js#L27

This condition is not met for all syntaxes, ie. liquid.
https://github.com/PrismJS/prism/blob/gh-pages/components/prism-liquid.js

Is it something important? I cant figure why comment should be obligatory in a syntax (or rather,  any truthy value under the key) to be visible in the code highlight dropdown.

**Comment by Alex-D** [comment]
Idk, that's from a contributor. If you want you can make a Pull Request to change that if it works without this condition.
