### ISSUE TITLE
Few button not work when i use it with Materialize CSS

### ISSUE THREAD

**Issue by adeguntoro** [Alex-D/Trumbowyg#777]
Hai,
I use Materialize as my main css, but when i use Trumbowyg some button on Trumbowyg won't work. How we can fix this ?
For example Strong button.

**Comment by Alex-D** [comment]
Demo page?

**Comment by RakeshKailash** [comment]
Same here. Inserting strong and strikethrough is fine, but can't remove. I click the buttons, but nothing happens. (sorry for my english, I'm brazilian)

**Comment by Alex-D** [comment]
OK. Known bugs, non Material-related.
