### ISSUE TITLE
icons on WYSIWYG editor does not show

### ISSUE THREAD

**Issue by isogunro** [Alex-D/Trumbowyg#783]
### Informations
Trumbowyg WYSIWYG editor does not work in IE but works perfectly in Chrome and Firefox but when I babeled the code, it worked in all browsers but no icons showed.

**Browser version**:  IE 11, Chrome and firefox
**OS**: Windows 7

### How to reproduce the bug?
Was not working in IE, so I put 'Trumbowyg.js' through babel for conversion and it worked in all browsers except now the little icons don't show in all browsers.

![image](https://user-images.githubusercontent.com/19296277/40021566-3fd3f68a-5793-11e8-8c7a-8d645554f611.png)

Any ideas?

**Comment by Alex-D** [comment]
Are icons working here? https://alex-d.github.io/Trumbowyg/

If yes, it's on your side, can't help you without more information.

**Comment by Alex-D** [comment]
Hey,

check this section of the doc :
https://alex-d.github.io/Trumbowyg/documentation/#common-issues

**Comment by vousys** [comment]
@Alex-D thanks for  your answer. Is there any way I can use it without https? because when you compile the hybrid app, is just like when you work on localhost. And your plugin is awesome

**Comment by Alex-D** [comment]
I don't understand. The just says you should use HTTP or HTTPS protocol, not FILE protocol.

If it doesn't works, try to directly embed SVG in HTML: https://alex-d.github.io/Trumbowyg/documentation/#svg-icons (Use SVG icons without XHR or via an another protocol than HTTP(S))

**Comment by vousys** [comment]
Thank you so much Alex!
