### ISSUE TITLE
Link insertion bug -- can't break out of link insertion

### ISSUE THREAD

**Issue by kurupted** [Alex-D/Trumbowyg#785]
### Informations

When you have a link at the end of the document, and press Enter to go to the next line, and start typing, it continues the link from the previous line.

**Browser version**: Firefox 56.0.2
**OS**: Windows 10
**Screen resolution**:

### How to reproduce the bug?

Starting from a blank document, insert a link. After inserting, the link text is selected. Deselect the link by eg clicking at the end of the line or pressing the End key. Press Enter to make a new line. If you start typing, it is normal text, as it should be. But, backspace back to the same line as the link, and press Enter again to start a new line, and now you can't type without it creating another link.

Another way, load an editor with just this:
`<p><a href="something.html">link</a></p>`
Try to add any normal text, and you can't do it -- it creates a new link when you start a new line and type.

**Comment by Alex-D** [comment]
Does it happens on Chrome.

**Comment by kurupted** [comment]
Tested in Chrome 66 and the bug doesn't occur.

**Comment by Alex-D** [comment]
So it's a Firefox-specific bug :/

I don't know how to fix bugs like that.

**Comment by kurupted** [comment]
Ah ok. I figured there were a lot of browser-specific conditions necessary already. I'll try to look into it when I have time in a few months. It's a pretty serious issue -- I wouldn't want to go to production with it in there.

**Comment by Alex-D** [comment]
Try to set semantic to false?

**Comment by kurupted** [comment]
I upgraded to Firefox Quantum (v 60.0.1) and now the bug is gone :)

**Comment by Alex-D** [comment]
Ah. Cool :)
