### ISSUE TITLE
Image not showing after upload

### ISSUE THREAD

**Issue by nabrih** [Alex-D/Trumbowyg#786]
### Informations

**Browser version**: Chrome 65.03
**OS**: Windows 7
**Screen resolution**:

after uploading image, its not showing on the editor in HTML mode. but when i see on view code. its showing up like this:

`<p class="ui-wrapper" style="overflow: hidden; position: relative; width: 0px; height: 0px; top: 0px; left: 0px; margin: 0px;"><img src="http://10.11.12.144/jx/public_html/assets/img/article/Screenshot_(2)1.png" class="ui-resizable" alt="" style="margin: 0px; resize: none; position: static; zoom: 1; display: block; height: 0px; width: 0px;"><p class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"><div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div></p><p class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"><div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div></p><p class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"><div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div></p></p>`

**Comment by Alex-D** [comment]
It seams related to resizable plugin. Try to disable it.

**Comment by nabrih** [comment]
Okay, its work after i disable the resizimg
Thanks

**Comment by zeelz** [comment]
Hi [Nabrih](https://github.com/nabrih), please can you take a look at [mine](https://github.com/Alex-D/Trumbowyg/issues/658#issuecomment-394596582), see if there's anything wrong.
Thanks

**Comment by nabrih** [comment]
Hi @zeelz,
Before you click submit button, see on the **Network tool** like this:
Go to **dev tool** > **Network** and then continue to click **Submit** to start upload
![image](https://user-images.githubusercontent.com/15963359/41017756-8d21cf62-6980-11e8-954d-f77dfd6b1b6f.png)
You can see example above, the **url** (image_upload) loaded and then click that and see on the **Preview** or **Response**.
I change **urlPropertyName** to **url** on config.
If the image uploaded successfully, it will load the image like _see-pass1.png_ above.

**Comment by zeelz** [comment]
Thanks for your response. I ready checked response from Network tool, it always returns the 'else' response as per my server code, meaning the upload was not successful. It also mean that the request got to the server code.
Another thing I notice was **no data was passed from the ajax request**. I tried with data: {} and $_POST could not pick anything.

See [screenshot](https://www.dropbox.com/s/2ayw842b17z7r0h/Screenshot%202018-06-06%2007.03.31.png?dl=0)

**Comment by nabrih** [comment]
I think you need to remove headers
`plugins: {
		    upload: {
		    	serverPath: 'fileuploader.php',
	            headers: {
	                'content-type': 'application/json' /* Just because Alex mentioned this in an issues */
	            }
		    }
	    }`
to 
plugins: {
		    upload: {
		    	serverPath: 'fileuploader.php'
		    }
	    }
because when the upload, you not send the image, not an json data. 
try to remove the headers

**Comment by zeelz** [comment]
Hello Nabrih, I'm having another issue, how do you handle the `alt` so it can also be inserted into db. I used `success` property of the `upload` plugin but the modal doesn't close anymore.

**Comment by nabrih** [comment]
you can fetch using $_POST['alt'] and then save it into your database, 
about property on the plugin, you can read the documentation at [https://alex-d.github.io/Trumbowyg/documentation/plugins/#plugin-upload](url)

**Comment by zeelz** [comment]
But I'm inserting anything to db at that instance, all I'm doing is upload the image and return true and image_url back to the plugin. The `image_url` and `image_url` will then be part of the `textarea` values. I run another ajax call to insert everything into db. My challenge is how to grab `alt` so I can insert it into its column in the db.
Sorry for the trouble and thanks for your help.

**Comment by Alex-D** [comment]
That's a server-side question, non linked to Trumbowyg in anything, more about RegExp or something like that. Please post on a dedicated forum to keep Trumbowyg issues clean.

Thank you

**Comment by leoperosa** [comment]
Hi @Alex-D. This bug after uploading image, its not showing on the editor in HTML mode, which @nabrih  reported at the beginning, will be fixed? The same thing happens to me and only works if I disable Resizimg.
