### ISSUE TITLE
Prevent fullscreen mode to scroll to top of container

### ISSUE THREAD

**Issue by WebSabaki** [Alex-D/Trumbowyg#791]
Good afternoon,

Is it possible to prevent fullscreen mode to scroll to top of container?

### How to reproduce the bug?
 
1. make a page that is per design scrollable
2. add Trumbowyg with a fix height 
3. click on Fullscreen mode 
4. go back normal editing (not fullscreen)

Page is scrolled to top, should not.

**Comment by Alex-D** [comment]
Needs to put an empty div which have the same size than the editor before going fullscreen and remove it after going back to normal size, avoiding the page to change its height.
