### ISSUE TITLE
Twitter embed code not working with Trumbowyg HTML Editor

### ISSUE THREAD

**Issue by bhavanac24** [Alex-D/Trumbowyg#793]
### Informations
I am Bhavana C. I have been using Trumbowyg HTML Editor and have really loved the way it is designed. We are a team related to Movies and we have many content related to Social Media to be edited in the textarea. I am facing a small issue only with twitter embed code which is added fine in the first go but if the content is tried to edit again it disappears fas the twitter code is replaced by <iframe> or <twitterwidget> tag. 

**Browser version**: Google Chrome
**OS**: Windows
**Screen resolution**:

### How to reproduce the bug?
1. Enter this embed code to code view: 
`<blockquote class="twitter-tweet"><p lang="et" dir="ltr">Azhake Azhake : <a href="https://twitter.com/hashtag/Neerali?src=hash&amp;ref_src=twsrc%5Etfw">#Neerali</a> video song <a href="https://t.co/MVOimtW1fy">https://t.co/MVOimtW1fy</a></p>— Mohanlal (@Mohanlal) <a href="https://twitter.com/Mohanlal/status/1003617901314621441?ref_src=twsrc%5Etfw">June 4, 2018</a></blockquote>`

Above code is rendered as: 
<blockquote class="twitter-tweet"><p lang="et" dir="ltr">Azhake Azhake : <a href="https://twitter.com/hashtag/Neerali?src=hash&amp;ref_src=twsrc%5Etfw">#Neerali</a> video song <a href="https://t.co/MVOimtW1fy">https://t.co/MVOimtW1fy</a></p>— Mohanlal (@Mohanlal) <a href="https://twitter.com/Mohanlal/status/1003617901314621441?ref_src=twsrc%5Etfw">June 4, 2018</a></blockquote>

2. Toggle code view back to WYSIWYG view.
3. You can view the embed result there.
4. Toggle back to code view, you'll find that the twitter embed code automatically convert to

```
`<p>
<script async="" src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</p><twitterwidget class="twitter-tweet twitter-tweet-rendered" id="twitter-widget-0" style="position: static; visibility: visible; display: block; transform: rotate(0deg); max-width: 100%; width: 500px; min-width: 220px; margin-top: 10px; margin-bottom: 10px;" data-tweet-id="1003617901314621441"></twitterwidget>`
```

5. Go back to WYSIWYG view and you'll find the twitter embed fail to view due to not working code/converted code.

I see that the blockquotes in the first embed code are replaced with <twitterwidget> tag. Is this intentional? Can we not retain the embed code pasted in the first instance. Can you please let me know how to fix this issue as we have lot of embed work for twitter needed for our developmental work.

**Comment by tomsx** [comment]
I'm not able to reproduce it. Test done on https://alex-d.github.io/Trumbowyg with Chrome 67.

**Comment by bhavanac24** [comment]
I am still able to reproduce the issue in https://alex-d.github.io/Trumbowyg with Chrome 67.

**Comment by tomsx** [comment]
Is this how you did it? https://vimeo.com/273505599

**Comment by bhavanac24** [comment]
Yes.. But the issue is reproducible once the media file from twitter is loaded. You can a have look at the issue here: https://vimeo.com/273520375

**Comment by bhavanac24** [comment]
Any Update on this??

**Comment by bhavanac24** [comment]
Thanks Alex. As a workaround I am not loading the Twitter script while embedding and calling it only when displaying the tweet.

**Comment by Alex-D** [comment]
I think it's the right way.

**Comment by w3spi5** [comment]
Hello bhavanac24, could you explain your method please. I am confronted with the problem.

**Comment by w3spi5** [comment]
> Thanks Alex. As a workaround I am not loading the Twitter script while embedding and calling it only when displaying the tweet.

Hello bhavanac24, could you explain your method please. I am confronted with the problem.

**Comment by w3spi5** [comment]
For those seeking the solution

Add ['viewHTML'], to btns and go in it to add embeded code of twitter or Instagram :)

**Comment by w3spi5** [comment]
Juste un mot à dire ... Excellent travail, j'adore cet outil, merci beaucoup ;)

For those seeking the solution
Add ['viewHTML'], to btns and go in it to add embeded code of twitter or Instagram :)

**Comment by w3spi5** [comment]
> Thanks Alex. As a workaround I am not loading the Twitter script while embedding and calling it only when displaying the tweet.

Could you explain how you achieve that please ?

**Comment by bhavanac24** [comment]
> > Thanks Alex. As a workaround I am not loading the Twitter script while embedding and calling it only when displaying the tweet.
> 
> Could you explain how you achieve that please ?

When you are embedding the tweet, make sure you do not include the twitter script tag. Use the Twitter script code only when you are rendering your UI. 

Do not include <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> while embedding your tweet.
