### ISSUE TITLE
Dynamically populate the template list

### ISSUE THREAD

**Issue by pierr0t** [Alex-D/Trumbowyg#794]
Hi,
Not a bug, more like a feature request :-)

Is it possible to dynamically populate the trumbowyg template list ? 

in my scheme, templates are stored in a mysql database. A PHP code and query populates a list of divs with 2 data attributes (one for name, one for html). 
Then a jquery code gets all that data into a string similar to the trumbowyg list of templates ... how do I get to put that string into the trumbowyg list of templates ... I would need the ability to call a function returning my string within the `template:[]` syntax ... ?

Impossible or am I missing something ? 
Thanks.
Pierre

**Comment by Alex-D** [comment]
You can wrap the Trumbowyg init with an AJAX call on your side which returns the `template: []`.

Or, you can write the JS in PHP, but that's not really cool ^^

So, it's possible, just need a little work on your side to fit to your needs.

**Comment by pierr0t** [comment]
Hi 
Thks for taking the time to answer :-)
I didn't think about Ajax, that's a possibility, and like you, I didn't want to put the js into PHP.
So far I do not have a pbm getting the data, I have a pbm inserting it into the settings ...

I wrote a function getting the data from some divs, that function return one string containing all the `{name: xxxx, html: yyyy},`
```
	function getclips() {
		var lestemplates = '';
		$('#listclip > div').each(function(){
			var datanom = $(this).data('nom');
			var dataclip = $(this).data('clip');
			lestemplates += "{name:"+datanom+", html:"+dataclip+"},";
		});
		return lestemplates;
	}
```
Which I then inserts into trumbowyg settings (simplified for the sake of explanation):

```
 $('#trombo').trumbowyg({
	btns: [
 		['template']
 	],
 	plugins: {
 		templates: [
 			getclips()
 		]
     }
 }); 
```
This does not seem to work, I get like 1 template with a weird name template_0. Of course getclips() returns the proper string. I guess my question was more about the possibility to use a function in the settings ...
Thks.
Pierre

**Comment by Alex-D** [comment]
```js
	function getclips() {
		var templates = [];
		$('#listclip > div').each(function(){
			var datanom = $(this).data('nom');
			var dataclip = $(this).data('clip');
			templates.push({name: datanom, html: dataclip});
		});
		return templates;
	}
```

```js
 $('#trombo').trumbowyg({
	btns: [
 		['template']
 	],
 	plugins: {
 		templates: getclips()
    }
 }); 
```

**Comment by pierr0t** [comment]
I really feel stupid ... I was looking as those settings as some json-like syntax, it's just an array ... I spent hours and hours testing this and then even looking at 10th of other wysiwyg editors but yours, with that template capability is the best.
Thanks for your kind answers.

**Comment by reeperbahnause** [comment]
Hi Alex,
is there also a possibility to update the templates once the trumbowyg is initialized?  
I already tried this:

`editor.trumbowyg({plugins: {templates: templates}});`

but it does not have an impect.

Best regards
Phillip

**Comment by Alex-D** [comment]
Nope, you can't since plugins are init once at build time. If you want you can destroy and recreate the editor, but it's a little bit hacky.

**Comment by reeperbahnause** [comment]
Thank you for you quick response.
I tried your option and it works perfectly.
I also tried to add a new event when a template was selceted which also works.
I needed it to beable to work with substitions for placeholders in the template.
Does this look correct?

`trumbowyg.$c.trigger('tbwtemplate', template);`

Best regards
Phillip

**Comment by Alex-D** [comment]
Yes you can do that if you want :)
