### ISSUE TITLE
Upload Plugin: Success Callback Prevents Modal from Closing Automatically

### ISSUE THREAD

**Issue by zeelz** [Alex-D/Trumbowyg#795]
### Informations

**Browser version**: Google Chrome, 66.0.3359.181
**OS**: OS X El Capitan, 10.11.6
**Screen resolution**: 1280 x 800

### How to reproduce the bug?
I need to send `alt` to db as image description so I used the `success` callback but it prevents the image from showing (but it uploads successfully) and also prevents the upload `modal` from closing automatically like it does normally when `Confirm` is clicked.

How else can I grab the json `response` returned by the server script?

![screenshot 2018-06-06 10 38 13](https://user-images.githubusercontent.com/5611040/41030266-d4b3096e-6975-11e8-942f-fe106135baf4.png)

**Comment by Alex-D** [comment]
Check: 

https://github.com/Alex-D/Trumbowyg/blob/develop/plugins/upload/trumbowyg.upload.js#L185-L211

If you override the success function, you should reimplement all the things. So, maybe start by a copy/paste, then add your custom code.
