### ISSUE TITLE
Template insertion replacing <br> by <p></p>

### ISSUE THREAD

**Issue by pierr0t** [Alex-D/Trumbowyg#796]
Hello,
I am using the template feature. Some of my templates have some very basic formatting using mostly "<br>" and of course I would like to keep them as created.
When selected by the template button and consequently pasted into the edit area, all "<br>" are replaced by "<p></p>" ... (generates a much bigger line spacing).
Questions:
- is this a feature or a bug ?
- would allowtagsfrompaste plugin correct that pbm ?
Thks.
Pierre.

**Comment by Alex-D** [comment]
Feature, due to normalization between browsers.

Cannot fix :/

Sorry.

**Comment by pierr0t** [comment]
Hello,
In case somebody has the same problem I found a workaround. When importing the old content in the textarea (ie the content containing only "br's") if you encase the whole content in a paragraph tag, br's inside the paragraph are preserved which suits me fine.
(I guess the problem mainly occurs to people like me adding Trumbowyg in an existing app already containing 10th of thousands of existing formatted pieces of text).
Thks for taking the time to look into this.
