### ISSUE TITLE
Not launching in Firefox

### ISSUE THREAD

**Issue by Chickenbreadlp** [Alex-D/Trumbowyg#799]
### Informations

**Browser version**: Firefox 60
**OS**: Windows 10

### How to reproduce the bug?
I'm writing a website, that is also supposed to work without a server.
Trumbowyg works just fine locally on Blink (Chrome/Opera) and Trident (IE).
However, in Firefox I get the following warning in the console:
`jQuery.Deferred exception: documentSelection is null saveRange@(removed filepath)/trumbowyg.js:1685:1`

The Editor adds a Textarea or somthing, because I can type. The Editor bar and Formatting is missing though.
![](https://user-images.githubusercontent.com/7395653/41224619-327b31f2-6d6d-11e8-871c-f6692444d1f3.png)

I first used the trumbowyg.min.js, but switching to the non 'min' varient seemed to fix it, but the error returned one reload later.

I am using Material Design Lite for the overall Layout and Design of the Page. And this doesn't seem to be related with the `file://` protocol, since I still have the problem on the `http://` protocol.

**Comment by tomsx** [comment]
It works all fine here with FF 60.0.2, 64bit
Test done on https://alex-d.github.io/Trumbowyg/

**Comment by Chickenbreadlp** [comment]
It's very likely because of the local execution. It works online in Firefox for me too. But why does it work in Blink and Trident, but not Firefox?

**Comment by Alex-D** [comment]
Sorry for not fixing that earlier, forgot :/
