### ISSUE TITLE
How to rename a dropdown item

### ISSUE THREAD

**Issue by mur-wtag** [Alex-D/Trumbowyg#803]
I've been trying to rename the dropdown item. I don't know maybe it's on the documentation but I didn't find it.

I've added a dropdown containing some buttons (default buttons), now I want to change the default name of these buttons.

**Is it possible?**
![screen shot 2018-06-14 at 9 54 26 am](https://user-images.githubusercontent.com/12680317/41390942-c41fe6c2-6fb9-11e8-8736-5a677a78e0b1.png)

**Comment by Globulopolis** [comment]
See in `plugins/upload/trumbowyg.upload.js`

**Comment by Alex-D** [comment]
You can overrite translations after load of jQuery, Trumbowyg and plugins.

https://github.com/Alex-D/Trumbowyg/blob/develop/plugins/upload/trumbowyg.upload.js#L48

With something like: 

```js
$.trumbowyg.langs.en.upload = 'Upload Image';
```

**Comment by mur-wtag** [comment]
Awesome. Tons of thanks!
