### ISSUE TITLE
Cleanpaste plugin breaks paragraph instead of stripping style attribute in Chrome

### ISSUE THREAD

**Issue by geoffbeaumont** [Alex-D/Trumbowyg#805]
### Informations

**Browser version**: Chrome 67.0.3396.87
**OS**: Windows 10

### How to reproduce the bug?
In Chrome browser, using CleanPaste plugin, paste formatted HTML text content with paragraphs from another browser tab (it needn't have inline styles - Chrome will helpfully add them for you...).

### Expected outcome
Clean HTML with paragraph tags that have no style attribute.

### Actual result
Broken HTML beginning <pstyle="some garbled CSS">content... and ending </p></pstyle="first-rule:>

The same code running in Firefox works as expected (even if pasting from Chrome).
I'm also using the AllowTagsFromPaste plugin, but this makes no difference (if I remove this plugin, the behaviour is the same).

**Comment by Alex-D** [comment]
Should be fixed in 2.22
