### ISSUE TITLE
translation to spanish fontSize plugin does not work

### ISSUE THREAD

**Issue by IsidroMar95** [Alex-D/Trumbowyg#808]
### Informations
i take the FontSize plugin and implement in the editor, its okay so far but when i want translate to spanish , the plugin still in english, and yes i added the translation to spanish in the .js just like this:
`            es: {
                fontsize: 'Tamaño de Fuente',
                fontsizes: {
                    'x-small': 'Extra Pequeña',
                    'small': 'Pequeña',
                    'medium': 'Normal',
                    'large': 'Grande',
                    'x-large': 'Extra Grande',
                    'custom': 'Personalizar'
                }`
and i added the plugin in the btn options::
`    $('#input-texto').trumbowyg({
        lang: 'es',
        btns: [
            ['fontsize'],
        ]
    });`

**Comment by Alex-D** [comment]
Can you make a demo page of the problem? Does it works in french for example?

**Comment by IsidroMar95** [comment]
Yeah , it's work in french , but in spanish does not
if in the code i put the lang in french 
![code](https://user-images.githubusercontent.com/23019968/42139308-09c9f86c-7d51-11e8-94c9-9c164f2dd202.png)

![screenshot_1](https://user-images.githubusercontent.com/23019968/42139297-d61237e6-7d50-11e8-8731-a5c5f5ff1caf.png)

but if i put in spanish

![codees2](https://user-images.githubusercontent.com/23019968/42139316-2eb0febe-7d51-11e8-9c03-d66bf91d2bb3.png)
![codees](https://user-images.githubusercontent.com/23019968/42139319-33349a0e-7d51-11e8-9fa1-406243842236.png)

the plugin still in english
![screenshot_2](https://user-images.githubusercontent.com/23019968/42139322-39e3e1f2-7d51-11e8-99ed-26f7fc728101.png)

i have few days trying to solve the issue but i dont ge it

**Comment by Alex-D** [comment]
Make me a Pull Request to add Spanish to the official plugin code, it will be simple to use it after that :)

**Comment by IsidroMar95** [comment]
Yeah i just did it. I hope the issue get solved soon

**Comment by IsidroMar95** [comment]
@Alex-D have you added this? please i need use this plugin in spanish man

**Comment by Alex-D** [comment]
Please make a clean Pull Request...
