### ISSUE TITLE
Superscript and subscript button are not working properly.

### ISSUE THREAD

**Issue by sudeshyadav-pws** [Alex-D/Trumbowyg#811]
### Informations

**Browser version**: Chrome  67.0.3396.99
**OS**: Ubuntu 16.04
**Screen resolution**:1366x768

### How to reproduce the bug?
1. Nothing happens if no text is selected.
2. If some text is selected and there is no more text after selected text (in same line) then user can not go to normal text mode after using subscript or superscript button.

**Comment by tomsx** [comment]
This has been discussed here #293 
My workaround is to use "remove format" to go back to normal text mode

**Comment by Alex-D** [comment]
Duplicates #293
