### ISSUE TITLE
Is it possible to add custom class on “trumbowyg-button-group” div?

### ISSUE THREAD

**Issue by mur-wtag** [Alex-D/Trumbowyg#812]
I've trying add custom class to trumbowyg-button-group.

Yes I know it's easy to add though `btnsDef` using `class:` attribute to a button. But I need to add to the button group not to the button.

![screen shot 2018-07-16 at 4 35 35 pm](https://user-images.githubusercontent.com/12680317/42754646-06564010-8917-11e8-9f5d-d88ff9012a60.png)

Any help would be appreciable.

**Comment by Alex-D** [comment]
No option allows that.

What are trying to do?

**Comment by Alex-D** [comment]
Use `:nth-child` :)
