### ISSUE TITLE
Page Break

### ISSUE THREAD

**Issue by guiaparicio** [Alex-D/Trumbowyg#814]
Hi guys

Is it possible to add a "page break" button in the editor?

**Comment by guiaparicio** [comment]
Page break for printing.

The Ckeditor has this functionality: https://ckeditor.com/cke4/addon/pagebreak

**Comment by Alex-D** [comment]
Trumbowyg does not have something like that, but feel free to create a plugin to do that :)

**Comment by guiaparicio** [comment]
OK

Thank you Alex!
