### ISSUE TITLE
Upload Plugin - How to get the file name from modal and pass it to server script

### ISSUE THREAD

**Issue by pbocca** [Alex-D/Trumbowyg#816]
Hi, i'm trying to use the upload plugin but i cannot understand how to pass the image value from the modal to my php script. I think that i must use the fileFieldName property but i don't know how to use it. Is it send via the ajax request? How can i access it from my server side script?

Thank you for the help

**Comment by Alex-D** [comment]
You should not send the filename from the front.

You get the file in the `fileFieldName` defined field, aka if you set `fileFieldName: 'myImageField'` you get the image in `$_FILES['myImageField']` in PHP.

Then, you can get the file name via: `$_FILES['myImageField']['name']` or something like that.

If you want to add a field to allow user to rename file on the fly, you should duplicate the plugin and add a custom field.

**Comment by pbocca** [comment]
Thank you man now it works perfectly!!

Your plugin is great :)
