### ISSUE TITLE
PageDown/PageUp will freeze your Chrome tab if using Ruby text

### ISSUE THREAD

**Issue by bonobus** [Alex-D/Trumbowyg#817]
Hullo! Lovely work done here, love this editor to bits and how you guys keep it up. 

I've found something rather bothersome that might happen to those like me that love to move the writing cursor with the keyboard to write or edit here and there in the same text. Bad habits from the Word/Outlook days I guess.

**To the point:** I'm using Trumbowyg on a personal project where I use extensively the **Ruby text plugin**. Now, what I've noticed is that when writing some text and returning over the paragraphs with ruby text by using the keys **PageDown** or **PageUp**, the browser tab will freeze entirely. Detailing time!

### Some info first
Issue shows up on a nominal Chrome 67 on a Win10 at 1920x1080.
Managed to replicate it 100% of the times, also tried on clean incognito tab without any browser plugins or extensions.
On Firefox 61 it actually behaves entirely differently (will cover that at the end).
### How to reproduce the bug?
1. Write something meaningful worth of a Pulitzer with a few paragraphs, or just go to a lovely Lorem Ipsum generator from the many out there. Your choice really.
2. After you have the paragraphs in, try to add some Ruby texts to a couple of words in two of the middle paragraphs.
3. Go to the very last paragraph, click in any word (in the middle for example) and from there press the PageUp key.
4. You've got a tasty frozen tab now!

### My own very test
![frozen-pastrami](https://user-images.githubusercontent.com/1674110/43005523-1afbae10-8c6e-11e8-878e-c6366338a67d.jpg)
For reference, this image with the latest test and what I did: after filling in the text, I added _tasty_ to _Salami_ in the third paragraph, and _delicious_ to the _Shoulder_ in the third. Then I popped in _pastrami_ in the last paragraph and pressed PageUp. It got frozen. Frozen pastrami. Damn it.

Could you spare some time to check what's causing this issue? 😀

In the meantime, in order to avoid going insane, I disabled those two keys with a silly one liner js snippet. It was that or taking the keys out of the keyboard.

Lastly, regarding **Firefox**. Well, Firefox decides that when you click those two keys you're referring to the entire site rather than the editor taking you outside Trumbowyg and preventing the crash. Another surprising behaviour in the lovely browser war I suppose.

Thanks a lot for your time, and again, love the work here!

**Comment by bonobus** [comment]
Oh, and if in the meantime someone needs that silly snippet to prevent death and they're very lazy to do it themselves, here it is:

`$(document).keydown(function(event){
		if (event.keyCode === 33 || event.keyCode === 34) {
			event.preventDefault();
		}
	});`

Hold those keys in place! 😛

**Comment by Alex-D** [comment]
Ping @0x00000F5C

**Comment by Alex-D** [comment]
It's a browser-level bug since there is no JS related to that in the plugin.

So your fix is the best ^^'
