### ISSUE TITLE
Feature request: special characters

### ISSUE THREAD

**Issue by burtonator** [Alex-D/Trumbowyg#818]
This is a nice feature from Froala.. and super easy to implement. It's just a table of math / etc characters that aren't readily available on the keyboard.

It's a good middle path between regular text and full math. You could discuss a lot of mathematical topics without needing a full feature set of mathml

![image](https://user-images.githubusercontent.com/45447/43011775-42f3c436-8bf9-11e8-906c-52161950cdee.png)

**Comment by geektortoise** [comment]
Hello, 

I made this 
https://github.com/geektortoise/Trumbowyg/commit/7aea6048f16f976acc78c0cdd857acc7534c8dc0

But it is really "hacky" : to separate the different categories, I put some null values and I use css on it.

To have a similar window, I think than we need to have a panel that is a mix between the current drop down lists and modal boxes and I don't know how to do it with the current state of Trumbowyg.

If i'm wrong, I'll be happy to adapt my code.

**Comment by Alex-D** [comment]
I've just merged @geektortoise plugin since it seems good enough in lot of cases.

I keep that in mind for v3 (See #875 for more details about v3)
