### ISSUE TITLE
How to get Trumbowyg to calculate height to fill available screen area

### ISSUE THREAD

**Issue by statler** [Alex-D/Trumbowyg#820]
I have 3 divs, Trumbowyg is in the middle. The top and bottom div have set heights.

How do I get trumbowyg to simply fill the available size in the middle div? I only seem to be able to get the height to work by explicitly setting its height or minheight

**Comment by Alex-D** [comment]
Force height to auto and use something like CSS flexbox or grid.

**Comment by statler** [comment]
I tried that to no avail. Any chance you can look at my codepen and advise what is wrong?

[Trumbowyg autoheight](https://codepen.io/anon/pen/ajVVJe)

If I take out the trumbo, then it works as expected, but with the control - I cannot make it behave.

**Comment by Alex-D** [comment]
https://codepen.io/Alex-D/pen/NBwmOQ

**Comment by statler** [comment]
Freakin' awesome.

Thanks so much mate. Much appreciated!
