### ISSUE TITLE
Question: Change toolbar on fullscreen

### ISSUE THREAD

**Issue by statler** [Alex-D/Trumbowyg#821]
I use a very minimal toolbar for my editors - I show only the fullscreen icon.

How would I go about changing the toolbar so that it is shown when fullscreen is invoked? 

e.g. 
1. the minimal (fullscreen button only) editor is displayed.
2. User clicks the fullscreen button
3. The fullscreen editor is displayed, showing the full toolbar

I reckon I could probably do it with a heap of CSS, but would prefer to set the toolbar at runtime - is there a way in through the api? Currently the toolbar is set up on init.

    init: function (element, valueAccessor, allBindings, viewModel, bindingContext) {

        // Create instance of Trumbowyg WYSIWYG on div.
        let wysiElem = <any>$(element);
        
        let isNoButtons = allBindings.get('noButtons');
        var isNoButtonsUW=ko.unwrap(isNoButtons);
        if (isNoButtonsUW) wysiElem.trumbowyg({
            btns: [['fullscreen']
            ]});
        else wysiElem.trumbowyg();

        // Load latest value in observable into Trumbowyg instance.
        wysiElem.trumbowyg('html', ko.unwrap(valueAccessor()));
    },

**Comment by statler** [comment]
I think I got to a solution - is there a better way? Are there likely to be any side effects?


        // Create instance of Trumbowyg WYSIWYG on div.
        let wysiElem = <any>$(element);

        let isNoButtons = allBindings.get('noButtons');
        var isNoButtonsUW = ko.unwrap(isNoButtons);
        if (isNoButtonsUW) wysiElem.trumbowyg({
            btns: [['fullscreen']]
        });
        else wysiElem.trumbowyg();

        // Load latest value in observable into Trumbowyg instance.
        wysiElem.trumbowyg('html', ko.unwrap(valueAccessor()));

        wysiElem.on('tbwopenfullscreen', function (e) {
            var thisObject = wysiElem;
            var t = thisObject.data('trumbowyg');
            t.o.btns = (<any>$).trumbowyg.defaultOptions.btns;
            t.$btnPane.remove();
            t.buildBtnPane();
            t.fixedBtnPaneEvents();
        })

        wysiElem.on('tbwclosefullscreen', function (e) {
            var thisObject = wysiElem;
            var t = thisObject.data('trumbowyg');
            t.o.btns = [['fullscreen']];
            t.$btnPane.remove();
            t.buildBtnPane();
            t.fixedBtnPaneEvents();
        })

**Comment by Alex-D** [comment]
Do it in CSS, it's *REALLY* simpler.
