### ISSUE TITLE
Image selection doesn't work on chrome

### ISSUE THREAD

**Issue by hasangursoy** [Alex-D/Trumbowyg#822]
### Informations

**Browser version**: Version 70.0.3509.0 (Official Build) canary (64-bit)
**OS**: Windows 10
**Screen resolution**: Full HD

### How to reproduce the bug?
On any HTML content containing image, clicking on the image doens't set it as active nor show dots to control the image size. It is working fine on Firefox.

**Comment by Alex-D** [comment]
Use the resize-image plugin if you want that :)
