### ISSUE TITLE
CleanPaste plugin is inserting link twice

### ISSUE THREAD

**Issue by StemateF** [Alex-D/Trumbowyg#824]
### Informations
Hi, firstly great work on this editor and now the problem : 
If you try to paste a link that can't be embedded the "paste embed" plugin should add an anchor tag and insert the link into the editor, but if you have the `removeformatPasted` set to true, the link gets inserted twice (once as an anchor and once as plain text). I would like to know if there is a way to stop this behavior. Ideally i would love to keep the plugin functionality ( transforming pasted links into anchor tags ).
**Browser version**: Chrome 66
**OS**: Ubuntu 16.04
**Screen resolution**:1600x900

### How to reproduce the bug?

- Set ` removeformatPasted: true`
- load cleanpaste plugin 
- Paste a link that can't be embedded 

Here is a [jsfiddle](https://jsfiddle.net/yk8daw4m/22/)  with the problem.

Ps. Sorry for any mistakes I've made .

**Comment by Alex-D** [comment]
You may not set removeFormatPasted *AND* cleanpaste plugin. They are exclusive.

I should add a note on the plugin documentation about that.

**Comment by StemateF** [comment]
I am not using cleanPaste plugin, the plugin with the problem is [this](https://github.com/Alex-D/Trumbowyg/blob/develop/plugins/pasteembed/trumbowyg.pasteembed.js)

**Comment by StemateF** [comment]
@Alex-D  any ideea how can i solve my problem tho ? It seams you misunderstood my problem :(

**Comment by StemateF** [comment]
i just realized i am retarded -.-

I am so sorry @Alex-D
