### ISSUE TITLE
Strange behaviour when adding button

### ISSUE THREAD

**Issue by Mits-Soft** [Alex-D/Trumbowyg#826]
I want to add a button to the text in the editor and I am able to do it with trumbowyg.html() method or with the execCmd command, even with innerHTML the button appears in the editor but the problem is the caret remains inside the button and I can't continue editing. If I press enter it breaks the line but the cursor remains inside the button so there is no way to get the focus back to the editor and keep working.

Is there any reason for this behaviour?

**Comment by Alex-D** [comment]
Idk, it due to some contenteditable issue of the browser :/

Maybe it can be fixed on my side, but I did not want to waste time on it since it's not a core feature, sorry.

**Comment by Mits-Soft** [comment]
Ok, thank you, I decided to add the button at the end of the edition so I have no problem now.
