### ISSUE TITLE
Range always report 0 or end of text

### ISSUE THREAD

**Issue by eradin** [Alex-D/Trumbowyg#828]
V 2.4.2

I'm trying to get the the caret insertion point so I can insert some text when the user presses a button.  In the button click event, call getRange and it either returns 0 or the end of the text.  When I click on something in between, same result.  I noticed that the range will be accurate once I type something but not after focus (without typing).  And if I highlight text, the start and end are always the same.  I can't seem to ever get a range of highlighted text.

I'm not sure if this worked in previous version between I never tried it.

**Browser versions**: Firefox and Chrome for sure
**OS**: Windows

**Comment by Alex-D** [comment]
It's OK: when you catch the click event, you have already blur the contenteditable div. So, since you are not in the div, you get a 0 as cursor position.

Also, you should update to the latest version ^^
