### ISSUE TITLE
First paragraph has no <p> tags

### ISSUE THREAD

**Issue by abrambailey** [Alex-D/Trumbowyg#834]
I am currently running 2.10.0 and experience the following issue:

When I type one line of text and submit the text, the text comes through with no `<p>` tags. When I type one line of text and hit enter, I end up with the first line with `<p>` tags and a string resembling:

`<p>Text</p><p><br></p>`

**Comment by Alex-D** [comment]
Duplicates #516

It's a known bug, but without fix for now :/
