### ISSUE TITLE
Giphy plugin

### ISSUE THREAD

**Issue by thatleeguy** [Alex-D/Trumbowyg#836]
I'd love a Giphy plugin for Trumbowyg and I'd be happy to throw some $$ at someone to put it together for me. 

Is there a bounty page you're using to that I can go create a request on?

**Comment by Alex-D** [comment]
I will have some time soon, so email me and make me a donation :)

https://alex-d.github.io/Trumbowyg/#donate

**Comment by grandecomplex** [comment]
@Alex-D Name your price for the giphy.

**Comment by Alex-D** [comment]
Hard to say without specs: what did you expect about a Giphy plugin ?

**Comment by grandecomplex** [comment]
![giphy](https://user-images.githubusercontent.com/95575/63186869-1a59ec80-c023-11e9-901e-edae10bcf070.jpg)

**Comment by Alex-D** [comment]
Hum, I think 200$ is fair since there is some layout to do and Ajax API call.

**Comment by grandecomplex** [comment]
You got it!

**Comment by Alex-D** [comment]
Thank you! I will work on it next week :)

**Comment by grandecomplex** [comment]
Great can't wait! 

When you search, will the list of optional GIFs scroll? I'm happy with a fixed list of the top 10.

Also, if you can choose in the configuration the rating of the set, that'd be great. Giphy can be NSFW so they added a rating options - https://developers.giphy.com/docs/api/endpoint#search

**Comment by Alex-D** [comment]
Hey, I've finished the plugin itself, I just need to create the icon, then I will merge it :)

Documentation & demo are also ready \o/

Stay tuned!

**Comment by Alex-D** [comment]
![trumbowyg-giphy-plugin](https://user-images.githubusercontent.com/426843/63783936-19ac3a80-c8ee-11e9-9d8a-3d7a232cd4a0.gif)

**Comment by Alex-D** [comment]
Yep:

https://github.com/Alex-D/Trumbowyg/blob/4b7a8964f760278a4d95b9e199389a59ccf8c5c8/plugins/giphy/trumbowyg.giphy.js#L74-77

Depends on IE versions and issues :/

**Comment by grandecomplex** [comment]
Ie11.

Focus css removal
Pressing enter doesn't line break

**Comment by Alex-D** [comment]
Giphy plugin available in 2.19.0
Give it a try: https://alex-d.github.io/Trumbowyg/demos/#plugins-giphy

For IE11 issues, I need more details. I've email you, but maybe you prefer continue here. It's just that IE11 are not related to Giphy so that's out of scope for this issue. Maybe you can open a GitHub issue for each bug you want I fix :)

**Comment by grandecomplex** [comment]
@thatleeguy you're welcome ;)
