### ISSUE TITLE
emojify icons not showing properly

### ISSUE THREAD

**Issue by iambastardo** [Alex-D/Trumbowyg#837]
I'm using trumbowyg in my Angular6, i've encountered a problem where the emojify icons are not showing their images.
code:

declare var $:any;
declare var emojify:any;

    ngOnInit(){
        $('#editor').trumbowyg({
            lang: 'hu',
            svgPath: '/assets/icons/icons.svg',
            removeformatPasted: true,
            autogrow: true,
            btns: [
                ['formatting'],
                ['undo', 'redo'], // Only supported in Blink browsers
                ['strong', 'em', 'del'],
                ['superscript', 'subscript'],
                ['link'],
                ['justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
                ['unorderedList', 'orderedList'],
                ['horizontalRule'],
                ['removeformat'],
                ['foreColor', 'backColor'],
                ['emoji'],
                ['historyUndo','historyRedo'],
                ['noembed'],
                ['base64']
            ]
        });
        
        // Setup emojify.js
        emojify.setConfig({
            img_dir : '//cdnjs.cloudflare.com/ajax/libs/emojify.js/1.1.0/images/basic/',
            mode: 'img'
        });
        emojify.run();

![image](https://user-images.githubusercontent.com/3540431/45197142-4e188800-b292-11e8-9ee8-73ae7a06773d.png)

**Comment by dmyers** [comment]
This seems to be a bug on the latest version (2.11), but does not happen on the emoji demo which is running on 2.10.

**Comment by zanechua** [comment]
I am quite sure that his issue is related to this emojione/emojify.js#175

I was having the same issue and had to use emojify.js another way hence my PR.

**Comment by sandrapender** [comment]
I'm seeing the same issue (Laravel + vue-trumbowyg), and it seems to also be affecting your emoji demo page: https://alex-d.github.io/Trumbowyg/demos/#plugins-emoji

<img width="806" alt="image" src="https://user-images.githubusercontent.com/3987015/47364562-8ef91e80-d6d1-11e8-96d7-f8e518afe6ec.png">

Nothing in the console.

**Comment by zanechua** [comment]
@sandrapender 

The demo is not working because the loader hasn't been updated. It has been fixed in the latest version of develop which hasn't been merged with master.

What version of the emoji plugin and trumbowyg are you on?

You can view the newest demo at:

https://rawcdn.githack.com/Alex-D/Trumbowyg/v2.11.1/docs/demos/#plugins-emoji

**Comment by sandrapender** [comment]
Hey @zanechua I'm on Trumbowyg 2.11.1 and trumbowyg.emoji.js v0.1. It's working locally but not in staging/production. I'll wait for the fix to be merged. Thanks for taking the time to respond.

**Comment by Alex-D** [comment]
Seems working now on demo page.
