### ISSUE TITLE
Trumbowyg isn't compatible with IE9/10

### ISSUE THREAD

**Issue by florianboehm** [Alex-D/Trumbowyg#838]
In trumbowyg.js (line 1284 & 1289) a variable type named "const" is used. This type was published in 
ECMAScript 6/ECMAScript 2015. But Internet Explorer has only supported this standard since version 11.  
I changed these two variables to "var" and it works. 
On alex-d.github.io/Trumbowyg/ is written, that your libary works for IE9+. Pls fix that. :)

source: https://caniuse.com/#search=es6

**Comment by Alex-D** [comment]
Use master. It's fixed.

**Comment by Alex-D** [comment]
2.11.0 is published now and it should fix your issue.
