### ISSUE TITLE
Setting semantic to false automatically adds buttons

### ISSUE THREAD

**Issue by AragurDEV** [Alex-D/Trumbowyg#843]
### Informations

**Browser version**: Google Chrome | 69.0.3497.23
**OS**: Solus (Linux)
**Screen resolution**: 1920x1080

### How to reproduce the bug?

Add the following to your defaults:
```js
$.trumbowyg.defaultOptions.btns = [['em', 'underline'], ['strong']];
$.trumbowyg.defaultOptions.semantic = false;

// Call Trumbowyg without any configuration
$('#trumbowyg-demo').trumbowyg();
```

This will produce this:
![Demo](https://user-images.githubusercontent.com/11004008/45432414-20747a00-b6aa-11e8-8f4e-5db4b7cadb6a.png)

**Comment by Alex-D** [comment]
```
// Makes default options read-only
Object.defineProperty(jQuery.trumbowyg, 'defaultOptions', {
```

You should not overwrite `defaultOptions`. It's like a private property, so create your own options object and give it to each new instance of Trumbowyg.
