### ISSUE TITLE
remove format from api

### ISSUE THREAD

**Issue by vivlachaga** [Alex-D/Trumbowyg#845]
### Informations

**Browser version**: Safari 12.0
**OS**: MacOS mojave
**Screen resolution**: 

### How to reproduce the bug?

is any way to execute the removeFormat action like this:

$trumbowygTextArea.trumbowyg('destroy');
$trumbowygTextArea.trumbowyg('empty');

but with removeFormat
$trumbowygTextArea.trumbowyg('removeFormat');

**Comment by Alex-D** [comment]
Yep, with something like that:

`$trumbowygTextArea.trumbowyg('execCmd', {cmd: 'removeformat'})`
