### ISSUE TITLE
Updating textarea content before submit

### ISSUE THREAD

**Issue by miquijax** [Alex-D/Trumbowyg#847]
It's a question, not an issue

**Browser version**: Safari 12 / Chrome 69
**OS**: macOS
**Screen resolution**: 2560 x 1440

### How to reproduce the bug?

Hi! I was trying to find some information about that by browsing all issues, but couldn't find necessary details.

I run Trumbowyg on multiple objects on page by class `.texteditor` (`inputs` and `textareas`) I understand that script updates them automatically after clicking submit form. But the problem is that I also have some code that I want to perform after changes in textarea. 

What I'm trying to do is something like that:
```
$('.texteditor').trumbowyg().on('tbwblur', function(){
	--UPDATE THIS TEXTAREA OR INPUT WITH CONTENT FROM TEXTEDITOR--
});
```
But I don't know how to call to the current textarea that is edited by Trumbowyg... If I had only one I could do that by ID, but in that case... I found something about "syncTextarea", but there's nothing about it in documentation and I don't know how to use it...

If you could explain this to me, I would be grateful!

**Comment by miquijax** [comment]
Ok, I came up with something like this:
```
$('.texteditor').trumbowyg().on('tbwblur', function(){
	var TXT = $(this).trumbowyg('html');
	$(this).html(TXT).trigger('change');
});
```

...and it works 😊 But could you explain if there is maybe better way to do that? Or what is 'syncTextarea" and how to use it?

Thanks!

**Comment by Alex-D** [comment]
Why did you just not use trumbowyg on a textarea?

You just have to do something like that:

```html
<textarea class="texteditor"></textarea>
```

```js
$('.texteditor').trumbowyg()
```

That's it!

**Comment by miquijax** [comment]
Well, that's exactly what I did, my `.texteditor` class was assigned to `textarea`, but it wasn't automatically updating its' content...

**Comment by Alex-D** [comment]
Try some hacky way: 

```javascript
$('.texteditor').trumbowyg().on('tbwblur', function () {
	$(this).trumbowyg('execCmd', {cmd: 'syncTextarea'});
});
```

Idk if this works ^^'

**Comment by Kelzo** [comment]
Hey. Same problem happened to me. I applied trumbowyg on $('textarea'). It is correctly appearing but not refreshing textarea when i am pressing key. So i added this

```
$('textarea').trumbowyg().on('tbwchange', function () {
	$(this).trumbowyg('execCmd', {cmd: 'syncTextarea'});
});
```
The tbwchange event is correctly fired, but then nothing :(

I am using the master version.

**Comment by Kelzo** [comment]
Actually i have a form with different input and textarea, the submit button is calling an ajax method. I correctly get data from raw input and textarea but i get nothing from the textarea replaced by trumbowyg.
I suppose trumbowyg is suppose to be in a form so it should works correctly.

**Comment by Alex-D** [comment]
Trumbowyg does not need to be in a form. It should works... Can you make a demo page of the bug with jsbin or something like this?
