### ISSUE TITLE
File manager integration?

### ISSUE THREAD

**Issue by t0n1zz** [Alex-D/Trumbowyg#848]
hello, i know that Trumbowyg already have image upload features, but i think it will be much nicer if there is also some file manager plugin, so instead of uploading image, it is better that it open some file manager where user can select the image that already uploaded and user can also uploading image into the file manager and then only pass the image url to the editor....

i find this file manager is quite capable: [unisharp laravel file manager](https://github.com/UniSharp/laravel-filemanager), it have image cropping and resize feature inside it and also all the features/workflow i mentioned above...

**Comment by Alex-D** [comment]
I close that to keep issues clean.

Feel free to make a Pull Request if you have some code for that :)
