### ISSUE TITLE
Can't remove delete line in editor

### ISSUE THREAD

**Issue by yuzeming** [Alex-D/Trumbowyg#849]
### Informations
Can't remove delete line on content in editor

**Browser version**:
Firefox 62 (64Bit)

**OS**:
Windows 10

**Screen resolution**:
2560x1440 (150% DPI)

### How to reproduce the bug?
1. Use the demo at https://alex-d.github.io/Trumbowyg/
2. Selete some text in the editor and click `Deleted` in toolbox
3. Click `Deleted` again, but you can't remove the delete line

Thank you.
Best Wish.

**Comment by Alex-D** [comment]
Duplicates #293
