### ISSUE TITLE
Two Modal box bugs

### ISSUE THREAD

**Issue by Costegillio** [Alex-D/Trumbowyg#853]
### Informations

**Browser version**: Chrome 69.0.3497.100
**OS**: Windows 8.1
**Screen resolution**: 1920x1080

### How to reproduce the bug?

**BUG 1**
Calling modal box like this opens it with "[object Object]" content:

```
var $modal = trumbowyg.openModal({
    title: 'A title for modal box',
    content: '<p>Content in HTML which you want include in created modal box</p>'
});
```

The only way to make it work is:

`var $modal = trumbowyg.openModal( 'A title for modal box', '<p>Content in HTML which you want include in created modal box</p>');`

**BUG 2**
If 'content' contains any inputs it ignores cursor position and prepend html at beginning of area.

`var $modal = trumbowyg.openModal( 'A title for modal box', '<p><input type="text" /></p>');`

**P.S.**
I use 2.10 version from cdnjs.

**Comment by Costegillio** [comment]
Second bug isn't a bug. I think it's happens because losing focus (and range) from main area to modal box's fields. So range needs to be restored via 'trumbowyg('restoreRange')' func. 

It  will be great if more specific info will stored in modal sections of documentation.

**Comment by Alex-D** [comment]
Bug 1 is not a bug, you should use external API, not internal one.

```javascript
var $modal = $editor.trumbowyg('openModal', {
    title: 'A title for modal box',
    content: '<p>Content in HTML which you want include in created modal box</p>'
});
```

See that:

https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L141-L147
