### ISSUE TITLE
RemoveFormat doesn't remove strike through format

### ISSUE THREAD

**Issue by Strohhalm** [Alex-D/Trumbowyg#854]
### Informations

**Browser version**: all
**OS**: Windows
**Screen resolution**: all

### How to reproduce the bug?

Format a text with the strike through format and then klick on remove format

**Comment by Alex-D** [comment]
Duplicates: #372 #521 #638 #750

https://github.com/Alex-D/Trumbowyg/issues?q=is%3Aissue+sort%3Aupdated-desc+strike+through+is%3Aclosed
