### ISSUE TITLE
What would be the simplest way to implement a ltr/rtl text direction toggle for different paragraphs in a single editor?

### ISSUE THREAD

**Issue by efroim102** [Alex-D/Trumbowyg#858]
I have as case where I need to support different languages within a single editor (specifically a rtl with a ltr language).

From what I've seen this isn't supported out of the box as the editor selects the text dir from the language file.

Would it be possible to implement a text direction toggle which would allow different paragraphs to have different text directions within a single editor?

If yes, could I please get advise on the best approach, I'm aware of Custom Buttons & Plugins.

Thanks

**Comment by Alex-D** [comment]
You just need to destroy and create a new instance with the new option :)

**Comment by efroim102** [comment]
I believe I mentioned both in the title & description of this issue that I'm trying to have different paragraphs within a **single** editor to have different text directions.

I'm aware that I can create instances of the editor with a different language.

**Comment by Alex-D** [comment]
Ah sorry, so Trumbowyg can't handle that at all since the direction is set on the contenteditable element and not on subelements.

Sorry :/
