### ISSUE TITLE
Upload input button overflows

### ISSUE THREAD

**Issue by nachitox** [Alex-D/Trumbowyg#859]
### Informations

**Browser version**: 62.0.3 (64-bits)
**OS**: Ubuntu 18.04
**Screen resolution**: 2560 x 1440

### How to reproduce the bug?

Open the Upload dialog

![captura de pantalla de 2018-10-09 17-53-48](https://user-images.githubusercontent.com/1167303/46698021-5e52b880-cbec-11e8-8f0b-46201615f486.png)

**Comment by Alex-D** [comment]
Can't fix without a lot of CSS, so I will not fix that, sorry.

**Comment by nachitox** [comment]
I made changes and "fixed" it... There's no cross browser solution, but I could make it look as good as possible.

I'll try submitting a pull request
