### ISSUE TITLE
Horizontal Rule

### ISSUE THREAD

**Issue by pranto91** [Alex-D/Trumbowyg#86]
**'insertHorizontalRule'** (mentioned in the documentation) didn't work for me. Then I changed it to the following and it worked fine.

>var btnsGrps = jQuery.trumbowyg.btnsGrps;

>$('.simple-editor').trumbowyg({
    btns: ['viewHTML',
           '|', 'formatting',
           '|', btnsGrps.design,
           '|', 'link',
           '|', 'insertImage',
           '|', btnsGrps.justify,
           '|', btnsGrps.lists,
           '|', 'horizontalRule']
});

**Comment by Alex-D** [comment]
Hi! Browser? Version?

Thanks :)

**Comment by Alex-D** [comment]
`insertHorizontalRule` is the execCommand function

`horizontalRule` is the button name for the toolbar.

I was make a mistake in the documentation ?

**Comment by Alex-D** [comment]
OK. I think you talk about this line : https://github.com/Alex-D/Trumbowyg/blob/gh-pages/documentation.html#L385

It's a mistake, i'll fix it very soon. Sorry for the flood and thanks for report!

**Comment by pranto91** [comment]
Tested in Google Chrome, Lastest Version 40.0.2214.111 m. I think so, you made a mistake in the documentation. Thanks.

**Comment by Alex-D** [comment]
Fixed now : https://github.com/Alex-D/Trumbowyg/blob/gh-pages-v2/documentation.html#L413

Soon published (when v2.0.0 will be stable).

**Comment by Alex-D** [comment]
Publised!
http://alex-d.github.io/Trumbowyg/documentation.html#button-pane
