### ISSUE TITLE
How to disable spell check in this trumbowyg-editor?

### ISSUE THREAD

**Issue by actimel33** [Alex-D/Trumbowyg#860]
### Informations

**Browser version**:
**OS**:
**Screen resolution**:

**Comment by Alex-D** [comment]
First, keep calm.

Then, RTFM: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck

So, put the `spellcheck="false"` attribute on the element you are using Trumbowyg on.

**Comment by actimel33** [comment]
thanks for help
