### ISSUE TITLE
Ugly results when copying an mhtm (unique file)

### ISSUE THREAD

**Issue by joaomelont** [Alex-D/Trumbowyg#863]
### Informations

**Browser version**: Chrome 69
**OS**: Windows 10
**Screen resolution**: 2700 x 1800

### How to reproduce the bug?
Just copy the source code of the file attached into html view of editor. When you switch to preview, it will be uggly (for an end user)

[Doc1.zip](https://github.com/Alex-D/Trumbowyg/files/2480692/Doc1.zip)

**Comment by Alex-D** [comment]
That's not the purpose of Trumbowyg.

If you want more advenced option, go on an advenced WYSIWYG editor which can handle that :)

Trumbowyg is light. Light means it cannot do anything, sorry.
