### ISSUE TITLE
Is there a way to toggle formating?

### ISSUE THREAD

**Issue by asolopovas** [Alex-D/Trumbowyg#864]
Hi, 

Is there a way to toggle formatting for example if I click bold the following text should be bold when I click bold again it should continue as normal? You can see such functionality in summernote wysiwyg.

It just that you need to select and undo bold if you bolded something while typing https://i.imgur.com/fLLLaWM.gifv

**Comment by Alex-D** [comment]
Nope :/

Not possible in v2.

Idk if I can do that in v3. I keep your issue for now.

**Comment by Alex-D** [comment]
See #875 for more details about v3.
