### ISSUE TITLE
Use select instead of text input for link target

### ISSUE THREAD

**Issue by code-man** [Alex-D/Trumbowyg#869]
### Informations

**Browser version**: All
**OS**: All
**Screen resolution**: All

### How to reproduce the bug?
Create a link, and pay attention to the Insert Link dialogue box. Selecting a "_target" should be easy for users with little to no HTML knowledge; they should not be expected to type or remember the different targets.

Instead, a drop down selection menu should be used.

**Comment by Alex-D** [comment]
I think if user does not know what is target, you should not enable this option since it's a bad UX idea for end users.

Dropdown = select = new input type which is not supported at this time.

**Comment by Alex-D** [comment]
I will keep that in mind for v3 (See #875 for more details).
