### ISSUE TITLE
After changing font style while writing cursor skips before style change

### ISSUE THREAD

**Issue by ra100** [Alex-D/Trumbowyg#87]
When I change font style (strong, emphasis) with button or keyboard shortcut cursor skips before the tag after few seconds/few letters. Or if I switch to strong, and write nothing, after a second style turns off. I hope picture will be more explanatory.
![trumowyg](https://cloud.githubusercontent.com/assets/3185410/6167362/d94b0cda-b2ba-11e4-9e28-1279095a8333.png)
I tried Opera, Chrome, Firefox.

**Comment by Alex-D** [comment]
This bug is not reproductible on master (will be v2 soon).

So I can only advise you to wait for v2 :)
