### ISSUE TITLE
resizimg width not work

### ISSUE THREAD

**Issue by LeeHyun-A** [Alex-D/Trumbowyg#870]
### Informations

**Browser version**: Chrome 69.0.3497.100
**OS**: MAC
**Screen resolution**: 

### How to reproduce the bug?

The image is not resized when dragging left or right. (width size not work)
So, I added the code below.

You have to add code in resizimg.js.

*** Before (your code)
```js
var opt = trumbowyg.o.plugins.resizimg;
if (newHeight < opt.minSize) {
    newHeight = opt.minSize;
}
newHeight -= newHeight % opt.step;
$el.height(newHeight);
return false;
```

*** After (my code)
```js
var opt = trumbowyg.o.plugins.resizimg;
if (newHeight < opt.minSize) {
    newHeight = opt.minSize;
}
newHeight -= newHeight % opt.step;
newWidth -= newWidth % opt.step;   // add
$el.height(newHeight);
$el.width(newWidth);    // add
return false;   
```

**Comment by Alex-D** [comment]
You should not resize both height and width.

**Comment by LeeHyun-A** [comment]
Yes, but in my case the ratio was not maintained. 
When I dragged, the height was adjusted, but the the width was the same.

**Comment by Alex-D** [comment]
Idk I do not manage image resize, it's browser-side :/ Sorry.
