### ISSUE TITLE
ie11 contenteditable border 

### ISSUE THREAD

**Issue by Bastien57** [Alex-D/Trumbowyg#872]
### Informations

**Browser version**: ie11
**OS**: win10
**Screen resolution**: 1920x1080

Hello, 

i'm using Trumbowyg and i'm having trouble with internet explorer 11, see below :

![image](https://user-images.githubusercontent.com/25859995/47509604-bdfcc500-d876-11e8-92aa-c162046c42be.png)

i don't know how to call this hatched border, but it appears only on internet explorer, and not on your demo website, but on our site (event raw install with 0 plugins).

How can I remove that ? 

Thanks

**Comment by Alex-D** [comment]
Cannot reproduce :/

If you make me a jsfiddle or something like that I can check again, but I think it's due to other CSS or other JS on your page.

My test is based on the index.html in the repository, there is no normalize, and it works on IE11.
