### ISSUE TITLE
Inserting link always prepends to start of editor content

### ISSUE THREAD

**Issue by harm0nic** [Alex-D/Trumbowyg#876]
I have pretty much everything working the way I want it to work (fantastic work Alex!), but have recently noticed weird behavior when creating a new link.

If either creating a new link or creating a link from selected text, when inserting the link, the link always appears at the start of the content. It does not turn the selected text into a link as you would think or place the link where the cursor was.

![peek 2018-11-05 23-01](https://user-images.githubusercontent.com/24963129/48042295-0063b300-e14f-11e8-9ec7-b88bd65aa87a.gif)

I am using v2.11.1 version in an electron app

**Comment by Alex-D** [comment]
Cannot reproduce :/

I you are planning to build a big app, check something more strong like Quill. I do not think you look at 20ko vs 200ko in a 150Mo Electron app :p
