### ISSUE TITLE
Base64 plugin doesn't show images on latest version

### ISSUE THREAD

**Issue by netgfx** [Alex-D/Trumbowyg#877]
### Informations

As posted here as well: https://github.com/ankurk91/vue-trumbowyg/issues/18#event-1948938155

the base64 images cannot be embed anymore. This can be viewed here:

https://jsfiddle.net/py8y56jo/14/ (without the component)

or

https://codepen.io/7linternational/pen/dQoazW

**Comment by Alex-D** [comment]
Duplicates #878
