### ISSUE TITLE
Plugin not showing image after upload

### ISSUE THREAD

**Issue by ton21** [Alex-D/Trumbowyg#878]
I can't get the upload to work.
The upload itself works, but the image is not showing.

I am using a local server: **xampp**.

**My code:** 

    $('textarea').trumbowyg({
            lang: 'pt_br',
            // autogrow: true,
            btnsDef: {
                // Create a new dropdown
                image: {
                    dropdown: ['upload'],
                    ico: 'insertImage'
                }
            },
            btns: [
                ['image']                
            ],
            plugins: {
                upload: {
                    serverPath: '/faq/upload',
                    urlPropertyName: 'url',
                    fileFieldName: 'file'
                }
            }
        });

**Comment by dragonjk777** [comment]
I also experienced the same problem.
You can modify this section.

**trumbowyg.js**

// Build out of ModalBox, it's the mask for animations
...
}).appendTo($(document.body));    =>   }).appendTo(t.$box);

https://imgur.com/a/ALxShrn

**Comment by Alex-D** [comment]
Did you try 

`}).appendTo($(t.doc));`

?

**Comment by Kaaly** [comment]
Same issue for me.

Any solution ? Other than downgrade to 2.10.0

**Comment by Alex-D** [comment]
I need to take a look at that. For now, there is no other solution than downgrade.

**Comment by Alex-D** [comment]
I have a fix :)

Just need to do a new version and push to npm

**Comment by Alex-D** [comment]
Duplicates #857
