### ISSUE TITLE
Cleanpaste cleans the already inserted text, not the newly pasted text.

### ISSUE THREAD

**Issue by Geniekort** [Alex-D/Trumbowyg#881]
When trying to use the Cleanpaste plugin (which is awesome by the way), the wrong text is cleaned; 

So when I paste some text which is not clean (for example it has a `style` attribute), the style attribute is pasted anyway, so the cleanpaste plugin is not picking it up.

However when I paste something again, next to the already pasted stuff, then the first text is cleaned.

To reproduce:

1.  I copy `<p style="color:red;">This goes wrong</p>`from a rendered html page. (So you actually see red text)

2.  I paste it in an initialized Trumbowyg editor (Observe it is still red)

3.  I copy `<p>Bladibla</p>` from a rendered html page

4.  I paste it in the same Trumbowyg editor. 

5. Now the "This goes wrong" text gets cleaned.

I can reproduce this on Ubuntu, in Chrome, Firefox and Opera.

Any suggestions?

**Comment by Geniekort** [comment]
Thanks! I"ll check if it's working now!

**Comment by Geniekort** [comment]
@Alex-D isn't the current behaviour "wrong"? I mean, cleaning all the text inside the text box seems fine, but the pasted text itself should also be cleaned right?

**Comment by Alex-D** [comment]
Deployed in 2.12.1
