### ISSUE TITLE
Lists don't align center along with their content

### ISSUE THREAD

**Issue by netgfx** [Alex-D/Trumbowyg#884]
### Informations

**Browser version**: Chrome 70
**OS**: Windows
**Screen resolution**: 1920x1200

### How to reproduce the bug?

Add an unordered/ordered list, add content and align center. The content is aligned but not the list indicators.

**Comment by Alex-D** [comment]
I cannot fix that in v2, added to v3 TODO.

**Comment by netgfx** [comment]
Any idea when v3 is coming together? @Alex-D

**Comment by Alex-D** [comment]
In one year or something like that.

If you need an alternative, check Quill.
