### ISSUE TITLE
Change event not fired when image is moved around the editor

### ISSUE THREAD

**Issue by dolbex** [Alex-D/Trumbowyg#885]
### Informations

**Browser version**: Chrome 70
**OS**: Mac OS
**Screen resolution**: 1600 

### How to reproduce the bug?

If you drag an image around the editor there is no update fired. Checking the source fires the update so I can't tell if the source is updated. I would imagine it is since the image appears in the place I would suspect. 

I know you are working on the next version but a resolution on this issue would solve one of our final issues on our own open source project that relies on Trumbowyg: The Greatest Editor of All Times. :)

**Comment by Alex-D** [comment]
Arf, I've never test this :/

Maybe it could fix by adding "drop" listener here: https://github.com/Alex-D/Trumbowyg/blob/v2.12.0/src/trumbowyg.js#L690

**Comment by dolbex** [comment]
Cool - thanks for the direction. Posted a pull for this https://github.com/Alex-D/Trumbowyg/pull/886

**Comment by Alex-D** [comment]
Fixed in 2.12.2 :)
