### ISSUE TITLE
tagsToKeep seems not to work 

### ISSUE THREAD

**Issue by MerzGH** [Alex-D/Trumbowyg#889]
v.2.12.2
All browsers
macOS Mojave

For an email template I need the whole html structure but trumbowyg deletes some html-tags. How can I avoid it? The option "tagsToKeep" seems not to work.

```
tagsToKeep: ['i', 'html', 'head', 'body', 'hr', 'img'],
tagsToRemove: ['script'],
semantic: false,
```

**Comment by Alex-D** [comment]
Trumbowyg v2 cannot handle tags like html, head, body because it's based on contenteditable API, and I think it's cleaned by the browser itself.

Maybe it could work in v3, IDK.
