### ISSUE TITLE
Problem with accents

### ISSUE THREAD

**Issue by AnnaNee** [Alex-D/Trumbowyg#89]
I can't type words with accents in my editor. It prints the letters without the proper accent.
Is there any way to set a charset for my lang file?

**Comment by boxmo** [comment]
:+1:

**Comment by Alex-D** [comment]
Have you got an example somewhere on the Web? I'm french and I can use all accent without any configuration.

**Comment by AnnaNee** [comment]
Semantic true was causing the problem. Removing this option from the js fixed my issue.
