### ISSUE TITLE
Problems with image insertion and resizing

### ISSUE THREAD

**Issue by heniotierra** [Alex-D/Trumbowyg#896]
### Informations

**Browser version**: Firefox 62 (64 bit)
**OS**: Linux Mint 18
**Screen resolution**: 1366x768

When I insert a new image, the mouse cursor shown when over it is the "grabbing" cursor, and the selection for resizing won't show even if I click over the image. The selection for resizing only shows if I add a second image to the stage and then click the first image, then the correct cursor is shown, but this will work only for the previously inserted image, while the newly inserted one can't be selected unless I add a third image, etc.

Besides that, the selection for resizing always appears in the top-left corner of the stage, no matter where the image actually is. In the screenshot below, the resizing selection is for the black image filled with characters.

Finally, resizing only works diagonally.

![screenshot_2018-12-09 trampo](https://user-images.githubusercontent.com/4629295/49703241-8907c000-fbe1-11e8-92a3-17d8799c0073.png)

### How to reproduce the bug?

With this configuration:

              "jquery/dist/jquery.js",
              "jquery-resizable/resizable.js",
              "trumbowyg/dist/trumbowyg.min.js",
              "trumbowyg/dist/plugins/noembed/trumbowyg.noembed.min.js",
              "trumbowyg/dist/plugins/pasteembed/trumbowyg.pasteembed.min.js",
              "trumbowyg/dist/plugins/base64/trumbowyg.base64.min.js",
              "trumbowyg/dist/plugins/resizimg/trumbowyg.resizimg.min.js",
              "trumbowyg/dist/plugins/template/trumbowyg.template.min.js",
              "trumbowyg/dist/plugins/fontfamily/trumbowyg.fontfamily.min.js",
              "trumbowyg/dist/plugins/fontsize/trumbowyg.fontsize.min.js",
              "trumbowyg/dist/plugins/colors/trumbowyg.colors.min.js",
              "trumbowyg/dist/plugins/table/trumbowyg.table.min.js",
              "trumbowyg/dist/plugins/history/trumbowyg.history.min.js",
              "trumbowyg/dist/plugins/preformatted/trumbowyg.preformatted.min.js"

Paste or insert an image, try to select or resize it. You can't. Now, insert a second image. You can select the first one, but not the second.

Thanks for the great work!

**Comment by Alex-D** [comment]
Trumbowyg does not support image resize. It's a browser behavior. So, I think it's a browser-level bug.

I will not try to fix that for now, maybe in v3 (see #875).

Use Quill or some other WYSIWYG if you need this feature.

**Comment by elybin** [comment]
maybe automatically setting image to 100% would help
