### ISSUE TITLE
jquery__WEBPACK_IMPORTED_MODULE_10__(...).trumbowyg is not a function

### ISSUE THREAD

**Issue by sungmin-kim-0129** [Alex-D/Trumbowyg#900]
Hello, people

I've just created react app by create-react-app, so I don't know webpack stuff yet.

I've tried to embed trumbowyg into react.js code, using jquery like below code.

```javascript
import * as $ from "jquery";
import jquery from "jquery";
import "node_modules/trumbowyg/dist/trumbowyg.min.js";
import "node_modules/trumbowyg/dist/ui/trumbowyg.min.css";

componentDidMount() {
    $("#trumbowyg_editor").trumbowyg();
  }

render() {
<div className="form-group">
            <textarea className="form-control " id="trumbowyg_editor" />
          </div>
}
```

I got an error 'jquery__WEBPACK_IMPORTED_MODULE_10__(...).trumbowyg is not a function' if I do that code. Is there any solutions?

Additionally, I used Trumbowyg component from react-trumbowyg as well, but the props that the component has are not many to use, and I need 'value' property that is available to read and write like HTML5. That's why I am here to use normal(?) trumbowyg.

**Comment by Alex-D** [comment]
Hey,

did you check: https://github.com/RD17/react-trumbowyg?

Maybe you can try that: https://github.com/facebook/create-react-app/issues/4281

**Comment by sungmin-kim-0129** [comment]
Thank you Alex, and sorry for replying late
I was working with Quill.js instead of Trumbowyg for the editor, but I am back to Trumbowyg now :)

One more question. I import react-trumbowyg and I would like to add custom buttons on react-trumbowyg. Do I just follow the documentation? The documentation is for jquery, not react. Is there any way to add custom buttons? Thanks

**Comment by Alex-D** [comment]
Check the react-trumbowyg README samples :)
