### ISSUE TITLE
Image Resize Plugin does not mark Editor Content as "dirty"

### ISSUE THREAD

**Issue by realulim** [Alex-D/Trumbowyg#903]
### Informations

Firefox 64.0 on Mac OS.

### How to reproduce the bug?

1. Go to https://alex-d.github.io/Trumbowyg/demos/plugins/resizimg.html
2. Open Javascript Console and type `document.getElementById('editor');`
3. Depending on screen resolution you'll see something like `<div id="editor" style="margin: 1rem; height: 237.8px;" class="trumbowyg-editor" dir="ltr" contenteditable="true">`
4. Now resize the image (make it smaller or larger)
5. Type `document.getElementById('editor');` again
6. You'll see that the image height is unchanged (237.8px in this example), even though the image is actually smaller or larger on screen.

The problem is, if Trumbowyg were used in a real application and that application would have a "Save" button and the user would press it to save after a resize operation, then the old size would be saved. And the user would have no chance of noticing, because on-screen everything looks right. I suspect that the image resize operation doesn't mark the editor content as "dirty" or perhaps forgets to call some update/refresh command on Trumbowyg.

**Comment by realulim** [comment]
My workaround currently is to do $("#myeditor").trumbowyg('toggle') on save and then get the content of the editor. The toggle switches to HTML mode, which seems to trigger an update of the content. After uploading the content to the server, I toggle again to get back to rich text mode.

**Comment by Alex-D** [comment]
The cleaner way to force a content refresh is to call `$('#editor').trumbowyg('execCmd', {cmd: 'syncCode'})`

**Comment by realulim** [comment]
`trumbowyg.$c.trigger('tbwchange');` is called. But I think that is something the editor should call, when it has changed. Here we need to signal an external change to the editor.

**Comment by Alex-D** [comment]
Yep, but it should call `syncCode` internally before tbwchange, and maybe the tbwchange should not be called anymore after that.

**Comment by realulim** [comment]
I agree and tried it with my application and it seems to work. Will create a pull request.

**Comment by Magenta94** [comment]
Is this fixed? I can reproduce the problem on the demo page with the steps described in the first post.
I have the same problem with the version 2.15.2 and a base64 image.
