### ISSUE TITLE
Page reloads after image upload in AngularJS 7 

### ISSUE THREAD

**Issue by Renish94** [Alex-D/Trumbowyg#910]
### Informations

**Browser version**: Firefox V 64.0
**OS**: Windows 8.1

### How to reproduce the bug?

**Added following code in html**

`<textarea type="text" formControlName="content" id="content" placeholder="Write Page Content" class="form-control m-b-5" rows="4"></textarea>`

**Added following code in component.**
Here we are not using 'api.imgur.com' but instead created our api that upload image in our local project folder.

```js
ngOnInit() {
  this.form = this.formBuilder.group({
    content: [''],
  });

  (<any>$('#content')).trumbowyg({
    svgPath: '/assets/admin/icon/trumbowyg.svg',
    autogrow: true,
    btns: [
      ['viewHTML'],
      ['historyUndo', 'historyRedo'],
      ['formatting'],
      ['strong', 'em', 'del'],
      ['foreColor', 'backColor'],
      ['link'],
      ['image'],
      ['justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
      ['unorderedList', 'orderedList'],
      ['removeformat'],
      ['fullscreen']
    ],
    btnsDef: {
      image: {
        dropdown: ['insertImage', 'upload', 'noembed'],
        ico: 'insertImage'
      }
    },
    plugins: {
      upload: {
        // serverPath: 'https://api.imgur.com/3/image',
        serverPath: 'http://localhost:1000/api/admin/upload/image',
        fileFieldName: 'image',
        urlPropertyName: 'data.link'
      }
    }
  });
}
```

**This is the response from api**

`{"success":true,"status":200,"data":{"type":"image/png","size":8543,"link":"assets/uploads/image-1546066153451-61534.png"}}`

Once we click Confirm button after selecting image, it reload the page.

It should not reload page in angularjs.

**Comment by julienr114** [comment]
Same for me wirh vuejs & nuxt.js

**Comment by Alex-D** [comment]
Any isolated demo of this bug?

**Comment by julienr114** [comment]
Sorry,
it's my bad. I did not see that the `data` parameters should be an Array of Objects and not simply an object. Correct that solved my issue. But @Renish94 doesn't have `data` parameters in this plugins upload options.
