### ISSUE TITLE
Colors plugin, colors plate is empty.

### ISSUE THREAD

**Issue by uwejan** [Alex-D/Trumbowyg#911]
### Informations
Hi, just installed colors plugin, but i do not see the colors plate, or the plate is empty.
![screenshot-20190105200651-702x236](https://user-images.githubusercontent.com/20250935/50727161-d6674680-1127-11e9-901e-8f4136796ba1.png)

**Browser version**:
latest chrome, latest firefox
**OS**:
Windows, Mac, Linux

**Comment by Alex-D** [comment]
I think your CSS is overriding the color plugin's CSS.

So it's more on your side, I think.
