### ISSUE TITLE
Add font?

### ISSUE THREAD

**Issue by crazee881** [Alex-D/Trumbowyg#913]
Hello,

is there any way to add another font to the Font Family plugin? There are currently only 13 of them, I need a bit more.

Thank you
P.

![image](https://user-images.githubusercontent.com/32751601/51085515-c5779000-173a-11e9-8609-715cc7590cb1.png)

**Comment by Alex-D** [comment]
As you can see here: 

https://github.com/Alex-D/Trumbowyg/blob/develop/plugins/fontfamily/trumbowyg.fontfamily.js#L58-L72

You should use `plugins.fontfamily.fontList` option to give your own list.

Example:

```js
$('#editor').trumbowyg({
  plugins: {
    fontfamily: {
      fontList: [
        {name: 'Your Own font 1', family: 'Own 1, Helvetica, sans-serif'},
        {name: 'Your Own font 2', family: 'Own 2, Helvetica, sans-serif'},
        {name: 'Your Own font 3', family: 'Own 3, Helvetica, sans-serif'}
      ]
    }
  }
})
```
