### ISSUE TITLE
Color display list shows as one long select list.

### ISSUE THREAD

**Issue by akabobo1122** [Alex-D/Trumbowyg#917]
### Informations

**Browser version**:  Safari 12.0.2, Chrome 71.0.3578.98, FF 64.0.2
**OS**: OSX 10.14.2
**Screen resolution**:

### How to reproduce the bug?
I've installed a fresh copy of the Trumbowyg and Trumbowyg colors v1.2 and rather than get the nice block of colors, I get a long list of colors with "foreColor" + hex value.  Attaching file.

Am I missing some kind of palette image?

![screen shot 2019-01-23 at 11 30 49 am](https://user-images.githubusercontent.com/46971684/51625312-7d0e5e00-1f02-11e9-9c08-5e851f1b8210.png)

**Comment by Alex-D** [comment]
For any other which have this bug: do not forget to add the color plugin's CSS

https://github.com/Alex-D/Trumbowyg/blob/master/dist/plugins/colors/ui/trumbowyg.colors.min.css
