### ISSUE TITLE
Cursor doesn't move after pressing return

### ISSUE THREAD

**Issue by Joralf** [Alex-D/Trumbowyg#920]
Hi there,

First let me thank for all the splendid work done on the trumbowyg editor. I recently updated from version 1 to the latest version and it has improved so much!

After deploying the latest version though, people using the editor on a day to day basis noted that adding a break would not move the cursor if on the first line. I have filled in the details below. If I look at the default behaviour of other WYSIWYG editors like Redactor or the one in Wordpress, then this behaviour doesn't occur, but I'm not sure it's a bug or whether it's by design. 

### Informations

**Browser version**: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
**OS**: macOS High Sierra (10.13.6 (17G4015))
**Screen resolution**: 1440x900

### How to reproduce the bug?

- Open a default trumbowyg instance (https://alex-d.github.io/Trumbowyg/demos/ also has this issue)
- Type something on the third line
- Move back to first line
- Press return
- Cursor will keep jumping back to first line, instead of moving after the inserted break.

### Gif animation of the behaviour

![wysiwyg2](https://user-images.githubusercontent.com/9008262/51971066-9e2dfc00-2478-11e9-8475-a839a86dde80.gif)

**Comment by Alex-D** [comment]
Thanks for the feedback!

I need to investigate, at this time I did not understand why the `p` tag is replaced by a `br` one :/

**Comment by Joralf** [comment]
> Thanks for the feedback!
> 
> I need to investigate, at this time I did not understand why the `p` tag is replaced by a `br` one :/

That was my second question actually. I think it happens here (https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L1160)?

**Comment by mebur** [comment]
I experience a similar error but at the end of a line in IE11.

**Comment by Alex-D** [comment]
Does it bug if you set `semantic` to false?

**Comment by Alex-D** [comment]
I think the problem comes from this test: https://github.com/Alex-D/Trumbowyg/blob/v2.14.0/src/trumbowyg.js#L1150

It should catch you case where the cursor is in the currently-edited `<p>`

**Comment by mebur** [comment]
"semantic: false" solved the issue for me, thanks!

**Comment by Joralf** [comment]
@Alex-D 

Sorry for the late reply, been busy with some other stuff and not really used to keeping track of PR's in open source projects. I had already set `semantic:false` pending this PR: https://github.com/Alex-D/Trumbowyg/pull/922 and you're right, this solves the issue.

I don't think we need conversion of tags, but when I have time I will try and debug the code and see if I can come up with a fix.

Thanks!
