### ISSUE TITLE
Inline styles removed when converting to semantic elements

### ISSUE THREAD

**Issue by Joralf** [Alex-D/Trumbowyg#921]
I found another small but slightly annoying bug (or feature), which is the fact that inline styles are removed when the editor is converting non semantic elements to semantic elements.

### Informations

**Browser version**: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
**OS**: macOS High Sierra (10.13.6 (17G4015))
**Screen resolution**: 1440x900

### How to reproduce the bug?

- Open a default trumbowyg instance
- Open `viewHTML`
- Paste the following content `<b style="color: rgb(230, 100, 84); font-size: x-large; line-height: 34.2857px;">Some text that I want in red with x-large fontsize</b>`
- Close `viewHTML`
- The styling will be removed
- Try with the following content `<div style="color: rgb(230, 100, 84); font-size: x-large; line-height: 34.2857px;">Some text that I want in red with x-large fontsize</div>`
- Close `viewHTML`
- The styling will not be removed

### Gif animation of the behaviour

![trumbowyg](https://user-images.githubusercontent.com/9008262/52113368-64d8c600-2609-11e9-8994-31d8923a5051.gif)

### Reason for the behaviour

If semantic is set to true, which is by default, then `b`, `i`, `s` and `strike` tag will be converted to their semantic tags `strong`, `em` and `del`. Whilst doing so, the attributes set to these tags will not be passed to their new semantic tag, which means you lose the styling. See https://github.com/Alex-D/Trumbowyg/blob/develop/src/trumbowyg.js#L1119.

I think these attributes should be passed though, so you keep the styling whilst converting the elements to something with a semantic meaning. I took the liberty to open a PR, see https://github.com/Alex-D/Trumbowyg/pull/922.

Let me know what you think!

**Comment by Alex-D** [comment]
AH.

The semantic feature is designed to normalize browser tags used via execCommand.

So, I've really consider the paste & convert side of the thing ^^'
