### ISSUE TITLE
Inserting a link with a selected text of a list element is broken

### ISSUE THREAD

**Issue by tyronx** [Alex-D/Trumbowyg#924]
### Informations

**Browser version**: Google Chrome 71
**OS**: Win 10
**Screen resolution**: 1920x1080

### How to reproduce the bug?

Make a bulleted list of a few items. Select the text of an item, select insert link. The dialog that opens up will has an URL field and a text field. The Text field is pre-filled with the html code of the list element(s), in my case: 
`<li xmlns="http://www.w3.org/1999/xhtml"></li><li xmlns="http://www.w3.org/1999/xhtml">sdfsdf</li>`

Actually inserting the link after does some very weird stuff to the list. 

Looks to me like whatever piece of code finds the currently selected text does not properly match that stuff

**Comment by kurupted** [comment]
I came here to report a similar issue.

I'm using Firefox.

Add a link
Double-clicking the link text selects all of the text.
Go to Insert Link.
That w3.org text appears in the Text field, and URL field is empty.
Click Cancel
Link text is still selected/highlighted
Go to Insert Link again, without having changed the text selection
Link URL and Text fields have the correct values.

Kinda weird.

Same thing applies in Chrome except you triple-click to select all of the text.

**Comment by kurupted** [comment]
It'd be cool too if double-clicking a link would open the Insert Link dialog, the way double-clicking an image opens its dialog

**Comment by Discartyptics** [comment]
I too am having this same issue, in Firefox. 
If I click the link once it works fine, if I select the text it also works fine. If I double click the link it says the documentSelection's range is 
`startContainer: div.trumbowyg-editor, startOffset: 1, endContainer: div.trumbowyg-editor, endOffset: 2, collapsed: false, commonAncestorContainer: div.trumbowyg-editor`

**Comment by Alex-D** [comment]
Should be fixed in 2.22
