### ISSUE TITLE
tbwchange only fires once, on page load

### ISSUE THREAD

**Issue by berianwilliams** [Alex-D/Trumbowyg#925]
### Informations

**Browser version**: Firefox 65.0
**OS**: Windows 10 Pro x64
**Screen resolution**: 1920x1080

### How to reproduce the bug?
My aim is for the following code (served through PHP, but that's stripped out here) to execute validateGamesFormLive every time the Trumbowyg textarea content changes:

```html
<div id="description" name="description">
</div>
<script>
	$('#description').trumbowyg({
		btns: ['strong', 'em'],
		autogrow: true,
		removeformatPasted: true
		})
	.on('tbwchange', validateGamesFormLive('description'));
</script>
```
The editor itself works fine, with all the specified options, but doesn't behave the way onchange or oninput events usually do (i.e. every time the event happens), but instead only fire once when the page first loads.  Is this a bug in Trumbowyg, or a problem with my implementation?

**Comment by Alex-D** [comment]
You just call `validateGamesFormLive` instead of wrap it in a callable function which will be called at each tbwchange.

```js
$('#description').trumbowyg({
  btns: ['strong', 'em'],
  autogrow: true,
  removeformatPasted: true
})
.on('tbwchange', function () {
  validateGamesFormLive('description');
});
```
