### ISSUE TITLE
Cannot insert a form in html mode

### ISSUE THREAD

**Issue by jemminger** [Alex-D/Trumbowyg#927]
If the trumbowyg editor is in a form, which it likely is if you intend to save data to the server, then you cannot insert a form into it using html mode.  After pasting in the form code, if you switch back to visual and again back to html mode, the form tags will be stripped out. 

Is there any way to prevent this?

**Comment by Alex-D** [comment]
WAW, you are creating an abomination :D

Hum. inserting a form in a form is invalid in HTML.

There is no code in Trumbowyg which strips from explicitly.

So, maybe it's a browser-level bug :/

**Comment by jemminger** [comment]
It's not unusual at all, I've got a form where the user is customizing what will be shown on their public event page, and they want to embed a Paypal donation form on it.

**Comment by Alex-D** [comment]
Ah :/

I suggest to develop a switch to disable Trumbowyg if the user want a fully customizable HTML.

Also, the user can use a PayPal.me URL :)

**Comment by jemminger** [comment]
Thanks, I'll look into that
