### ISSUE TITLE
Table support

### ISSUE THREAD

**Issue by alexkavon** [Alex-D/Trumbowyg#93]
It would be great to have a table button for inserting tables, rows, and columns.

**Comment by Alex-D** [comment]
Hi!

It will never be in the Trumbowyg core. But anybody can code it as a plugin for Trumbowyg like colors plugin :)

**Comment by absalomedia** [comment]
Hopefully this [https://github.com/Alex-D/Trumbowyg/pull/246](https://github.com/Alex-D/Trumbowyg/pull/246) will help

**Comment by absalomedia** [comment]
There should now be the ability to add rows & columns individually.

**Comment by Alex-D** [comment]
Released in [v2.2.0](https://github.com/Alex-D/Trumbowyg/tree/v2.2.0)
Thanks for your contribution!
