### ISSUE TITLE
image alt attribute paste even I use removeformatPasted: true

### ISSUE THREAD

**Issue by fabioceccarani** [Alex-D/Trumbowyg#930]
I set removeformatPasted: true but pasting html with images in text there are all images ALT attributes.

**Comment by Alex-D** [comment]
As you can see in the [removeformatPasted](https://alex-d.github.io/Trumbowyg/documentation/#remove-format-pasted) option documentation, this is not about remove all attributes, but only unwanted `style`'s one.
