### ISSUE TITLE
insertText on first insert not correct caret location

### ISSUE THREAD

**Issue by wworley** [Alex-D/Trumbowyg#931]
I have a series of buttons which that when clicked insert handlebars for dynamic text that will get inserted later when processed by a php script, the issue is the first time I click the first button even after selecting a point inside of the editor div/window the caret is set to the first character in the editor window, code i'm using to insert is below.

```
        $(".insertIntoAgreement").on("click",function(){
            // Restore the previous position
            $('#trumbowyg').trumbowyg('restoreRange');

            // Insert text at the current position
            $('#trumbowyg').trumbowyg('execCmd', {
                cmd: 'insertText',
                param: event.target.getAttribute('data-replace')
            });
        });
```

After the first time OR once the focus is put inside of the editor div/window and any character or space is entered the inserted text will be inserted at the right location.

Any help is greatly appreciated!

**Comment by Alex-D** [comment]
You should try use custom buttons: https://alex-d.github.io/Trumbowyg/documentation/#custom-buttons

**Comment by wworley** [comment]
@Alex-D Thanks! Took your advice and created custom buttons and addressed the issue.

For anyone wanting to do the same, then create you own custom buttons and drop downs
`$('#trumbowyg').trumbowyg({
    btns: [
        ['strong', 'em', 'del'],
        ['justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
        ['unorderedList', 'orderedList'],
        ['removeformat'],
        ['companyDropDown'],
        ['fullscreen']
    ],
    btnsDef: {
        cAddress1: {
            fn: function() {
                $('#trumbowyg').trumbowyg('execCmd', {
                    cmd: 'insertText',
                    param: '{{cinfo1}}'
                });
            },
            title: 'Insert Company Info 1',
            text: 'Company Info 1',
            hasIcon: false
        },
        cAddress2: {
            fn: function() {
                $('#trumbowyg').trumbowyg('execCmd', {
                    cmd: 'insertText',
                    param: '{{cinfo2}}'
                });
            },
            title: 'Insert Company Info 2',
            text: 'Company Info 2',
            hasIcon: false
        },
        companyDropDown: {
            dropdown: ['cInfo1', 'cInfo2'],
            title: 'Company Info',
            hasIcon: false
        }
    }
});`
