### ISSUE TITLE
CloseModal uses document.body

### ISSUE THREAD

**Issue by softaculous** [Alex-D/Trumbowyg#934]
CloseModal uses document.body instead of t.doc.body
This causes a wrong reference to the body and the modal doesnt close.
This is only if you load the script in an iFrame and create an instance for the parent.

**Comment by Alex-D** [comment]
You right, nice catch!

Will fix it soon.

**Comment by ravi45722** [comment]
Same issue.. Using iframe for isolating css. From then no modals is working.

**Comment by Alex-D** [comment]
Fixed in v2.16.0
