### ISSUE TITLE
Reply with quote

### ISSUE THREAD

**Issue by francyleo** [Alex-D/Trumbowyg#937]
How can I keep `<! DOCTYPE html>`, `<html>`, `<head>`, and `<body>`?

**Comment by Alex-D** [comment]
Use a textarea without any WYSIWYG?

Since the browser is building the HTML code in the page, it's invalid to have a HTML document inside your current HTML document.

:/

No issue/option from Trumbowyg for that. It's up to you to make an option to destroy the editor if needed.
