### ISSUE TITLE
Upload doesn't work

### ISSUE THREAD

**Issue by tomatoTom** [Alex-D/Trumbowyg#941]
I'm trying to upload an image with Trumbowyg.
But this seems to bee a little bit difficult.

Could you / somebody else please post a working sample code?

I'm not able to get the image and upload it to the server.
My code: 

```      
$('#bericht').trumbowyg({
            lang: 'de',
            autogrow: true,
            removeformatPasted: true,
            imageWidthModalEdit: true,
            btnsDef: {
                // Create a new dropdown
                image: {
                    dropdown: ['upload'],
                    ico: 'insertImage'
                }
            },
            btns: [
                // ['viewHTML'],
                ['historyUndo', 'historyRedo'],
                ['formatting'],
                ['strong', 'em', 'del'],
                ['link'],
                ['image'],
                ['justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
                ['unorderedList', 'orderedList'],
                ['horizontalRule'],
                ['removeformat'],
                ['fullscreen']
            ],
            plugins: {
                upload: {
                    serverPath: 'uploader.php',
                    fileFieldName: 'image',
                    urlPropertyName: 'url',
                }
            }
        });
```

And the upload API:
```
<?php

    $alt=$_POST["alt"];
    $image=$_POST["image"];

    $data= array (
    'success' => true,
    'url' => 'uploads/plan.png',
    );

    $json = json_encode($data);
    echo $json;

?>
```

**Comment by Alex-D** [comment]
In PHP uploaded files are not in `$_POST` but in temp folder and the temp path is in `$_FILES`, check out the PHP doc:

http://php.net/manual/en/features.file-upload.post-method.php#example-387

**Comment by tomatoTom** [comment]
Thank you for the reference. I'm still not able to implement the download function. Could you please provide a sample code? I'm wondering how others could bring this to work. I was not able to find any instructions on the internet or detailed explanation.

**Comment by Alex-D** [comment]
Try something like:

```php
$fileFieldName = 'image';
var_dump($_FILES[$fileFieldName]);
```

You should see some useful data to do the `move_uploaded_file`: 
- http://php.net/manual/en/features.file-upload.post-method.php#example-386
- https://www.php.net/manual/en/function.move-uploaded-file.php

**Comment by tomatoTom** [comment]
Thank you for the fast answer. I checked the documentation and tried a lot.
I understand that you don't want to document insecure code but I think it's absolutely clear that everybody has to look for the security. It would be very good to know how Trumbowyg works in the background because this is difficult.

I updated my code regarding the information you provided but the file uploads to my server still doesn't work.

``` php
<?php


    $fileFieldName = 'image';
    $uploadfile = var_dump($_FILES[$fileFieldName]);

    if (move_uploaded_file($_FILES[$fileFieldName], 'uploads/')) {

       // Success
       $data= array (
        'success' => true,
        'url' => "uploads/$fileFieldName",
        );
    
        echo json_encode($data);

    } else {
        // Error
       $data= array (
        'success' => false,
        );
    }

?>
```

**Comment by Alex-D** [comment]
- `$_FILES[$fileFieldName]` => `$_FILES[$fileFieldName]['tmp_name']`
- `'upload/'` should be absolute path to avoid errors if you move the file while refactoring
- returned `url` should be absolute to avoid strange errors
- Factorize the missing error case `echo` with the success one

```php
<?php

$fileFieldName = 'image';

if (move_uploaded_file($_FILES[$fileFieldName]['tmp_name'], 'uploads/')) {
    // Success
    $data = [
        'success' => true,
        'url' => "/uploads/$fileFieldName",
    ];
} else {
    // Error
    $data = [
        'success' => false,
    ];
}

echo json_encode($data);
```

**Comment by tomatoTom** [comment]
I'm using exactly the provided code and adapted, tried and tested a lot but the file upload is still not working. May I can send you FTP access via mail so you can check this? Is there a bug known in Trumbowyg regarding this?

**Comment by tomatoTom** [comment]
Hi Alex,

Is it okey, when I send you my FTP data so you can have a look?
I would donate you 20€ for the trouble.
Thank you for your answer.

Best Regards
Julian Tom Heusel

**Comment by Alex-D** [comment]
If it works on the Trumbowyg demo page, it should works for you too.

It's not as easy to debug and I did not want to go through your FTP ^^'

You need to learn PHP on your side. It could be the code, the server configuration, ...
