### ISSUE TITLE
English words are broken with new line

### ISSUE THREAD

**Issue by osenv** [Alex-D/Trumbowyg#947]
Hello,

This editor is really nice. But here comes a problem: when I use phone mode in Chrome console, the english words are seperated and broken.
![image](https://user-images.githubusercontent.com/4160306/55287340-2463b180-53da-11e9-9efa-d897e2280d30.png)

Here is my configuration:
![image](https://user-images.githubusercontent.com/4160306/55287360-63920280-53da-11e9-9518-d6397b86c90c.png)

Is there any way I can fix this?

Much appreciated if I could get any help.

**Comment by Alex-D** [comment]
I think it's a CSS issue on your side. Check this out to fix it: https://developer.mozilla.org/fr/docs/Web/CSS/overflow-wrap
