### ISSUE TITLE
Bug In Documentation at "Only build inputs in modal"

### ISSUE THREAD

**Issue by NeoTrix2000** [Alex-D/Trumbowyg#953]
Hi , I found a (writing) bug In Documentation at "Only build inputs in modal" ...

at ...
```
 alt: {
            label: 'Alt',
            name: 'alt',
            value: img.attr('alt'),
            type: 'text'.
            attributes: {}
        },
```
`type: 'text'**.**` should be `type: 'text'**,**`

- Issue from original question was for this

**Comment by Alex-D** [comment]
Thanks!

Should be fixed soon :)
