### ISSUE TITLE
Table plugin delete does not work

### ISSUE THREAD

**Issue by milmed13** [Alex-D/Trumbowyg#959]
If you register after deleting the table, row, column after page expansion, it will not be reflected.
Similarly, deletion of a column or deletion of a table is not reflected only when the operation is performed.

It seems that the value is not reflected in the base text area.
It will be reflected if you rewrite something at the same time, such as entering another.

You may need to call syncCode ().

**Comment by Alex-D** [comment]
Fixed in v2.16.0
