### ISSUE TITLE
Overriding server script path for image uploads

### ISSUE THREAD

**Issue by msimkunas** [Alex-D/Trumbowyg#96]
Is it possible to override the path to the php file responsible for managing image uploads? I'm talking about this line in particular: https://github.com/Alex-D/Trumbowyg/blob/master/plugins/upload/trumbowyg.upload.js#L36

I'm using Laravel and I'd like to point the script to my own route and manage file uploads my way.

**Comment by msimkunas** [comment]
I've solved this issue by doing the following:

```$.trumbowyg.upload.serverPath = '/my-custom-route'```

**Comment by Alex-D** [comment]
I confirm it's the good way to do :)
