### ISSUE TITLE
Selecting text after an image selects the image too

### ISSUE THREAD

**Issue by kurupted** [Alex-D/Trumbowyg#960]
Selecting text using the keyboard (eg using the Shift key + arrow keys, or Shift + End) will select an image that precedes the text, if the initial caret position is at the start of a text line. This happens even if there are multiple linebreaks between the image and the line of text.

So let's say you add an image, a few linebreaks, then some text, and you later decide to remove that line of text, so you place the caret at the beginning of the line and press Shift+End. The selection expands _backwards_ before the caret, and selects the image too, so when you press Del the image gets deleted.

This happens in both Firefox and Chrome.

**Comment by Alex-D** [comment]
I will not fix that in v2.

Since a new v3 is on the road, I hope this will not be buggy in it.
