### ISSUE TITLE
Tooltip for buttons

### ISSUE THREAD

**Issue by cromartie1984** [Alex-D/Trumbowyg#963]
Hi,
I noticed there is not tooltip for each button. Your plugin is awesome btw.

**Comment by Alex-D** [comment]
Hey, thanks :)

You need to be more precise, since there is a lot of buttons ^^

Which buttons does not have tooltip?

**Comment by cromartie1984** [comment]
i mean tooltips like bootstrap (on top / on hover)

**Comment by Alex-D** [comment]
There are some title attribute on each button which let the browser manage the display of the tooltip if it's what you want.

But if you want something stylized in CSS, I assume you need to do it yourself.

**Comment by Antonio-Martinez-20** [comment]
Hello Alex-D,

Could you please advise how to change the tooltip of the default buttons (i.e. NOT custom buttons), for example:
- Strong (Ctrl + B) -> Bold (Ctrl + B)
- Emphasis (Ctrl + I) -> Italic (Ctrl + I)
- Deleted -> Strike out

I read in the documentation that there is a parameter:
**Title String**: The text displayed in a tooltip on mouse over a button.

But the only example is for Custom buttons, there are no example for the Default buttons. Could you please advise if it is possible to change the tooltips of the default buttons and provide an example?

Thanks in Advance, 
Best Regards,
Antonio

**Comment by Alex-D** [comment]
Hey, create your own translation file :)
