### ISSUE TITLE
Tables may be created inside Header tags

### ISSUE THREAD

**Issue by dvtan** [Alex-D/Trumbowyg#964]
Tables may be created inside an `<h1>` tag like this:

    <h1><table class="table"><tr><td>asdf</td><td></td></tr></table><br></h1>

This makes it buggy to later revert the text within the table back to normal `<p>`. The table plugin can force the table to be created at top-level to avoid this.

### How to reproduce?

1. Switch to Header 1
1. Create a table
1. Type something in a cell

**Comment by Alex-D** [comment]
I don't plan to put time on v2 anymore... so if anyone want to fix it, I will be happy to merge the fix :)

**Comment by Alex-D** [comment]
It seems to be working as of v2.27.2
