### ISSUE TITLE
Feature Request: Adding attributes to dropdown elements

### ISSUE THREAD

**Issue by Braunson** [Alex-D/Trumbowyg#965]
Looking to provide attributes like a custom data attribute on a dropdown item: i.e. `data-template-id="' + template.id + '"` (so it can be references outside the editor)

Adding a class or other attribute would be helpful also. The use case is I'm using the editor for an email editor, we have a nicer UI for selecting a pre-existing template which we want to (on select of that template), click a referenced dropdown item to trigger the replacement of the content natively inside the editor.

So a code example inside the `template` plugin would be.. 

```js 
function templateSelector(trumbowyg) {
    var available = trumbowyg.o.plugins.templates;
    var templates = [];

    $.each(available, function(index, template) {
        trumbowyg.addBtnDef('template_' + template.id, { // I changed the index to the template.id I provide in the passed templates array
            fn: function() {
                trumbowyg.html(template.html);
            },
            class: 'template-option-' + template.id, // Pass a class
            data: { // Pass multiple data attributes
                'template-id':  template.id,
            },
            hasIcon: false,
            title: template.name
        });
        templates.push('template_' + index);
    });

    return templates;
}
```

The `class` and `data` attribute can be of course nested in an `attributes` object to keep things clean..

**Comment by Alex-D** [comment]
I keep that in mind for Trumbowyg 3, but I will not do that in v2.
