### ISSUE TITLE
Built-In URL Modal Not working

### ISSUE THREAD

**Issue by mlammert** [Alex-D/Trumbowyg#968]
### Description
Provide relevant details according to the context:
  - Windows 10
  - FF 66, Chrome 74, IE
  - 1920 x 1080
  - jQuery 3.3.1
  - jQuery UI 1.12.1
  - Trumbowyg  2.17.0

I am incorporating Trumbowyg into a fairly sophisticated content management system.

I have pared down the formatting buttons to:
italic, underline, url, and clear

When you click the URL button and the URL modal appears, the first thing I notice is that the Trumbowyg text area does not blur out like in the demo. Then, when you move your cursor over any of the text fields within the URL modal and click to focus, the URL modal fields do not focus. Instead the cursor appears in the actual Trumbowyg text area. If I type, my text within the Trumbowyg text area changes.

I have some pretty heavy CSS stuff going on. But, I am not doing anything JavaScript related that would change focus or disable anything to do with Trumbowyg.

BTW, the Trumbowyg editor is being used inside of a jQuery UI dialog.

Anybody seen this behavior before or have any ideas of where to start troubleshooting?

Thanks!

**Comment by Alex-D** [comment]
> the first thing I notice is that the Trumbowyg text area does not blur out like in the demo

Check if some of your CSS override the Trumbowyg's one.

> Instead the cursor appears in the actual Trumbowyg text area

Check if some of your CSS change position or z-index of form or textarea or other. I think it's a bug on your side.

Hope it helps :)

**Comment by adamsow** [comment]
You need to add this extension for jQuery UI dialog to make it working
`//extension for ui-dialog so htmleditor modal will work
$.widget("ui.dialog", $.ui.dialog, {
    /*! jQuery UI - v1.11.4 - 2015-06-05
     *  http://bugs.jqueryui.com/ticket/9087#comment:27 - bugfix
     *  http://bugs.jqueryui.com/ticket/4727#comment:23 - bugfix
     *  allowInteraction fix to accommodate windowed editors
     */
    _allowInteraction: function (event) {
        if (this._super(event)) {
            return true;
        }
        if ($(event.target).closest(".trumbowyg-modal").length) {
            return true;
        }
    }
});`
