### ISSUE TITLE
Trumbowyg steals cursor from autofocus elements

### ISSUE THREAD

**Issue by Meekohi** [Alex-D/Trumbowyg#975]
When including Trumbowyg on a page with an autofocus element, the cursor no longer starts inside the autofocus element. `document.activeElement` is still correct, but the cursor is missing.

### Description
Chrome OSX

### How to reproduce?
https://codepen.io/meekohi/pen/joGYMN

**Comment by Alex-D** [comment]
Seems to be a browser-level bug :/

Cannot reproduce on Firefox. I did not run any `.focus()` in the Trumbowyg code.

You can do this little hack to avoid that: https://codepen.io/Alex-D/pen/mYBXgE

But I can't help you more :(

Hope it helps!

**Comment by Meekohi** [comment]
Huh funny that work-around didn't work for my case, I had to do something a bit weirder:

```
if(document.activeElement.setSelectionRange && /text|search|password|tel|url/i.test(document.activeElement.type || ''))
  document.activeElement.setSelectionRange(0,0); // Put cursor it back.
```

**Comment by Meekohi** [comment]
Huh _actually_, what I had tried is this, which doesn't work:

```
  $('#trumbo').trumbowyg();
  document.activeElement.activeElement.blur()
  document.activeElement.activeElement.focus()
```

definitely weird behavior on Chrome's part, I might try to file a bug over there.

**Comment by Alex-D** [comment]
When you do that: `document.activeElement.blur()` you change the value of `document.activeElement` since you just blur it. So you need to save it before blur then focus.
