### ISSUE TITLE
Insert image when clicking on an external object (execCmd)

### ISSUE THREAD

**Issue by Ramir1** [Alex-D/Trumbowyg#976]
Hi!
Tell me, please, how to do this:
`<img src="/images/image.jpg" class="trumbowygInsert"/>`

```js
$('body').on('click','.trumbowygInsert',function (e) {
         let url = $(this).attr('src');
         $('.wisy-editor').trumbowyg('execCmd', {
             cmd: 'insertImage',
             param:  url,
             forceCss: false,
            skipTrumbowyg: true
        });
     })
```
I get a modal window with fields url and alt.

**Comment by Alex-D** [comment]
AH!
the `skipTrumbowyg` parameter binding is missing here: 
https://github.com/Alex-D/Trumbowyg/blob/fa6f4728c5b71855d6fecf018b88312648a8cb7f/src/trumbowyg.js#L141-L143
