### ISSUE TITLE
Japanese(multibyte character) bug in firefox

### ISSUE THREAD

**Issue by abenger** [Alex-D/Trumbowyg#979]
Hi!

### Description
- Browser version: Firefox 67.0
- OS: Mac HighSierra
- Language: Japanese

### How to reproduce?
At the time of Japanese input, confirmation and line feed are performed simultaneously.
Therefore, I can not continue writing.
(Firefox only)

Behavior is observable on example page.

![demo](https://user-images.githubusercontent.com/12757457/58525403-96a01900-8206-11e9-9291-298e7d725c79.gif)

#### Request
1st Enter: confirm
2nd Enter: line feed

Thanks!

**Comment by Alex-D** [comment]
Hum, that only appends when you clean all the text/start from scratch.

I will not investigate on this for v2. I keep that for v3, sorry :/
