### ISSUE TITLE
Problem with at.js

### ISSUE THREAD

**Issue by philippejadin** [Alex-D/Trumbowyg#980]
I use [at.js](https://github.com/ichord/At.js) mention library and the content inserted contains `contenteditable="false"` : 

`<p><span class="atwho-inserted" data-atwho-at-query="f:" contenteditable="false"><span>f:1</span></span></p><br>`

Do you know if the contenteditable="false" line is inserted by trumbowyg or by at.js?

I'm trying to understand how those two interact :-)

Thank you for this great no-nonsense wysiwyg editor

**Comment by Alex-D** [comment]
It's not Trumbowyg. I think it comes from the at.js lib as you see here: https://github.com/ichord/At.js/search?q=contenteditable&unscoped_q=contenteditable
