### ISSUE TITLE
Font family bug when selecting a font with a space in the name

### ISSUE THREAD

**Issue by mikevoid101** [Alex-D/Trumbowyg#988]
### Description
https://www.loom.com/share/395dda79065842868321417b0b106d38
As you can see, if I choose a font family that has a space in the name (Arial Black for example), in the source code, the name is surrounded by quote entities, once saved in the database (what you see in green) an reused exactly the same in the textarea, trumbowyg gets confused and generates some random attributes and does not display the font family correctly.

OS: Windows 10
Browser: Google Chrome 74.0.3729.169
Trumbowyg: 2.18.0

### How to reproduce?
https://jsfiddle.net/mikevoid101/8jcasL6r/4/

**Comment by Alex-D** [comment]
Will be fixed in 2.19.0

**Comment by devguar** [comment]
Hi @Alex-D , it was fixed? I'm having exactly the same issue described here. but with the version 2.23.0.
