### ISSUE TITLE
Textarea visible

### ISSUE THREAD

**Issue by mondul** [Alex-D/Trumbowyg#99]
![image](https://cloud.githubusercontent.com/assets/1645338/6661555/d11b372c-cb7b-11e4-9801-a0951fca84c5.png)
Changing .trumbowyg-textarea display from block to none fixed it for me. Tested on Chrome 42 running on OS X Yosemite.

**Comment by Alex-D** [comment]
I think the bug is a due to a side effect of your CSS. See buttons of button pane : they have padding.

I need to apply a reset to buttons and textarea.

**Comment by mondul** [comment]
Found in my css a padding applied to all input elements, including textarea, marked as important; disabled it and fixed the issue also, but left my previous fix to avoid conflicts with the other elements of my page.

**Comment by Alex-D** [comment]
Ok, so i need to errased any padding with important flag in the editor scope.
Thanks for informations :)

**Comment by Alex-D** [comment]
Fix'd in [2.0.0-beta.2](https://github.com/Alex-D/Trumbowyg/tree/2.0.0-beta.2)

Reopen if not.

**Comment by thejhnz** [comment]
Hi this still exists in latest build, fixed by adding a opacity:0 style to the old textarea.

```
      t.$ta
                .addClass(prefix + 'textarea')
                .attr('tabindex', -1)
                .attr('style', 'opacity:0')
            ;
```

**Comment by Alex-D** [comment]
Can you try with the new one ? (I dont have deploy a new tag)
