### ISSUE TITLE
Div automatically converts to p tag

### ISSUE THREAD

**Issue by RajasekarPR** [Alex-D/Trumbowyg#990]
@Alex-D How to prevent automatic conversion of div to p tag in editor plugin ?

**Comment by Alex-D** [comment]
Hey!

You need to customize the `semantic` option, read the docs here: https://alex-d.github.io/Trumbowyg/documentation/#semantic

Hope it helps :)

**Comment by JulioMunozc** [comment]
@Alex-D Thanks for the response , I had a question, how can I implent the semantis in React, for example to avid convert div in p
```
        <Trumbowyg
          id='react-trumbowyg'
          buttons={
            [
              //['viewHTML'],
              ['undo', 'redo'], // Only supported in Blink browsers
              ['formatting'],
              ['strong', 'em', 'del'],
              ['foreColor', 'backColor'],
              ['superscript', 'subscript'],
              ['link'],
              ['insertImage'],
              ['justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
              ['unorderedList', 'orderedList'],
              ['horizontalRule'],
              ['removeformat'],
              ['fullscreen']
            ]
          }
          data={this.props.content}
          placeholder='Type your text!'
          onChange={(HTMLobject) => this.onTextChange(HTMLobject.target.innerHTML)}
          ref={(editor) => { this.editorObject = editor; }}
          semantic={{ div: 'div'}}
        />
```

**Comment by Alex-D** [comment]
I think the react-trumbowyg third party lib is not ready to get anything else than boolean :(
https://github.com/RD17/react-trumbowyg/blob/master/src/react-trumbowyg.js#L161

**Comment by JulioMunozc** [comment]
Thank you @Alex-D, you are the best, but now how can I customize the semantic tag mapping for each one in angular control like says the documentation https://alex-d.github.io/Trumbowyg/documentation/#semantic. Thank you for your help
