### ISSUE TITLE
How to add default text before and after link or image

### ISSUE THREAD

**Issue by isthabenahadirani** [Alex-D/Trumbowyg#991]
I want to add text '{{ LOOP }}' and '{{ ENDLOOP }}' automatically before and after inserting image or link. 

Expected output : 

`<p>{{ LOOP }} <a href="www.google.com">google</a> {{ ENDLOOP }}<br></p>`

I had tried several ways : 

1. Call 'insertText' before and after 'createLink' or 'insertImage' . 
    Result : text and link didn't appear in order. 
2. Create new modal by modifying file dist/trumbowyg.js
    Result : work in firefox. but no chrome. (the modified file is attached. the new function called 'insertImageDynamic' and 'createLinkDynamic')

Firefox
![image](https://user-images.githubusercontent.com/51994300/59758056-4113d500-92b7-11e9-916f-1ffa5e7d9c50.png)

Chrome
![image](https://user-images.githubusercontent.com/51994300/59758078-4e30c400-92b7-11e9-908e-5e95336cf5c1.png)

[trumbowyg.txt](https://github.com/Alex-D/Trumbowyg/files/3305654/trumbowyg.txt)

Kindly need your help. 
Thank you.

**Comment by Alex-D** [comment]
Hey!

You should follow the doc for creating your own plugin which will do what you want. I did not have the time to help you more.

Plugin docs: https://alex-d.github.io/Trumbowyg/documentation/plugins/#create-your-own

Feel free to check out how others plugins are working, it will helps you :)

**Comment by isthabenahadirani** [comment]
I have successfully created new plugins and added that to the editor. But is there a way to call that new plugins outside editor ? like command 
`$('#textarea').trumbowyg('execCmd',` {cmd: 'createLink' ... }`

Thank you.

**Comment by Alex-D** [comment]
Yes, just change `createLink` with the button name you just created :)

**Comment by isthabenahadirani** [comment]
Already did that. But it didn't work.

`$('#email-body-msg').trumbowyg('execCmd', {
                        cmd: 'linkdynamic',
                        forceCss: false
                    });`

This is the new plugins

`(function ($) {
    'use strict';

    $.extend(true, $.trumbowyg, {
        langs: {
            en: {
                linkdynamic : "Insert Placeholder"
            }
        },
        plugins: {
            linkdynamic: {
                init: function (trumbowyg) {
					 const btnDef = {
						fn: function(cmd) { 		
						trumbowyg.execCmd('insertHTML', '<p>{{ LOOP }} </p><a href="{{ OFFERING.LINK }}">{{ OFFERING.TITLE }}</a><p> {{ ENDLOOP }} </p>');
						}
					};
					
					trumbowyg.addBtnDef('linkdynamic', btnDef);
				}
            }
        }
    });
})(jQuery);`


Kindly need your help. Thank you.

**Comment by Alex-D** [comment]
Ah! You can't call the button function directly.

You need to do some dirty code like:

```js
init: function(trumbowyg) {
  trumbowyg.linkdynamic = function () {
    // ...
  };
  const btnDef = {
	hasIcon: false
  };
  trumbowyg.addBtnDef('linkdynamic', btnDef);
}
```

I need to improve that in v3... because it's really hacky. Sorry ^^'

**Comment by isthabenahadirani** [comment]
Oh what I mean is I need to call that new plugins in HTML button. not in button trumbowyg. 
But I can't call it just simply using this command : 

`$('#email-body-msg').trumbowyg('execCmd', { cmd: 'linkdynamic', forceCss: false });`

Kindly need ur help. Thank you.

**Comment by Alex-D** [comment]
Did you try something like I just give you in my previous message? It should work.
