### ISSUE TITLE
Merge `strong` tags

### ISSUE THREAD

**Issue by lcswillems** [Alex-D/Trumbowyg#992]
Hi,

First, thank you so much for this great plugin!!

Second, I tried it a little bit on this text `Lorem ipsum`.

I wanted to bold `ipsum`, but I mistakenly only selected `psum` and bolded it. Then I saw I didn't bold `i`, hence I selected it and bolded it.

However, I ended up with the following html code:

```
Lorem <strong>i</strong><strong>psum</strong>
```

The non HTML specialist users would think that he finally bolded the whole word. However, this is not what the markup reflects.

**Comment by Alex-D** [comment]
Hey!

Thank you :)

You cannot do that with v2.

Fortunately, this is already in the roadmap of v3 which can be followed here: #875
