### ISSUE TITLE
destroy method doesn't work with classes

### ISSUE THREAD

**Issue by VeeK727** [Alex-D/Trumbowyg#994]
Pretty self explanatory title.

`$('#editor').trumbowyg('destroy');`
works
`$('.editor').trumbowyg('destroy');`
doesn;t work

I'm using classes to initialize multiple editors on the same page and would like to destroy all of them together.

**Comment by Alex-D** [comment]
Loop around them on your own :)

```js
$('. editor').each(function(i, $editor) {
  $editor.trumbowyg('destroy');
});
```

API calls must be done on one instance of Trumbowyg at the time.

Hope it helps :)

**Comment by VeeK727** [comment]
Weirdly its giving me an error `$editor.trumbowyg is not a function`. Are you sure that works?

**Comment by Alex-D** [comment]
I've updated, sorry ^^'

**Comment by VeeK727** [comment]
That works. Thanks
