### ISSUE TITLE
Base64 Image Ctrl+Z in Description field

### ISSUE THREAD

**Issue by Yokomoko** [Alex-D/Trumbowyg#996]
### Description
Using Chrome with the Base64 plugin. If you enter in a description, and then do Ctrl-Z, it clears the description fine, however, pressing Ctrl-Z again undos the template behind.

### How to reproduce?
1. Make changes to the template
2. Use the Base64 plugin button
3. Enter in a description
4. Do Ctrl+Z to clear that text
5. Press Ctrl+Z again - This will trigger undo's in the main editor in the background.

**Comment by Alex-D** [comment]
Did you try the history plugin?

**Comment by Yokomoko** [comment]
Yep - Same issue as before. It'll undo the main editor when pressing Ctrl+Z in the 'Insert Image' description after entering in text and pressing Ctrl+Z multiple times.

**Comment by Alex-D** [comment]
Aaaah, I've just understand the issue. You are saying that you press Ctrl+Z while you are in modal? If it's that, that's not only a base64 bug but a core bug with modals.

Just need to catch keyboard events while a modal is open.

**Comment by Alex-D** [comment]
Too hard to do, but I keep that in mind for v3.
