### ISSUE TITLE
Some minified CSS files have invalid 5-digit hex colors

### ISSUE THREAD

**Issue by biziclop** [Alex-D/Trumbowyg#997]
For example, this file ( https://github.com/Alex-D/Trumbowyg/blob/master/dist/plugins/mathml/ui/trumbowyg.mathml.css ) has `background-color: #ffffffd4;` which is minified to `background-color:#fffd4;` in https://github.com/Alex-D/Trumbowyg/blob/master/dist/plugins/mathml/ui/trumbowyg.mathml.min.css .

See this issue: https://github.com/jakubpawlowicz/clean-css/issues/1034  
This was a bug in an earlier version of clean-css, but now it's fixed.

Spec (draft) doesn't know 5 digit hex colors: https://drafts.csswg.org/css-color/#typedef-hex-color

I try to merge all relevant css files to one, but the scss parser I use died on the malformed color. :)

Thanks!

**Comment by Alex-D** [comment]
Thanks! Fixed on develop, will be published in the next release :)
