### ISSUE TITLE
Firefox adds extraneous <br> tags to output stream, but not Safari

### ISSUE THREAD

**Issue by SkipperHosting** [Alex-D/Trumbowyg#999]
Using FF to edit a trumbowyg instance will result in extra `<br>` tags being inserted in the final output.  This does not happen with at least Safari (both on OSX).

Tested on OSX with current public FF68, FFdev69, and Safari 12
Tested against both the trumbowyg main demo (https://alex-d.github.io/Trumbowyg/demos/) and a local barebones instance of the current github code.

With public Trumbowyg demo:

### Using Safari...

1. Click show HTML
2. => the output is as expected, each line wrapped in a `<p>` pair
3. Click to insert text caret at the very end of the text body
4. type a few letters
5. Click show HTML
6. => output as expected
7. Repeat putting caret at end of text
8. Press enter to add carriage return
9. Type some text on the new line
10. Add a second carriage return and a few more bits of text
11. Click show HTML
12. => output is as expected (this is where the output changes for FF)

### Using FF68/FFdev69...

1. follow same steps as above
2. => everything is the same until the very last result that this now includes an extraneous `<br>` in the last paragraph.

This is just one set of steps to get the `<br>` to appear.  Most any random usage in FF will cause the extra line break to be left in the output.

As mentioned, this behaves the same with a completely bare-bones test install with no plugins.

**Comment by Alex-D** [comment]
Hey, thank you for you detailed issue!

I'm sorry about that kind of bugs, but they are from browsers, not Trumbowyg since it's based on `contenteditable`.

Trumbowyg v3 (see #875) will not be based on the `contenteditable`/`execCommand` API and will fix this kind of issues, but not before few months, maybe spring 2020 or later, don't know for now when it will be ready.

**Comment by n-makarin** [comment]
Perhaps you can avoid this behaviour in ff using contenteditable's parent conteiner with style: display: inline-block; (i didn't check it)
